### ISSUE TITLE
Pinning dependencies can be dangerous for libraries - should focus on applications

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#1000]
**Describe the bug**

Pinning dependencies has its pros and cons. It's probably an overall win for applications.
However, having *libraries* pin all their dependencies is dangerous.
If library L1 pins its dependencies on a specific version of library L2, and the runtime
only allows one version of a library for a given component (true for most runtimes),
then the system can only use that specific version of L2 (which is probably not the same
version as all other users of L2). Many libraries won't update more than every few months or years,
so this *forces* everyone to use a really old & probably insecure version of a library.

So I think the pinning-dependency criterion needs to focus on requiring this for *applications*
but not for *libraries* that are incorporated into applications.

**Comment by laurentsimon** [comment]
This is tracked in https://github.com/ossf/scorecard/issues/689.

**Comment by laurentsimon** [comment]
@nanikjava is looking into it, so closing this issue (I've linked to *this* issue in there). @david-a-wheeler please subscribe to the other issue.
