### ISSUE TITLE
Dependabot detection not working on CII Best Practices badge

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#1028]
**Describe the bug**
Dependency-Update-Tool  reports "Warn: dependabot not detected" for https://github.com/coreinfrastructure/best-practices-badge yet we *do* have dependabot enabled

**Reproduction steps**
1. Run scorecard on <https://github.com/coreinfrastructure/best-practices-badge>, it incorrectly reports:

~~~~
    {
      "details": [
        "Warn: dependabot not detected",
        "Warn: renovatebot not detected"
      ],
      "score": 0,
      "reason": "no update tool detected",
      "name": "Dependency-Update-Tool"
    },
~~~~

**Expected behavior**
I expected it to correctly report dependabot.

**Comment by naveensrinivasan** [comment]
>Signup for automatic dependency updates with dependabot or renovatebot and place the config file in the locations that are recommended by these tools.

Scorecard can identify if these settings are enabled only by looking at the config files. If these files aren't there then it can't identify it has been enabled. That is the reason you are seeing this message.

To resolve this issue, add dependabot config and it will solve the issue.

**Comment by david-a-wheeler** [comment]
Then the message is misleading. The error message says:

> Warn: dependabot not detected

It should say something like this:

> Warn: dependabot config file not detected

The *easy* way to enable dependabot on GitHub is via a project setting, and it's the recommended way.

**Comment by inferno-chromium** [comment]
> Then the message is misleading. The error message says:
> 
> > Warn: dependabot not detected
> 
> It should say something like this:
> 
> > Warn: dependabot config file not detected

Yes +1, lets fix message like 
Warn: dependabot config file not detected in source location <path>. It is recommended to set this configuration in code.

> 
> The _easy_ way to enable dependabot on GitHub is via a project setting, and it's the recommended way.

**Comment by david-a-wheeler** [comment]
Instead of this vague:

> It is recommended to set this configuration in code.

I don't know anyone who recommends this, and the text doesn't give a rationale. People often need rationales before they'll do something. How about instead say:

> We recommend setting this configuration in code so its setting can be easily verified by others.

**Comment by david-a-wheeler** [comment]
Or, shorter:

> We recommend setting this configuration in code so it can be easily verified by others.

**Comment by inferno-chromium** [comment]
> Or, shorter:
> 
> > We recommend setting this configuration in code so it can be easily verified by others.

yes sure! @naveensrinivasan wdyt ?

"Warn: dependabot config file not detected in source location <path>. We recommend setting this configuration in code so it can be easily verified by others."

**Comment by naveensrinivasan** [comment]
> > Or, shorter:
> > > We recommend setting this configuration in code so it can be easily verified by others.
> 
> yes sure! @naveensrinivasan wdyt ?
> 
> "Warn: dependabot config file not detected in source location . We recommend setting this configuration in code so it can be easily verified by others."

Sounds good. I agree. Working on the fix. Thanks
