### ISSUE TITLE
Scorecard should try to earn a CII Best Practices badge

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#1032]
**Is your feature request related to a problem? Please describe.**
Scorecard should try to earn a [CII Best Practices badge](https://bestpractices.coreinfrastructure.org/).

**Additional context**
Both scorecard & the CII Best Practices badge are OpenSSF projects focused on best practices to improve OSS security. They have different approaches and somewhat different criteria, but I think each would be helped by working on the other. I'm the lead of the CII Best Practices badge project, and I'm trying to meet the scorecard criteria (or complain when I think there's a problem). I think it'd be great if scorecard reciprocated.

**Comment by naveensrinivasan** [comment]
Not stale.

**Comment by david-a-wheeler** [comment]
Happy to help if you'd like!

**Comment by naveensrinivasan** [comment]
Yes,Thank you! What is the process?

**Comment by laurentsimon** [comment]
I've started the process by clicking "get a badge". Waiting for OSSF to accept the OAuth request.

**Comment by david-a-wheeler** [comment]
@laurentsimon - presuming you're logged into GitHub, the "get a badge" click should have gotten you to a list & getting started pretty quickly. If you're hung, something is wrong.

What happened? If you're stuck I want to make sure you (& anyone else) gets unstuck :-).

**Comment by laurentsimon** [comment]
I indeed got a list of repos, but `ossf/scorecard` does not show up. I think it's because the OAuth does not have the scope to read it, I see "Access request pending" under Installation > Application

**Comment by azeemshaikh38** [comment]
@justaugustus assigning this to you since you earned Scorecard a CII Best Practices [badge](https://bestpractices.coreinfrastructure.org/en/projects/5621) (yay, thanks a lot!). We can close this unless you plan on working on this further and want to use this to track your progress.

**Comment by justaugustus** [comment]
> @justaugustus assigning this to you since you earned Scorecard a CII Best Practices [badge](https://bestpractices.coreinfrastructure.org/en/projects/5621) (yay, thanks a lot!). We can close this unless you plan on working on this further and want to use this to track your progress.

Will keep this open as there's still a bunch to do! :)

**Comment by afmarcum** [comment]
@justaugustus Scorecard now has a "passing" BP badge. Do we want to continue working toward silver or gold level badges at this time or do we consider this issue done?

**Comment by justaugustus** [comment]
Closing this, as leaving it open for all badge levels might be too much.

I'll open additional issues as needed, as part of the "Apply for appropriate status in OpenSSF project lifecycle" task in https://github.com/ossf/scorecard/issues/4073.
