### ISSUE TITLE
Update go-github

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/scorecard#1036]
32 is looking a little old: https://github.com/google/go-github/releases

**Comment by naveensrinivasan** [comment]
We are at `v38` https://github.com/ossf/scorecard/blob/4c4fb61d5106e39988dce8c277a8575d939a83e7/go.mod#L16

Closing this as dependabot will open a PR for these updates. Thanks

**Comment by jeffmendoza** [comment]
Ah, thanks for the update! I need to update my version of scorecard I'm pulling in.
