### ISSUE TITLE
BUG: we don't check for declared dependencies for libs

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1042]
In the Pinned Dependencies check, we only look for pinning https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies.go#L759

The documentation for the check https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies says "has declared and pinned its dependencies".

related: https://github.com/ossf/scorecard/issues/689

FYI @nanikjava

**Comment by nanikjava** [comment]
Feel free to assign this to me if necessary @laurentsimon

**Comment by laurentsimon** [comment]
Thanks. Discuss plans here before writing up a PR. I'm not sure what we should do for this to tackle this issue :-)
