### ISSUE TITLE
Feature: scorecard builds comply with SLSA

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1051]
see https://security.googleblog.com/2021/09/distroless-builds-are-now-slsa-2.html

**Comment by naveensrinivasan** [comment]
Related #309 #950

**Comment by naveensrinivasan** [comment]
> First steps:
> 
> 1. Enable reproducible builds for golang. This can be done using `ko` (see related issue [Feature: Use `google/ko` instead of `Dockerfile` #744](https://github.com/ossf/scorecard/issues/744))

Why would ko alone do reproducible builds?
> 2. Use a GCP KMS key to sign the build and containers (cosign)

Why GCP KMS?

**Comment by laurentsimon** [comment]
> > First steps:
> > 
> > 1. Enable reproducible builds for golang. This can be done using `ko` (see related issue [Feature: Use `google/ko` instead of `Dockerfile` #744](https://github.com/ossf/scorecard/issues/744))
> 
> Why would ko alone do reproducible builds?

Apparently there's an option to make a reproducible build for go binaries, e.g. it will strip off time/date information, etc

@loosebazooka do you have additional info?

> > 1. Use a GCP KMS key to sign the build and containers (cosign)
> 
> Why GCP KMS?

Because the OSSF project and build uses GCP, so GCP KMS is the best choice (and it supported by cosign). We want the keys to never be accessible by human, and KMSs can give us this guarantee. Let me know if I mis-understood the question.

**Comment by naveensrinivasan** [comment]
> > > First steps:
> > > 
> > > 1. Enable reproducible builds for golang. This can be done using `ko` (see related issue [Feature: Use `google/ko` instead of `Dockerfile` #744](https://github.com/ossf/scorecard/issues/744))
> > 
> > 
> > Why would ko alone do reproducible builds?
> 
> Apparently there's an option to make a reproducible build for go binaries, e.g. it will strip off time/date information, etc
> 
> @loosebazooka do you have additional info?
> 
> > > 1. Use a GCP KMS key to sign the build and containers (cosign)
> > 
> > 
> > Why GCP KMS?
> 
> Because the OSSF project and build uses GCP, so GCP KMS is the best choice (and it supported by cosign). We want the keys to never be accessible by human, and KMSs can give us this guarantee. Let me know if I mis-understood the question.



> > > First steps:
> > > 
> > > 1. Enable reproducible builds for golang. This can be done using `ko` (see related issue [Feature: Use `google/ko` instead of `Dockerfile` #744](https://github.com/ossf/scorecard/issues/744))
> > 
> > 
> > Why would ko alone do reproducible builds?
> 
> Apparently there's an option to make a reproducible build for go binaries, e.g. it will strip off time/date information, etc
> 
> @loosebazooka do you have additional info?
> 
> > > 1. Use a GCP KMS key to sign the build and containers (cosign)
> > 
> > 
> > Why GCP KMS?
> 
> Because the OSSF project and build uses GCP, so GCP KMS is the best choice (and it supported by cosign). We want the keys to never be accessible by human, and KMSs can give us this guarantee. Let me know if I mis-understood the question.

Why not use the keyless option with ODIC provider? GitHub should be opening OIDC provider for actions soon. https://github.com/sigstore/cosign/blob/main/KEYLESS.md#custom-infrastructure

**Comment by laurentsimon** [comment]
> 
> Why not use the keyless option with ODIC provider? GitHub should be opening OIDC provider for actions soon. https://github.com/sigstore/cosign/blob/main/KEYLESS.md#custom-infrastructure

That sounds good. Let me just CC team members who are more up-to-date than me on cosign state.
@loosebazooka @priyawadhwa @asraa comments?

**Comment by priyawadhwa** [comment]
Cosign also has support for keyless signing in GCB, so you could use that as well since you're already building the image in GCB. We do that in distroless in addition to signing with KMS (https://github.com/GoogleContainerTools/distroless/pull/827) 

I'm not sure if provenance will eventually be able to be signed this way too, or if you'll need a KMS key eventually for that though...

**Comment by naveensrinivasan** [comment]
What value add does provenance provide? 

We could still run into issues like this https://github.com/testifysec/solarsploit , or can tekton pipelines mitigate this?
 
 I am not trying to be hard. I am really trying to understand what value prop it provides.

One of the ways to mitigate the `solarsploit` is a reproducible build that is not being built within GCP.

**Comment by priyawadhwa** [comment]
Hey @naveensrinivasan

> What value add does provenance provide?

There are some details of specific attacks that provenance can help mitigate on the SLSA website [here](https://slsa.dev/levels).  I think the `Supply chain threats` section does a good job of explaining some of the specific threats. That's why if we want to achieve higher SLSA levels, we'll need provenance.

> We could still run into issues like this https://github.com/testifysec/solarsploit , or can tekton pipelines mitigate this?

You're right, provenance wouldn't have mitigated that particular attack. I think it can still be a useful component in other scenarios though :)

**Comment by loosebazooka** [comment]
> Apparently there's an option to make a reproducible build for go binaries, e.g. it will strip off time/date information, etc
> Why would ko alone do reproducible builds?

Ko is a convenience, but you still want to configure it for reproducibility (it already uses `--trimpath` by default to build), but it looks like you want to use [SOURCE_DATE_EPOCH](https://reproducible-builds.org/docs/source-date-epoch/) which it does respect: maybe to the git commit/tag time or something (https://github.com/google/ko#why-are-my-images-all-created-in-1970)

**Comment by laurentsimon** [comment]
shared by @asraa https://github.com/sigstore/root-signing/pull/31#issuecomment-930288618

**Comment by priyawadhwa** [comment]
I think @dekkagaijin might be able to confirm that better than I can :)

**Comment by laurentsimon** [comment]
This is really cool, @naveensrinivasan ! Is it something we could do for v4?

Does the information stored in sigstore also contain data about which workflow and which hash/branch of the project triggered this signature?

AFAICT, a verifier cannot right away trust the signature: it could have been generated by anyone who can create a workflow, e.g. in a different branch of the repo not protected by branch protection. I suppose this is what SLSA levels will help us achieve, and it's not possible right now.

@asraa

**Comment by laurentsimon** [comment]
I ran `COSIGN_EXPERIMENTAL=1 ./cosign verify ghcr.io/naveensrinivasan/stunning-tribble` and there's some info about the workflow in the cert `"Subject":"https://github.com/naveensrinivasan/stunning-tribble/.github/workflows/docker-sign.yml@refs/heads/main"`

I think the above means the workflow was triggered from a push to main. Is that correct? 

Might be useful for GitHub to add the trigger and other info to the certificate, it not already present. 

I did not find the hash commit at first sight, but it may be present somewhere in the cert (have not had time to extract it). One could do some correlation with the time in rekor to map to candidate commits as a last resort - pretty ugly.

So for someone to verify a slsa level with attestation, I suppose we (the community) wil need a list of ready-made workflows (for each language) that everyone uses. ThThis way verifiers can use it as a policy during verification.

**Comment by laurentsimon** [comment]
Chatted with @asraa . The GitHub token format is https://github.com/google-github-actions/auth#github-token-format and contains GitHub context, including trigger and commit hash. So we need to add support in sigstore to use this info as part of cert generation. Thanks @asraa !

**Comment by laurentsimon** [comment]
See a draft proposal [here](https://docs.google.com/document/d/1JbLFhpCpy6Y607g72W-BekAoBC6djaKz3gbcMcLWhwQ/edit?resourcekey=0-eRujJ1O_5m4_Bt0Z0KugsA#).
