### ISSUE TITLE
Feature - Web API for Scorecard bigquery data

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1056]
**Is your feature request related to a problem?
The scorecard bigquery is accessible only via bigquery client/API. This is an issue in consuming the scorecard data.

Tools like `osv` are great because it has a REST endpoint https://osv.dev/docs/#section/Getting-Started and it can be consumed by other tools without having to jump through hoops. 

 For example, I was able to build https://github.com/naveensrinivasan/stunning-tribble to validate any new `go` dependencies against `osv` with the help of the rest API and not needing a google cloud account.  This brings an advantage of now new dependencies are checked against for OSV's (let's set aside the existing dependencies can have new OSV/CVE which we have to validate as a cron job and also this is an option https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies#detection-of-vulnerable-dependencies)

 HTTP is the standard for querying data.  Now with `150k` repositories, we will have collected significant data and it would be best only if it is accessible as an interface that the community wants in the format.

**Describe the solution you'd like**

Provide a REST endpoint over Scorecard data that can be retrieved from the BigQuery and return as `JSON`

**Comment by naveensrinivasan** [comment]
@kimsterv @bobcatfish were building a demo that used scorecard data and an API would have been helpful.

**Comment by naveensrinivasan** [comment]
One of the options that we discussed was to export the BigQuery `latest` run into cloud buckets so that it provides an HTTP endpoint for consumers to query. 

This avoids us from maintaining a server and handling uptime.

**Comment by azeemshaikh38** [comment]
We are hoping to start work on this soon. Re-opening.

**Comment by naveensrinivasan** [comment]
A design document for this https://docs.google.com/document/d/13Uy6PGNudL9ha-LtSJGLmdBFF1qj6gGoPbs6WyxHy8A/edit?usp=sharing

To access the document please join the google group https://groups.google.com/g/ossf-scorecard-dev

**Comment by naveensrinivasan** [comment]
A design document for this https://docs.google.com/document/d/13Uy6PGNudL9ha-LtSJGLmdBFF1qj6gGoPbs6WyxHy8A/edit?usp=sharing

To access the document please join the google group https://groups.google.com/g/ossf-scorecard-dev

**Comment by mathew-horner** [comment]
@naveensrinivasan

This is awesome to see!

I read through your design document. Is that API ready to be used _now_? The example request in the document seems to work, and I tried it out with a few other repos that also seem to work:

https://ossfscorecard.dev/v2/github.com/vercel/next.js/result.json
https://ossfscorecard.dev/v2/github.com/clap-rs/clap/result.json
https://ossfscorecard.dev/v2/github.com/trpc/trpc/result.json

We would like to start consuming this API if at all possible.

**Comment by naveensrinivasan** [comment]
@mathew-horner Thanks! The API is not yet ready. We are discussing this today. We are hoping to make this available soon! This was a prototype.

**Comment by naveensrinivasan** [comment]
We have agreed to work on this as a feature we had discussed in our Bi-Weekly Scorecard meeting.
