### ISSUE TITLE
Project mvdan.cc/sh/

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1107]
Scorecard uses the mvdan.cc/sh/ for parsing shell-script. This is maintained by a single individual and is looking for sponsorship. 

> Consider becoming a sponsor if you benefit from the work that went into this release! https://github.com/sponsors/mvdan
![Screen Shot 2021-10-05 at 1 27 11 PM](https://user-images.githubusercontent.com/172697/136081472-7bb4bdf6-75a3-4018-806a-2244ea520e40.png)

https://github.com/ossf/scorecard/pull/1098

**Comment by laurentsimon** [comment]
Maybe good opportunity for https://sos.dev/, assuming scorecard is considered a critical piece of software

**Comment by azeemshaikh38** [comment]
@inferno-chromium @meder FYI

**Comment by naveensrinivasan** [comment]
@inferno-chromium @meder Any updates on this? We use this library extensively

> Maybe good opportunity for https://sos.dev/, assuming scorecard is considered a critical piece of software

**Comment by naveensrinivasan** [comment]
I don't know why this was closed. Probably mistake.
