### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#111]
Most of us would like to run a docker run , instead of pulling down the repo. 

There is an existing dockerfile. The docker container has to be built and pushed into a registry.

**Comment by naveensrinivasan** [comment]
@inferno-chromium how about pushing the docker containers into GitHub registry?

**Comment by dlorenc** [comment]
Ah! I already have one publishing to gcr.io. I'll add some documentation about this.

**Comment by naveensrinivasan** [comment]
@dlorenc  Where do we want to publish the non-gsutil docker image https://github.com/ossf/scorecard/pull/114? Github?

**Comment by naveensrinivasan** [comment]
This could be automated with goreleaser https://goreleaser.com/customization/docker/

**Comment by naveensrinivasan** [comment]
It is being published now to Github docker registry https://github.com/orgs/ossf/packages https://github.com/ossf/scorecard/pull/153
