### ISSUE TITLE
BUG - Branch Protection check data in cron

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1115]
**Describe the bug**
I took a sample of 300+ repositories and Branch-Protection is failing in all of them. Are we sure this check is working?

This is failing for `scorecard` also 

```SELECT h.Confidence,h.Name,h.Pass,Repo FROM `openssf.scorecardcron.scorecard`, UNNEST(checks) as h WHERE 
Repo in ("github.com/ossf/scorecard") and 
h.Name = "Branch-Protection"```

**Comment by azeemshaikh38** [comment]
Closing the issue, re-open if needed.
