### ISSUE TITLE
Fix go.mod for v3 release

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1117]
**Is your feature request related to a problem? Please describe.**
Fix the go.mod for the v3 release similar to https://github.com/ossf/scorecard/pull/716

**Comment by azeemshaikh38** [comment]
Thanks for creating this Naveen, I forgot we need to do this step. Do you want take this on?

**Comment by 06kellyjac** [comment]
Can someone please make a release `3.0.1` with this fix

**Comment by naveensrinivasan** [comment]
> Can someone please make a release `3.0.1` with this fix

Thanks, I can do that.
