### ISSUE TITLE
DISCUSSION: v4 milestone

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1121]
To start thinking of our next step towards v4 release, let's write some ideas in this issue. We're thinking of v4 release for EOY 2021.

We can talk about them during next scorecard meeting, create issues and assign them to contributors, and then have them as milestones. Here a list to start with:

- Scorecard scaled to 1M+ repos (P1)
- Scorecard adoption (could be showcasing how to use scorecard to vet dependencies @naveensrinivasan)
- Scorecard CI/CD action finished (market place and verified?)
- Allstar policy for scorecard (joint with allstar)
- Scorecard badges
- Scorecard E2E tests
- Stackdriver cost optimization
- GitHub API rate limits
- Scorecard contributing + communication process
- SLSA compliance checks, verification (doc, 1-2 checks)

Please add what you think is worth discussing about. This will help for selection and prioritization.

Thanks everyone!

**Comment by asraa** [comment]
Random thought that might be nice to do for another release (not sure when v4 is on the timeline): scorecard as in-toto attestation? would mean defining a scorecard predicate and having an output format for that.

Higher levels could sign the envelope (e.g. a github-runner could run scorecard and then sign the in-toto proving that it ran scorecard.

**Comment by laurentsimon** [comment]
automatic documentation generation https://github.com/ossf/scorecard/issues/898

**Comment by laurentsimon** [comment]
This issue https://github.com/ossf/scorecard/issues/426 is an important one, especially the `pull_request_target` trigger.

**Comment by laurentsimon** [comment]
Adding lines to our results https://github.com/ossf/scorecard/issues/725 is an important issue we should tackle for v4 since it improves the UX experience in the GitHub scanning dashboard

**Comment by laurentsimon** [comment]
FYI, Asra @asraa will tackle part of https://github.com/ossf/scorecard/issues/426. Thanks you Asra!

**Comment by laurentsimon** [comment]
Would love to have dangerous workflows in v4 https://github.com/ossf/scorecard/pull/1168, if possible
Long-term, I think we'll merge Token-Permissions into it, as well as the GH pinning that currently lives under pinned dependencies.

**Comment by azeemshaikh38** [comment]
We seem to have a lot more v4 issues than initially discussed. Do we have the time commitment to complete all these extra items? Please note that we are aiming for a mid-Jan timeframe for a v4 release. And with a winter break, it does not give us a lot of time. @laurentsimon @naveensrinivasan 

Extra issues I noted: #1174, #1196, #1038, #1260, #1270, #1275, #1238.

**Comment by laurentsimon** [comment]
I've removed the first one. The others are best effort. Many are simple enough that it's doable, and they improve the checks: I think it's god if we can fix those small issues before releasing. The ignore list for binary artifacts would be great, so I added in case I have time.

**Comment by laurentsimon** [comment]
Aiming for a release mid-January 2022. What's left:
1. verify GH action for market place (WIP)
2. documentation of the action
3. submit starter workflows (WIP)
4. Test end to end flow of installation
5. Install on a few repos OSSF owns and others

**Comment by georgettica** [comment]
hey! I found this v4 when testing locally
```
docker run -v ${PWD}:/app -e SCORECARD_V4=y -e GITHUB_AUTH_TOKEN=token gcr.io/openssf/scorecard:stable --show-details --local=/app
```
makes it much faster to make my codebase comply with scorecard

**Comment by laurentsimon** [comment]
when running on a local repo `--local=`, not all the checks are run. Checks that are run are those that do not use GitHub APIs. Supported checks are indicated thru a `repos: local` in this file https://github.com/ossf/scorecard/blob/main/docs/checks/internal/checks.yaml#L47

**Comment by laurentsimon** [comment]
Closing since v4 is out.
