### ISSUE TITLE
README doesn't say what type of access token to create

### ISSUE THREAD

**Issue by benlaurie** [ossf/scorecard#1139]
What it says on the tin.

**Comment by laurentsimon** [comment]
@olivekl FYI. Can you handle this issue?

**Comment by naveensrinivasan** [comment]
@olivekl Is this still an issue?

**Comment by olivekl** [comment]
Thanks for the reminder, @naveensrinivasan. It's not closed yet, but the change is mostly ready -- @azeemshaikh38, can you weigh in on whether I understood the scope correctly, as described in my previous comment?

**Comment by azeemshaikh38** [comment]
> "When creating the personal access token, we suggest you choose the `public_repo` scope."

I'm still unsure of the scope of this bug. But we can add this line as you have suggested and close this issue. In case that is not enough, folks can choose to re-open the bug or file a new issue.
