### ISSUE TITLE
Feature: crowdsourcing scorecard run via GitHub action

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1144]
We (scorecard team) run scorecard weekly on 200k repos.

This documentation proposes an alternative: let repo owners run scorecard in a GitHub workflow. How do we trust the results then?

This is what the [proposal](https://docs.google.com/document/d/1s9xkRM2EasyEf6tBO8a6vGieMNxN9h3I00UoCQOrnw8/edit?resourcekey=0-CuJDKI0Q0A0P6udmVAhSog#heading=h.ud469ds22f9c) is about, by using OIDC flow.

**Comment by azeemshaikh38** [comment]
Assigning to @asraa since she's helping with this.
