### ISSUE TITLE
Feature: detect code that updates dependency hash pins "manually"

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1175]
Tools that help update dependencies is what we advise user to use in the `Dependency-Update-Tool` check.

Asa result, we should never see, inn a script, a command that tries to update dependencies, e.g. `npm update` - same for other package managers.

We should add support to check for such commands in the `Pinned-Dependencies` check.

**Comment by azeemshaikh38** [comment]
Does it make more sense for this to be part of `Dependency-Update-Tool`? Basically, what if we upgrade the scope of `Dependency-Update-Tool` to check how projects manage their different dependencies (automatically or manually)and score them accordingly?

**Comment by laurentsimon** [comment]
Good point, I think you're right. It's going to take some effort to re-use the shell utility functions and disentangle them from the `Pinned-Dependency` check. Adding to `Pinned-Dependency` is straight forward. 

Is there value in first landing it in `Pinned-Dependency` check to have the data available, and then 2) work on the more long-term solution?

**Comment by azeemshaikh38** [comment]
If its easier to add it in `Pinned-Dependencies` then let's do that, no need to complicate.

On a separate note though, its weird that these generic file parsing util fns are tied to checks. Maybe we should separate these out such that any check can use them. Probably have a `fileparser` package inside the `checks` package to do this. Wdyt?

**Comment by laurentsimon** [comment]
> If its easier to add it in `Pinned-Dependencies` then let's do that, no need to complicate.
> 
> On a separate note though, its weird that these generic file parsing util fns are tied to checks. Maybe we should separate these out such that any check can use them. Probably have a `fileparser` package inside the `checks` package to do this. Wdyt?

definitely, we should do that. Once it's done, we can move the code to `Dependency-Update-Tool`. I'll create a PR
