### ISSUE TITLE
Feature - Vendor dependencies for hermetic builds

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1188]
**Is your feature request related to a problem? Please describe.**
Vendor dependencies for hermetic builds.

**Comment by laurentsimon** [comment]
Can you elaborate a little more?
1. Is this "let's do it for scorecard builds" or "let's add a check in scorecard"? 
2. What do you mean by vendored dependencies? Is it like hash pinning? Or you're thinking of "runtime" vendored dependencies (fetch dependencies then build without network access)? If the former, what are the advantages of vendored vs hash pinning? Are tools like dependabot/renovabot able to update dependencies that are copied into a repo?

**Comment by laurentsimon** [comment]
where does go stored the vendored dependencies?

**Comment by naveensrinivasan** [comment]
https://golang.org/ref/mod#go-mod-vendor `/vendor` and  here are a couple of examples 

- https://github.com/tektoncd/chains/tree/main/vendor 
- https://github.com/kubernetes/kubernetes/tree/master/vendor

**Comment by laurentsimon** [comment]
do you know how much latency this would add to the download of the tarball?
Let's add this topic to the agenda for next meeting?

**Comment by naveensrinivasan** [comment]
> do you know how much latency this would add to the download of the tarball?
Could you please explain which tarball? The `Scorecard` or our dependencies.

> Let's add this topic to the agenda for next meeting?
Yes I will.

**Comment by justaugustus** [comment]
Closing as not planned given the discussion in https://github.com/ossf/scorecard/pull/1208.
