### ISSUE TITLE
Feature: add unit test for `getEnabledChecks()` function in `cmd/root.go`

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1196]
Function `getEnabledChecks()` determines which checks are enabled, using a combination of 1) supported checks for the repo interface, 2) wether a policy is given or not, 3) whether `--checks` is passed as argument or not.

Changing this behavior would be a breaking change.

**Comment by naveensrinivasan** [comment]
https://github.com/ossf/scorecard/pull/1750

**Comment by afmarcum** [comment]
Closing this issue as v4 has been released and related issues added since reopening this issue have also been closed.
