### ISSUE TITLE
Active != 90-day releases

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#120]
The current definition of "active" is:

* Did the project get any commits and releases in last 90 days?

I think this is a *terrible* definition. Many projects intentionally do not release every 90 days, nor do their users want that kind of churn.

Can we please change "and" to "or"? Or alternatively, remove "and releases" entirely?

**Comment by inferno-chromium** [comment]
I think we mean EITHER commits OR releases. Should i fix that in docs or you want to get rid of releases completely. I think just commits should be sufficient, i am trying to remember why i added releases as well.

**Comment by inferno-chromium** [comment]
removing releases.
