### ISSUE TITLE
Should we add check for this trojan source attack?

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#1205]
**Is your feature request related to a problem? Please describe.**
https://www.trojansource.codes/trojan-source.pdf

**Describe the solution you'd like**
Unsure, detect those code sequences in code. Will be pretty heavy weight check, lets think it through.

**Describe alternatives you've considered**
Still to be evaluated.

**Additional context**
https://twitter.com/rossjanderson/status/1454962928923418626
https://twitter.com/briankrebs/status/1455028491938934792
https://twitter.com/matthew_d_green/status/1455151344491405312

**Comment by azeemshaikh38** [comment]
I think its a good idea. We can check for the presence of bidirectional unicode characters in any text file. If we are able to get in a v0 by EOW, next week's cron job results can show the state of OSS with regards to this vulnerability.

**Comment by azeemshaikh38** [comment]
In the long run, maybe it makes more sense for this to be part of Package Analysis? @oliverchang fyi.

**Comment by naveensrinivasan** [comment]
> In the long run, maybe it makes more sense for this to be part of Package Analysis? @oliverchang fyi.

Package Analysis is all about runtime analysis not inspecting the source code. 

This should be in more of linters like `gosec` IMO.

 Are we sure that there won't be any uses case the `bidirectional unicode characters ` would be desired need? 
 If we identify do flag them as a major vulnerability?  I think we need to have answers to these questions.

**Comment by oliverchang** [comment]
We are actually planning to add more static analysis to package analysis, as that provides useful signals in addition to dynamic analysis. 

FYI @calebbrown who will be working more on package analysis.

**Comment by inferno-chromium** [comment]
If you want to create a generic code search check that searches various patterns, then fine to add this as well, but this is not a priority now given limited impact.

**Comment by azeemshaikh38** [comment]
Yeah, we can skip a new check for now since impact is not too high. But this is an interesting threat vector to detect. @oliverchang @calebbrown should we track this in PackageAnalysis project and close this issue in Scorecard?
