### ISSUE TITLE
Change Fuzzing measurement

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#121]
The current definition of "Fuzzing" is:

* Does the project use OSS-Fuzz?

I think the definition should be:

* Does the project use fuzzing to detect security vulnerabilities (e.g., by using OSS-Fuzz)?

If they do fuzzing some other way it should be fine. It may be harder to detect, but that's okay, that can be improved over time as long as the definition allows for it.

**Comment by inferno-chromium** [comment]
> The current definition of "Fuzzing" is:
> 
> * Does the project use OSS-Fuzz?
> 
> I think the definition should be:
> 
> * Does the project use fuzzing to detect security vulnerabilities (e.g., by using OSS-Fuzz)?
> 
> If they do fuzzing some other way it should be fine. It may be harder to detect, but that's okay, that can be improved over time as long as the definition allows for it.

Yes agree, fixed in docs.
