### ISSUE TITLE
Feature: More output format options

### ISSUE THREAD

**Issue by hectorcustodiozup** [ossf/scorecard#1221]
**Is your feature request related to a problem? Please describe.**
The generated table output is not always clear. Sometimes the lines break inconsistenly which dificults readability

**Describe the solution you'd like**
I would like to have an option to generate the output results in file or concise object form as JSON, so it could be saved or used as output from github workflows for example.

**Additional context**
I would like to help on the development of this improvement if it makes sense and could be achieved.

**Comment by laurentsimon** [comment]
It's supported: run `--format json`, you can pipe it into a file as `--format json > results.json`

**Comment by hectorcustodiozup** [comment]
Hello @laurentsimon,

Thanks, that's exactly what I needed. I missed this in the documentation I'm sorry. I'm closing the issue.
