### ISSUE TITLE
The "Fuzzing" check doesn't seem to always work correctly

### ISSUE THREAD

**Issue by evverx** [ossf/scorecard#1231]
**Describe the bug**

According to `scorecards` some projects like [`util-linux`](https://github.com/google/oss-fuzz/tree/master/projects/util-linux) and [`selinux`](https://github.com/google/oss-fuzz/blob/master/projects/selinux/project.yaml) aren't fuzzed on OSS-Fuzz even though they have been fuzzed there since 2020 as far as I can remember.

**Reproduction steps**
```
$ ./scorecard-linux-amd64 version
GitVersion:	v3.1.1
GitCommit:	fd238d0e40ebc898e4aa592ad133b1f15687384f
GitTreeState:	clean
BuildDate:	1635283925
GoVersion:	go1.17.2
Compiler:	gc
Platform:	linux/amd64
```
```
$ GITHUB_AUTH_TOKEN=*** ./scorecard-linux-amd64 --show-details  --checks=Fuzzing --repo=https://github.com/util-linux/util-linux
Starting [Fuzzing]
Finished [Fuzzing]

RESULTS
-------
Aggregate score: 0.0 / 10

Check scores:
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
| SCORE  |  NAME   |             REASON             | DETAILS |                                       DOCUMENTATION/REMEDIATION                                        |
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
| 0 / 10 | Fuzzing | project is not fuzzed in       |         | https://github.com/ossf/scorecard/blob/fd238d0e40ebc898e4aa592ad133b1f15687384f/docs/checks.md#fuzzing |
|        |         | OSS-Fuzz                       |         |                                                                                                        |
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
```
```
$ GITHUB_AUTH_TOKEN=*** ./scorecard-linux-amd64 --show-details  --checks=Fuzzing --repo=https://github.com/SELinuxProject/selinux
Starting [Fuzzing]
Finished [Fuzzing]

RESULTS
-------
Aggregate score: 0.0 / 10

Check scores:
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
| SCORE  |  NAME   |             REASON             | DETAILS |                                       DOCUMENTATION/REMEDIATION                                        |
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
| 0 / 10 | Fuzzing | project is not fuzzed in       |         | https://github.com/ossf/scorecard/blob/fd238d0e40ebc898e4aa592ad133b1f15687384f/docs/checks.md#fuzzing |
|        |         | OSS-Fuzz                       |         |                                                                                                        |
|--------|---------|--------------------------------|---------|--------------------------------------------------------------------------------------------------------|
```

**Comment by asraa** [comment]
I can try to debug this. I can definitely repro it.

**Comment by azeemshaikh38** [comment]
Thanks @asraa. Assigning this to you.

**Comment by asraa** [comment]
Might need to replace the `-` with `.` when building the query

```
 curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/search/code?q=repo:google/oss-fuzz+github.com/util.linux/util.linux
```

**Comment by evverx** [comment]
@asraa thanks for looking into this! I didn't know `scorecard` uses the GitHub API. I somehow thought it just cloned the oss-fuzz repository and looked for urls there :-)

> As far as the SElinux project, that one I can't seem to figure out properly.

According to https://docs.github.com/en/search-github/searching-on-github/searching-code#considerations-for-code-search, it seems `/` can't be used as part of search queries. I replaced `/` with `+` and ran something like
```
curl   -H "Accept: application/vnd.github.v3+json"   'https://api.github.com/search/code?q=repo:google/oss-fuzz+filename:project.yaml+github.com+SELinuxProject+selinux'
```
It worked but I have to admit I have no idea why

**Comment by azeemshaikh38** [comment]
This is a great find @evverx and @asraa! If I understand correctly, the problem is the special characters as mentioned here:

![image](https://user-images.githubusercontent.com/4825078/141334929-36667b29-7cab-4f1b-a1e1-77f242dc8ea2.png)

When I replaced `/` with space, the queries seem to work. So I can think of 2 solutions here:

- Option 1: Update the GitHub API search query to replace all special characters with space. This may cause a small amount of false positives but it's probably better than what we currently have.
- Option 2: Replace the GitHub API search with a local search instead.  i.e locally download the oss-fuzz repo and use our [local `RepoClient`](https://github.com/ossf/scorecard/blob/main/clients/localdir/client.go) to do the search instead. 

@asraa or @evverx what do you think? Also, would either of you be interested in taking this up?

**Comment by asraa** [comment]
I just created a PR https://github.com/ossf/scorecard/pull/1241

**Comment by evverx** [comment]
> So I can think of 2 solutions here

I think option 2 would be better in the sense that it seems to be more reliable but given that at this point I'm not sure how many false positives the current check might produce I think it would make sense to just keep the code sending search queries via the GitHub API.

> Also, would either of you be interested in taking this up?

@azeemshaikh38 I just followed the links @asraa posted and then poked the requests until they worked without fully understanding what was going there :-) so I don't think I could have come up with a proper fix.

> I just created a PR #1241

@asraa thanks!

**Comment by evverx** [comment]
I'm not sure why GitHub didn't close it automatically. Closing. Thanks!
