### ISSUE TITLE
Feature: Improve `CII-Best-Practices-Badge` API access

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#1240]
Scorecard check for `CII-Best-Practices-Badge` makes a single HTTP request per repo. With our current scale of 1M repos, the cron job constantly receives 429 errors and is also affecting the CII Best Practices servers. To remediate this, will use the page-based API to pre-download the data into Google Cloud and access this instead - https://github.com/coreinfrastructure/best-practices-badge/blob/main/doc/best_practices.py

@david-a-wheeler FYI.

**Comment by david-a-wheeler** [comment]
Thanks so much! I think this optimization will improve help both Scorecard & CII Best Practices.
