### ISSUE TITLE
The "Code Review" check seems to reject "reviewed" PRs

### ISSUE THREAD

**Issue by evverx** [ossf/scorecard#1260]
Looking at https://github.com/ossf/scorecard/blob/51de6b6e5d9b025561b15c30cbb498bf31101427/checks/code_review.go#L118-L128

and https://github.com/systemd/systemd/pull/21305 (which was rejected by the check because due to the "rebase" button it was presumably created, reviewed and merged by the same person as far as I can tell) I don't think the check should always rely on whatever `pr.MergeCommit.Committer.Login` is. It seems `.merged_by.login` could have helped in this case:
```
curl  --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/systemd/systemd/pulls/21305 |
jq .merged_by.login,.user.login
```
```
"poettering"
"ml-"
```

**Comment by azeemshaikh38** [comment]
Is this now fixed?

**Comment by evverx** [comment]
I don't think it's fixed. https://github.com/ossf/scorecard/pull/1272 is still open because as far as I understand it needs more tests

**Comment by azeemshaikh38** [comment]
Thanks @evverx. Is #1272 the only pending thing here?

**Comment by evverx** [comment]
Yes, I think it is.

As far as I can remember I ran into another issue with the "code review" check but I haven't figured out what it was yet so I think it's safe to assume that it has nothing to do with this issue :-)

I'm not sure if it helps but with #1272 applied the systemd code-review score went from
```
      "score": 7,
      "reason": "GitHub code reviews found for 23 commits out of the last 30 -- score normalized to 7",
```
to
```
      "score": 9,
      "reason": "GitHub code reviews found for 29 commits out of the last 30 -- score normalized to 9",
```

**Comment by evverx** [comment]
As far as I understand scorecard switched to commits and associated PRs (where it should be relatively easy to figure out who commiters and authors are). I'm not sure whether it works as expected in its current form but I think this issue is kind of out of date and can be closed.
