### ISSUE TITLE
Feature: enable branch protection on pull request for GitHub action

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1271]
I'd be useful to enable BP on pull request triggers for the GH action.

**Comment by laurentsimon** [comment]
Possible ways to do it:

1. Create a new repo interface for GitHub that does only uses a graphClient for BP check and a local folder for the rest.
2. Run scorecard twice in the GitHub action: once on a local repo, once on a GitHub repo. Then concatenate both results into a single SARIF file. For this we need a utility: `jq`, our own, etc.
3. Same as 2, but make our GH action return multiple files. This is confusing for users.

**Comment by spencerschrock** [comment]
(doing some milestone cleaning)

Due to the age, and lack of interest, I'm going to close this. We can always re-open in the future.
Personally I don't see the value in the branch protection data for the `pull_request` trigger, as it's not something that would be modified by the PR.
