### ISSUE TITLE
Should scorecard be forcing users to use a zap.Logger?

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1273]
External packages like Allstar would like to use as a scorecard as a Library. 
https://github.com/ossf/allstar/blob/913bb71913d373d0daaf2a59957c3610d2522e50/pkg/policies/binary/binary.go#L120
https://github.com/ossf/scorecard/blob/1050b1cd607b3686641c96ac071ae6774e60588f/clients/githubrepo/client.go#L183

This API call is forcing the consumers to use `zap.Logger`. This should not be forced to use a specific logger. It could be interface for logging, not a specific implementation.

**Comment by laurentsimon** [comment]
I agree it should not.

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 FYI...

**Comment by jeffmendoza** [comment]
Ideally CreateGitHubRepoClient() can be refactored to take a [`DetailLogger`](https://github.com/ossf/scorecard/blob/63e3b92466f0403159c02f1ccedd43f9400e8b26/checker/check_result.go#L81) instead of a zap.Logger.

**Comment by justaugustus** [comment]
I _might_ be able to pick this up after https://github.com/ossf/allstar/pull/98.
(Just commenting to shake up the stale bot...)

**Comment by azeemshaikh38** [comment]
Thanks @justaugustus!

**Comment by justaugustus** [comment]
Working on this in https://github.com/ossf/scorecard/pull/1502.

**Comment by justaugustus** [comment]
The first bit is merged in https://github.com/ossf/scorecard/pull/1502.
Before I continue, I want check in on something...

What's the motivation behind https://github.com/ossf/scorecard/blob/0d76deace2b3edd9216a15ec5a8387130acd8db4/checker/detail_logger_impl.go#L42-L50?

More specifically, the function argument, `(msg *LogMessage)`:

```go
func (l *logger) Info3(msg *LogMessage) { ... }
```

`*LogMessage` makes it hard to do `logger.Info3()` without first doing something like:

```go
log := &LoggerMessage{}
log.Text = "the thing I want to log"

logger.Info3(log)
```

I just want to make sure I'm not missing something about the intended ergonomics, before trying to implement.

Perhaps something variadic could work nicely here?

```go
// Adds a struct of fields to the log entry. All it does is call `WithField` for
// each `Field`.
func (logger *Logger) WithFields(fields Fields) *Entry {
	entry := logger.newEntry()
	defer logger.releaseEntry(entry)
	return entry.WithFields(fields)
}
```

ref: https://github.com/sirupsen/logrus/blob/85981c045988a3ebe607e2f5b8a6499d86e0ddac/logger.go#L121-L127

e.g.,

```go
logger := log.Logger().WithFields()
```

where the fields are roughly the fields of the `LogMessage` struct.

---

Another question...
Is the intent to use https://github.com/ossf/scorecard/blob/0d76deace2b3edd9216a15ec5a8387130acd8db4/checker/detail_logger.go#L17-L28

for all program logs or just the checker?

**Comment by laurentsimon** [comment]
> The first bit is merged in #1502. Before I continue, I want check in on something...
> 
> What's the motivation behind
> 
> https://github.com/ossf/scorecard/blob/0d76deace2b3edd9216a15ec5a8387130acd8db4/checker/detail_logger_impl.go#L42-L50
> 
> ?
> More specifically, the function argument, `(msg *LogMessage)`:
> 
> ```go
> func (l *logger) Info3(msg *LogMessage) { ... }
> ```
> 
> `*LogMessage` makes it hard to do `logger.Info3()` without first doing something like:
> 
> ```go
> log := &LoggerMessage{}
> log.Text = "the thing I want to log"
> 
> logger.Info3(log)
> ```
> 
> I just want to make sure I'm not missing something about the intended ergonomics, before trying to implement.

the motivation for the structure is that we wanted to be able to add fields to the function without changing the function signature - because it requires going thru all calls and updating them :/

> Perhaps something variadic could work nicely here?
> 
> ```go
> // Adds a struct of fields to the log entry. All it does is call `WithField` for
> // each `Field`.
> func (logger *Logger) WithFields(fields Fields) *Entry {
> 	entry := logger.newEntry()
> 	defer logger.releaseEntry(entry)
> 	return entry.WithFields(fields)
> }
> ```
> 
> ref: https://github.com/sirupsen/logrus/blob/85981c045988a3ebe607e2f5b8a6499d86e0ddac/logger.go#L121-L127
> 
> e.g.,
> 
> ```go
> logger := log.Logger().WithFields()
> ```

I think variadic function would work. Is there a way to fix the list of acceptable fields in order to detect typo mistakes at compilation time?

> where the fields are roughly the fields of the `LogMessage` struct.
> 
> Another question... Is the intent to use
> 
> https://github.com/ossf/scorecard/blob/0d76deace2b3edd9216a15ec5a8387130acd8db4/checker/detail_logger.go#L17-L28
> 
> for all program logs or just the checker?

We only use if for the checker today, because those "logs" are a way to convey the results of each check. I think it's fair to say this is not going to change.

**Comment by justaugustus** [comment]
@laurentsimon --

> I think variadic function would work.

Okay thanks, that makes this a bit more flexible.

> Is there a way to fix the list of acceptable fields in order to detect typo mistakes at compilation time?

I think ideally, we don't expose the opportunity for a mistake.
For each client, there will be an idea of what kind of data you want out of the logs, so we can force the client to do the right things.

WARNING, pseudocode ahead:

```go
func AllOfTheThings() {
    t1 := NewThing1Client()
    t1.Do()

    t2 := NewThing2Client()
    t2.Do()

    t3 := NewThing3Client()
    t3.Do()
}

func NewThing1Client() *Thing1Client {
    logger := log.NewLogger()
    logger.WithFields(/* thing1-specific fields */)

    client := &Thing1Client{
        Log: logger,
    }

    return &client
}

type Thing1Client struct {
    Log log.Logger
    /* other thing1 stuff */
}

func (t1 *Thing1Client) Do() {
    t1.Log.Info("look at all of the thing1 stuff we're doing!")
}
```

Maybe you expose the log level for configuration, but let give the client the responsibility of setting the context/fields that are unique to it.

> We only use if for the checker today, because those "logs" are a way to convey the results of each check. I think it's fair to say this is not going to change.

SGTM!

**Comment by laurentsimon** [comment]
SGTM. @naveensrinivasan @justaugustus  @azeemshaikh38 thoughts?

**Comment by justaugustus** [comment]
> SGTM. @naveensrinivasan @justaugustus @azeemshaikh38 thoughts?

Yep, I'm happy to roll with the https://github.com/go-logr/logr API!
Will wait for another +1 from a maintainer before proceeding.

**Comment by thockin** [comment]
And, you know, drop me a line if it doesn't satisfy for some reason.

**Comment by justaugustus** [comment]
> And, you know, drop me a line if it doesn't satisfy for some reason.

Hehe, always happy to bug you, Tim! :)

**Comment by azeemshaikh38** [comment]
> SGTM. @naveensrinivasan @justaugustus @azeemshaikh38 thoughts?

I love it! I have not looked into the implementation/code, but from the description it seems to fit our usecase pretty well. It'll definitely help if we can clean up our logging interfaces and piggy back on an existing and well trusted interface instead.

**Comment by justaugustus** [comment]
Calling this closed w/ https://github.com/ossf/scorecard/pull/1516.
