### ISSUE TITLE
BUG: `urllib3/urllib3` security policy not detected in cron run

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1275]
The 9th Nov cron job contains `repo unreachable: GET https://api.github.com/repos/urllib3/.github: 404 Not Found []`.
Yet, there is a `.github/security.md` on their repo dating back to 4 months ago.
When running scorecard locally, I get the correct results, i.e. the security file is detected

**Comment by laurentsimon** [comment]
@azeemsgoogle FYI

**Comment by laurentsimon** [comment]
additional info:

urllib3: github.com/urllib3/urllib3 , commit:fac7db19a1e8e15e5b302e2203ce35cd0485bc88 
scorecard: 3.1.1-39-g4fbd0fe, commit: 4fbd0fe93ec800e42fddf6a66a39298c76a829bb

**Comment by azeemshaikh38** [comment]
This is now fixed
