### ISSUE TITLE
scorecard seems to miss some status checks

### ISSUE THREAD

**Issue by evverx** [ossf/scorecard#1322]
Looking at the results of the SAST check I noticed that sometimes `scorecard` says that some status checks (namely `lgtm-com`) weren't run even though they were. GitHub API described at https://docs.github.com/en/rest/reference/checks#get-a-check-suite has no problem finding them:
https://github.com/libbpf/libbpf/pull/353
```
$ curl --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/libbpf/libbpf/commits/aafe84ae9b8e7b837c6469e48e85f7c3769c79b6/check-suites | jq '.check_suites[] | .app.slug, .latest_check_runs_count'
"lgtm-com"
1
"github-actions"
13
"github-actions"
13
"github-actions"
13
```
https://github.com/mesonbuild/meson/pull/9576
```
$ curl --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/mesonbuild/meson/commits/53120d13e56f8536dfb093a35fb90559c171295a/check-suites | jq '.check_suites[] | .app.slug, .latest_check_runs_count'
"lgtm-com"
2
"github-actions"
1
"github-actions"
3
"github-actions"
1
"github-actions"
1
"github-actions"
2
"github-actions"
1
"github-actions"
3
"github-actions"
12
"github-actions"
4
"azure-pipelines"
7
"codecov"
2
```
I'm not sure how exactly `ListCheckRunsForRef` is implemented but it seems it's different from what the "check-suites" returns.

**Comment by evverx** [comment]
It's kind of related to https://github.com/ossf/scorecard/issues/1322

**Comment by laurentsimon** [comment]
It's using https://github.com/google/go-github/blob/master/github/checks.go#L250
They also expose check suites API, see https://github.com/google/go-github/blob/master/github/checks.go#L274

if you give it a try, let us know.

cc @azeemsgoogle

**Comment by evverx** [comment]
Apparently https://github.com/google/go-github/blob/master/github/checks.go#L250 is where `lgtm-com` gets lost because with `check-runs` instead of `check-suites` I can no longer see it anywhere:
```
curl --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/mesonbuild/meson/commits/53120d13e56f8536dfb093a35fb90559c171295a/check-runs |
grep -i lgtm
```

**Comment by laurentsimon** [comment]
so you're saying this is a GitHub issue maybe? Shall we file an issue on GitHub repo?

**Comment by evverx** [comment]
I'm not sure it's a GitHub issue given that they provide both [check-runs](https://docs.github.com/en/rest/reference/checks#list-check-runs-for-a-git-reference) and [check-suites](https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference) (which I think should be different from each other. Otherwise, they wouldn't have been split in the first place I think). The question is what exactly `check-runs` and `check-suites` are and when they should be used.

**Comment by evverx** [comment]
According to https://docs.github.com/en/rest/guides/getting-started-with-the-checks-api#about-check-suites
> A check suite is a collection of the check runs created by a single GitHub App for a specific commit. Check suites summarize the status and conclusion of the check runs that a suite includes

> A check run is an individual test that is part of a check suite. Each run includes a status and conclusion.

so as far as I can tell `scorecard` should go over `check_suites` and get every check suite's runs. This way in https://github.com/libbpf/libbpf/pull/353 LGTM would have been found via https://api.github.com/repos/libbpf/libbpf/commits/aafe84ae9b8e7b837c6469e48e85f7c3769c79b6/check-suites and then https://api.github.com/repos/libbpf/libbpf/check-suites/3433098465/check-runs and in https://github.com/mesonbuild/meson/pull/9576 via https://api.github.com/repos/mesonbuild/meson/commits/53120d13e56f8536dfb093a35fb90559c171295a/check-suites and https://api.github.com/repos/mesonbuild/meson/check-suites/4359629405/check-runs.

I'm not sure why those runs aren't included in https://api.github.com/repos/libbpf/libbpf/commits/aafe84ae9b8e7b837c6469e48e85f7c3769c79b6/check-runs and https://api.github.com/repos/mesonbuild/meson/commits/53120d13e56f8536dfb093a35fb90559c171295a/check-runs. That's probably a GitHub issue assuming `check-runs` is supposed to return all the check runs triggered by a commit.

**Comment by evverx** [comment]
> so as far as I can tell scorecard should go over check_suites and get every check suite's runs

On second thought it doesn't seem to be necessary to get every check suite's runs since "check suites summarize the status and conclusion of the check runs that a suite includes"

**Comment by evverx** [comment]
I'm inclined to say that it's probably a GitHub bug and it should be probably fixed elsewhere. Closing.
