### ISSUE TITLE
Feature: integration tests should not require distinct approval

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1329]
The integration tests currently require an approval to run the tests even if the PR is LGTM'ed; and this is needed every time we push a new commit to the PR.

I find myself clicking on buttons to enable integration tests all the time. Is there a better solution?

**Comment by laurentsimon** [comment]
@naveensrinivasan @azeemsgoogle

**Comment by azeemshaikh38** [comment]
IMHO, no. The reason PR approval is not enough to run `e2e` tests is because authors can push commits *after* approval is given. The current methodology ensures that every commit needs an explicit approval to run the `e2e` tests.

FYI, this is how it used to work before too. `ok-to-test` had to be specified on a particular commit. We didn't find this solution painful because `e2e` tests were either not enforced or got skipped.

**Comment by laurentsimon** [comment]
> IMHO, no. The reason PR approval is not enough to run `e2e` tests is because authors can push commits _after_ approval is given. The current methodology ensures that every commit needs an explicit approval to run the `e2e` tests.

this is the same as the Branch Protection's `dismiss review automatically` which we enabled a few months ago and dropped because of usability concerns. Now we're re-introducing it. We have the exact same security concerns without `dismiss review automatically` enabled, yet we don't have it turned on.

> FYI, this is how it used to work before too. `ok-to-test` had to be specified on a particular commit. We didn't find this solution painful because `e2e` tests were either not enforced or got skipped.

and now that we have it enabled, I consider it painful.

**Comment by azeemshaikh38** [comment]
> but changing code after LGTM gives PR submitters `write` permission to the repo.

Not sure I understand this. How exactly does it give PR submitters `write` permission?

> So we're paying a high usability price for less security gains.

If it's that much of a pain (which I personally don't think it is), I'm ok with disabling this. My only condition is that we still require `e2e` tests to pass for all PRs. I'm tired of constantly fixing someone else's broken code.

> What permission does the token need to run the integration tests?

It is a PAT with `:public_repo` scope that will potentially get leaked. If the owner is ok with this, I have no issues.

**Comment by laurentsimon** [comment]
> > but changing code after LGTM gives PR submitters `write` permission to the repo.
> 
> Not sure I understand this. How exactly does it give PR submitters `write` permission?

unreviewed PRs end up being pushed to main branch, so basically PR authors get to push their code unreviewed... wgich is the same as `contents:write` permission. 

> > So we're paying a high usability price for less security gains.
> 
> If it's that much of a pain (which I personally don't think it is), I'm ok with disabling this. My only condition is that we still require `e2e` tests to pass for all PRs. I'm tired of constantly fixing someone else's broken code.

I want the 2e2 tests too.

> > What permission does the token need to run the integration tests?
> 
> It is a PAT with `:public_repo` scope that will potentially get leaked. If the owner is ok with this, I have no issues.

Is it feasible to use the `secrets.GITHUB_TOKEN` that GitHub provisions to workflows with `read-all`? Or it has limitations because it's not a PAT?

**Comment by azeemshaikh38** [comment]
> unreviewed PRs end up being pushed to main branch, so basically PR authors get to push their code unreviewed... which is the same as `contents:write` permission.

Hmm, that's not possible in our case right? Scorecard requires atleast 1 approving review *and* the `e2e` tests to pass at the commit before it can be merged. 

> Is it feasible to use the `secrets.GITHUB_TOKEN` that GitHub provisions to workflows with `read-all`? Or it has limitations because it's not a PAT?

AFAICT, no. `secrets.GITHUB_TOKEN` does not have `:public_repo` scope - https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by naveensrinivasan** [comment]
TBH the new process is painful!

**Comment by laurentsimon** [comment]
> > unreviewed PRs end up being pushed to main branch, so basically PR authors get to push their code unreviewed... which is the same as `contents:write` permission.
> 
> Hmm, that's not possible in our case right? Scorecard requires atleast 1 approving review _and_ the `e2e` tests to pass at the commit before it can be merged.

it is still possible. Once we LGTM, the author can still make changes and push the changes. The only way to force a re-review is to enable the branch protection's `dismiss stale review automatically` setting. E2e tests are testing functionality of the PR, not adversarial coding. Say, PR author writes `if $GITHUB_ACTION == "", open a shell and connect to remote server`: the e2e2 tests would pass, but when someone runs scorecard outside of GitHub actions, it would launch a remote shell.

> > Is it feasible to use the `secrets.GITHUB_TOKEN` that GitHub provisions to workflows with `read-all`? Or it has limitations because it's not a PAT?
> 
> AFAICT, no. `secrets.GITHUB_TOKEN` does not have `:public_repo` scope - https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

That's unfortunate :-(
You've verified that it does not work if we use it? 
I'm personally not very concerned about a read token being leaked. We could rotate it once in a while. ideally, automatic rotation would be nice but it does not seem possible, right?

**Comment by laurentsimon** [comment]
I've spent my entire day clicking buttons to re-enable the integration tests. I also had to wait for 30s every time a new commit is pushed to be able to "approve" the integration tests. I think this GitHub feature is entirely unusable, the same way that `pull request stale dismissal` is.

**Comment by azeemshaikh38** [comment]
> it is still possible. Once we LGTM, the author can still make changes and the changes will be pushed to repo. The only way to force a re-review is to enable the branch protection's `dismiss stale review automatically` setting. E2e tests are testing functionality of the PR, not adversarial coding. Say, PR author writes `if $GITHUB_ACTION == "", open a shell and connect to remote server`: the e2e tests would pass, but when someone runs scorecard outside of GitHub actions, it would launch a remote shell.

I strongly disagree with this. An approval to run e2e tests is given *for a commit*. Which means if the author makes a change after approval, a new approval is needed before the tests can run and the PR can be submitted. The "painful" mechanism is in place to precisely solve for the problem you have mentioned. But anyways, this debate is moot since the issue seems to be whether it's worth keeping this security mechanism for the sake of a PAT. 

And in that matter, like I said - I'm completely ok to remove this as long as: (i) e2e test are not disabled, and (ii) the owner of the PAT is ok with the potential leak (I don't know who owns the current token).

**Comment by azeemshaikh38** [comment]
On a separate note, maybe we should consider setting up a Scorecard GitHub app whose token will be used for e2e tests. That way, its not a PAT that gets leaked and also we don't compete with the cron job for API limits.

**Comment by laurentsimon** [comment]
FYI, Ive created a new token and disabled the need for approval to run the integration tests: they will now run autmatically. We can keep it this way to update the workflow to not use environments too.
