### ISSUE TITLE
BUG: goreleaser proxying fails

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#1337]
goreleaser fails with `error=failed to proxy module` - https://github.com/ossf/scorecard/runs/4301302671?check_suite_focus=true

Most likely due to #1282. @naveensrinivasan assigning this to you. Feel free to re-assign if this is unrelated to changes in #1282.

**Comment by naveensrinivasan** [comment]
The issue with this is timing. The build was run because there was new tag that was pushed `3.2.1`

```
 proxying go module
62
      • proxying github.com/ossf/scorecard/v3@v3.2.1 to build github.com/ossf/scorecard/v3
63
   ⨯ release failed after 46.73s error=failed to proxy module: exit status 1: go: github.com/ossf/scorecard/v3@v3.2.1: verifying go.mod: github.com/ossf/scorecard/v3@v3.2.1/go.mod: reading https://sum.golang.org/lookup/github.com/ossf/scorecard/v3@v3.2.1: 410 Gone
64
	server response: not found: github.com/ossf/scorecard/v3@v3.2.1: invalid version: unknown revision v3.2.1
65

```
But the go proxy didn't have that version yet. I re-ran the action and it ran successfully.

**Comment by naveensrinivasan** [comment]
@caarlos0 How can we solve this issue? Any suggestions would be helpful.

**Comment by caarlos0** [comment]
in theory it should have proxied it on the first try, not idea why it didn't though... maybe some flake on sum.golang.org?

**Comment by naveensrinivasan** [comment]
> in theory it should have proxied it on the first try, not idea why it didn't though... maybe some flake on sum.golang.org?

OK, we will try again and let you know. Thanks
