### ISSUE TITLE
scorecard shouldn't complain about actions in the same repository

### ISSUE THREAD

**Issue by evverx** [ossf/scorecard#1340]
It's possible to reference actions that are kept in the same repository using `./path/to/dir`: https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#referencing-an-action-in-the-same-repository-where-a-workflow-file-uses-the-action. I don't think scorecard should complain about them.

**Comment by laurentsimon** [comment]
Great catch, thanks! Feel free to send a PR and cc me on it for approval.

**Comment by laurentsimon** [comment]
see https://github.com/ossf/scorecard/pull/1357
