### ISSUE TITLE
BUG: --local option is broken

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1353]
at this line https://github.com/ossf/scorecard/blob/main/cmd/root.go#L322, we're creating clients that use GitHub APIs. When run on a local repo, this forces users to define a GitHub token which is not needed.

These clients should only be created if they are requested by a user who runs scorecard, i.e. if the checks are requested.

I think the fix is as simple as leaving these variables `nil` if the checks are not requested by users.

**Comment by laurentsimon** [comment]
@azeemsgoogle can you tackle this? 

fyi, @naveensrinivasan this is another case that requires unit test to prevent it from happening again.

**Comment by laurentsimon** [comment]
I'll take it, since I needed to fix it for testing anyway.

**Comment by azeemshaikh38** [comment]
Ouch. I had also created a commit for it. We can go with your PR itself. Just added comment to your PR.

**Comment by laurentsimon** [comment]
closed by https://github.com/ossf/scorecard/pull/1355
