### ISSUE TITLE
Feature Pinned SHA versions of GitHub Actions

### ISSUE THREAD

**Issue by developer-guy** [ossf/scorecard#1362]
**Is your feature request related to a problem? Please describe.**

This is not related to a problem, it is more like a question, or maybe improvement. In GitHub Actions there is a security consideration related to 3rd party GA, so, GitHub recommends us to use `Pinned SHA` of the 3rd party GA[^1]. I thought that it'd be nice to add this check to the scorecard project.

**Describe the solution you'd like**

Verify GitHub Actions whether they use pinned SHA or version. 

**Describe alternatives you've considered**

**Additional context**

There are already side projects that ensure that like the following:

* https://michaelheap.com/ensure-github-actions-pinned-sha
* https://michaelheap.com/improve-your-github-actions-security/

[^1]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

cc: @naveensrinivasan @dentrax

**Comment by naveensrinivasan** [comment]
@developer-guy Thanks, we already have pinned SHA check for GitHub Actions.

**Comment by developer-guy** [comment]
I mean we can add this security check to the scorecard project.

**Comment by naveensrinivasan** [comment]
> I mean we can add this security check to the scorecard project, so, we can start verifying open-source projects whether they use Pinned SHA versions of GitHub actions in their workflows, this is what I wanted to say above.

Sorry If I wasn't clear. We already have it. https://github.com/ossf/scorecard/blob/b323cded0449828ecdfdfd0e6df7313417434576/checks/pinned_dependencies.go#L543
