### ISSUE TITLE
Upgrade github.com/google/go-containerregistry from 0.6.0 to 0.7.0.

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1382]
**Is your feature request related to a problem? Please describe.**
The github.com/google/go-containerregistry  has a breaking change from 0.6.0 to 0.7.0. The code has to be addressed to fix this issue.

More information https://github.com/ossf/scorecard/pull/1281

**Comment by justaugustus** [comment]
Reattempting in https://github.com/ossf/scorecard/pull/1506.
