### ISSUE TITLE
Support for Gitlab Repositories

### ISSUE THREAD

**Issue by kuchanamounika** [ossf/scorecard#1383]
Hi Team,

is there any support provided for gitlab repos score card?

Thanks
Mounika Kuchana

**Comment by dota17** [comment]
Maybe it's the same as #40 and #868 .

For the upcoming release, it isn't. PR's are welcome.

**Comment by naveensrinivasan** [comment]
Closing it as it duplicate https://github.com/ossf/scorecard/issues/40
