### ISSUE TITLE
Question: which category will scorecard action be in?

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1434]
The scorecard GitHub action uses the "Code Scanning" property https://github.com/actions/starter-workflows/blob/main/code-scanning/properties/scorecards.properties.json#L6

When clicking New workflow on the Action tab, e.g., in https://github.com/ossf/scorecard/actions/new, only 3 categories are presented: Deployment, Continuous integration and  Automation. I don't see a Code Scanning category.

Will the scorecard action feature a new category?

cc @josepalafox

**Comment by josepalafox** [comment]
Currently these show under the security tab after clicking "set up code
scanning" we are in progress migrating everything in the security tab into
the main actions page under code scanning, so yes there will be a new
category in the coming weeks.

**Comment by laurentsimon** [comment]
awesome, thanks!
cc @azeemsgoogle
