### ISSUE TITLE
Issue and Comment structs aren't consistent

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1448]
The issue date is a pointer
https://github.com/ossf/scorecard/blob/192ae4d18fbaaeb7d2510b1116c26c817825e210/clients/issue.go#L22

whereas the commit date is not a pointer
https://github.com/ossf/scorecard/blob/192ae4d18fbaaeb7d2510b1116c26c817825e210/clients/commit.go#L21

This needs to be consistent.

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 FYI...

**Comment by azeemshaikh38** [comment]
Thanks for bringing this up. I think #1242 should have handled this, but I mistakenly closed the issue before completing it. I'm marking this as duplicate of #1242
