### ISSUE TITLE
Use compressed versions of the two png logos

### ISSUE THREAD

**Issue by cqueern** [ossf/scorecard#1485]
Optimized images load faster and consume less data.  Currently the two png files in the [artwork directory](https://github.com/ossf/scorecard/tree/main/artwork) are not optimized. 

Suggest using the two attached png files instead of the two png files that are currently available. 

* openssf_security.png is currently 197kb and would be reduced to 126kb (about 36% savings).
* openssf_security_alt.png is currently 205 kb and would be reduced to 135kb (about 36% savings).

The proposed png files were optimized using [imageoptim](https://github.com/ImageOptim/ImageOptim) 1.8.8.
![openssf_security_alt](https://user-images.githubusercontent.com/1588185/149866168-d8a87845-2d02-4110-99ee-85a8363f2531.png)
![openssf_security](https://user-images.githubusercontent.com/1588185/149866169-db7c04fe-6753-494c-9ba6-2e10ca925484.png)

**Comment by naveensrinivasan** [comment]
Thanks! Could you open a PR for this?
