### ISSUE TITLE
BUG: Maintained check list issue update from non-maintainers

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1488]
In the Maintained check, we look for issue thru `c.RepoClient.ListIssues()`. I think anyone can create issues, but that does not indicate that the maintainers are active. We should either look for closed issues or comments by maintainers (users who have committed to the main branch, for example)

I have not looked in details, though.

cc @azeemsgoogle

**Comment by chrismcgehee** [comment]
I could work on this one. The [Issue](https://docs.github.com/en/graphql/reference/objects#issue) object has `closedAt` so it will be easy to check if the issue has been closed in the past 90 days. It also has a `comments` field which has an `authorAssociation` field. We can check if any comments from the past 90 days are from one of these [personas](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation):
- OWNER
- MEMBER
- COLLABORATOR

**Comment by azeemshaikh38** [comment]
That's a pretty neat solution @chrismcgehee, I like it! If it's possible to figure out the persona who `opened`, `closed` or `updated` the issue, that'd be awesome. If not, let's proceed with the `comment` and `authorAssociation` part of it for now and we can iterate on it further. Wdut?

**Comment by laurentsimon** [comment]
very neat! Are we going to change the signature of `ListIssues()` to have input parameters?

**Comment by chrismcgehee** [comment]
@azeemshaikh38 I can use the `authorAssociation` field on the issue itself to figure out the persona who opened the issue. Figuring out updates on the issue would be trickier. I think I'd have to use `timelineItems` which is a union of like 30 different types, so the code would be very complex if we wanted to find the persona of the updater. I won't do that now; it probably won't ever make sense to do it, but we can always revisit later.

@laurentsimon I don't think I'll need to give input parameters to `ListIssues()`. I'll add additional fields to the `Issue` struct, but other than that, the `RepoClient` interface should stay the same.

**Comment by azeemshaikh38** [comment]
SGTM @chrismcgehee, thanks!

**Comment by laurentsimon** [comment]
fyi, I don't think https://github.com/ossf/scorecard/blob/main/checks/maintained.go#L93 is true. I think the creator of an issue can close it even if they are external to a repo and not a collaborator. I think we need to verify who closed the issue, if feasible.
