### ISSUE TITLE
Checks within the SecurityPolicy checks makes it hard to test

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1491]
The security policy check instantiates repo client within the check which makes it hard to unit test
https://github.com/ossf/scorecard/blob/fc874315074dd947bf765199da8f3ac7dd1cc1da/checks/raw/security_policy.go#L78-L83

**Comment by justaugustus** [comment]
@naveensrinivasan -- my team in Kubernetes Release Engineering maintains a GitHub package, which is pretty well-tested and would allow you to offload this.

Could you look around and see if some of this fits your needs?

https://github.com/kubernetes-sigs/release-sdk/blob/main/github/github.go

**Comment by naveensrinivasan** [comment]
@justaugustus  We already have this capability within the scorecard. We use the GitHub library extensively. It so happens this code doesn't use the right method which makes it hard to write unit tests.

**Comment by justaugustus** [comment]
@naveensrinivasan — closing this as discussed in today's meeting that the code path has very likely changed since 2022. Feel free to reopen, if needed.
