### ISSUE TITLE
403 Resource protected by organization SAML enforcement

### ISSUE THREAD

**Issue by nibanks** [ossf/scorecard#1504]
**Describe the bug**

I followed the steps [here](https://github.com/marketplace/actions/ossf-scorecard-action) to add a scorecard action to [microsoft/msquic](https://github.com/microsoft/msquic) with [this PR](https://github.com/microsoft/msquic/pull/2310). The Action [passed](https://github.com/microsoft/msquic/actions/runs/1724043976) on the PR.

After I merged the PR, the action [failed](https://github.com/microsoft/msquic/runs/4887778614?check_suite_focus=true) though:

```
Event file: /github/workflow/event.json
Event name: push
Ref: refs/heads/main
Private repository: false
Publication enabled: true
Format: sarif
Policy file: /policy.yml
2022/01/20 20:05:01 repo unreachable: GET https://api.github.com/repos/microsoft/msquic: 403 Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization. []
panic: repo unreachable: GET https://api.github.com/repos/microsoft/msquic: 403 Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization. []
```
I just double checked my PAT and it exactly matches what is required per the setup instructions. What am I doing wrong? Is the Microsoft organization doing something special on push runs to prevent this from working?

The only difference on my end is that publication is disabled for PRs, but enabled on push to main. Does the above only execute when publication is enabled?

**Comment by azeemshaikh38** [comment]
Thanks for bringing this to our attention @nibanks. Is it possible that [SAML authentication](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/about-authentication-with-saml-single-sign-on) is enabled on you GitHub organization? If so, you'll need to follow the instructions [here](https://docs.github.com/en/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on) to give the right access to your PAT.

Let me know if that works. I did some preliminary digging to find this info.

@laurentsimon this is an interesting corner case. We should look into it and document it for the users.

**Comment by nibanks** [comment]
Ah, yes. The Microsoft org does use SSO. I just enabled that for the PAT and reran the latest workflow and it [passed](https://github.com/microsoft/msquic/runs/4888355764?check_suite_focus=true). So I'd definitely update the PAT instructions to note this edge case and how to fix for it.

Thanks!

**Comment by laurentsimon** [comment]
cc @olivekl

**Comment by azeemshaikh38** [comment]
Thanks for confirming @nibanks. @olivekl @laurentsimon assigning this to you both. Let's update the documentation before closing this issue.
