### ISSUE TITLE
Guidelines for scanning new projects

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#152]
There need to be guidelines for including projects that are scanned. Here is a PR for including repositories to be scanned #151

**Comment by dlorenc** [comment]
For the most part we can scan whatever! If the list gets too long we'll need to better shard out the job, but I have no concerns yet unless we get to around 5x the size.

**Comment by inferno-chromium** [comment]
> For the most part we can scan whatever! If the list gets too long we'll need to better shard out the job, but I have no concerns yet unless we get to around 5x the size.

+1, Goal is to scale this system infinitely, we shouldn't be saying no to any project.

**Comment by naveensrinivasan** [comment]
Thanks

> > For the most part we can scan whatever! If the list gets too long we'll need to better shard out the job, but I have no concerns yet unless we get to around 5x the size.
> 
> +1, Goal is to scale this system infinitely, we shouldn't be saying no to any project.
