### ISSUE TITLE
BUG: Checks using ListMergedPRs() need hardening

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1524]
`ListMergedPRs()` lists the last 30 or so PRs in a repo. Imagine the following scenario:
1. Repo owners using PRs and review their code, etc
2. They stop using PRs and only commit directly to head

IIUC, Scorecard will be looking at old PRs, e.g. in the Code-Review check, and conclude that reviews are done on the repo, even though it's not the case.

We need to harden all the checks that list PRs and compare their `MergeCommit` to the ones returned by `ListCommits()`.

Could we do this within the repo interface implementation, in order to avoid making mistakes in check implementations. For example, shall we make `ListMergedPRs()` return only the PRs that are in the `ListCommits()`? Something along these lines. Note: we'd need to be able to differentiate between "n PRs" only are available for this repo and "n PRs out of last m commits"

**Comment by laurentsimon** [comment]
cc @azeemsgoogle

**Comment by azeemshaikh38** [comment]
I wonder if #575 can solve this. Basically, if Scorecard knows that it is evaluating commitSHA `X` and looks at the last `N` commits before `X` (currently `N` is 30), this should solve the problem you are talking about?

**Comment by laurentsimon** [comment]
yes that would solve it, but most checks don't work based on a commit: we cannot get settings for a certain commit, for example. 
We can easily fix the problem inside the checks by calling `ListCommits()` and comparing them to `ListMergedPRs()` for now.

Let's have it inside the repo interface in the second iteration. This is a problem we should fix ASAP.

**Comment by azeemshaikh38** [comment]
Makes sense. +1 to solving it within the `RepoClient` interface itself so that the checks don't need to be updated separately. 

What do you think about asking Rohan to work on this? It might be a good starter issue for him. @asraa fyi.

> yes that would solve it, but most checks don't work based on a commit: we cannot get settings for a certain commit, for example.

Let's discuss this in our sync.

**Comment by azeemshaikh38** [comment]
@laurentsimon do you mind if I gave this a shot? Working on #1543 gave me an idea about how to improve the behavior here.
