### ISSUE TITLE
GHSA-mvff-h3cj-wj9c - Vulnerability reported for github.com/containerd/containerd

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1537]
The dependabot has reported a `High Severity` vulnerability  `github.com/containerd/containerd` https://github.com/ossf/scorecard/blob/d50788f6381d1fea21e4e50caa2de41012a38982/tools/go.sum#L471

We don't use this directly. This is part of `tools` https://github.com/ossf/scorecard/tree/main/tools module.

```
➜  tools  ✗ go mod why github.com/containerd/containerd
# github.com/containerd/containerd
(main module does not need package github.com/containerd/containerd)
```

I have tried this  replace in the `tools` `go.mod` which fails when `make install`

`replace github.com/containerd/containerd => github.com/containerd/containerd v1.5.9`

This is because our dependencies have this issue https://deps.dev/go/github.com%2Fgoogle%2Fgo-containerregistry

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @laurentsimon @david-a-wheeler FYI...

**Comment by naveensrinivasan** [comment]
https://github.com/google/go-containerregistry/issues/1269

**Comment by naveensrinivasan** [comment]
> google/go-containerregistry#1269

They don't have specific timelines as to when they would address this issue. 

https://github.com/google/go-containerregistry/issues/1269#issuecomment-1022712624

cc @inferno-chromium

**Comment by justaugustus** [comment]
Closed via https://github.com/ossf/scorecard/pull/1560.

**Comment by naveensrinivasan** [comment]
Still not closed, because  the go.sum refers to version that has the vulnerability
