### ISSUE TITLE
AuthorAssociation should be part of User

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1546]
We've added fields like `AuthorAssociation *RepoAssociation` `Issue` and `IssueComment`.
Should these live under `User` instead?

It would be more natural to have:
```
// Issue represents a thread like GitHub issue comment thread.
type Issue struct {
	URI               *string
	CreatedAt         *time.Time
	Creator         User
	Comments          []IssueComment
}

// IssueComment represents a comment on an issue.
type IssueComment struct {
	CreatedAt         *time.Time
	Commenter User
}

type User struct{
   Login string
  AuthorAssociation *RepoAssociation
}
```

This will also be useful for checks like Contributors, where we can add this field in the raw results.

**Comment by laurentsimon** [comment]
cc @chrismcgehee @azeemsgoogle wdut?

**Comment by chrismcgehee** [comment]
Yeah, I think that would work, as long as we put a comment on the User struct to make clear that it's for a user in relation to a specific repository, and not a generic user object. If Azeem agrees on the approach, I can take this one.

**Comment by azeemshaikh38** [comment]
Hmm, I prefer the way it is today. It matches the GitHub graphQL objects - https://docs.github.com/en/graphql/reference/objects#issue
https://docs.github.com/en/graphql/reference/objects#issuecomment

I haven't tested to see if the same author can appear with different `association` for different objects. But if that is the case, it might be beneficial to keep it as is.

But I see why we might want to have it inside the `User` object itself. So if you feel strongly about it, please go ahead.

**Comment by laurentsimon** [comment]
Any update on this? @chrismcgehee any interest? Further opinion?

**Comment by chrismcgehee** [comment]
I agree with Azeem that I'd prefer to leave this code as is. I'm okay if you close this issue.

**Comment by laurentsimon** [comment]
ok, thanks for the input. I'll keep the issue open as I'd like to see if it's valuable/feasible to have this info in the RAW results https://github.com/ossf/scorecard/blob/main/pkg/json_raw_results.go

Any concerns about having the info the raw results?

**Comment by chrismcgehee** [comment]
No concerns from me.

**Comment by laurentsimon** [comment]
I did this this in one of the raw results PRs. I'll see if something break down the line.
Closing this issue for now
