### ISSUE TITLE
Feature: add support for flutter-dashboard and Cirrus CI in the CI Test Check

### ISSUE THREAD

**Issue by godofredoc** [ossf/scorecard#1547]
**Is your feature request related to a problem? Please describe.**
Yes, Dart and Flutter are enabling score card for both Flutter and Dart orgs. As we started addressing the alerts we found that CI Test validation is failing because flutter-dashboard(LUCI) and Cirrus CI are not included in the list of CI systems. 

**Describe the solution you'd like**
I'm planning to send a PR to add "flutter-dashboard" and "Cirrus CI" to the CI systems list.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by laurentsimon** [comment]
Brilliant, thanks for filing the issue. I'll take a loom at the PR today.

**Comment by azeemshaikh38** [comment]
Closing this since #1548 addresses this issue. Feel free to re-open if not.
