### ISSUE TITLE
BUG - Pinned-Dependencies erroneously finds unpinned dep in unit test

### ISSUE THREAD

**Issue by imjasonh** [ossf/scorecard#1573]
**Describe the bug**

Example alert: https://github.com/GoogleContainerTools/kaniko/security/code-scanning/119?query=ref%3Arefs%2Fheads%2Fmain

This matches some unit test code meant to test Dockerfile parsing behavior, and is not indicative of any actual dependency on this image:

https://github.com/GoogleContainerTools/kaniko/blob/ff3ee40293cb943c4ffb70d808c4e8772189c7e1/pkg/dockerfile/dockerfile_test.go#L605-L605

Because similar strings are found in lots of other files in this repo and only this file caused an alert, I think this is happening because the file is named `dockerfile_test.go`, and the system doesn't know that it's meant to be interpreted as a Go file and not a Dockerfile.

**Reproduction steps**
1. Include the string `FROM alpine` in a Go unit test file named `dockerfile_test.go`
2. Scan
3. See Pinned-Dependencies alert

**Expected behavior**

I'd expect the system to detect that the file isn't a valid Dockerfile and not to try to parse it as one.

**Additional context**

N/A

**Comment by imjasonh** [comment]
There are a ton of identical spurious alerts on the same file:

<img width="492" alt="Screen Shot 2022-01-31 at 12 47 18 PM" src="https://user-images.githubusercontent.com/210737/151845785-ef2ce7ba-62ab-4ea3-802a-afa064ee9685.png">

**Comment by laurentsimon** [comment]
weird, the parser does not fail :-), thanks for reporting. @chrismcgehee
