### ISSUE TITLE
BUG: maven signatures not detected by Signed-release check

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1582]
See https://github.com/remkop/picocli/commit/87ff7a67bb0310e399823fb2b3950cc51b997990#commitcomment-65815736 for details.

The extension seems to be `.asc.sha256`. To be confirmed. Other hashes may be supported.

**Comment by remkop** [comment]
Thanks for raising this!

Apologies, `.asc.sha256` should be .`asc` for signature files. Details follow below.

Releases published with Maven will follow Apache Software Foundation's [release signing policy](https://infra.apache.org/release-signing.html):

> Every artifact distributed by the Apache Software Foundation must be accompanied by one file containing an OpenPGP-compatible ASCII armored detached signature and another file containing a SHA checksum.

(That page is out of date, SHA1 and MD5 should be no longer used in ASF releases, but in practice may still be used.)

I am not sure if "OpenPGP-compatible ASCII armored detached signature" files always have the `.asc` file extension, but that is what I have seen so far.

For example, if my project publishes a `picocli-4.6.2.jar`, then it should also publish a
* `picocli-4.6.2.jar.asc` signature file
* `picocli-4.6.2.jar.sha256` (or other hash) checksum file

Note that the build toolchain may additionally produce `picocli-4.6.2.jar.asc.sha256` checksum files but those are superfluous and can be ignored.

Example: [log4j-api 2.17.1 artifacts](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/) on Maven.

I am not sure how easy it is to automate the verification of `.asc` signatures, especially how to automate retrieving the release manager's public key...
The manual procedure is documented here: https://httpd.apache.org/dev/verification.html

**Comment by laurentsimon** [comment]
> Thanks for raising this!
> 
> Apologies, `.asc.sha256` should be .`asc` for signature files. Details follow below.
> 
> Signed releases published with Maven will follow Apache Software Foundation's [release signing policy](https://infra.apache.org/release-signing.html):
> 
> > Every artifact distributed by the Apache Software Foundation must be accompanied by one file containing an OpenPGP-compatible ASCII armored detached signature and another file containing a SHA checksum.
> 
> (That page is out of date, SHA1 and MD5 should be no longer used in ASF releases, but in practice may still be used.)
> 
> I am not sure if "OpenPGP-compatible ASCII armored detached signature" files always have the `.asc` file extension, but that is what I have seen so far.

Thanks for the details. Scorecard already checks for .asc files in release artifacts on GitHub. Does it mean the only left to do is for you to add this file to your artifacts? Is there something else we need to do on our side?

> For example, if my project publishes a `picocli-4.6.2.jar`, then it should also publish a
> 
> * `picocli-4.6.2.jar.asc` signature file
> * `picocli-4.6.2.jar.sha256` (or other hash) checksum file
> 
> Note that the build toolchain may additionally produce `picocli-4.6.2.jar.asc.sha256` checksum files but those are superfluous and can be ignored.
> 
> Example: [log4j-api 2.17.1 artifacts](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-api/2.17.1/) on Maven.
> 
> I am not sure how easy it is to automate the verification of `.asc` signatures, especially how to automate retrieving the release manager's public key... The manual procedure is documented here: https://httpd.apache.org/dev/verification.html

**Comment by remkop** [comment]
> Thanks for the details. Scorecard already checks for .asc files in release artifacts on GitHub. Does it mean the only thing left to do is for you to add this file to your artifacts? Is there something else we need to do on our side?

I see, great! 
I got the `.asc` files for the picocli jar files from Maven Central and added them to the [release artifacts](https://github.com/remkop/picocli/releases/tag/v4.6.2) in GitHub for the latest picocli release.

There is one `picocli-all-4.6.2.zip` for which there is no `picocli-all-4.6.2.zip.asc` file, and there are the GitHub-generated `v4.6.2.zip` and  `v4.6.2.tar.gz` files without `.asc` files. Curious how that will affect the Signed-release check outcome.

Is there any way to test this? I guess I'll have to wait for the next scan to be run. 

> We'd like to be able to detect the package name and look up from maven in the future, but we're not quite there yet. Please feel free to provide info how to do that in https://github.com/ossf/scorecard/issues/688

Ok, will do.

**Comment by laurentsimon** [comment]
You can use our docker image to test, see https://github.com/ossf/scorecard#docker
`... --repo=$REPO --format json --show-details --checks Signed-Releases | jq`
```
{
      "details": [
        "Info: signed release artifact: picocli-4.6.2.jar.asc: https://api.github.com/repos/remkop/picocli/releases/assets/55709725",
        "Warn: release artifact v4.6.1 not signed: https://api.github.com/repos/remkop/picocli/releases/35918383",
        "Warn: release artifact v4.6.0 not signed: https://api.github.com/repos/remkop/picocli/releases/35892823",
        "Warn: release artifact v4.5.2 not signed: https://api.github.com/repos/remkop/picocli/releases/32560082",
        "Warn: release artifact v4.5.1 not signed: https://api.github.com/repos/remkop/picocli/releases/30137358"
      ],
      "score": 2,
      "reason": "1 out of 5 artifacts are signed -- score normalized to 2",
      "name": "Signed-Releases",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases",
        "short": "Determines if the project cryptographically signs release artifacts."
      }
    }
```

**Comment by remkop** [comment]
@laurentsimon Awesome, thank you! The docker image worked very smoothly.

I noticed one thing that seems like a false positive:

```
----------|-----------------------------------------------------------------------------------------------------
| 0 / 10  | SAST                   | SAST tool is not run on all    | Warn: 1 commits out of 30 are       
|         |                        | commits -- score normalized to | checked with a SAST tool Warn:    
|         |                        | 0                              | CodeQL tool not detected    
           https://github.com/ossf/scorecard/blob/a69e1d97d44ebba908ad4cf574d51c0f2e0f761e/docs/checks.md#sast  
```

The remkop/picocli project _does_ have CodeQL set up:
The config file is here: `.github/workflows/codeql-analysis.yml`

And the workflow has been set up and is active:
![image](https://user-images.githubusercontent.com/5917763/152527332-1d856351-fa0d-4f3c-b90b-0d028bd14730.png)

Wonder what I am doing wrong...

**Comment by laurentsimon** [comment]
Please create an issue for it and I will follow up. Fyi, we're in the process of updating this check https://github.com/ossf/scorecard/pull/1487#issuecomment-1028556509

**Comment by laurentsimon** [comment]
I've noticed that CodeQl is defined in your workflow, but seems to fail uploading the results: https://github.com/remkop/picocli/actions/runs/1794898507 which may be why scorecard is not detecting it

**Comment by remkop** [comment]
@laurentsimon Thank you for pointing out that the upload is the part that seems to be failing.
I created https://github.com/ossf/scorecard/issues/1605 for this.

It appears that  .asc files are recognized when they are added them to the [release artifacts](https://github.com/remkop/picocli/releases/tag/v4.6.2) in GitHub.
It would be nice if the tool could get them from Maven, but that is related to https://github.com/ossf/scorecard/issues/688, so... 

I think this ticket can be closed.
Thank you so much for your help!

**Comment by laurentsimon** [comment]
You're welcome. Thanks for trying out scorecard. Don't hesitate to reach out!
