### ISSUE TITLE
BUG: Scorecard analysis scheduled/cron fails

### ISSUE THREAD

**Issue by GuillaumeRoss** [ossf/scorecard#1610]
**Describe the bug**
I have setup the Github Action last week, and it's been reporting issues to the repo's list of vulnerabilities perfectly. This weekend, the first scheduled run was to occur, and it failed during the Run Analysis step with the following:

```
Run ossf/scorecard-action@c8416b0b2bf627c349ca92fc8e3de51a64b005cf
  with:
    results_file: results.sarif
    results_format: sarif
    repo_token: ***
    publish_results: true
/usr/bin/docker run (long docker command here)
Event file: /github/workflow/event.json
Event name: schedule
Ref: refs/heads/main
Private repository: null
Publication enabled: true
Format: sarif
Policy file: /policy.yml
Default branch: refs/heads/null
refs/heads/main not supported with 'schedule' event.
Only the default branch 'refs/heads/null' is supported
```

The setup was pretty much the standard one, so I wondered if maybe I had made a mistake in the configuration. So I headed to the scorecard repo's own github action to compare with my own, and noticed it also failed with the same logs at the end of the step.

https://github.com/ossf/scorecard/runs/5075008668?check_suite_focus=true

**Reproduction steps**
1.  Configure Scorecard github actions with a scheduled run
2. Wait for scheduled run to occur
3. Notice the failure

**Expected behavior**
I would expect the run to succeed, or the logs to be a bit more verbose about what is wrong in the configuration.

**Additional context**
It has never run properly for us, it was the first attempt, so it is possible the issue is in the configuration. But since I saw the same error on this very repo, I figured maybe it was an issue with the action referred.

Thanks for your help!

**Comment by laurentsimon** [comment]
Thanks for the report. We have a tracking issue for it https://github.com/ossf/scorecard-action/issues/84 (another repo :-))
Im closing this use and adding you to the other issue.
