### ISSUE TITLE
Feature:  Public JSON Type

### ISSUE THREAD

**Issue by colek42** [ossf/scorecard#1673]
I am using score card data as a part of attestation in witness https://github.com/testifysec/witness.  We marshal the data in the scorecard json result.

**Describe the solution you'd like**
Make the `jsonScorecardResultV2` type Public

**Describe alternatives you've considered**
Copy paste the types into witness

**Comment by naveensrinivasan** [comment]
@colek42  Do you want to do a PR for the change? also, you should demo how you are building with the scorecard in our Bi-Weekly meeting.

**Comment by laurentsimon** [comment]
Fyi, we're also experimenting with a `--format raw` flag that outputs "raw" data for the results, before the scores have been calculated. We're aiming to make this for all checks, with the goal of allowing policies to be written.
The raw result format will be unstable for the next few months, though. You can see the existing checks we've migrated (and the current format) in https://github.com/ossf/scorecard/blob/main/pkg/json_raw_results.go

If this is of interest to you, let us know and we can share a design once we have one.

And +1 on presenting what you're building on a scorecard meeting, this sounds super exciting!
