### ISSUE TITLE
Remove download of unnecessary tarball

### ISSUE THREAD

**Issue by chrismcgehee** [ossf/scorecard#1697]
**Describe the bug**
Scorecard downloads the `google/oss-fuzz` repo even though it's unnecessary.

**Reproduction steps**
1. Run a single check against a small repo, e.g. `scorecard --repo=chrismcgehee/test-scorecard --checks=Pinned-Dependencies`
2. Notice that it takes a few seconds (or more depending on your internet speed) before it displays `Starting [Pinned-Dependencies]`.

**Expected behavior**
Scorecard can start the actual checks immediately after invoking the command.

**Additional context**
Before running any checks, scorecard [initializes](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/checker/client.go#L61) the `google/oss-fuzz` repo for later use in the Fuzzing check. One of the steps of the initialization is to [download and extract](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/clients/githubrepo/client.go#L74) the tarball for that repo. The Fuzzing check doesn't even utilize this tarball; it makes an [api call](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/checks/fuzzing.go#L61) to check if the current repo is one of the projects fuzzed by OSS-Fuzz.

On my laptop with a 40 Mbps connection, downloading and extracting the OSS-Fuzz tarball adds 20 seconds to the runtime of scorecard. When Scorecard is run as part of cron, I don't think this penalty is paid for every repo that it evaluates; the worker will [initialize OSS-Fuzz](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/cron/worker/main.go#L191) once and then evaluate many projects after that. I think it's still worth making this performance improvement for other users who run the Scorecard CLI tool.

I'll assign this to myself, and I'd like to double-check my plan of implementation with one or two of you. My plan is to make a new interface called something like `RepoSearcher` which will have a single method `Search(request SearchRequest) (SearchResponse, error)`. Then in `CheckRequest`, instead of the `OssFuzzRepo` field being a `clients.RepoClient`, it will be a `RepoSearcher`. When initializing the `RepoSearcher`, we will not need to download the tarball for the repo.

**Comment by azeemshaikh38** [comment]
A simpler fix might be to initialize the `oss-fuzz` repo only if the `Fuzzing` check is [enabled](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/cmd/root.go#L159).  Similar optimization can be done for `ciiClient` too if needed.

**Comment by justaugustus** [comment]
> A simpler fix might be to initialize the `oss-fuzz` repo only if the `Fuzzing` check is [enabled](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/cmd/root.go#L159). Similar optimization can be done for `ciiClient` too if needed.

Agreed. Overall I'd like to refactor the clients, but if someone beats me to it, have at it!

**Comment by chrismcgehee** [comment]
> A simpler fix might be to initialize the `oss-fuzz` repo only if the `Fuzzing` check is [enabled](https://github.com/ossf/scorecard/blob/738b246fe97dfc555bb9a082434d85dee4011503/cmd/root.go#L159).

With this approach, the performance gain would only be achieved a small portion of the time. I'd like to do a slightly more complicated fix so that we get the performance gain every time.

**Comment by azeemshaikh38** [comment]
> With this approach, the performance gain would only be achieved a small portion of the time.

In that case how about updating [`tarbalHandler.init()`](https://github.com/ossf/scorecard/blob/4904b317ac0f74b69590a60f8e278c791ec3bae0/clients/githubrepo/tarball.go#L72) to not download/extract the tarball by default. We do a one time `setup()` only if there is a call to either `listFiles()` or `getFileContent()` (see [graphqlHandler for example](https://github.com/ossf/scorecard/blob/main/clients/githubrepo/graphql.go#L134)).

**Comment by chrismcgehee** [comment]
I like it. I'll go with that approach.
