### ISSUE TITLE
Extend Vulnerabilities check with https://github.com/github/advisory-database

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1707]
**Is your feature request related to a problem? Please describe.**
Scorecard does vulnerability scan with osv.dev. Recently GitHub OSS their Vulns https://github.com/github/advisory-database. It would be nice if scorecard can check with this DB for reporting any issues.

**Comment by naveensrinivasan** [comment]
Related https://github.com/G-Rath/osv-detector/issues/3

**Comment by G-Rath** [comment]
@naveensrinivasan `osv-detector` is at a pretty good point now that I think it should be usable here - I'm wondering if it could be used as a binary to avoid having to duplicate all the manifest/lockfile finding stuff, and then scorecard could parse its json output. Would that work?

**Comment by spencerschrock** [comment]
This was implemented back in #2509 via osv-scanner, which has the GitHub Advisory Database
