### ISSUE TITLE
openssf:scorecardcron.scorecard-v2 dataset missing in bigquery-public-data

### ISSUE THREAD

**Issue by stm9** [ossf/scorecard#1715]
**Describe the bug**
Openssf:scorecardcron.scorecard-v2 is not accessible or missing in GCP BigQuery public datasets. 

**Reproduction steps**
1. Login to http://console.cloud.google.com/bigquery
2. Search for Openssf:scorecardcron.scorecard-v2

**Expected behavior**
Openssf:scorecardcron.scorecard-v2 should be accessible via http://console.cloud.google.com/bigquery as a public dataset for query. Accordingly steps at https://github.com/ossf/scorecard#public-data should be updated.

**Additional context**
https://github.com/ossf/scorecard#public-data
https://github.com/ossf/scorecard/issues/218

CCing the team
@azeemshaikh38 
@laurentsimon

**Comment by azeemshaikh38** [comment]
@stm9 I'm not sure how the `search` bar feature works in BigQuery UI. But if you were to click on the `Add Data` button in the bigquery Explorer and add the `openssf` project, you'll be able to see and explore `scorecard-v2` data.

Let me know if that helps.

**Comment by stm9** [comment]
Hi Azeem. Thank you for quick reply. It seems however that the gcp project is not accessible to all users.
