### ISSUE TITLE
Sign up for CII Best Practices 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#174]
Sign up for CII Best Practices.

https://bestpractices.coreinfrastructure.org/en

**Comment by naveensrinivasan** [comment]
Needs to org level GitHub permission for CII to view the score card repo.

**Comment by azeemshaikh38** [comment]
Might be a good issue for our next milestone. Re-opening.

**Comment by azeemshaikh38** [comment]
Duplicate of #1032. Closing this and tracking it there.
