### ISSUE TITLE
BUG: need token for local repo

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1740]
```
$ go run . --local=../TEST2 --format raw --show-details | jq .

ERRO[0000] GitHub token env var is not set. Please read https://github.com/ossf/scorecard#authentication  error="an error occurred while getting GitHub credentials"
```

cc @azeemsgoogle @naveensrinivasan we really need this case covered by unit tests. It happened 2 weeks ago as well

**Comment by laurentsimon** [comment]
Thanks Naveen!

**Comment by naveensrinivasan** [comment]
@laurentsimon I can't seem to recreate this issue on the a496d8c which is the `main` at the moment. 

`SCORECARD_V6=1 go run . --local=.  --format raw --show-details | jq .`

Can you please provide the steps to recreate this?

**Comment by laurentsimon** [comment]
do you have a `GITHUB_AUTH_TOKEN` var defined in your env? The above triggered only when not set

**Comment by azeemshaikh38** [comment]
I'm unable to reproduce this too, even with `GITHUB_AUTH_TOKEN` unset. Closing this for now, @laurentsimon please re-open if needed and add steps to reproduce.
