### ISSUE TITLE
BUG: Security-Policy throws internal error if `--local .` passed

### ISSUE THREAD

**Issue by Dentrax** [ossf/scorecard#1752]
**Describe the bug**
`$ scorecard --local .` throws `input repo should be of type repoURL` error.

**Reproduction steps**
1. `$ git clone github.com/chainguard-dev/apko`
2. `$ scorecard --local .`
3. See: `internal error: input repo should be of type repoURL: <nil>`

**Expected behavior**
We should not print out `Security-Policy` section in case we don't pass `--repo` flag?

**Additional context**
Version: `4.1.0`

**Comment by laurentsimon** [comment]
cc @naveensrinivasan

**Comment by naveensrinivasan** [comment]
Thanks, @Dentrax!
