### ISSUE TITLE
BUG: macOS: brew: `scorecard version` prints `unknown`

### ISSUE THREAD

**Issue by Dentrax** [ossf/scorecard#1753]
**Describe the bug**
```
$ scorecard version

GitVersion:     unknown
GitCommit:      unknown
GitTreeState:   unknown
BuildDate:      unknown
GoVersion:      go1.17.6
Compiler:       gc
Platform:       darwin/amd64
```

**Reproduction steps**
1. `$ brew install scorecard`
2. `$ scorecard version`
3. See the `unknown` fields.

**Expected behavior**
It should print the correct version.

**Additional context**
`-`

**Comment by laurentsimon** [comment]
this happens when the `ldflags` are not set properly during compilation. We don't own the brew installation, AFAIK. The brew formula is done by someone else.  

@naveensrinivasan remember who is in charge of it?

**Comment by naveensrinivasan** [comment]
> this happens when the `ldflags` are not set properly during compilation. We don't own the brew installation, AFAIK. The brew formula is done by someone else.
> 
> @naveensrinivasan remember who is in charge of it?

AFAIK it is maintained by the community.

**Comment by azeemshaikh38** [comment]
I have opened https://github.com/Homebrew/homebrew-core/pull/98177 to get this fixed. Let's see how that goes.

**Comment by naveensrinivasan** [comment]
> I have opened [Homebrew/homebrew-core#98177](https://github.com/Homebrew/homebrew-core/pull/98177) to get this fixed. Let's see how that goes.

Thank you!

**Comment by azeemshaikh38** [comment]
This is now fixed. Reinstall Scorecard using `brew` to check.
