### ISSUE TITLE
Use Circle CI for running e2e

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#176]
The GitHub PR's on forks cannot run e2e tests. How about using Circle CI for doing it? This will ensure all the PR's in the future even from forks have our e2e tests checked.

**Comment by naveensrinivasan** [comment]
@inferno-chromium  @dlorenc  Thoughts?

**Comment by naveensrinivasan** [comment]
@dlorenc Need permission at the org level to allow Circle CI. I have sent the request out.

**Comment by dlorenc** [comment]
SGTM - it's really annoying we can't run tests from forks.

**Comment by dlorenc** [comment]
Accepted the request.

**Comment by naveensrinivasan** [comment]
> Accepted the request.

Thank you!

**Comment by naveensrinivasan** [comment]
![image](https://user-images.githubusercontent.com/172697/107896257-b78d2e00-6f03-11eb-8593-5fe7b90c153d.png)
I need permission to set up the project in Circle CI for Scorecard. Need `admin` permission https://app.circleci.com/projects/project-dashboard/github/ossf

**Comment by naveensrinivasan** [comment]
![image](https://user-images.githubusercontent.com/172697/108128941-7e77c980-707b-11eb-9d72-022835130b31.png)

It is not recommended for forks https://circleci.com/docs/2.0/oss/, 🤦  I should have read the docs before going through all of this.
