### ISSUE TITLE
Fix the protobuf GitHub Action failures

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1774]
All my PRs are failing with:
```
protoc --go_out=../../../ cron/data/request.proto
/bin/bash: protoc: command not found
make: *** [Makefile:10[8](https://github.com/ossf/scorecard/runs/5652653919?check_suite_focus=true#step:7:8): cron/data/request.pb.go] Error 127
```

_Originally posted by @laurentsimon in https://github.com/ossf/scorecard/issues/1772#issuecomment-1075808052_

**Comment by laurentsimon** [comment]
any ideas why this is happening?

**Comment by naveensrinivasan** [comment]
No idea! I wish there was an easy answer!

**Comment by azeemshaikh38** [comment]
Let me know if the failures are still going on. Hopefully, #1797 fixed this.

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  https://github.com/ossf/scorecard/runs/5761442359?check_suite_focus=true still happening 😞

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  Most of the PR's are failing with Protoc API rate limit https://github.com/ossf/scorecard/actions/runs/3299383490/jobs/5442690117

As we had discussed offline I am assigning it to you.
