### ISSUE TITLE
🎱  Some ideas

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#178]
I put down some thoughts on scorecard features  https://hackmd.io/s/HyMn_08-u

**Comment by naveensrinivasan** [comment]
I like hackmd makes the whole thing collaborative :)

**Comment by naveensrinivasan** [comment]
@inferno-chromium Would appreciate your feedback and ideas on some of these.

**Comment by inferno-chromium** [comment]
> @inferno-chromium Would appreciate your feedback and ideas on some of these.

Would love to chat over VC on this as well. Haven't been able to reach your email, my email is aarya,at,google,dot,com
Some work was planned, e.g. https://github.com/ossf/scorecard/pull/181

**Comment by naveensrinivasan** [comment]
> > @inferno-chromium Would appreciate your feedback and ideas on some of these.
> 
> Would love to chat over VC on this as well. Haven't been able to reach your email, my email is aarya,at,google,dot,com
> Some work was planned, e.g. #181
@inferno-chromium  Are you on the ossf slack?
