### ISSUE TITLE
Feature: rename fields of raw results

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1781]
The current implementation used fields as `some-field`, let's rename to `someField`.
Fyi, BQ does not accept `-` in name.

**Comment by laurentsimon** [comment]
Don't close

**Comment by spencerschrock** [comment]
> Don't close

@laurentsimon can you provide background on this issue? I'm not seeing any fields in RawResults with `-` in the name. Or the JSON tags.

**Comment by laurentsimon** [comment]
I must have fixed it at some point then. If that's the case, we can close the issue.
