### ISSUE TITLE
New check - Use of tools that update deps like dependabot

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#179]
Check if the dependabot is turned on the repository. This helps to identify any vulnerabilities on the project's dependencies.

**Comment by vin01** [comment]
Perhaps this should be a general category for automatic dependency updates, also supporting popular tools like Renovate for dependency updates: https://github.com/renovatebot/renovate

**Comment by naveensrinivasan** [comment]
closing it #322
