### ISSUE TITLE
Binary Artifacts should allow well-known artifacts, if best practices are followed

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/scorecard#1815]
**Is your feature request related to a problem? Please describe.**

> The gradle-wrapper.jar is a binary blob of executable code that is checked into nearly [2.8 Million GitHub Repositories](https://github.com/search?l=&q=filename%3Agradle-wrapper.jar&type=Code).

This is the intended use of this jar

https://github.com/marketplace/actions/gradle-wrapper-validation
https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification

**Describe the solution you'd like**
Binary artifacts knows about gradle-wrapper.jar and allows it if the repo has the Wrapper Validation Action installed (or another community-approved mitigation best practice).

**Describe alternatives you've considered**
An alternative could be fully user configurable, like providing the name and checksum (https://gradle.org/release-checksums/).  The public scorecard results wouldn't have this, but user-run scorecard checks could exempt certain binaries.

**Comment by david-a-wheeler** [comment]
As I noted in https://github.com/ossf/allstar/issues/157
supporting an .artifact-ignore could be very useful.

**Comment by jeffmendoza** [comment]
Discussion in the sync meeting was against the proposed solution, and for the described alternative above. That works for me as well.

**Comment by laurentsimon** [comment]
With `.artifact-ignore`, would we ignore the results only for maintainers or also for the weekly scans?

**Comment by JLLeitschuh** [comment]
I'm one of the co-authors of the [gradle-wrapper-validation](https://github.com/marketplace/actions/gradle-wrapper-validation) plugin. I agree that all-star should safely ignore the `gradle-wrapper.jar` in the presence of the validation GitHub action

**Comment by laurentsimon** [comment]
Should it be ignored by scorecard as well?

**Comment by JLLeitschuh** [comment]
If the `gradle-wrapper-validation` is present, then yes, it can be safely ignored. The `gradle-wrapper.jar` is supposed to be present. It's the prescribed way for Gradle users to invoke Gradle against their projects to build and test their code.

**Comment by naveensrinivasan** [comment]
> With `.artifact-ignore`, would we ignore the results only for maintainers or also for the weekly scans?

We would need to provide  two scores `ignore project claims` without `.artifact-ignore`  & `accept project claims` with `.artifact-ignore`. That is the only way to avoid bad actors from using this feature.
cc @david-a-wheeler

**Comment by loosebazooka** [comment]
> I'm one of the co-authors of the [gradle-wrapper-validation](https://github.com/marketplace/actions/gradle-wrapper-validation) plugin. I agree that all-star should safely ignore the gradle-wrapper.jar in the presence of the validation GitHub action

I wonder what we need to verify here to allow this sort of mechanism
- scorecards is aware of the action, and that it is enabled on every PR/merge
- scorecards needs the action to be on latest (or some set of approved new version?)

I feel like it could be easier for scorecards to just keep track of the binary hashes itself and compare instances of `gradle-wrapper.jar` with it. This could then be extended to other future known binaries.

**Comment by laurentsimon** [comment]
On the flip side, the need to maintain a list of hashes (or pull them programmatically) is additional complexity that I would not mind avoiding. If there's an ecosystem Action for it, why not rely on it if we can :-)

**Comment by loosebazooka** [comment]
Yeah and I don't disagree, just curious what the constraints/mechanism are to enable this kind of thing.

**Comment by laurentsimon** [comment]
@JLLeitschuh can you tell us more about how the `gradle-wrapper-validation` work? 
- It searches for `gradle-wrapper.jar` in all directories or in one in particular?
- The hashes it uses for validation are automatically fetched via URL, I presume?

If it's best practice for the Graddle ecosystem, I'm personally in favor of making Scorecard aware of it.
There are several reason I believe we should do it:

1. Credibility of Scorecard results: Scorecard should not output false positives that are easily avoidable. This will erode credibility in the results. We're trying to make Scorecard more aware of programming languages and ecosystems (e.g., https://github.com/ossf/scorecard/issues/1726#issuecomment-1065895570), so making Scorecard aware of the Graddle Action seems to be a step in the right direction

2. Such false positives lead to burden on repo maintainers: they need to "dismiss" them in the the GitHub scanning dashboard. They have already plenty on their plate to work on.
 
3. Such false positives lead to burden for consumers: when reading the results, consumers need to filter them out, even though some are easily preventable

4. Such false positive have a negative impact on the score. If another project just `wget` the jar instead, it would not be penalized but it'd be a worse practice. We're slowly moving away from scores https://github.com/ossf/scorecard/issues/1245, but they will still be around and people will look at them

5. The premise of the Binary-Artifact check is that it violates code reviews. But there's nothing fundamentally wrong with a binary in the repo if we know where it comes from and validate it by hash. This is akin to vendoring dependencies. The only worry I'd have is whether the jar will be kept updated or not.

Please chime in if you have a different opinion.

**Comment by JLLeitschuh** [comment]
> It searches for `gradle-wrapper.jar` in all directories or in one in particular?

It searches for all directories. It also looks for [homoglyph](https://en.wikipedia.org/wiki/Homoglyph) attacks (example PR can be found here https://github.com/JLLeitschuh/playframework/pull/1/files). If the wrapper action is present, it also fails if there are no `gradle-wrapper.jar` files found at all (for example, in the case where a homoglyph attack was not otherwise caught). It also lets you increase the `min-wrapper-count` if your repository has multiple `gradle-wrapper.jar` files and fails if the number detected falls below this number.

> The hashes it uses for validation are automatically fetched via URL, I presume?

Correct, they are fetched from `https://services.gradle.org/versions/all`

> If it's best practice for the Gradle ecosystem, I'm personally in favor of making Scorecard aware of it.

It is. The advantage of having the `gradle-wrapper.jar` checked into source control is that it ties your repository to a specific version of Gradle. That way, you can always checkout your repository, at any point in it's history, and the version of Gradle that was used to build that version of your software will still work. You don't need to downgrade your local version of Gradle (which can be tricky if you haven't recorded what version you used).

**Comment by laurentsimon** [comment]
Thanks for the explanation. 

If you're interested in sending a PR, the file to update is https://github.com/ossf/scorecard/blob/main/checks/raw/binary_artifact.go. To parse workflow files, you can look into https://github.com/ossf/scorecard/blob/main/checks/packaging.go

**Comment by laurentsimon** [comment]
time to learn :-) nw, I was just asking in case. We can take care of it.
