### ISSUE TITLE
BUG: Cannot find the public dataset from the google Bigquery

### ISSUE THREAD

**Issue by lingpiao0128** [ossf/scorecard#1831]
I cannot find the public dataset from the google Bigquery. Could you provide the specific link of the dataset?

**Comment by azeemshaikh38** [comment]
See https://github.com/ossf/scorecard#public-data

> You can query the data using [BigQuery Explorer](http://console.cloud.google.com/bigquery) by navigating to Add Data > Pin a Project > Enter Project Name > 'openssf'

**Comment by azeemshaikh38** [comment]
Closing, feel free to re-open.
