### ISSUE TITLE
BUG: are we updating our container images?

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1843]
I was pulling some images and found that https://github.com/ossf/scorecard/blob/main/Dockerfile#L15, for example, was built in 08-2021, and the latest image is from 2022-04

I stumbled upon this by chance because the image was failing to build in unit tests.

Our dependabot config file has an entry for docker images, so I'm not exactly sure what's going on.

@naveensrinivasan any thoughts?

**Comment by naveensrinivasan** [comment]
No clue! It should work, AFAIK.

**Comment by laurentsimon** [comment]
when is the last time we merged a dependabot PR for a dockerfile update?

**Comment by naveensrinivasan** [comment]
> when is the last time we merged a dependabot PR for a dockerfile update?

https://github.com/ossf/scorecard/pull/1786 21 days before

**Comment by spencerschrock** [comment]
Closing as all 8 docker files are in our dependabot config, and the various docker files are being updated.
And both the [docker builds](https://github.com/ossf/scorecard/actions/workflows/docker.yml) and the cloud builds are succeeding.
