### ISSUE TITLE
BUG: fix doc for Webhook check

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1847]
`If there is no support for token authentication, consider implementing it by following [these directions](https://docs.github.com/en/developers/webhooks-and-events/webhooks/securing-your-webhooks).` is mis-leading because users do not control the authentication support: the webhook service is often provided by a 3P entity.

**Comment by Suhit-Majumdar** [comment]
Hi! Can you please suggest which file is the bug in? I will go through it and try to resolve it after going through the documentation in detail.

**Comment by spencerschrock** [comment]
Can be fixed at same time as #2154

**Comment by leec94** [comment]
i can take on this issue. is the solution to this issue to update the doc to remove that sentence? i can look at #2154 as well

**Comment by spencerschrock** [comment]
> i can take on this issue. is the solution to this issue to update the doc to remove that sentence? i can look at #2154 as well

I could see removing it, or clarifying what a repo owner can do. Maybe something like "check if the webhook can be configured to use auth " or "request the functionality"?
