### ISSUE TITLE
BUG Binary Artifacts False positive scripts/Makefile.lib

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/scorecard#1868]
**Describe the bug**
The file scripts/Makefile.lib from Linux Kernel forks is triggering as a binary artifact, when it is a Makefile.

**Reproduction steps**
Example repo: 
https://github.com/google/capsicum-linux/blob/capsicum/scripts/Makefile.lib

Run scorecards, scripts/Makefile.lib is reported as a binary artifact.

**Expected behavior**
Not to be reported.

**Comment by laurentsimon** [comment]
Is this a standard naming convention Makefile.lib, or that's what they picked?
