### ISSUE TITLE
Use renovate bot GitHub Actions

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1880]
**Is your feature request related to a problem? Please describe.**
Use renovate bot for GitHub actions instead of Dependabot because it adds the comment on pinned SHA for actions. 

Also, it is nice to use renovate bot that we recommend users to use.

**Comment by laurentsimon** [comment]
I like the idea, in particular if renovatebot supports batched PRs: that would avoid reviewing a dozen of PRs each week.

**Comment by HonkingGoose** [comment]
Renovate supports batching dependencies. Read the [Renovate docs about noise reduction](https://docs.renovatebot.com/noise-reduction/) to learn more. 😉

**Comment by spencerschrock** [comment]
Closing due to age, and dependabot now updates version comments and has basic grouped updates. We can always re-evaluate later.
