### ISSUE TITLE
Metadata from deps.dev 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1888]
Also, I noticed that these dependencies have `num_dependencies_deps.dev` metadata field. Please remove that. We get that metadata from deps.dev API directly.

_Originally posted by @azeemshaikh38 in https://github.com/ossf/scorecard/pull/1886#pullrequestreview-962679994_

**Comment by naveensrinivasan** [comment]
The deps.dev API isn't open to everyone. How is this being added to scorecards?

**Comment by azeemshaikh38** [comment]
Yes it is not public. We get a one-off dump from deps.dev with the num_deps for a project.
