### ISSUE TITLE
BUG scorecard 4.2.0 does not print version number anymore

### ISSUE THREAD

**Issue by chenrui333** [ossf/scorecard#1891]
**Describe the bug**

**Reproduction steps**
1. download release artifact (e.g. https://github.com/ossf/scorecard/releases/download/v4.2.0/scorecard_4.2.0_darwin_amd64.tar.gz)
2. unzip and run `./scorecard-darwin-arm64 version`

**Expected behavior**

The version information

```
GitVersion:    v4.2.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.17.9
Compiler:      gc
Platform:      darwin/arm64
```

**Additional context**

relates to https://github.com/Homebrew/homebrew-core/pull/101012

**Comment by naveensrinivasan** [comment]
I don't seem to have an issue.
```
➜  scorecard_4.2.0_darwin_amd64 ./scorecard-darwin-amd64 version
         __  ____     ____    ___    ____    _____    ____      _      ____    ____
        / / / ___|   / ___|  / _ \  |  _ \  | ____|  / ___|    / \    |  _ \  |  _ \
       / /  \___ \  | |     | | | | | |_) | |  _|   | |       / _ \   | |_) | | | | |
  _   / /    ___) | | |___  | |_| | |  _ <  | |___  | |___   / ___ \  |  _ <  | |_| |
 (_) /_/    |____/   \____|  \___/  |_| \_\ |_____|  \____| /_/   \_\ |_| \_\ |____/
./scorecard: Security Scorecards

GitVersion:    v4.2.0
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.17.9
Compiler:      gc
Platform:      darwin/amd64
```

I downloaded https://github.com/ossf/scorecard/releases/download/v4.2.0/scorecard_4.2.0_darwin_amd64.tar.gz and ran it.

@azeemshaikh38 @laurentsimon  Can you guys check if it is?

Also I noticed the `e2e` on the `main` for scorecard action is failing with a similar message https://github.com/ossf-tests/scorecard-action/runs/6338427881?check_suite_focus=true

**Comment by naveensrinivasan** [comment]
Edit - I apologize I read the issue incorrectly. Yes, it is not showing up. The other issue that I mentioned is different from this.

**Comment by chenrui333** [comment]
> After this is merged, I can do another release to address the problem. Thanks!

that would be good, thanks!

**Comment by azeemshaikh38** [comment]
This is now fixed at HEAD. Will push out a release for it soon.

**Comment by chenrui333** [comment]
Sounds good, thanks!
