### ISSUE TITLE
Feature: tag builds as stable after the releasetest is successful

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#1901]
Is it feasible to tag builds/container images as stable after they have successfully run the releasetest integration tests? 

@azeemsgoogle WDUT?

**Comment by azeemsgoogle** [comment]
Yes, that's what we do today already. A successful run of releasetest automatically tags the associated container images as `:stable`. Did you mean this or something else?

**Comment by laurentsimon** [comment]
ok, interesting. I pushed some commits on Monday and did not see that commit tagged as "stable". I need to double check then

**Comment by azeemshaikh38** [comment]
So I think I figured out what's going on. After #1886 lot of repositories were failing for 2 reasons:

- `Vulnerabilities` check was erroring out on empty repositories which is not the right behavior. #1914 should fix that.
- #1320 is continuing to cause failures like before.

IMO, we should fix #1320 to fix the failing releasetests before making a new release. @naveensrinivasan @laurentsimon wdyt?

**Comment by laurentsimon** [comment]
@asraa do you have cycles to fix https://github.com/ossf/scorecard/issues/1320?

**Comment by azeemshaikh38** [comment]
> @asraa do you have cycles to fix #1320?

I believe @naveensrinivasan plan's to work on this issue?
