### ISSUE TITLE
Integration with CI/CD and GitHub Code Scanning Results

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#193]
https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github

**Comment by naveensrinivasan** [comment]
That is a cool idea. Probably use Scorecard all the dependencies of the codebase and upload it.

**Comment by inferno-chromium** [comment]
Can even just start with showing it for the repo itself. it wont block the CI, but just run on it. this github token limit might be pain.

**Comment by naveensrinivasan** [comment]
For this, we need to export the results from the scorecard to `sarif` format and after that, it coming up with a `Github action`, I think.

**Comment by azeemshaikh38** [comment]
@laurentsimon I think we can close this now?

**Comment by laurentsimon** [comment]
Yes!
