### ISSUE TITLE
New Check: Signed Commits

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#1938]
**Is your feature request related to a problem? Please describe.**
Add a new check if the Git Commits are signed. Now that the commits are stored in `rekor` and keyless https://github.com/sigstore/gitsign

**Comment by naveensrinivasan** [comment]
@dlorenc FYI...

**Comment by laurentsimon** [comment]
this is also relevent https://github.com/github/feedback/discussions/7744#discussioncomment-2603637

**Comment by laurentsimon** [comment]
landed https://github.blog/changelog/2022-08-23-ssh-commit-verification-now-supported/
I have no idea how revocation works

**Comment by LappleApple** [comment]
@spencerschrock @afmarcum and others: From our Jan 25 meeting, we said we'd close this one as a "won't do."

**Comment by spencerschrock** [comment]
Additionally this one is a duplicate of #379. Any future discussion should take place there.
