### ISSUE TITLE
BUG: nil-ptr dereference 

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#1942]
Reproduce using:

```
SCORECARD_V6=1 ./scorecard --repo=ossf-tests/scorecard-check-token-permissions-e2e --commit=35a3425d1e682c32946b7d36adcfd772cf772e63 --checks=Token-Permissions
```

@laurentsimon seems to be happening in the `remediation.go` code that was added recently. Could you take a look.

On a side note, it still boggles me how the e2e tests don't catch this but fail when we run locally.

**Comment by laurentsimon** [comment]
interesting. I'm surprised the e2e tests did not catch it.

**Comment by laurentsimon** [comment]
fix in https://github.com/ossf/scorecard/pull/1947/files
