### ISSUE TITLE
no badge detected for CII while there is a badge

### ISSUE THREAD

**Issue by ldemailly** [ossf/scorecard#1958]
It could be I don't know where the badge detection is looking but

https://deps.dev/go/fortio.org%2Ffortio

shows 

CII-Best-Practices
0/10
Determines if the project has a CII Best Practices Badge.
REASONING
no badge detected

while

https://github.com/fortio/fortio/blob/master/README.md

has

[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/6054/badge)](https://bestpractices.coreinfrastructure.org/projects/6054)

https://bestpractices.coreinfrastructure.org/en/projects/6054 shows 100%

**Comment by azeemshaikh38** [comment]
Did the project's status change recently? If that is the case, it is likely that the Scorecard cron job which updates its internal copy of CII data once every few weeks hasn't picked it up. Which would explain the diff in `deps.dev`. 

Note that Scorecard CLI (which directly looks up CII data) recognizes the project's `passing` score already:

```
scorecard --repo=fortio/fortio --checks=CII-Best-Practices
```

So it should get updated through the cron job soon.

**Comment by laurentsimon** [comment]
I verified that the badge is detected via scorecard CLI:
```
"checks": [
    {
      "details": null,
      "score": 5,
      "reason": "badge detected: passing",
      "name": "CII-Best-Practices",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#cii-best-practices",
        "short": "Determines if the project has a CII Best Practices Badge."
      }
    }
  ],

```

**Comment by ldemailly** [comment]
oh thanks! yes I filled it up recently when I learned about deps.dev; might be worth adding that update frequency to the docs to avoid false reports like mine

thanks a lot for having checked!

**Comment by ldemailly** [comment]
and just to confirm that the package canonical url is fortio.org/fortio while the source resides in github.com/fortio/fortio is not a factor that cause confusion either?

**Comment by azeemshaikh38** [comment]
> and just to confirm that the package canonical url is fortio.org/fortio while the source resides in github.com/fortio/fortio is not a factor that cause confusion either?

Nope. That's handled as long as CII has the right repo URL.

**Comment by laurentsimon** [comment]
Just wanted to point out that des.dev page does show a `Scorecard as of May 16, 2022.`
