### ISSUE TITLE
Docs: Meeting Notes doc is not open for public access

### ISSUE THREAD

**Issue by webchick** [ossf/scorecard#1972]
This might be "by design," but just in case...

I noticed that the [Notes doc](https://docs.google.com/document/d/1dB2U7_qZpNW96vtuoG7ShmgKXzIg6R5XT5Tc-0yz6kE/edit#heading=h.4k8ml0qkh7tl) linked in the README isn't publicly accessible, unlike the ones from other OpenSSF WGs. Is this intentional?

**Comment by naveensrinivasan** [comment]
The access to the document is associated with this google group. I don’t know if it is this https://groups.google.com/g/ossf-scorecard-announce group or this https://groups.google.com/g/ossf-scorecard-dev.

**Comment by naveensrinivasan** [comment]
Closing this. If you have other questions, please start a [discussion](https://github.com/ossf/scorecard/discussions)

**Comment by evverx** [comment]
I'm not sure why this issue was closed without making the meeting notes public (or at least expanding on why they aren't). The other OpenSSF repositories like https://github.com/ossf/wg-securing-critical-projects and https://github.com/ossf/tac provide links to their publicly available read-only meeting notes. Can it be reopened?

**Comment by spencerschrock** [comment]
Due to some limitations with how the doc was created, it can't be setup such that "Anyone with the link can read". I believe that's one reason access it routed through https://groups.google.com/g/ossf-scorecard-dev. Does this help with access @evverx ?

I'm checking on fixes to avoid needing to join the dev group, but the answer probably involves recreating the doc and updating the links to it.

**Comment by evverx** [comment]
I don't have a Google account (or more precisely I have one account I created to be able to view OSS-Fuzz reports but it isn't something I use very often). I think it would be great if links lead to read-only docs by analogy with the other OpenSSF repositories. I think it would be the most convenient option.

**Comment by spencerschrock** [comment]
> I don't have a Google account (or more precisely I have one account I created to be able to view OSS-Fuzz reports but it isn't something I use very often). I think it would be great if links lead to read-only docs by analogy with the other OpenSSF repositories. I think it would be the most convenient option.

resolved by #3111

**Comment by evverx** [comment]
Thanks! I can confirm that I have access to that google doc.

https://github.com/ossf/scorecard/blob/36e3364c5a7d30ece75f407b5c1a17e2b3214f76/README.md?plain=1#LL553C41-L553C148 still points to the private doc though. (I'm not sure why the meeting notes are mentioned twice there)

**Comment by evverx** [comment]
FWIW @spencerschrock looks like that doc isn't read-only. Even though I'm all for open access I think random people from the internet shouldn't be able to edit it :-)

**Comment by spencerschrock** [comment]
> FWIW @spencerschrock looks like that doc isn't read-only. Even though I'm all for open access I think random people from the internet shouldn't be able to edit it :-)

The doc is managed by the linux foundation now (which is part of what enabled it to be anonymously shared, different org different sharing policies). I also pointed out editable by anyone, but they haven't had an issue with it yet.

**Comment by evverx** [comment]
> they haven't had an issue with it yet

For the record to judge from https://docs.google.com/document/d/1b6d3CVJLsl7YnTE7ZaZQHdkdYIvuOQ8rzAmvVdypOWM/edit it seems it came up today
> I’d like to change our Scorecard meeting note permissions; currently they are “edit by all”. I want to switch to “comment by all” to prevent problems from trolls

I'm not sure why it took two weeks to get to that point but either way it was fixed. As far as I can remember there were other OSSF "edit-all" docs like https://docs.google.com/document/d/1wSugi_EjgQ6ttINg1yXqsVAO9V3B-v2jdQT1RX22MZQ/edit?usp=sharing. They should probably be fixed too.
