### ISSUE TITLE
Upgrade go to 1.16

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#204]
Upgrade go version to 1.16 https://blog.golang.org/go1.16

**Comment by inferno-chromium** [comment]
Just fyi, https://blog.golang.org/go116-module-changes

**Comment by naveensrinivasan** [comment]
> Just fyi, https://blog.golang.org/go116-module-changes

Yes, Thanks for the heads up.

**Comment by naveensrinivasan** [comment]
Fixed by #233
