### ISSUE TITLE
Move application of Binary Artifacts Gradle Wrapper Action exception into checks/evaluation/

### ISSUE THREAD

**Issue by ethanent** [ossf/scorecard#2048]
**Is your feature request related to a problem? Please describe.**
This is where the feature should be implemented so that log messages can reflect the exception, rather than having it be an opaque process for users. It would mean that [raw/binary_artifacts](https://github.com/ossf/scorecard/blob/main/checks/raw/binary_artifact.go) returns the expected files, without special exclusions.

**Describe the solution you'd like**
Move the exception to [checks/evaluation/binary_artifacts.go](https://github.com/ossf/scorecard/blob/main/checks/evaluation/binary_artifacts.go).
- Create log messages reflecting the status of the exception so that users can see details

**Describe alternatives you've considered**
Current stopgap implementation is opaque and solves the immediate issue by having raw/binary_artifacts exclude gradle-wrapper.jar files from being returned when the Action is detected.

**Additional context**
First mentioned in #2039.

**Comment by spencerschrock** [comment]
Completed as part of #3508
