### ISSUE TITLE
BUG: Pinned-Dependencies results do not show up in some scorecard-action runs

### ISSUE THREAD

**Issue by varunsh-coder** [ossf/scorecard#2051]
**Describe the bug**
I have observed that Pinned-Dependencies results do not show up in some scorecard-action runs. 

**Reproduction steps**

Here are some recent runs of scorecard-action where Pinned-Dependencies results do not show up. 
1. https://github.com/step-security/secure-workflows/runs/7322716505?check_suite_focus=true#step:4:386
2. https://github.com/project-zot/zot/runs/7310494657?check_suite_focus=true#step:4:389
3. https://github.com/WeblateOrg/weblate/runs/7307864288?check_suite_focus=true#step:4:394

**Expected behavior**

I expected findings related to Pinned-Dependencies since there are GitHub Actions workflows in the above 3 repos that do not have pinned Actions. 

**Additional context**
This is not always the case. Here is a recent run in a different repo that did have Pinned-Dependencies results
https://github.com/wallarm/ingress/runs/7322496587?check_suite_focus=true#step:4:410

**Comment by laurentsimon** [comment]
Thanks for the report. The SARIF generated show no PinnedDependency entry, even though the scorecard CLI does.
I'll take a look. Anything special about the token you're using?

Maybe we should start dumping the results as JSON as well in the log, to help troubleshooting

**Comment by varunsh-coder** [comment]
> Thanks for the report. The SARIF generated show no PinnedDependency entry, even though the scorecard CLI does. I'll take a look. Anything special about the token you're using?
> 
> Maybe we should start dumping the results as JSON as well in the log, to help troubleshooting

Thanks @laurentsimon!

For all of the 3 workflow runs I mentioned in the issue, the workflows use `GITHUB_TOKEN`. I am assuming the scorecard-action uses `GITHUB_TOKEN` when `PAT` is not specified. The 3 workflows do not specify `PAT`.

**Comment by varunsh-coder** [comment]
Another possibly related issue is that in first 2 of these workflow runs, the token permission results show up, but the remediation section does not have deep link to app.stepsecurity.io.

**Comment by laurentsimon** [comment]
Yeah I remember seeing something strange like this a while ago too.
I remember there was a problem in the tagging we did in our staging builds, so it could happen that we're using a wrong scorecard binary. I doubt it.. but we could verify by extracting the binary from the container we use.

Mhh, I checked your logs:
first link: Scorecard v4.3.1
second link: v4.3.0-36-g70d045b
third link: v4.3.1
last link: v4.3.1

None of them use the latest scorecard version, maybe that's the reason. Although I checkout the tag and I still see a proper SARIF results for PinnedDependency. I. don't see the custom remediation, however.

**Comment by laurentsimon** [comment]
Could you try running `uses: laurentsimon/scorecard-action@test/bug-2051` or `ossf/scorecard-acction@main`. It should print both the JSON and SARIF format. I suspect the pinned dependency is catching an error, and we ignore errors when creating the SARIF format.

Thanks

**Comment by laurentsimon** [comment]
follow-up: if you use my branch, the workflow will eventually fail because of the new badge code. (Just Fyi, it's normal and s you can ignore ). The `@main` should succeed.

**Comment by varunsh-coder** [comment]
Thanks @laurentsimon!

I ran using both. 
This is run using `laurentsimon/scorecard-action@test/bug-2051`
https://github.com/step-security/secure-workflows/runs/7371135468?check_suite_focus=true

This is run using `ossf/scorecard-action@main`
https://github.com/step-security/secure-workflows/runs/7371108796?check_suite_focus=true

I can see this error for pinned dependencies:
`{"details":null,"score":-1,"reason":"internal error: remdiationSetup: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration","name":"Pinned-Dependencies","documentation":{"url":"https://github.com/ossf/scorecard/blob/70d045b9ef00e7171ce3950aca38eef6ea4d7308/docs/checks.md#pinned-dependencies","short":"Determines if the project has declared and pinned its dependencies."}}`

I did not notice anything related to why remediation deep link for token permission issue not showing with app.stepsecurity.io, but it may be related...

**Comment by varunsh-coder** [comment]
Looks like it tries to fetch default branch using GraphQL, which is failing...

https://github.com/ossf/scorecard/blob/70d045b9ef00e7171ce3950aca38eef6ea4d7308/clients/githubrepo/branches.go#L143

Also, for token perms, this error does not return, but continues using earlier logic. This explains why it does not show the deep link, but does show the earlier remediation info...

https://github.com/ossf/scorecard/blob/70d045b9ef00e7171ce3950aca38eef6ea4d7308/checks/permissions.go#L86-L88

**Comment by laurentsimon** [comment]
> Thanks @laurentsimon!
> 
> I ran using both. This is run using `laurentsimon/scorecard-action@test/bug-2051` https://github.com/step-security/secure-workflows/runs/7371135468?check_suite_focus=true
> 
> This is run using `ossf/scorecard-action@main` https://github.com/step-security/secure-workflows/runs/7371108796?check_suite_focus=true
> 
> I can see this error for pinned dependencies: `{"details":null,"score":-1,"reason":"internal error: remdiationSetup: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration","name":"Pinned-Dependencies","documentation":{"url":"https://github.com/ossf/scorecard/blob/70d045b9ef00e7171ce3950aca38eef6ea4d7308/docs/checks.md#pinned-dependencies","short":"Determines if the project has declared and pinned its dependencies."}}`

Great, so that's the reason. It looks like graphQL is not able to use the default GITHUB_TOKEN to retrieve the branch setting !? @azeemsgoogle any thoughts?

> I did not notice anything related to why remediation deep link for token permission issue not showing with app.stepsecurity.io, but it may be related...

definitely related, because we need the query the default branch to generate the link.

**Comment by varunsh-coder** [comment]
For the token permissions scenario, I was looking at the latest code. 

If I look at the code for `v4.4.0` of `v4.3.1`, the code is different. Please see this (`v4.4.0`):

https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/checks/permissions.go#L86-L94

I am not sure how to interpret this w.r.t remediation deep link, but it does not immediately return an error like the code for pin dependencies does (below). This is why the results for token permissions are shown, even though `remdiationSetup` returns an error. 

https://github.com/ossf/scorecard/blob/e42af756609b2cde6d757fd45ea05ddf0016ff62/checks/pinned_dependencies.go#L44-L46

**Comment by laurentsimon** [comment]
I managed to reproduce the problem, I think. AFAICT, it happens with a PAT only:
```
error during branchesHandler.setup: internal error: githubv4.Query: Your token has not been granted the required scopes to execute this query. The 'allowsDeletions' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:discussion', 'read:org', 'read:packages', 'read:repo_hook', 'security_events'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

@varunsh-coder can you confirm you're using a PAT? The required permission is the same needed for the branch protection setting. It should work with the default GITHUB_TOKEN.
I'll check whether the equivalent REST API works with the PAT I use.

**Comment by laurentsimon** [comment]
the default branch can be queried with the same PAT using the REST API `/repos/org/repo | jq -r '.default_branch'`

@azeemsgoogle what do you think of using the REST API to get the default branch? 

We also nee to have better tests for this; it was not caught :/

**Comment by varunsh-coder** [comment]
> I managed to reproduce the problem, I think. AFAICT, it happens with a PAT only:
> 
> ```
> error during branchesHandler.setup: internal error: githubv4.Query: Your token has not been granted the required scopes to execute this query. The 'allowsDeletions' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:discussion', 'read:org', 'read:packages', 'read:repo_hook', 'security_events'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> ```
> 
> @varunsh-coder can you confirm you're using a PAT? The required permission is the same needed for the branch protection setting. It should work with the default GITHUB_TOKEN. I'll check whether the equivalent REST API works with the PAT I use.

Hi @laurentsimon I am not using PAT. Here is the workflow: https://github.com/step-security/secure-workflows/blob/main/.github/workflows/scorecards.yml

The other two workflows I had reported in the initial bug report are also not using PAT. 
https://github.com/project-zot/zot/blob/main/.github/workflows/scorecards.yml
https://github.com/WeblateOrg/weblate/blob/main/.github/workflows/scorecards.yml

Also, the error from the workflow logs is different. It simply says `Resource not accessible by integration`. 

I am assuming that absence of explicit PAT will result in use of GITHUB_TOKEN. Based on this assumption, these workflows should use GITHUB_TOKEN. Is there a way to confirm from workflow logs whether PAT or GITHUB_TOKEN is being used?

**Comment by laurentsimon** [comment]
> > I managed to reproduce the problem, I think. AFAICT, it happens with a PAT only:
> > ```
> > error during branchesHandler.setup: internal error: githubv4.Query: Your token has not been granted the required scopes to execute this query. The 'allowsDeletions' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:discussion', 'read:org', 'read:packages', 'read:repo_hook', 'security_events'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @varunsh-coder can you confirm you're using a PAT? The required permission is the same needed for the branch protection setting. It should work with the default GITHUB_TOKEN. I'll check whether the equivalent REST API works with the PAT I use.
> 
> Hi @laurentsimon I am not using PAT. Here is the workflow: https://github.com/step-security/secure-workflows/blob/main/.github/workflows/scorecards.yml
> 
> The other two workflows I had reported in the initial bug report are also not using PAT. https://github.com/project-zot/zot/blob/main/.github/workflows/scorecards.yml https://github.com/WeblateOrg/weblate/blob/main/.github/workflows/scorecards.yml
> 
> Also, the error from the workflow logs is different. It simply says `Resource not accessible by integration`.

Interesting. I was not able to reproduce the problem with the default token. 

> I am assuming that absence of explicit PAT will result in use of GITHUB_TOKEN. Based on this assumption, these workflows should use GITHUB_TOKEN. Is there a way to confirm from workflow logs whether PAT or GITHUB_TOKEN is being used?

Correct.

**Comment by laurentsimon** [comment]
If you fork the repo, do you still see the same error message? I'm trying to figure out a way to reproduce the problem... would forking it be enough? 

Could you try run again with `laurentsimon/scorecard-action@test/bug-2051`? I added some more printf.

**Comment by varunsh-coder** [comment]
> If you fork the repo, do you still see the same error message? I'm trying to figure out a way to reproduce the problem... would forking it be enough?
> 
> Could you try run again with `laurentsimon/scorecard-action@test/bug-2051`? I added some more printf.

I ran it with the action you suggested. here is the log:
https://github.com/step-security/secure-workflows/runs/7507610419?check_suite_focus=true

See this error:
https://github.com/step-security/secure-workflows/runs/7507610419?check_suite_focus=true#step:4:162
`end remediation.Setup: error during branchesHandler.setup: internal error: githubv4.Query: Resource not accessible by integration`

**Comment by laurentsimon** [comment]
Thanks. So it's the same error message I got.
I've tested with workflow_dispatch only. Ill try with push: I think that's the culprit. push trigger has restricted access to permissions (read all), I bet this is the problem.

**Comment by laurentsimon** [comment]
No problem on `push` / `pull_request` trigger event on my end with the GITHUB_TOKEN.

**Comment by varunsh-coder** [comment]
I figured out why this works on some repos and not on others. 

It has to do with whether the repo has branch protection enabled or not. To repro, please enable branch protection on `https://github.com/laurentsimon/scorecard-action-test-2` and try running scorecard using GitHub Action. 

The reason this happens is because this code tries to get details about branch protection. Some of those attributes need `administration` access, which the `GITHUB_TOKEN` does not have. 

https://github.com/ossf/scorecard/blob/0eb7cb2d748725b177d633bcd421a07fc0732721/clients/githubrepo/branches.go#L94-L106

When branch protection is not setup, I believe those attributes do not exist, so the call works. When branch protection is enabled, the call fails.

**Comment by laurentsimon** [comment]
Great finding, thank you!
So is the solution to use the public REST API to figure the default branch instead? The REST API, IFAIK, does not have restrictions based on token.

**Comment by varunsh-coder** [comment]
In the `remediations.go` file, the reason to call `GetDefaultBranch` is to set `branch`. 

https://github.com/ossf/scorecard/blob/0eb7cb2d748725b177d633bcd421a07fc0732721/remediation/remediations.go#L63-L65

I am wondering if there is already code in Scorecard that gets this info without calling `GetDefaultBranch` in `branches.go`. 
e.g. this should have default branch. I believe default branch is included in the GET repo call (e.g. https://api.github.com/repos/ossf/scorecard).
https://github.com/ossf/scorecard/blob/0eb7cb2d748725b177d633bcd421a07fc0732721/clients/githubrepo/client.go#L41

If not, then yes, looks like we need a method that only returns default branch (without querying branch protection). 
It can also be done using GraphQL as long as the request does not query branch protection stuff. 
The restriction is not due to use of GraphQL, but due to querying branch protection, which needs `administration` access, which the GITHUB_TOKEN does not have.

**Comment by varunsh-coder** [comment]
I can confirm that `default branch name` is already available and we do not need to make extra calls for it. 

I can add this new method in `RepoClient` interface and below implementation in `githubrepo/client.go`. 

When I make these changes, the issue gets fixed. I tried it out and the workflow got all the pinned-dependencies issues. 

```
func (client *Client) GetDefaultBranchName() (*string, error) {
 	return client.repo.DefaultBranch, nil
 }
```

Let me know if this looks good, and I can create a PR for it.

**Comment by laurentsimon** [comment]
That'd be great. It's my mistake that I did not use `GetDefaultBranchName()`, I think I did not see the function so I picked the one that seemed to jut work :/

**Comment by varunsh-coder** [comment]
Actually, `GetDefaultBranchName` does not exist today. I was proposing to add it with this implementation. 

```
func (client *Client) GetDefaultBranchName() (*string, error) {
 	return client.repo.DefaultBranch, nil
 }
```

`client.repo.DefaultBranch` does exist, so adding it should be easy.

**Comment by laurentsimon** [comment]
LGTM.
