### ISSUE TITLE
Use https://github.com/dorny/paths-filter for GH Actions

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#2052]
**Is your feature request related to a problem? Please describe.**
Right now our GH Actions run for every change and we are being throttled by GH API. We could use this https://github.com/dorny/paths-filter to filter out when each of these actions runs based on code changes.

**Comment by Shofiya2003** [comment]
Can I work on this issue?

**Comment by naveensrinivasan** [comment]
> Can I work on this issue?

Thank you @Shofiya2003! Can we start with a few changes in a PR to make sure it works the way we expect it to work?

**Comment by Shofiya2003** [comment]
From what I understand, currently all the jobs in github actions run when a pull request is created. We need to use [path filters](https://github.com/dorny/paths-filter) to run some jobs only when particular file is changed or the change meets the condition specified. 
I will start by studying the syntax of `path-filters` and how to integrate them.
Then will look for jobs in  `main.yml `  that are specific. 
Jobs like `unit tests` should run for every pull request. Right?
@naveensrinivasan

**Comment by naveensrinivasan** [comment]
> From what I understand, currently all the jobs in github actions run when a pull request is created. We need to use [path filters](https://github.com/dorny/paths-filter) to run some jobs only when particular file is changed or the change meets the condition specified.
> I will start by studying the syntax of `path-filters` and how to integrate them.
> Then will look for jobs in `main.yml ` that are specific.
> Jobs like `unit tests` should run for every pull request. Right?
> @naveensrinivasan

I agree, unit-tests should run for every PR, unless they are markdown changes alone.

**Comment by spencerschrock** [comment]
Take a look at some of the discussion in:
https://github.com/ossf/scorecard/pull/2508
and 
https://github.com/ossf/scorecard/pull/2566

We are using `tj-actions/changed-files` to filter in some of our other steps

**Comment by Shofiya2003** [comment]
@naveensrinivasan I used path filters to check if there are only markdown changes and made sure the job `unit-test`
https://github.com/ossf/scorecard/blob/2ea140a3ee9279904f29ed335b2bbef0923f242e/.github/workflows/main.yml#L34
does not run when there are only markdown changes
Do you want me to create a PR to test the changes? Then I can work on other jobs.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan I used path filters to check if there are only markdown changes and made sure the job `unit-test`
> 
> https://github.com/ossf/scorecard/blob/2ea140a3ee9279904f29ed335b2bbef0923f242e/.github/workflows/main.yml#L34
> 
> 
> does not run when there are only markdown changes
> Do you want me to create a PR to test the changes? Then I can work on other jobs.

That is great start! Thanks

**Comment by Shofiya2003** [comment]
@naveensrinivasan created a PR could you please see if this is what has to be done. I'll start making further changes accordingly
Thanks a ton

**Comment by Shofiya2003** [comment]
@naveensrinivasan do you want me to think of more changes to reduce the throttling?

**Comment by spencerschrock** [comment]
Throttling hasn't been a problem in quite a while, going to close for now.
