### ISSUE TITLE
Move to Renovate  instead of GH Dependabot 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#2053]
**Is your feature request related to a problem? Please describe.**

- We have lots of PRs from Dependabot. This makes it harder to maintain renovate seems to have an option to combine many of these into 1 single PR.
- Our actions run into rate limiting because at the moment we have about 10-12 Dependabot PRs and every time we merge one we run into every other PR rebase and in turn that causes all our actions to run. 
- Recently https://github.com/slsa-framework https://github.com/slsa-framework/slsa-github-generator started using this to avoid this many PR's.

**Comment by spencerschrock** [comment]
Is this still something we're considering? 
Dependabot doesn't appear to have an ETA for the feature https://github.com/github/roadmap/issues/148

**Comment by spencerschrock** [comment]
Note: Grouped updates are a thing for dependabot now, just not across ecosystems (e.g. we'll have one update for our go.mod and one update for our tools/go.mod)
