### ISSUE TITLE
Implement abuse detection in GitHub API requests

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#206]
The GitHub API would return `403` if there are too many requests for example `cron` running for a bunch of `repositories`

```
{
      "CheckName": "Signed-Releases",
      "Pass": false,
      "Confidence": 0,
      "Details": [
        "error, retrying: GET https://api.github.com/repos/activescaffold/active_scaffold/releases: 403 You have triggered an abuse detection mechanism. Please wait a few minutes before you try again. []"
      ]
    },
    {
      "CheckName": "Signed-Tags",
      "Pass": false,
      "Confidence": 0,
      "Details": [
        "error, retrying: non-200 OK status code: 403 Forbidden body: \"{\\n  \\\"documentation_url\\\": \\\"https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#abuse-rate-limits\\\",\\n  \\\"message\\\": \\\"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\\\"\\n}\\n\""
      ]
    }
 ```
 
Probably implement this solution 
https://github.com/google/go-github/issues/431#issuecomment-427844348
https://github.com/hashicorp/terraform-provider-github/blob/fa73654b66e37b1fd8d886141d9c2974e24ba42f/github/transport.go#L42-L109 and it also has [tests](https://github.com/hashicorp/terraform-provider-github/blob/master/github/transport_test.go)

**Comment by afmarcum** [comment]
Does this bug still needs to be addressed?
If there is no feedback in the next 7 days on whether this remains important for the project, then this issue will be closed.

**Comment by spencerschrock** [comment]
We haven't been getting abuse detection responses in the cron this year. We also handle `Retry-After` as part of #2721, so maybe that's why we're not seeing them anymore.
