### ISSUE TITLE
BUG: potential missing fuzzing results when ListProgrammingLanguages() returns an error

### ISSUE THREAD

**Issue by aidenwang9867** [ossf/scorecard#2062]
**Describe the bug**
The fuzzing check might return **empty** when `RepoClient.ListProgrammingLanguages()` fails and an error occurs, but has already found checking results  of `ossFuzz` or `CFLite`. See the code logic [here](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L96-L98).

**Reproduction steps**
I haven't tested this with cases because the call of `RepoClient.ListProgrammingLanguages()` always succeeds. However, in [raw.Fuzzing](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L64), if we've already found ossFuzz/CFLite fuzzers but the repo language retrieval failed, it'll return `checker.FuzzingData{}` (empty data), such that the previous fuzzer records might be dropped.

**Expected behavior**
The `raw.Fuzzing` function should return results of ossFuzz/CFLite fuzzers even if an error occurs when retrieving the repo languages.

That said, change [this line](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L98) from
```go
return checker.FuzzingData{}, fmt.Errorf("cannot get langs of repo: %w", err)
```

to 

```go
return checker.FuzzingData{Fuzzers: fuzzers}, fmt.Errorf("cannot get langs of repo: %w", err)
```

**Additional context**
We might should not always trust the [GitHub List Repo Languages API](https://docs.github.com/en/rest/repos/repos#list-repository-languages) will give us the correct list of repo languages. It might give us an error, an empty one, or one with duplicates (issue #2060) sometimes.

**Comment by aidenwang9867** [comment]
The possible reasons for the `ListProgrammingLanguages` to fail can be traced to the langauge [setup()](https://github.com/ossf/scorecard/blob/main/clients/githubrepo/languages.go#L46) func.

If (1) the request to the GitHub API fails or (2) parsing the response fails, the setup() func will wrap the error and return it all the way back to `ListProgrammingLanguages`. That said, a possible error situation might be the first one, when the GitHub API is not available, so we cannot get the list of repo languages to check the function-level fuzzers.

**Comment by aidenwang9867** [comment]
Actually, I haven't seen it fail in my previous testing, and the `ListProgrammingLanguages` is only used by the fuzzing check now, so I don't think its failure will affect the other checks.

If the HTTP request to the GH Language API fails and thus leads to the `ListProgrammingLanguages` failing, the only check that will be affected should be the Fuzzing check. My concern is if the language API fails with an HTTP error when we already have fuzzer results of other fuzzing tools in var [fuzzers](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L65), returning an empty fuzzer result at [L98](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L98) might lose the previous results.

Again, since I have not seen the lang API error before, maybe I'm a bit over-worried about this?

**Comment by laurentsimon** [comment]
It's probably fine leave as-is then. It's good to return an error, rather than ignore it and use the incomplete results. Feel free to close the bug if your agree.

**Comment by aidenwang9867** [comment]
thank you!
