### ISSUE TITLE
Feature: use the BigQuery dataset to supplement null source repo URLs for dependency checks

### ISSUE THREAD

**Issue by aidenwang9867** [ossf/scorecard#2063]
**Is your feature request related to a problem? Please describe.**
In v0 of the DepedencyDiff API (issue #2008), we skip those dependencies without a srcRepo URL for the scorecard checks, but those dependencies might be important.

**Describe the solution you'd like**
Use the BigQuery dataset to retrieve the srcRepo given the dependency's {pkg_ecosystem, pkg_name, pkg_version}, to supplement those null srcRepo URLs and get them checked by scorecard.

**Additional context**
This is a TODO introduced in PR #2046.

**Comment by spencerschrock** [comment]
https://github.com/ossf/scorecard/issues/2008#issuecomment-2140865208
