### ISSUE TITLE
Release scorecard 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#2115]
Release scorecard https://github.com/sigstore/sigstore-java/issues/2#issuecomment-1201899264

**Comment by naveensrinivasan** [comment]
@laurentsimon @azeemshaikh38  Planning to release at this SHA `69eb1ccf1d0cf8c5b291044479f18672bf250325`.

**Comment by azeemshaikh38** [comment]
SGTM.

**Comment by laurentsimon** [comment]
Thank you!

**Comment by naveensrinivasan** [comment]
https://github.com/ossf/scorecard/releases/tag/v4.5.0
