### ISSUE TITLE
scorecard_4.5.0_linux_amd64.tar.gz wasn't released

### ISSUE THREAD

**Issue by suzuki-shunsuke** [ossf/scorecard#2118]
Thank you for your great project!

I found scorecard_4.5.0_linux_amd64.tar.gz wasn't released.

https://github.com/ossf/scorecard/releases/tag/v4.5.0

<img width="984" alt="image" src="https://user-images.githubusercontent.com/13323303/182516879-76abbc01-90b1-460e-8ca3-b46123888d5e.png">

On the other hand, scorecard_4.4.0_linux_amd64.tar.gz was released.

https://github.com/ossf/scorecard/releases/tag/v4.4.0

<img width="973" alt="image" src="https://user-images.githubusercontent.com/13323303/182516944-11fcabc9-6acb-4713-9bd7-249e93977e15.png">

Could you release scorecard_4.5.0_linux_amd64.tar.gz?

Thank you.

**Comment by suzuki-shunsuke** [comment]
https://github.com/ossf/scorecard/runs/7638647801?check_suite_focus=true

**Comment by suzuki-shunsuke** [comment]
Oh, this change seems to be intentional.
I'll take a look SLSA.

**Comment by suzuki-shunsuke** [comment]
```console
$ slsa-verifier --artifact-path scorecard-linux-amd64 \
  --provenance scorecard-linux-amd64.intoto.jsonl \
  --source github.com/ossf/scorecard \
  --tag v4.5.0
2022/08/03 04:10:35 open scorecard-linux-amd64: no such file or directory
```

**Comment by suzuki-shunsuke** [comment]
CI failed.
https://github.com/ossf/scorecard/runs/7638656220?check_suite_focus=true

**Comment by azeemshaikh38** [comment]
@laurentsimon fyi.

**Comment by laurentsimon** [comment]
Thanks. Sigstore made a breaking change which breaks every existing builder. Sorry abut that. Working on backporting some fixes to the older builders ...

**Comment by laurentsimon** [comment]
Now it is released https://github.com/ossf/scorecard/releases/tag/v4.6.0
I encourage you to verify the provenance, using the steps described in https://github.com/ossf/scorecard#installation

It would be fun to simulate an attack and catch it via your automated CI.
