### ISSUE TITLE
Usage of scorecard with docker - documentation incomplete

### ISSUE THREAD

**Issue by norppaturva** [ossf/scorecard#212]
Is it possible to have a bit more information in the readme on how to run scorecard from docker, please?

I have pulled the package (docker pull docker.pkg.github.com/ossf/scorecard/scorecard) and then started the container (docker run -d --name scorecard docker.pkg.github.com/ossf/scorecard/scorecard) however, when I am trying to execute the scorecard with this command: docker exec -it scorecard ./scorecard , I am getting an error:

OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "./scorecard": stat ./scorecard: no such file or directory: unknown

I have also tried to connect to bash first (docker exec -it scorecard bash), but it seems like there is no bash...

Am I missing something or am I running the container in a wrong way?

**Comment by naveensrinivasan** [comment]
@norppaturva  Can you try with this command?
`docker run -e GITHUB_AUTH_TOKEN=token docker.pkg.github.com/ossf/scorecard/scorecard  --show-details  --repo=https://github.com/ossf/scorecard`

To the above docker container, you should be able to pass the standard command-line arguments.

The docker container does not have a bash.

**Comment by norppaturva** [comment]
Thank you so much for a fast reply, this finally works!
