### ISSUE TITLE
Feature: Scorecard policy that helps evaluate results for GCP Binary Authorization

### ISSUE THREAD

**Issue by raghavkaul** [ossf/scorecard#2136]
### Current Behavior
Today, scorecard's policies can be used to enable/disable certain checks. As per #1405 , the `--policy` flag was disabled in favor of implementing a settings-based policy file. 

### Desired Behavior
One motivation for scorecard policies is to use them to make decisions about the runtime authorization (e.g. Google Cloud [Binary Authorization](https://cloud.google.com/binary-authorization/)) for an application. For example, an operator may want to use scorecard to implement the rule `Don't run this application unless the SCM repo used to build this application is free from Binary Artifacts AND unless the SCM repo mandated two-party review.`

We can think of 'policies' as a way of using all of scorecard's data to answer questions an operator may have about an application, as opposed to what is done today, which uses policies to change how scorecard behaves.

One possible approach would take heavy inspiration from the way [Allstar policies](https://pkg.go.dev/github.com/ossf/allstar/pkg/policies/branch#OrgConfig) are written.

This is linked to #1245.

**Comment by david-a-wheeler** [comment]
Thanks! I wonder - the yaml-based approach may have some overlap with the proposed "SECURITY-INSIGHTS" document, per <https://github.com/ossf/security-insights-spec>.

**Comment by raghavkaul** [comment]
@david-a-wheeler Thanks for bringing that project to my attention! My initial thought is that the threat model of Security-Insights is different from that of a Binary Authorization policy (or other deployment policy). Whereas Security-Insights is the set of insights about a specific repo declared by the repo owner, the Binary Authorization policy would be a set of standards for any repo declared by a cloud deployment gatekeeper. If repo owners controlled the Binary Authorization/deployment policy, then they could upload a policy that would always pass and always allow deployment, even if the Scorecard score was low and the practices followed were poor.
However, if we were to use this schema on the deployer-side, an allstar-style policy would be easier to use because it would expresses security requirements more directly. For example, if I wanted to express "The code in an artifact must require 2-party review in its SCM in order to be deployed," in an allstar-style policy format, this would be a one-line change (`ApprovalCount: 2`), and the implementation of the policy logic would fall on Scorecard maintainers. Using Security-Insights means Scorecard can be more generic and not maintain as much custom logic for each check, but I think expressing the same requirement as a YAML (even if it was sparse, and we did something like semantic YAML matching) would be a higher bar for the end-users of this feature.

**Comment by azeemshaikh38** [comment]
@laurentsimon @naveensrinivasan @justaugustus - Raghav is ready to start work on this. Please give a shout if there are any concerns here.

**Comment by laurentsimon** [comment]
This work works well on branch protection because each result is "named", but not well for other checks like token-permissions or pinning. What's the plan for the others?

**Comment by azeemshaikh38** [comment]
IMO some checks like `Branch-Protection`, `Token-Permissions` shouldn't be exposed at all through this policy. I don't see these checks being useful to gate an image built at commit X. The list of checks to expose here IMO are: `Bin-Artifact`, `CI-Tests`, `Code-Review`, `Pinned-Deps`, `SAST` and `Vulnerabilities` (atleast for the initial release).

And for checks that require an ignoreList (`Pinned-Deps`, `Bin-Artifacts`) how about something like:

```
ScorecardPolicy struct  {
  // In YAML, specify:
  // allowedUnpinnedDependencies: nil // Disable this check.
  // allowedUnpinnedDependencies: []  // Enable this check and apply on all.
  // allowedUnpinnedDependencies: // Enable and apply on all except provided exceptions.
  //   - dependency:
  //        filepath: <>
  AllowedUnpinnedDependencies []Dependency{
     Filepath string
     PackageName string
     Version string
  }
  // 
  AllowedBinaryArtifacts []FilePath
}
```

Wdyt?

**Comment by laurentsimon** [comment]
> IMO some checks like `Branch-Protection`, `Token-Permissions` shouldn't be exposed at all through this policy. 

do you mean `Dependency-Pinning` or `Branch-Protection`? (I'm asking because @raghavkaul 's initial description is heavy on the Branch-Protection check.) I understand that the check is not bound to a commit / source code, though. If this is better suited for AllStar, does this mean we'll ask users to install both? Or will AllStar encompass all the policies we declare here?

I don't see these checks being useful to gate an image built at commit X. The list of checks to expose here IMO are: `Bin-Artifact`, `CI-Tests`, `Code-Review`, `Pinned-Deps`, `SAST` and `Vulnerabilities` (atleast for the initial release).

It's not clear why, for example, `Token-Permissions` could not be exposed. What's the reasoning?

> And for checks that require an ignoreList (`Pinned-Deps`, `Bin-Artifacts`) how about something like:
> 
> ```
> ScorecardPolicy struct  {
>   // In YAML, specify:
>   // allowedUnpinnedDependencies: nil // Disable this check.
>   // allowedUnpinnedDependencies: []  // Enable this check and apply on all.
>   // allowedUnpinnedDependencies: // Enable and apply on all except provided exceptions.
>   //   - dependency:
>   //        filepath: <>
>   AllowedUnpinnedDependencies []Dependency{
>      Filepath string
>      PackageName string
>      Version string
>   }
>   // 
>   AllowedBinaryArtifacts []FilePath
> }
> ```
> 
> Wdyt?

**Comment by azeemshaikh38** [comment]
> If this is better suited for AllStar, does this mean we'll ask users to install both? Or will AllStar encompass all the policies we declare here?

Scope here does not include defining a generic policy. This policy definition will only be used for expressing a BinAuthz policy.

> It's not clear why, for example, Token-Permissions could not be exposed. What's the reasoning?

It could be exposed, I mean they *don't need to be* because there doesn't seem to be a strong usecase for a BinAuthz client to gate on Token-Permissions.

**Comment by raghavkaul** [comment]
The main reason to keep Branch-protection out of the checks is that it's point in time, so it makes sense for Allstar because Allstar checks it during merge-time, but for a deployment-time check, Binary authorization could have been enabled post-hoc.

Also agree with the first set of checks implemented into policy to be:
```
Bin-Artifact, CI-Tests, Code-Review, Pinned-Deps, SAST and Vulnerabilities
```

> This work works well on branch protection because each result is "named", but not well for other checks like token-permissions or pinning. What's the plan for the others?
It's case by case - everything we express in YAML may have a different check format depending on what makes sense for a deployer to gate on
