### ISSUE TITLE
Feature: Improved Security-Policy checks

### ISSUE THREAD

**Issue by shissam** [ossf/scorecard#2137]
**Is your feature request related to a problem? Please describe.**
The mere existence of a `SECURITY.md` file (or other file(s) searched such as `.adoc`) with 1 or more bytes in the repo rewards the project's score to the fullest possible score (`10`).

**Describe the solution you'd like**
Gradate the Security-Policy check which would incrementally improve the Security-Policy score if the `SECURITY.md` (or found file) contained links to pages or email addresses. That is detecting `https:`, or `mailto:`, or some other pattern (perhaps using regex) on the contents of that file. There would be no need to actually determine if the `https:`, or `mailto:` actually resolved (DNS) or didn't bounce (SMTP). Perhaps:

no Security-Policy: score 0
one found link content: score += 3
more than one found link content: score += 6
more bytes than the sum of the length of all the link content found: score += 4

the score of `10` here could then assume that around all that link content are intelligible words. for instance:

```
Sed ut perspiciatis unde omnis iste https://example.com/security or email security@example.com natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni
```

would score 10 as it has 2 link contents (score = 6) and a length of content (~379) which is greater than the sum of the length of the two link content (48 = strlen of the https (28) + strlen of the email (20)) would be (score = 6 + 4). If the content had no link content, then the final score would be score = 4 or had it only 1 link content, score = 7.

In practice, ossf's own [scorecard file](https://github.com/ossf/scorecard/blob/main/SECURITY.md) would score = 7 (it has one email address and many bytes beyond the length of that email). If ossf's scorecard is intended to be the exemplar, then perhaps another scale could be devised to detect portions of timelines, days, and other disclosure practices - which would require language analysis.

**Describe alternatives you've considered**
If a score for a project was non-zero, pull the appropriate security-policy file and inspect/parse myself. scorecard already details in the report that `"reason": "security policy file detected"` but does not display the file/path/name/URI of what was actually detected--therefore, the burden is on the consumer to 'go hunting' (first) then analyze later.

**Additional context**
The same could be said for the checks `License` and `Signed-Releases` as long as the representative file in GitHub is 1 byte or more, the project is award full points. Although checking the validity of `Signed-Releases` is troublesome, a single byte length file seems too small for any signature. For `License`, more NLP might be called for, but with further investigation known strings could be searched and recommended for those that want to be scorecard friendly. Such as [https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository](url) or [https://opensource.org/licenses](url)

**Comment by laurentsimon** [comment]
sounds like a good idea. One worry is around false negative. We want to be sure we don't miss certain patterns. Have you checked, say, 100 SECURITY.md files to be validate it would work properly?

If you're interested in this, please feel free to send a PR once you've done some preliminary validation.

**Comment by shissam** [comment]
I can do that... when you say `PR` - sorry, my brain is not decoding, do you mean Problem Report?

**Comment by naveensrinivasan** [comment]
> I can do that... when you say `PR` - sorry, my brain is not decoding, do you mean Problem Report?

Pull Request https://docs.github.com/en/get-started/quickstart/github-glossary#pull-request

**Comment by laurentsimon** [comment]
Thank you for this preliminary analysis. If there was a way to map a score ti what piece of information is missing, it would be even better, but I'm not sure it's do-able here. (We this for the branch protection check).

Let me cc @annabellegoth2boss, @SecurityCRob and @david-a-wheeler who have worked on the vulnerability disclosure guideline and may have additional feedback https://github.com/google/oss-vulnerability-guide/blob/main/guide.md
