### ISSUE TITLE
SLSA provenance available check

### ISSUE THREAD

**Issue by behnazh-w** [ossf/scorecard#2145]
@laurentsimon I have a question about the recent [change](https://github.com/ossf/scorecard/commit/777298477c07c262a4ec7e95ceee839b7b3b75ae#diff-ec7162da628e8587757286bab0848563d1be93f39b0e33facc307792d27ffe94R28) that checks for `.intoto.jsonl` extensions in the release assets. With this check, the Scorecard repository itself will not meet the provenance available check, looking at the [latest release assets](https://github.com/ossf/scorecard/releases).

I can see that the trusted builder workflow is called [here](https://github.com/ossf/scorecard/blob/main/.github/workflows/slsa-goreleaser.yml#L32). Would Scorecard report a false positive against itself for SLSA provenance available check?

**Comment by laurentsimon** [comment]
You're right. The provenance is stored inside the zip file.. good catch!
Im going to move Scorecard to use the generic generator soon, because the Go builder only supports a single build. Once we have support for multiple builds, we will release binaries and the provenance will stored next to the binaries, without zip files.

**Comment by behnazh-w** [comment]
Yes, thanks for the quick reply :+1:

**Comment by laurentsimon** [comment]
See https://github.com/ossf/scorecard/pull/2146

**Comment by behnazh-w** [comment]
>If SLSA provenances are found for the releases

Because Scorecard looks for the `.intoto.jsonl` files in the release assets, it would be better to point it out I think, e.g., 
```markdown
If SLSA provenances are found in the [release assets](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)
```

**Comment by laurentsimon** [comment]
Updated, PTAL

**Comment by behnazh-w** [comment]
Great. To be consistent, I think the [docs/checks.md](https://github.com/ossf/scorecard/pull/2146/files#diff-d8f43b021010b7446a8899b82a2a922995dc61b817f61102b5a72a8b97b2eea4R541) should change too.
