### ISSUE TITLE
BUG: Check for created_since in Maintained check

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2150]
Given the recent [malicious forks attack](https://www.bleepingcomputer.com/news/security/35-000-code-repos-not-hacked-but-clones-flood-github-to-serve-malware/), one idea that came up was to use `created_since` signal and use it in the `Maintained` check. What we could do is, if a repo was created in the last X days (say 90), dock some score and add a `warn` detail to the logger. Else the behavior of the check remains the same.

**Comment by naveensrinivasan** [comment]
👍
