### ISSUE TITLE
Improve Score Reporting: License check regexes should be improved  

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2159]
License check should include the following file names: GPL-2.0, LICENSE, LICENCE, LICENSE.txt, LICENSE.rst, LICENSE.PSF, LICENSE.APACHE, LICENSE.BSD, LICENSE.md, LICENSE-MIT.

**Comment by spencerschrock** [comment]
I can tackle this.

Based on how I implement the regex, are additional combinations (`LICENCE.md` instead of `LICENSE.md`) also acceptable? Or should the expanded file names only include the ones you've listed?

**Comment by naveensrinivasan** [comment]
> I can tackle this.
> 
> Based on how I implement the regex, are additional combinations (`LICENCE.md` instead of `LICENSE.md`) also acceptable? Or should the expanded file names only include the ones you've listed?

Thanks, @spencerschrock! Assigning it to you!
