### ISSUE TITLE
Improve Score Reporting: Binary-Artifact filetype detection is not reliable

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2163]
There have been multiple reports by users in the past that Binary-Artifact reports false positives and is noisy. Need to fix this behavior.

**Comment by laurentsimon** [comment]
Was it before or after https://github.com/ossf/scorecard/pull/1879 was merged?
@jeffmendoza reported improvements after this PR and may have some ideas about noise / FP still left

**Comment by spencerschrock** [comment]
Closing due to age, and we haven't seen false positive reports related to file types recently.
