### ISSUE TITLE
Publishing Scorecard data

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#218]
The cron runs the scorecard data for multiple repositories and it is published via the GCS bucket `gs://ossf-scorecards/`. It would be easier to consume this data if it can be published into BigQuery and CDN.

**Comment by naveensrinivasan** [comment]
For example, a use case would be to run scorecard on envoy dependencies and publish it via BigQuery so that the Envoy team can write a query and use this to make decisions on their dependencies.  It is much easier to write queries and it also gives the team how their dependencies are progressing over time by just including the date filter via the query.

**Comment by inferno-chromium** [comment]
Yes definitely agree, we should publish in bigquery. GCS one is just for easy debugging and in case, people just want to pull the database in one big chunk.

**Comment by azeemshaikh38** [comment]
Closing this issue. We now have a cron job which regularly populates the public BigQuery dataset `openssf.scorecardcron.scorecard`.
