### ISSUE TITLE
:bug: Security-Policy check does not catch security policies set at the org level

### ISSUE THREAD

**Issue by wenottingham** [ossf/scorecard#2181]
**Describe the bug**

GitHub allows setting security policies at the organization level.

Example: the aiohttp python project sets their org policy here for their org: https://github.com/aio-libs/.github/blob/master/SECURITY.rst

This policy is read by github, and shown for organization projects: https://github.com/aio-libs/aiohttp/security/policy

However, the scorecard check doesn't find it, as shown on https://deps.dev/pypi/aiohttp  - 0/10 score.

**Reproduction steps**
1.  find a project where the security policy is set at the org level
2.  check that GitHub finds and links their policy
3.  look at the scorecard score

**Expected behavior**

Expected score: 10/10

**Additional context**

Actual score: 0/10

**Comment by azeemshaikh38** [comment]
Fixed in #2180
