### ISSUE TITLE
Blog - Scorecard

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#2204]
With the upcoming release of https://github.com/ossf/scorecard-webapp as a public domain, scorecard should have its blog similar to every other large OSS Supply chain security project https://slsa.dev/blog https://blog.sigstore.dev, etc.

This allows end-users/communities to write blog articles about how scorecard is helping them, and new scorecard releases can be in Scorecard's domain, etc.

This is with respect to community building for scorecard

**Comment by naveensrinivasan** [comment]
@ossf/scorecard  Thoughts?

**Comment by david-a-wheeler** [comment]
@jorydotcom - is there any policy related to a Scorecard blog? SLSA has a blog, didn't know if there were any special rules.

**Comment by LappleApple** [comment]
Is this still relevant? If yes, I'd remove the `enhancement` label.

**Comment by david-a-wheeler** [comment]
I suggest instead of creating a new Scorecard-specific blog, close this issue, and write blog entries (as desired) & post them via the OpenSSF blog. I think you'd get more visibility that way, and no one has to set up another blog site.

**Comment by justaugustus** [comment]
Agreed with leveraging the OpenSSF blog (this has been discussed amongst the maintainers in the past) and it fits what we've been doing to date.
