### ISSUE TITLE
Feature: Questions - Does Scorecard also generate score for app's in App stores?

### ISSUE THREAD

**Issue by rjb4standards** [ossf/scorecard#2205]
Not really a request, more of a question. Can Scorecard generate scores for app's in App stores?

Can Scorecard produce scores on any binary software object or is it limited to certain types of objects?

Thanks,
Dick Brooks
Reliable Energy Analytics (REA)
mailto:dick@reliableenergyanalytics.com

**Comment by spencerschrock** [comment]
Scorecard is run on source code, and is currently heavily geared towards open-source projects hosted on GitHub. 

There are apps in App Stores that meet that definition (such as Signal's [Android](https://github.com/signalapp/Signal-Android) or [iOS](https://github.com/signalapp/Signal-iOS) apps), but you cannot run Scorecard against most apps in an App store. If you know an app is open-source and can find the source repository, you can point Scorecard to that.

**Comment by azeemshaikh38** [comment]
To add to @spencerschrock's answer - for binary artifacts the recommendation is to use [SLSA](https://slsa.dev/). SLSA provenances tie an artifact to a source code from which it was built. Scorecard can then be used produce scores on the source.

**Comment by azeemshaikh38** [comment]
Closing for now, re-open if needed.
