### ISSUE TITLE
BUG: Scorecard not building

### ISSUE THREAD

**Issue by sgoggins** [ossf/scorecard#2213]
**Describe the bug**

**Reproduction steps**
1. Clone repository
2. Type `go build`
3. See results!
```
build github.com/ossf/scorecard/v4: cannot load embed: malformed module path "embed": missing dot in first path element

```
**Expected behavior**
Successful build. 

**Additional context**
Ubuntu 20.04 and several different, recent versions of go have the same result.

**Comment by naveensrinivasan** [comment]
@sgoggins Thanks, What version of `go` are you using to build? 

Scorecard requires go 1.18

Also, we have make a target for building scorecard `make build-scorecard`

**Comment by sgoggins** [comment]
@naveensrinivasan : I'm on 1.19. I will try `make build-scorecard`

**Comment by naveensrinivasan** [comment]
Closing it for now. Please reopen if you have any issues.
