### ISSUE TITLE
Feature: Support `--commit-depth`

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2224]
The number of commits Scorecard analyzes is hardcoded to 30 (for GitHub) today. We can let users configure this by providing a `--commit-option`. The default can remain 30 so as we don't affect current behavior.

This will be useful to analyze developmental practices between 2 releases, for example.

@nadgowdas @lehors @leec94 fyi.

**Comment by azeemshaikh38** [comment]
I was thinking it would be an int. How do you mean `Commit-ish`?

**Comment by raghavkaul** [comment]
For example, say that a maintainer uses tags on the default branch to mark releases, instead of branching out for each release. To analyze development practices between today and the last release, a user could pass in the tag for the previous release. Scorecard would score all commits between the default branch's HEAD and the release tag. This would switch scorecard to run only on a single branch - the one the Commit-ish is on (which, typically, would be the default branch, but could be another).

Or is the idea to analyze all release/ branches as we do today, just with a larger window size?

**Comment by nadgowdas** [comment]
I believe we would need `--commit-option` <int> and `ref-commit` <commit-id>. The ref would act as the base commit-id and then traverse the depth of <int> forward (is there a case for backward traversal ?). 

So essentially, if user is using version 1.2 of a package and wants to upgrade to 1.5, then he can provide base-reference commit of 1.2 and option would be number of commits until 1.5 (Q. How user know # of commits between 2 releases is up-to user and out-of-scope for scorecard, there are graphQL queries available to do that)

**Comment by azeemshaikh38** [comment]
@raghavkaul Scorecard doesn't analyze all release branches (except in Branch-Protection check), only the default branch. The proposal is to make the analysis on default branch itself to be configurable.

**Comment by lehors** [comment]
It's clear that the default being 30 is really arbitrary and adding this kind of option so that the user can set it to whatever they think is best (which may be as arbitrary but that's their arbitrary ;-) is the way to go.
Thanks for opening this issue to track this.

**Comment by lehors** [comment]
I agree with @nadgowdas that basing this on releases is probably more meaningful to the user. I don't know why we would ask the user for the number of commits though, why not just go with the release tags?

**Comment by azeemshaikh38** [comment]
> why not just go with the release tags

Primarily because Scorecard by definition is meant to solve a larger scope problem - assess the security posture of a project based on its developmental practices. Assessing the security posture of a release based on developmental practices preceding the release tag is a subset of this problem IMO.

Apart from that, commits are also more universal across the OSS ecosystem compared to release tags.

**Comment by azeemshaikh38** [comment]
@ossf/scorecard-maintainers are there any concerns if development work on this feature were to start?

**Comment by laurentsimon** [comment]
you're asking about just increasing the commit depth, or also passing an older tag as the "start" of the analysis? Correct me if I'm wrong: you're saying that  `--commit` already covers tags, because the users passes the commit corresponding to the release tag?

I think there were several proposals in the issue so I might have gotten lost:
```
--commit-sha h --commit-depth n // commits in [h - n, h]
--commit-sha h // same as above with default to n = 30
--commit-tag t  // commits in [t-1, t], basically it's a shorthand for users so they need not know the hash corresponding to a tag
--commit-tag t -commit-depth n // commits in [t - n, t]
```

re: older tag -> I think @nadgowdas  wanted to add which checks would be supported, and which would not.

**Comment by nadgowdas** [comment]
@laurentsimon @azeemshaikh38 if we run default set of checks on previous commits, then for the non-file/commit based (e.g. branch-protection) it will still run against current configuration (ie. from today). 
So we can possibly disable those checks when we are running in `commit-based` evaluation mode. Thoughts ?

**Comment by azeemshaikh38** [comment]
> you're asking about just increasing the commit depth, or also passing an older tag as the "start" of the analysis? 

Both - `--commit` for passing older tag as the start and `--commit-depth` for increasing commit depth. These are mutually exclusive options.

`--commit` is already implemented (#575) and takes care of returning the right set of checks when `--commit=HEAD` vs. `--commit=olderThanHEAD`. `--commit-depth` should just increase the commit depth for analysis.

> @laurentsimon @azeemshaikh38 if we run default set of checks on previous commits, then for the non-file/commit based (e.g. branch-protection) it will still run against current configuration (ie. from today).
So we can possibly disable those checks when we are running in commit-based evaluation mode. Thoughts ?

Yes, this is the behavior today already with `--commit` option. Which makes me realize we never updated our documentation to reflect this. Will do that.

**Comment by laurentsimon** [comment]
SGTM.

> > you're asking about just increasing the commit depth, or also passing an older tag as the "start" of the analysis?
> 
> Both - `--commit` for passing older tag as the start and `--commit-depth` for increasing commit depth. These are mutually exclusive options.

Does this mean you cannot run scorecard for all commits between v1 and v2 tags?

**Comment by laurentsimon** [comment]
> Question for clarification - is this issue to implement just `--commit-depth`, which from my understanding changes the default of 30 commits to a user defined number of commits? Is `--commit-option` a separate flag to implement as well? If so, what is the purpose of `--commit-option`?

I think it's a typo: commit-depth and commit-options are the same.

> Also for commit based evaluation, I did a test run and here's the list of what is and isn't scanned (apologies if this is already added to documentation, but figured I'd save someone a click):
> 
> Commit-based scan checks:
> 
> * Binary-Artifacts
> * CI-Tests
> * Code-Review
> * Dangerous-Workflow
> * License
> * Pinned-Dependencies
> * Security-Policy
> * Token-Permissions
> * Vulnerabilities
> 
> Doesn't scan on:
> 
> * Branch-Protection
> * CII-Best-Practices
> * Contributors
> * Dependency-Update-Tool
> * Fuzzing
> * Maintained
> * Packaging
> * SAST
> * Signed-Releases

seems correct

**Comment by latortuga71** [comment]
Currently being implmented here in PR https://github.com/ossf/scorecard/pull/2407

**Comment by latortuga71** [comment]
Completed feature but there is a TODO
to fix an issue where cache misses happen when using the sast and ci checks, when commits go above 100 because paging is needed. Will start on this fix.

**Comment by spencerschrock** [comment]
Closing as the feature is completed, and the only remaining aspect is a cache log statement that can be its own issue.
