### ISSUE TITLE
Enable signed commits for this repository

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#223]
Enable signed commits for all the commits to this repository.

![image](https://user-images.githubusercontent.com/172697/109320109-a86c8100-781d-11eb-9b9e-e3f9e382253e.png)

### Why Sign Git Commits
As useful as signing packages and ISOs is, an even more important use of GPG signing is in signing Git commits. When you sign a Git commit, you can prove that the code you submitted came from you and wasn't altered while you were transferring it. You also can prove that you submitted the code and not someone else.

Being able to prove who wrote a snippet of code isn't so you know who to blame for bugs so the person can't squirm out of it. Signing Git commits is important because in this age of malicious code and back doors, it helps protect you from an attacker who might otherwise inject malicious code into your codebase. It also helps discourage untrustworthy developers from adding their own back doors to the code, because once it's discovered, the bad code will be traced to them.

source https://www.linuxjournal.com/content/signing-git-commits

**Comment by naveensrinivasan** [comment]
@inferno-chromium  @dlorenc  Your thoughts /opinions? 

I understand this could potentially reduce the number of people who would like to contribute to this repository, but it is educating the community to do the right stuff. 

It is similar to 2FA for GitHub Authentication for Org members.

**Comment by inferno-chromium** [comment]
We were thinking of breaking the checks in tiers, like starting the devs with fixing tier 1 checks, then tier 2, tier3. Having this as part of branch protection check seems better since fixing that check is a cultural shift in day-to-day developer workflow anyway, so we can add all these recommendations there. Thoughts ?

**Comment by naveensrinivasan** [comment]
> We were thinking of breaking the checks in tiers, like starting the devs with fixing tier 1 checks, then tier 2, tier3. Having this as part of branch protection check seems better since fixing that check is a cultural shift in day-to-day developer workflow anyway, so we can add all these recommendations there. Thoughts ?

I agree with your thoughts on doing as tiers. It would help devs to view this as not all or nothing which is a hard sell.


I was referring to just enabling signed commits just for `Scorecard`  https://github.com/ossf/scorecard/  repository alone. So that we can practice what we recommend to the rest of the community and also it gives us the confidence as to the commits haven't tampered.

**Comment by azeemshaikh38** [comment]
We decided against doing this IIRC. closing this for now.
