### ISSUE TITLE
QUESTION: How to get the scorecard score badge?

### ISSUE THREAD

**Issue by miguelnietoa** [ossf/scorecard#2230]
### Description

The documentation is not clear to me, I can't get the Scorecard score badge.
I set up the scorecard analysis workflow, but I don't know how to get the scorecard score badge. I've followed the explanation of the README https://github.com/ossf/scorecard#scorecards-badges but the badge did not appear.

[![OpenSSF
Scorecard](https://api.securityscorecards.dev/projects/github.com/kommitters/stellar_sdk/badge)](https://api.securityscorecards.dev/projects/github.com//kommitters/stellar_sdk)

I got an "invalid repo path"

![image](https://user-images.githubusercontent.com/39246879/188242742-75ba6518-bd3f-4c95-b1fa-c6065bdd8219.png)

---
Or is it necessary to place the badge in the README for the scorecard score to be enabled?

**Comment by azeemshaikh38** [comment]
Hi @miguelnietoa, thanks for your interest in Scorecard. I see that you are using [v1.1.2](https://github.com/kommitters/stellar_sdk/blob/main/.github/workflows/scorecards.yml#L33) of `scorecard-action`. Badges are supported from `v2` onwards - see [details](https://github.com/ossf/scorecard-action/#scorecard-badge).

We'll be releasing v2 in a week. However, if you are interested in trying this out earlier, we have a pre-release for those interested to be early adopters - https://github.com/ossf/scorecard-action/releases/tag/v2.0.0-alpha.2. Hope that helps.

**Comment by miguelnietoa** [comment]
I get it! Thanks for your reply @azeemshaikh38 😄
