### ISSUE TITLE
Definitely ignoring `-e local/path` will help.  Why not also allow a URL?

### ISSUE THREAD

**Issue by Oamwarit098** [ossf/scorecard#2247]
Definitely ignoring `-e local/path` will help.  Why not also allow a URL?

_Originally posted by @nedbat in https://github.com/ossf/scorecard/issues/2228#issuecomment-1240107922_

**Comment by nedbat** [comment]
What is this issue for? It has just one sentence from a longer discussion on the other issue (#2228)

**Comment by spencerschrock** [comment]
Closing as spam, similar to the other invalid issues from Sep 9.
