### ISSUE TITLE
BUG: LGTM is going away

### ISSUE THREAD

**Issue by wenottingham** [ossf/scorecard#2259]
**Describe the bug**
The SAST check states in its docs (and in the code) that it checks for CodeQL (github-code-scanning), LGTM and SonarCloud in the recent (~30) merged PRs, or the use of "github/codeql-action" in a GitHub workflow.

LGTM is being shut down at the end of December, and is no longer accepting new signups. See https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ for details.

The checks can probably still check for LGTM, but the docs should probably clarify that it's not something new users should try.

**Reproduction steps**
1. Look at SAST check docs
2. Open up the list of services

**Expected behavior**
All active services used, no deprecated or being-shut-down services suggested.

**Additional context**

**Comment by naveensrinivasan** [comment]
@wenottingham  Thank you! Would you be interested in doing a PR for this?
