### ISSUE TITLE
Support for GitLab Projects

### ISSUE THREAD

**Issue by N8BWert** [ossf/scorecard#2266]
**Is your feature request related to a problem? Please describe.**
Scorecard only supports Github Repositories, but GitLab Projects would also benefit from scorecard checks.

**Describe the solution you'd like**
A GitLab client to allow scorecard checks on GitLab Projects.

**Comment by azeemshaikh38** [comment]
Just fyi for Scorecard maintainers, reference docs on GitLab API limits:

- https://docs.gitlab.com/ee/user/admin_area/settings/user_and_ip_rate_limits.html
- https://docs.gitlab.com/ee/administration/instance_limits.html
- https://docs.gitlab.com/ee/security/rate_limits.html

**Comment by jheck88** [comment]
Interested in seeing this get released!

**Comment by naveensrinivasan** [comment]
@jheck88 Thank you! It would great if you can take it up and get it released. Here is one of the PR's that needs work https://github.com/ossf/scorecard/pull/2280

**Comment by jheck88** [comment]
Alright, I'll see what we can do.  There's a couple of us that are looking into this

**Comment by jheck88** [comment]
@naveensrinivasan we tagged up at security con.  Did you say you have someone that can tackle this? Or do you still want us to throw something at this issue?

**Comment by kgangerlm** [comment]
@naveensrinivasan @raghavkaul @jheck88 There are a few of us looking for this capability, who are willing to help.  Would you all be open to tagging up to talk about how we can best contribute to finishing and testing this work?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan @raghavkaul @jheck88 There are a few of us looking for this capability, who are willing to help. Would you all be open to tagging up to talk about how we can best contribute to finishing and testing this work?

👍

**Comment by azeemshaikh38** [comment]
@raghavkaul fyi who's working on supporting GitLab.
