### ISSUE TITLE
BUG Running Scorecard on a private repo always results in a score of 10 for Token-Permissions and Pinned-Dependencies check

### ISSUE THREAD

**Issue by h0x0er** [ossf/scorecard#2277]
**Bug Description**
If `scorecard` is run on a `private-repo`  with `Token-Permissions or  Pinned-Dependencies` checks. The score is not calculated properly. It always shows `max-score` i.e 10. Whereas if you run the same checks on a public repo, the score is calculated correctly.

**Reproduction steps**
> Pre-requisite: A private-repo with a workflow file having no token-permission and no pinned actions

1. Download the latest version of scorecard
2. Run the below command.
```bash
GITHUB_AUTH_TOKEN="<tokenHere>" ./scorecard-linux-amd64 --repo "owner/repo" --checks=Token-Permissions,Pinned-Dependencies --verbosity Debug
```
3. Observe the score.
4. Change the visibility of same repo to `public`.
5. Re-run the above command.
6. Observe the score again.

By performing the above steps; you will observe the difference in score.

**Expected behavior**
For both runs; the score should be same

----

### Current Flow of Scorecards for calculating score of pinning & tokenPermission
1. Fetch the tarball, of the repo
2. Perform the analysis, on `Dockerfile` or `Workflow` files for `pinned-Dependencies or Token-Permission`
3. Generate Score.

### Cause of Bug

Authorization Token is not supplied in `http-call` for fetching `tarball`. The calls fails for `private-repos` and works for `public-repos`, because of `authorizationToken not being supplied`.

### Place of Bug.
The miscalculation of score occurs in `step2 & step3`; if `fetching of tarball fails`. 
In current code for `fetching tarball` [here](https://github.com/ossf/scorecard/blob/10b6052acfb4f0b8136bc4876cb6f5b6f26bfe93/clients/githubrepo/tarball.go#L113), if you see the preparation of request at `line 121`; there is no `Authorization Header` being added due to which the request fails for `private-repos`, which causes miscalculation of scores.

### Fix
In order to fix this bug;
* I tried adding `authorizationHeader` in my [fork](https://github.com/h0x0er/scorecard/blob/main/clients/githubrepo/tarball.go#L125); 
* build the binary in local machine and 
* Ran it.
The outcome was `positive`, the changes worked :)

/cc @varunsh-coder @boahc077

**Comment by azeemshaikh38** [comment]
Great find @h0x0er! Could you send a PR for this since you already have the fix? Suggestion - pass in the `httpClient` here to the `tarballHandler` and use that to make the http call instead.
