### ISSUE TITLE
Feature: Zombie Commits Support

### ISSUE THREAD

**Issue by latortuga71** [ossf/scorecard#2285]
**Description**
Zombie commits are commits to a repository directly to the main branch, not attached to any pull requests. Adding a check to scorecard on zombie commits could help users determine if owners adhere to strict guidelines regarding contributions.

**Describe the solution you'd like**
Add a check for "Zombie Commits" that ranks 1-10 based on the percentage of zombie commits on the repository, or between two releases.

**Comment by varunsh-coder** [comment]
I have seen few important open-source projects implement detection for this using GitHub Actions workflows. I will try to find that and share here.

**Comment by nadgowdas** [comment]
I had this feature in my open-source project `gauge` as well:
https://github.com/tap8stry/gauge

Example: https://github.com/tap8stry/gauge#package-mode

**Comment by laurentsimon** [comment]
Could we surface these commits in the Code-Review check? As being non-reviewed / not having an associated PR?

**Comment by varunsh-coder** [comment]
I could not find the project I had seen use this. But there is similar discussion in this SO question:
https://stackoverflow.com/questions/66376960/detect-direct-pushes-to-master-w-github-actions

**Comment by laurentsimon** [comment]
Was this implemented or dropped?

**Comment by latortuga71** [comment]
Dropped determined too similar to code review checks
