### ISSUE TITLE
Missing BigQuery data

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#2307]
**Describe the bug**
The cron job has partial results for the 9/19 partition.

**Reproduction steps**
Not user reproducible, but occurs when the controller crashes without publishing shard metadata.

**Expected behavior**
Every weekly cron produces complete data.

**Additional context**
1. the controller started, and pushed some subset of messages to the pubsub topic (at least 109k shards of the expected 124k were pushed). Batch 1
2. the controller crashed within the first 12 seconds. and the shard metadata file was never created
3. the controller restarted and pushed another 124k shards to the pubsub topic. Batch 2
4. the workers tried to work on all 200k+ requests and only finished when the messages died after 1 week in the pubsub

This leads to two bugs:
1. the bq transfer tool transferred partial results on Thursday since the first batch didn't have a metadata file
2. the bq transfer tool never transferred results for batch 2 because workers only processed 10% of the batch 2 shards which is less than the transfer threshold.

**Comment by spencerschrock** [comment]
The above PR should prevent this going forward.

@azeemshaikh38 thoughts on deleting the `.transfer_complete` file from the `2022.09.19` bucket so it gets re-uploaded tomorrow? Might also need to make a `.shard_metadata`, but I don't think those changes will be in `stable` by the time the transfer tool runs. It should increase the results in the 9/19 run to roughly 1.1M instead of the half it currently has.

**Comment by azeemshaikh38** [comment]
+1, lets do that. Maybe move the `.shard_metadata` from `20013` to `20001` and vice-versa for `.transfer_complete` ? Can also re-run the transfer job ourselves once we do this.

**Comment by spencerschrock** [comment]
Triggered a manual re-upload of all the completed 9/19 repos, which brought the number of results up to approximately 1M repos (up from the ~500k that were initially transferred). 

There were ~150k repos that were unfortunately not processed in time due to the duplicate pubsub messages detailed above. So they're still not in the 9/19 results, but at least this solved the pre-mature upload.
