### ISSUE TITLE
Improve Score Reporting: Packaging check regex bug

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2321]
Packaging check regex looks for [`mvn*deploy`](https://github.com/ossf/scorecard/blob/b491f40d44285453895d28b88a086149e4ed5bb3/checks/fileparser/github_workflow.go#L460), but workflows can specify this over multiple lines. Example: https://github.com/open-feature/java-sdk/blob/715fd032cff446e83bf45f86ecb6fbc7a1c7c0f4/.github/workflows/release.yml#L48. This is a bug and we should extend our regex to handle multi-line cases too.

**Comment by spencerschrock** [comment]
Note: this can affect the permissions check too. 
https://github.com/ossf/scorecard/blob/6fc08e7c9ce05bbff1329e777b2eca38cb41564f/checks/raw/permissions.go#L410
