### ISSUE TITLE
BUG: Fuzzing check mismatch repo name in OSS-Fuzz list

### ISSUE THREAD

**Issue by gabibguti** [ossf/scorecard#2325]
**Describe the bug**
The fuzzing score checks if the repository name is included in OSS-Fuzz list. However, for a repository B that is a substring of repository A the check fails. The check finds a partial match because repository A is in the list and says that repository B itself is in the list when it's not.

**Reproduction steps**
1. [Open scores for Ultimaker/Cura repository](https://api.securityscorecards.dev/projects/github.com/Ultimaker/Cura)
2. View that Fuzzing check scores 10
```json
{
      "name": "Fuzzing",
      "score": 10,
      "reason": "project is fuzzed with [OSSFuzz]",
      "details": null,
      "documentation": {
        "short": "Determines if the project uses fuzzing.",
        "url": "https://github.com/ossf/scorecard/blob/b491f40d44285453895d28b88a086149e4ed5bb3/docs/checks.md#fuzzing"
      }
},
```
3. Attest that [Ultimaker/Cura](https://github.com/Ultimaker/Cura) does not contain any fuzzing
4. [Open google/oss-fuzz repository](https://github.com/google/oss-fuzz/)
5. Try to find Ultimaker/Cura repository
6. [Find only a similar name repository called Ultimaker/CuraEngine](https://github.com/google/oss-fuzz/blob/master/projects/cura-engine/project.yaml)

**Expected behavior**
I expect that a repository that is not included in the OSS-Fuzz list does not get a 10 in fuzzing for that reason.

**Additional context**
None.

**Comment by pnacht** [comment]
The issue seems to be that Scorecard uses a GitHub search on the oss-fuzz repo with the query `Ultimaker Cura in:file filename:project.yaml repo:google/oss-fuzz`. However, GitHub search allows for partial matching, so `Ultimaker Cura` gets matched to

```yml
# cura-engine/project.yaml
homepage: "https://github.com/Ultimaker/CuraEngine"
#                             ^^^^^^^^^ ^^^^
# ...
main_repo: "https://github.com/Ultimaker/CuraEngine.git"
#                              ^^^^^^^^^ ^^^^
```

Unfortunately I haven't figured out how to pull off an exact match (I'm using the web interface).

Wrapping in quotes enforces word order, but still allows partial matching (so `"Ultimaker Cura"` behaves identically in this case, since spaces can still be replaced by symbols). I hoped to make use of the fact that `main_repo:` has the ".git" extension. I hoped `"Ultimaker CuraEngine git"` would work but `"Ultimaker Cura git"` would not. However, both give zero results, which tells me spaces can't be replaced by periods... and unfortunately periods themselves can't be used at all.

**Comment by gabibguti** [comment]
Due to GH search tool improvements, I think we can improve our match as well by adding the `.git` extension to the search.

E.g. `repo:google/oss-fuzz path:**/project.yaml /Ultimaker\/Cura.git/`
https://github.com/search?q=repo%3Agoogle%2Foss-fuzz+path%3A**%2Fproject.yaml+%2FUltimaker%5C%2FCuraENGINE.git%2F&type=code&ref=advsearch&l=&l=

**Comment by gabibguti** [comment]
GitHub API `/search/code` unfortunately does not support the new advanced search used on UI 😢

**Comment by spencerschrock** [comment]
> One idea, we could "download" OSS-Fuzz source code to search manually for the projects. Not through GitHub API.

Is this still an issue? `Fuzzing` doesn't check with search anymore.

**Comment by pnacht** [comment]
Yes. Scorecard still gives Ultimaker/Cura a 10/10 for Fuzzing, but the project that's actually fuzzed is Ultimaker/CuraEngine.

**Comment by spencerschrock** [comment]
Are you still testing with v4.10.2? That repo gets a 0/10 for me on v4.10.5

**Comment by gabibguti** [comment]
Right, so [Ultimaker/Cura](https://github.com/Ultimaker/Cura) now has 0/10 in Fuzzing using v4.10.5. That's fixed. But now we broke [Ultimaker/CuraEngine](https://github.com/Ultimaker/CuraEngine), which also has 0/10 Fuzzing in v4.10.5 but should have 10/10 according to https://github.com/google/oss-fuzz/blob/e0d89187f3707d47572e47dbbbd172df22ee2def/projects/cura-engine/project.yaml#L9. Should we open another bug for this?

**Comment by spencerschrock** [comment]
Maybe file an issue with OSS Fuzz. I don't see the repo listed in the status file we use to check:
https://oss-fuzz-build-logs.storage.googleapis.com/status.json

**Comment by gabibguti** [comment]
Ack. Done https://github.com/google/oss-fuzz/issues/10455
