### ISSUE TITLE
Use release notes from the PR content

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#2329]
**Describe the bug**
At the moment, we use PR titles release notes. This isn't helpful for someone who wants to know what has changed https://github.com/ossf/scorecard-action/pull/786

**Reproduction steps**
We adopted a section in the PR to help with release note generation. We should utilize that.

**Comment by naveensrinivasan** [comment]
@justaugustus  👀

**Comment by spencerschrock** [comment]
This was added to the release instructions in #3322
