### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by nir-valtman** [ossf/scorecard#2348]
**Is your feature request related to a problem? Please describe.**
Pull request reviews are important for the quality and security of the code. 
GitHub's CODEOWNERS is typically used to review PRs based on specific paths for selected approvers. However, it is [easy to misconfigure CODEOWNERS](https://www.arnica.io/blog/what-every-developer-should-know-about-github-codeowners) to make it avoid the rules defined in it.

**Describe the solution you'd like**
I suggest to check both the existence of the CODEOWNERS file and the enforcement in the branch protection policy. [Here is my code sample in Python that does it](https://gist.github.com/nir-valtman/c264c34464d82de8afb1d78f18f6a785).  
The caveat is that my script checks only the default branch, but it should be a good start. 

**Describe alternatives you've considered**
The alternative way is to go repo by repo manually and test the existence of file and the enforcement in the branch protection policy. 

**Additional context**

- [More information about CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
- The expected configuration in the protected branch should have the following checkboxes enabled, at minimum: 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/82189190/195479508-b9dcfa50-6a59-4a79-af8e-e4e71b3637f3.png">

**Comment by nir-valtman** [comment]
If the check is enabled but there is no CODEOWNERS file, this control doesn't enforce a review by the authorized reviewers.
Similarly, if the file exists but the check is disabled in the branch protection policy, the policy isn't working.

**Comment by raghavkaul** [comment]
Yes, I think it makes sense to ensure the presence of the CODEOWNERS file on top of simply looking to see if the Branch Protection check for CODEOWNERS is enabled. I can take a look into this.
