### ISSUE TITLE
Feature: Scorecard scan between two releases

### ISSUE THREAD

**Issue by leec94** [ossf/scorecard#2368]
**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to run scorecard scans between any two releases of a repo. This way it would be useful to know the change in security health between the two releases.  

**Describe the solution you'd like**
A new flag for scorecard such as `--diff-release=release-a,release-b`

Full example:
```
./scorecard --repo=https://github.com/ossf/scorecard --diff-release=v4.0.1,v4.8.0
```

**Describe alternatives you've considered**
Related issue discusses scanning for individual releases, but not between releases.  
https://github.com/ossf/scorecard/issues/1985

**Additional context**
- Issue to implement `--commit-depth` should be completed first, as this issue would utilize that feature to implement. 
https://github.com/ossf/scorecard/issues/2224  
- The use of `--diff-release` would conflict with `--commit` and `--commit-depth`, if scorecard detects that `--diff-release` is used with  `--commit` or `--commit-depth` it should exit without running.

**Comment by naveensrinivasan** [comment]
A similar one is this https://github.com/ossf/scorecard/issues/2092 which will add release information in the API. I am planning to work on this after the [infrastructure for this is finalized](https://github.com/ossf/scorecard/issues/2066), which is set up for discussion in our Bi-Weekly meeting 

If we add release information to the API, wouldn't that suffice most of this requirement?

**Comment by leec94** [comment]
Thanks for the quick response! I think #2092 would cover the request in #1985, but this issue is a bit different. 

In this issue, you'd be able to scan between any two releases, so if there were releases `a`, `b`, and `c`, then this feature would let you scan between `b` and `c` for example, and scorecard would look at all the commits between the two. #2092 would report on release `c`, and the default 30 commits back.

**Comment by leec94** [comment]
Found a related slack discussion previously - it was for #2224 but mentions releases too. want to add it here for more detail.

> So as of today, Scorecard only understands commits (not version or release tags). So the X  in --commit-depth=X  is referring to the number of commits between any 2 releases. So, X  (the number of commits between 2 releases someone is interested to analyze) must come from a tool like Gauge

https://openssf.slack.com/archives/C0235AR8N2C/p1661808651764329?thread_ts=1661457748.035939&cid=C0235AR8N2C

so currently scorecard doesn't understand versions or release tags, i think this issue would be the work so that it could

**Comment by leec94** [comment]
Discussed this at bi-weekly scorecard meeting oct 20. 
points made: 
-     repositories may not necessarily be using the release tag feature. example: kubernetes
-     how about gitlab? would get complicated to have different logic for gitlab vs github
-     basically just commit-sha anyway
-     overall, wait until --commit-depth is done first, since this feature would be a wrapper on top of it

**Comment by azeemshaikh38** [comment]
@leec94 now that there's progress on the `--commit-depth` feature (https://github.com/ossf/scorecard/pull/2496 should fix it fully), what else do you think is needed here?

**Comment by leec94** [comment]
how about changing this issue to add flag `--diff-commit=commit-a,commit-b` to continue the convention of using commits instead of releases?

**Comment by azeemshaikh38** [comment]
We can use `git rev-list --count commitA...commitB` to do this? So basically:

`scorecard --repo=<> --commit=commitA --commit-depth=$(git rev-list --count commitA...commitB)`

What do you think?

**Comment by leec94** [comment]
i haven't seen rev-list before, that's pretty cool! yeah i agree with the command you've built this satisfies what i'm looking for. thanks! i can close this out
