### ISSUE TITLE
Question: Rest API Rate Limits

### ISSUE THREAD

**Issue by denizmgun** [ossf/scorecard#2374]
I would like to fetch scorecards for a couple of thousand repositories on a somewhat regular basis (perhaps weekly). Will I hit a rate limit for the usage of the REST API? If so, is there any pre-established way to increase this rate limit?

I am aware of the fact that I can use  the bigquery service to acquire the scorecards myself. However, my cloud environment has deployment package size limitations, which make it particularly difficult to use bigquery inside of it. If there is an established way to make bulk requests to the REST API already, that would be an enormous time saver. If not, also fine and I guess I need to find a workaround.

I didn't find any information concerning my questions in the FAQ or on any other of your resources. Furthermore, I didn't find any other place to ask. So, I apologize if this is issue is misplaced.

**Comment by naveensrinivasan** [comment]
As of now, we don't have any rate limits. cc @azeemshaikh38

**Comment by azeemshaikh38** [comment]
There are no explicit rate limits, but the API runs behind a loadbalancer, so there may be some throttling. Although if it's a couple of thousand repositories, I'd expect this to be fine. Let us know how it goes. 

Closing this issue for now. Feel free to re-open if needed.
