### ISSUE TITLE
Write access for @spencerschrock

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#2375]
Posting on behalf of @naveensrinivasan's request in today's weekly sync, this issue is to get thoughts from @ossf/scorecard-maintainers about moving myself from Collaborator to Approver (as defined in https://github.com/ossf/allstar/issues/238) to help deal with the PR backlog.

**Comment by naveensrinivasan** [comment]
👍

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @laurentsimon @justaugustus  👀

**Comment by azeemshaikh38** [comment]
+1.

**Comment by naveensrinivasan** [comment]
I have invited @spencerschrock to maintainers.

**Comment by laurentsimon** [comment]
+1
