### ISSUE TITLE
BUG: Some merged PRs that should qualify as "reviewed" are not being tagged as such

### ISSUE THREAD

**Issue by smagill** [ossf/scorecard#2391]
**Describe the bug**
spring-core is getting reported as not doing code review, but it appears that recently-merged changes do qualify as reviewed based on the description of that check.  Here’s the API results:
https://api.securityscorecards.dev/projects/github.com/spring-projects/spring-framework
And here is an example of a PR that I think should qualify (merged by someone other than the committer (implicit review)):
https://github.com/spring-projects/spring-framework/pull/28753
Here is the description of the "code review" check:
https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review
And the relevant excerpt from the description:
"If this fails, the check determines whether the most recent (~30) commits have a Github-approved review or if the merger is different from the committer (implicit review)"

**Reproduction steps**
1. View the API link above
2. View the PR linked above

**Expected behavior**
I had expected the linked PR to count as code review (maybe with a low score -- not as good as branch protection with required review but better than nothing).

**Additional context**
None

**Comment by seberg** [comment]
Curious, maybe it just happens to be that way in the recent commits.  But NumPy still shows few commits as reviewed, even though I would think they are reviewed based on "implicit" review?
https://api.securityscorecards.dev/projects/github.com/numpy/numpy

**Comment by raghavkaul** [comment]
@seberg Code review must be from someone other than the PR opener [[1](https://github.com/ossf/scorecard/blob/1c6ab16e454af68e0a8628544625d65fa2e086f1/checks/evaluation/code_review.go#L106)], I see only one changeset in numpy (PR 23066) that scorecard marks unreviewed and it's because of this requirement. 

This requirement is known to be a problem for single-maintainer projects, so we are looking to improve it with the release of structured results.

**Comment by seberg** [comment]
Ah OK, so maybe just a temporary thing since there were uncommonly many such commits recently.  Of course it must be someone else, it just isn't particularly typical on the `main` branch (it is pretty typical for backports for us).
