### ISSUE TITLE
BUG Retrieving signed certificate... fails

### ISSUE THREAD

**Issue by jenstroeger** [ossf/scorecard#2408]
**Describe the bug**

Take a look at this failing run: https://github.com/jenstroeger/python-package-template/actions/runs/3342864737/jobs/5535522990

The failing action is here: https://github.com/jenstroeger/python-package-template/blob/main/.github/workflows/scorecards-analysis.yaml

**Reproduction steps**

n/a

**Expected behavior**

It works.

**Additional context**

n/a

**Comment by spencerschrock** [comment]
Starting from scorecard-action:v2, GITHUB_TOKEN permissions or job permissions needs to include `id-token: write` if you have `publish_results: true`. This is needed to access GitHub's OIDC token which verifies the authenticity of the result when publishing it.

Including the permission should resolve your issue. 
Related: https://github.com/ossf/scorecard-action/issues/900#issuecomment-1245665197

**Comment by spencerschrock** [comment]
Closing this, feel free to re-open if the issue persists.

**Comment by jenstroeger** [comment]
@spencerschrock worked: https://github.com/jenstroeger/python-package-template/actions/runs/3350112568

Thank you!
