### ISSUE TITLE
Code hotspots

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#2412]
A significant portion (5.5%) of the cron job is spent in `raw.isText`
https://github.com/ossf/scorecard/blob/1fa791043273aae2dfce4ee54cf4035be6802486/checks/raw/binary_artifact.go#L170-L180

There's some experimental code that also does this, and has better performance. I plan to import/copy the implementation over.

```go
// IsText reports whether a significant prefix of s looks like correct UTF-8;
// that is, if it is likely that s is human-readable text.
func IsText(s []byte) bool {
	const max = 1024 // at least utf8.UTFMax
	if len(s) > max {
		s = s[0:max]
	}
	for i, c := range string(s) {
		if i+utf8.UTFMax > len(s) {
			// last char may be incomplete - ignore
			break
		}
		if c == 0xFFFD || c < ' ' && c != '\n' && c != '\t' && c != '\f' {
			// decoding error or control character - not a text file
			return false
		}
	}
	return true
}
```

Should be an easy performance win, but would change the behavior slightly as it **only checks the first 1024 bytes**. 

Since you implemented the heuristic, thoughts @laurentsimon ? I know the code was introduced to reduce false positives, so should still be valid for that.

Benchmarking shows a 2x speedup on small files (1KiB). 6x speedup on medium files (3KiB). And on gigantic files (like our 50MB `projects.csv` file), the difference is 5-6 orders of magnitude.
```
cpu: Intel(R) Xeon(R) CPU @ 2.20GHz
BenchmarkIsText-8                     79         295087760 ns/op
BenchmarkExternalIsText-8       13462120              1763 ns/op
```

**Comment by laurentsimon** [comment]
Do you know why it is faster? What's the source of slowdown in the current version?
Looking at the first 1k byte would be OK of we have data (from cron) that the results are the same?

Btw, how did you perform the benchmark?

**Comment by laurentsimon** [comment]
Thanks for the additional info. So inlining code is what speed things up. I'm surprised there's a 2x speedup on 1k files due to that. In fact that seems weird to me because there's a single stack frame created to call the function...
It would be great to have cone numbers confirming we're not making things worse. Maybe we can add some logging code temporarily to call both function in the cron (gated with an env variable) and mine the logs for different results?

**Comment by spencerschrock** [comment]
> In fact that seems weird to me because there's a single stack frame created to call the function...

In a loop, called for each rune in the file contents. 

> Maybe we can add some logging code temporarily to call both function in the cron (gated with an env variable) and mine the logs for different results?

👍 SGTM. 
env gated variable, enabled in the release test. the repos get shuffled daily, so should be able to test over the week
