### ISSUE TITLE
Keeping go.mod up-to-date for both `scorecard` and `scorecard-attestor` modules

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#2418]
This seems like it could be a frequent pain point going forward.
 
https://github.com/ossf/scorecard/actions/runs/3373560170/jobs/5598256385#step:7:95
```
Error: ../../checks/raw/binary_artifact.go:30:2: missing go.sum entry for module providing package golang.org/x/tools/godoc/util (imported by github.com/ossf/scorecard/v4/checks/raw); to add:
```
Or the number of `go mod tidy` commits in the original PR https://github.com/ossf/scorecard/pull/2309/commits

@raghavkaul Is there a benefit to having the attestor as its own module? Is there anything blocking us from doing what we do with some of the cron binaries [add](https://github.com/ossf/scorecard/tree/main/cron/internal/data/add) or [worker](https://github.com/ossf/scorecard/tree/main/cron/internal/worker)?

**Comment by naveensrinivasan** [comment]
We avoided this up until now. We should have a strong reason to keep in its own module.

**Comment by raghavkaul** [comment]
It makes sense to make the attestor a subpackage of scorecard. It was initially kept as its own module to let it to be experimental and to let things break without affecting scorecard. But now the code is relatively stable.
