### ISSUE TITLE
? values in default ASCII table format are translated to -1 in JSON format

### ISSUE THREAD

**Issue by huornlmj** [ossf/scorecard#2425]
When a repository is measured and has a metric which is displayed as a ? instead of an out of 10 score when viewed in default ASCII table format, the value is shown as -1 when viewed in JSON format.

Is this the correct and expected behaviour?

**Comment by spencerschrock** [comment]
Happened to see this today when doing some work on our issue labels. 

Yes this is expected behavior since the JSON score field expects an int.
