### ISSUE TITLE
BUG A link within checks.md for Security-Policy results in a 404

### ISSUE THREAD

**Issue by shissam** [ossf/scorecard#2429]
**Describe the bug**

`https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy` for Security-Policy has a link to "_coordinated vulnerability disclosure guidelines_" which points to `https://github.com/ossf/oss-vulnerability-guide/blob/main/guide.md` however in issue #2137, a link to `https://github.com/google/oss-vulnerability-guide/blob/main/guide.md` appears to be the link that should be used "_guidelines_"

**Reproduction steps**
1. Launch to [ossf/scorecard](https://github.com/ossf/scorecard)
2. Navigate down to "Checks" or page search for "Security-Policy" (currently the 5th match) and click through [Security-Policy](https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policyl)
3. Once there, under **Remediations steps**, click through on [coordinated vulnerability disclosure guidelines](https://github.com/ossf/oss-vulnerability-guide/blob/main/guide.md)
4. Observe the 404

**Expected behavior**
Expect to not get a 404 and be given the promised `guide.md` to support Security-Policy remediation.

**Additional context**
It appears that [https://github.com/google/oss-vulnerability-guide/blob/main/guide.md](https://github.com/google/oss-vulnerability-guide/blob/main/guide.md) is the correct link - not sure. this would be a change from `/ossf/` to `/google/`

**Comment by shissam** [comment]
I can fix this in PR #2195 just need confirmation the google repo is where the link is intended to point for `guide.md`

**Comment by spencerschrock** [comment]
The OSSF one should be correct, the file just got renamed. Providing a permalink would prevent file renamings from leading to 404s, but then we lose out on content updates.

https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md

**Comment by shissam** [comment]
if you concur - I'll squash this one now in PR #2195 if you think we're close enough.

**Comment by spencerschrock** [comment]
Sure. You've touched the check docs anyway in the PR.  Seems like a great time to update the link. Make sure to merge the latest changes from main, and should be ready to get the whole PR in.

**Comment by shissam** [comment]
done and PR pushed for integration test. I'll close this out now (can reopen if I botched it :-))
