### ISSUE TITLE
Feature: Security benefit on having 2 or more Required Reviews no clear (Feedback)

### ISSUE THREAD

**Issue by joycebrum** [ossf/scorecard#2472]
**Is your feature request related to a problem? Please describe.**
Some maintainers had raised the question about whether it is really a relevant security best practice to have 2+ Required Review (related to the branch protection check)

**Describe alternatives you've considered**
The Branch-Protection check explanation could talk (or at least refer) an explanation on why it is important to have 2 or more required reviews

**Additional context**
https://github.com/electron/electron/pull/35741#pullrequestreview-1118960274

**Comment by laurentsimon** [comment]
To protect against insider risks: if one maintainer is compromised, an attacker can send a PR and use the compromised account to LGTM their own PRs. X LGTMs requires X compromised maintainers, which is harder.

**Comment by joycebrum** [comment]
I've created a PR https://github.com/ossf/scorecard/pull/3013 to address this issue and try to make this benefit clear to the user too. Thanks for the explanation @laurentsimon !
