### ISSUE TITLE
Features: Add "Require approval of the most recent push" to Branch protection check

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#2475]
**Is your feature request related to a problem? Please describe.**
Seems like a serious evasion of branch protection check if this ""Require approval of the most recent push" (new sub-feature) is not enabled. Read why - "Add evil commits to good PR and self-approve" - https://medium.com/boostsecurity/slsa-dip-source-of-the-problem-a1dac46a976
https://raw.githubusercontent.com/boostsecurityio/supply-chain-research/main/001-source/attack-tree_source.svg

**Describe the solution you'd like**
Require "Require approval of the most recent push" as part of branch protection

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by laurentsimon** [comment]
Good catch. This seems to be a new setting. Sent https://github.com/ossf/scorecard/pull/2492
