### ISSUE TITLE
Gradle wrapper action check for binary artifact exception does not recognize actions pinned by hash

### ISSUE THREAD

**Issue by loosebazooka** [ossf/scorecard#2477]
**Describe the bug**
Cannot include a gradle wrapper and use the gradle/wrapper-validation-action to exempt the repo from violations if pinning the action by hash (instead of tag)

**Reproduction steps**
1. Add gradle wrapper to repo
2. Add gradle/wrapper-validation-action to ensure validity of the wrapper (but use a hash instead of tag)
3. Allstar hates it

Example: https://github.com/sigstore/protobuf-specs/issues/23#issuecomment-1322837470

**Expected behavior**
Allstar has no complaints.

**Additional context**
The action hash should be converted to a version (or compared against a version)

**Comment by anantshri** [comment]
check this too : https://github.com/ossf/scorecard/issues/2357
