### ISSUE TITLE
Consider versioned go modules pinned

### ISSUE THREAD

**Issue by favonia** [ossf/scorecard#2491]
**Is your feature request related to a problem? Please describe.**
Currently, any `go install` and `go get` without using an SHA-256 hash is considered unpinned. I believe this is overkill and goes against the current practice.

**Describe the solution you'd like**
I think versioned Go modules should be considered pinned because newer go tools (>= 1.13), by default, will verify the downloads against <https://sum.golang.org>. The checksum service <https://sum.golang.org/> has made it almost impossible for the original source to change a published release. Moreover, the design of the checksum service made it possible for others to audit the server itself. To change a versioned module, one would have to temper with the data on <https://sum.golang.org/>, and if that can be done without any auditor noticing it, we could very well doubt whether the go tools themselves are secure. It is perhaps more reasonable to assume Go module versions are practically as permanent as SHA-256 hashes.

**Additional context**
An empty version string or `latest` should still be considered unpinned.

**Comment by laurentsimon** [comment]
This makes sense to me. Is there an assumption here that command uses the go proxy?

**Comment by favonia** [comment]
> This makes sense to me. Is there an assumption here that the user uses the go proxy?

Yes. The user can choose to bypass the checking by intentionally using an old version of Go tools or setting `GOINSECURE` and pass `-insecure`. This would depend on what the role of `scorecard` wants to play. If the goal is just to remind users of better practice, then we can probably warn about `-insecure` and allow more versions that effectively pin down the dependencies. We cannot possibly prevent users from intentionally circumventing the detection.

BTW I would like to make some corrections to my previous comment. `go get` also accepts version _prefixes_ and branches like `main`, which are not great for the purpose of pinning. The full syntax is at https://go.dev/ref/mod#versions. I think the following three should be accepted.

1. Specific (full) semantic versions, such as `@v3.0.0` (I'm not sure if pre-releases are protected by the checksum server.)
2. Pseudo-versions, such as `@v3.0.1-0.20221111111111-aaaaaaaaaaaa`
3. Hashes

Maybe we can also accept this one:

1. `none`: removing a dependency

These should be rejected:

1. No version strings at all.
2. Version prefixes such as `v3.0`.
3. Anything that does not look like a pinned version, which can be branches or special tags like `latest`, `upgrade`, and `patch`. `scorecard` can treat all these cases the same way.

**Comment by laurentsimon** [comment]
> I'm not sure if pre-releases are protected by the checksum server

I would guess they are, since it fetches by tag and does not use GH API to query release metadata.

Thanks for the clarification. Are you interested in sending a PR? This would be the function to update https://github.com/ossf/scorecard/blob/main/checks/raw/shell_download_validate.go#L419

**Comment by favonia** [comment]
> Thanks for the clarification. Are you interested in sending a PR? This would be the function to update https://github.com/ossf/scorecard/blob/main/checks/raw/shell_download_validate.go#L419

In principle, yes, but you would have to wait. Maybe someone can give it a try first. (I know that part of the code very well, thanks to my debugging experience in #2490, but writing the correct parser still takes time and the Thanksgiving weekend was over.)
