### ISSUE TITLE
Update Security-Policy recommendations to recommend new GitHub private reporting feature

### ISSUE THREAD

**Issue by olivekl** [ossf/scorecard#2502]
GitHub has introduced [private vulnerability reporting]( https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability) (must be enabled). We should update our recommendations around the Security-Policy check to instruct users to enable this option.

**Comment by spencerschrock** [comment]
@olivekl Was this intentionally marked as completed? Is there a corresponding PR?

**Comment by olivekl** [comment]
There isn't a PR ---  it was intentional attempt to delete, mistakenly closed instead.
