### ISSUE TITLE
Feature Implement GitLab Native License Check for GitLab Hosted Projects

### ISSUE THREAD

**Issue by shissam** [ossf/scorecard#2517]
**Is your feature request related to a problem? Please describe.**
The License check was improved to provide more details as to the nature of the license selected for a given project. This improvement used GitHub's License API to get those details. These improved details should also be available for GitLab hosted projects (and scored accordingly).

**Describe the solution you'd like**
`clients/gitlabrepo/licenses.go` should behave in a like manner as `clients/githubrepo/licenses.go` where possible applying the same semantic results as returned by the GH API and the builtin heuristics used by `scorecard` when an API is not available.

**Describe alternatives you've considered**
PR #2442 implemented an improved builtin heuristic for better identification of the license selected for a given project but does not actually open the identified license file to attest to that license selected (but rather naming conventions, which is unlike the GH API which performs such content analysis). That builtin heuristic is only used when the hosting repository does not have an License API endpoint for getting that information--and is therefore slower and potentially not as accurate. Although the builtin heuristic should work on GitLab hosted projects, use of a GitLab License API endpoint, would be a better choice.

**Additional context**

**Comment by spencerschrock** [comment]
Completed as part of #3413
