### ISSUE TITLE
Add Code of Conduct as an Open Source Hygiene Factor

### ISSUE THREAD

**Issue by torgo** [ossf/scorecard#2524]
**Is your feature request related to a problem? Please describe.**

I recently found myself running Scorecard on a number of related repos and reporting on the result. For each project I also found myself checking for the presence of a code of conduct. This is a hygiene factor which is highlighted by Github along side of License and Contributing guidelines. It's generally considered to be a best practice to have one. All of our repos in OpenSSF have one. So I thought to myself "hey... what if the Scorecards system also checked for the presence of a code of conduct."  It feels equally relevant to me as the **code review**, **contributors**, **license** and **maintained** tests.

**Describe the solution you'd like**

I'd like Scorecards to check for the presence of a code of conduct and ideally do something to check its quality - specifically to see if the code has information about enforcement procedure and contact details.

Thanks for your consideration! ✨

**Comment by justaugustus** [comment]
Thanks for filing this, @torgo!
The OpenSSF Code of Conduct was added in https://github.com/ossf/scorecard/pull/2508.

**Comment by spencerschrock** [comment]
I believe this was issue wasn't asking if we added one, but rather a request for a check which detects if a repo has one.
