### ISSUE TITLE
Mention 2FA relevance although not checked by Scorecard

### ISSUE THREAD

**Issue by joycebrum** [ossf/scorecard#2526]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem itself, but could be important to mention that scorecard does not check for 2FA although it strongly recommends using it and why

**Describe the solution you'd like**
In the `Checks` part of the `readme` file, we could add a topic `Scorecard Non-Checks` that list all the checks that scorecard wasn't able to check but should be extremely relevant to be adopted. 

I can work in this update if you are ok with it

**Comment by naveensrinivasan** [comment]
I think the concept is great. However, I'm worried that if we add a section called "Scorecard Non-Checks," it will get too long. I'm not sure people will be interested in what Scorecard doesn't check.
