### ISSUE TITLE
Unit tests for scorecard run multiple times

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#2533]
In https://github.com/ossf/scorecard/issues/2522, we found out that it's easy to make a mistake by not initializing client's variables. To avoid this in the future, we should have additional tests that run scorecard twice and verify the results are the same. We can start by comparing that the number of warn / info / debug details is identical.

**Comment by spencerschrock** [comment]
> We can start by comparing that the number of warn / info / debug details is identical.

+1 on this. I tried a little to compare the results in more depth, but the comparison is difficult due to the non-deterministic ordering of many of the slices.

**Comment by laurentsimon** [comment]
right, to go further you can order the slices. I think go-cmp package has support for this. Maybe too complicated for what you're trying to do?

**Comment by spencerschrock** [comment]
It's somewhat feasible to order the details, it's very annoying to order all the slices and maps in all the raw data results
