### ISSUE TITLE
Typo in name of dependency update bot: Renovate

### ISSUE THREAD

**Issue by HonkingGoose** [ossf/scorecard#2568]
**Describe the bug**

Spelling error in name of dependency bot in these file(s):

https://github.com/ossf/scorecard/blob/c6d76807b76b7b72659525e103d6b1284c7b01b5/checks/raw/dependency_update_tool.go#L91

https://github.com/ossf/scorecard/blob/c6d76807b76b7b72659525e103d6b1284c7b01b5/e2e/dependency_update_tool_test.go#L84

**Reproduction steps**

1. Open the `ossf/scorecard` repository
2. Search for string `Renovabot`
3. Find these two files

The bad spelling also shows up in the response body:

```bash
curl -X 'GET' \
  'https://api.securityscorecards.dev/projects/github.com/renovatebot/renovate' \
  -H 'accept: application/json'
```

```json
    {
      "name": "Dependency-Update-Tool",
      "score": 10,
      "reason": "update tool detected",
      "details": [
        "Info: Renovabot detected: renovate.json:1"
      ],
      "documentation": {
        "short": "Determines if the project uses a dependency update tool.",
        "url": "https://github.com/ossf/scorecard/blob/c61f6bc297ee71dc4b5f2511144d6c031b946089/docs/checks.md#dependency-update-tool"
      }
    },
```

**Expected behavior**

Change `Renovabot` to `Renovate`.

**Additional context**

I don't know how hard it is for a newcomer to fix this problem? It looks like I can just rename the two entries in the files, and then create a PR?

Related issue:

- #2055

**Comment by azeemshaikh38** [comment]
@naveensrinivasan would you be able to take this on?
