### ISSUE TITLE
BUG Pinned-Dependencies check does not handle direct docker GitHub Actions correctly

### ISSUE THREAD

**Issue by rajbos** [ossf/scorecard#2580]
**Describe the bug**
Pinned-Dependency check does not detect a direct docker based action (uses statement is the docker container) correctly and fails to see that sha hash pinning is used, as advised. Therefor an alert is generated that should not be the case.

**Reproduction steps**
1. Use a docker image as an action with for example: 
`uses: docker://rhysd/actionlint@sha256:5f957b2a08d223e48133e1a914ed046bea12e578fe2f6ae4de47fdbe691a2468 # 1.6.22`
3. Run the `ossf/scorecard-action` action in a workflow
4. Result: a `Pinned-Dependencies` alert that you cannot resolve:
![image](https://user-images.githubusercontent.com/6085745/210577374-afd4f926-0200-4b2b-976f-f6b45b95548e.png)

**Expected behavior**
Detect that this is proper use of a sha hash and not alert, or close an already open alert.

**Additional context**
Note: I am using the `ossf/scorecard-action` in a workflow to run the checks. Alert is integrated with the GitHub Advanced Security Code scanning alerts.

**Comment by azeemshaikh38** [comment]
Maybe we are looking for `org/repo` pattern only and not `docker://` in GitHub workflows? @laurentsimon fyi. 

@raghavkaul assigning this to you. Could you please look into fixing this?
