### ISSUE TITLE
Feature - Update the number of tokens used in cronjob

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#262]
**Is your feature request related to a problem? Please describe.**
Increase the number of tokens used in the cron job to reduce the time spent on fetching the data.
**Describe the solution you'd like**
Get a few personal access tokens for GitHub and update them in the secrets to increase the throughput of fetching scorecard data from the GitHub API.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by naveensrinivasan** [comment]
Increase the number of tokens from `2` to `4`.

**Comment by naveensrinivasan** [comment]
It is `6` now

**Comment by azeemshaikh38** [comment]
Assigning to myself for now. Although 6 (or maybe 5 as of now) should be enough, will close this issue issue once we have a few more tokens.

**Comment by azeemshaikh38** [comment]
Closing this issue now. We have ~15 tokens now.
