### ISSUE TITLE
BUG: New Badge does not recognize Npm Organizations

### ISSUE THREAD

**Issue by UlisesGascon** [ossf/scorecard#2639]
**Describe the bug**
There is bug that prevents register new projects that are belonging to an NPM organization

**Reproduction steps**

1. Enter in https://bestpractices.coreinfrastructure.org/en/projects/new

2. Try to submit the github repo (https://github.com/onebeyond/systemic-knex)
![openssf_selection_1](https://user-images.githubusercontent.com/5110813/216524036-a59f2402-1c3c-4fb0-80b5-232ec49c6f31.gif)

3. OR try to submit URL (https://www.npmjs.com/package/@onebeyond/systemic-knex
, https://github.com/onebeyond/systemic-knex)

![openssf_selection_2](https://user-images.githubusercontent.com/5110813/216524041-2215d49f-a4c0-4a48-947e-3c7df1dcc05a.gif)

**Expected behavior**

The project is valid and the urls are correct, but there is an issue with the regex used to manage the URLs `https?:\/\/[A-Za-z0-9_][-A-Za-z0-9_.]*(\/([-A-Za-z0-9_.:\/\+!,#~]|%(20|[89A-Ea-e][0-9A-Fa-f]|[Ff][0-7]))*)?` as does not include support for `@`, so refactoring to `https?:\/\/[A-Za-z0-9_][-A-Za-z0-9_.]*(\/([-A-Za-z0-9_.:\/\@+!,#~]|%(20|[89A-Ea-e][0-9A-Fa-f]|[Ff][0-7]))*)?` should work.

**Additional context**

I can create a PR with the changes needed but I am not sure where the code is located

**Comment by gabibguti** [comment]
I believe this is the repo to make the changes: https://github.com/coreinfrastructure/best-practices-badge
I will try to take a look at the bug Ulises!

**Comment by UlisesGascon** [comment]
Yeah @gabibguti! It is working now, I just [submitted the app](https://bestpractices.coreinfrastructure.org/en/projects/7143) 👍
