### ISSUE TITLE
Scorecard attestor: add policy for CI-Tests that have passed

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#2717]
Add a new [policy](https://github.com/ossf/scorecard/blob/def5eadd77ef62d64617fa9d76b0c0b36a9618bd/attestor/policy/attestation_policy.go#L33) in Scorecard attestor that allows users to specify CI-Tests that should be passing on a commit before deploying the image.

**Comment by LappleApple** [comment]
Closing during community backlog refinement as "won't do" — no longer relevant.

**Comment by afmarcum** [comment]
Scorecard attestor feature has not been developed further. No longer relevant.
