### ISSUE TITLE
Suggestion: Change Branch-Protection check to consider rule of "change only through PRs"

### ISSUE THREAD

**Issue by diogoteles08** [ossf/scorecard#2727]
#### Is your feature request related to a problem? Please describe.

The current [Branch Protection check](https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection) does not consider the rule named `Require a pull request before merging` (you can check it on the [GitHub page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)). This rule is actually very important because it forces any change on the branch to be made through PRs, and would therefore prevent malicious pushes -- that could even be made through actions with write permissions. 

The closest to this we currently have is the requirement of `Reviewers >= 1` to get a 6/10 score. But this might be specially difficult to solo-devs, while the `Require a pull request before merging` is possible even for a single maintainer.

#### Describe the solution you'd like

The purpose is to make this rule enhance the Branch-Protection rule somehow. My suggestion would be to add this rule as a new tier with a 5/10 punctuation. This would give a score higher than the 3/10, which basically requires prevention of force pushes and branch deletion, and slightly lower than 6/10, which requires a reviewer other than the commiter.

#### Describe alternatives you've considered

- The rule could be added as a new requirement to get a 3/10 grade. But this might be frustrating to the projects that already had the effort to get this grade, as they could be led to 0/10.

**Comment by diogoteles08** [comment]
Is there any opposition to this? If not, feel free to assign me to it

**Comment by spencerschrock** [comment]
Overall, I could see this being some sort of partial credit. I've left some comments inline.

> #### Is your feature request related to a problem? Please describe.
> The current [Branch Protection check](https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection) does not consider the rule named `Require a pull request before merging` (you can check it on the [GitHub page](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)). This rule is actually very important because it forces any change on the branch to be made through PRs, and would therefore prevent malicious pushes -- that could even be made through actions with write permissions.
> 
> The closest to this we currently have is the requirement of `Reviewers >= 1` to get a 6/10 score. But this might be specially difficult to solo-devs, while the `Require a pull request before merging` is possible even for a single maintainer.

I think "Require branch to pass at least 1 status check before merging" also captures this to some extent. Of course this has the issue of tiers (which you raised in #3123). 
Also some of the admin level tier 2 points indirectly hit on this, which might become more visible after repo rules are supported (#3326).


> #### Describe the solution you'd like
> The purpose is to make this rule enhance the Branch-Protection rule somehow. My suggestion would be to add this rule as a new tier with a 5/10 punctuation. This would give a score higher than the 3/10, which basically requires prevention of force pushes and branch deletion, and slightly lower than 6/10, which requires a reviewer other than the commiter.

I think the code review is a much more important bit, but I could see requiring a PR to possibly be worth a single point.

> #### Describe alternatives you've considered
> * The rule could be added as a new requirement to get a 3/10 grade. But this might be frustrating to the projects that already had the effort to get this grade, as they could be led to 0/10.


This could also be part of the tier 1 if #3123 is changed.

**Comment by diogoteles08** [comment]
One important detail that I discovered:
By my testings, the `Require a pull request before merging` seems only to be retrievable when using an admin token :/
I concluded this because running Scorecard in a repository with this option disable, using an Admin token, I get 
``` 
BranchProtectionRule.RequiredPullRequestReviews = {
    RequiredApprovingReviewCount: *int32 nil,
    DismissStaleReviews: *false,
    RequireCodeOwnerReviews: *false
}
```
, but if I run without the admin token, for the exact same repository without changing the configs, I get
``` 
BranchProtectionRule.RequiredPullRequestReviews = {
    RequiredApprovingReviewCount: *int32 0,
    DismissStaleReviews: *false,
    RequireCodeOwnerReviews: *false
}
```
, which is the exact same result that we get when the repository requires PRs, but doesn't require a reviewer. This way, we could not differentiate a repository that does not requires PRs to a repository that requires PRs but doesn't require another reviewer.

Obs: those values were gotten inside the run of Scorecard as values available on the `evaluation` part of the run. This could be fact-checked by looking into the complete response of Github's API.

In any ways, I think this feature is still important, especially thinking that after repo rules support (#3326) all branch protection configuration should be public.

**Comment by diogoteles08** [comment]
One important detail that I discovered:
By my testings, the Require a pull request before merging seems only to be retrievable when using an admin token :/
I concluded this because running Scorecard in a repository with this option disable, using an Admin token, I get
```
BranchProtectionRule.RequiredPullRequestReviews = {
    RequiredApprovingReviewCount: *int32 nil,
    DismissStaleReviews: *false,
    RequireCodeOwnerReviews: *false
}
```
, but if I run without the admin token, for the exact same repository without changing the configs, I get
```
BranchProtectionRule.RequiredPullRequestReviews = {
    RequiredApprovingReviewCount: *int32 0,
    DismissStaleReviews: *false,
    RequireCodeOwnerReviews: *false
}
```
, which is the exact same result that we get when the repository requires PRs, but doesn't require a reviewer. This way, we could not differentiate a repository that does not requires PRs to a repository that requires PRs but doesn't require another reviewer.

Obs: those values were gotten inside the run of Scorecard as values available on the evaluation part of the run. This could be fact-checked by looking into the complete response of Github's API.

In any ways, I think this feature is still important, especially thinking that after repo rules support (https://github.com/ossf/scorecard/issues/3326) all branch protection configuration should be public.
