### ISSUE TITLE
Feature: add verification step for SLSA 3 provenance with slsa-verifier

### ISSUE THREAD

**Issue by developer-guy** [ossf/scorecard#2747]
**Is your feature request related to a problem? Please describe.**
This is a feature.

**Describe the solution you'd like**
[slsa-verifier](https://github.com/slsa-framework/slsa-verifier) is a tool to verify provenance from SLSA-compliant builders. As the scorecard uses one of the SLSA-compliant builders, I thought that it'd be good to use slsa-verifier in the verification step to verify provenance as we did in the ko project. 

> _https://github.com/ko-build/ko/blob/2860fcf5eec19d9716aaa9c26394da0b1e7b13de/.github/workflows/release.yml#L70_

I'm willing to do this, assign it to me please ✋ 

**Describe alternatives you've considered**

**Additional context**

/cc @asraa @laurentsimon @ianlewis

**Comment by developer-guy** [comment]
kindly ping @naveensrinivasan @azeemshaikh38

**Comment by laurentsimon** [comment]
Please send us a PR and I'll LGTM it. Thanks!
