### ISSUE TITLE
Improvement - Add GitHub private security report in the Scorecard output

### ISSUE THREAD

**Issue by luigigubello** [ossf/scorecard#2791]
**Is your feature request related to a problem? Please describe.**
Not really. This feature might be an improvement to better evaluate the security posture of a project. Currently, the Scorecard reports only if a project has or does not have a security policy (e.g. `SECURITY.md`), without additional context. Recently, GitHub has introduced private security reports to report vulnerabilities to maintainers without opening a public issue. Even if only GitHub (AFAIK) offers a similar feature at the moment, and even if this feature is still in beta, it might be helpful to report this info in the Scorecard output - without points or evaluation.

**Describe the solution you'd like**
Community, platforms, and products can evolve rapidly by introducing new features or adopting new standards. It might be useful to have some of this info in the scorecard output, even if the scorecard will not add any score in the aggregated score.

**Describe alternatives you've considered**
//

**Additional context**
In OpenSSF, we are evaluating to use GitHub private security reports for our open-source projects. It is the easiest solution to enable security reports to an organization level - without creating a unique email address for all the repositories or multiple email addresses.

**Comment by spencerschrock** [comment]
Duplicate of #2465. Closing to track in one issue.
