### ISSUE TITLE
Provide some way for smaller Javascript projects to pass the Fuzzing check

### ISSUE THREAD

**Issue by djahandarie** [ossf/scorecard#2792]
Currently, the following options exist for passing the fuzzing check:

* > if the repository name is included in the [OSS-Fuzz](https://github.com/google/oss-fuzz) project list;
  
  Not possible for smaller projects
* > if [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/) is deployed in the repository;
   
   Does not support Javascript
* > if there are user-defined language-specified fuzzing functions (currently only supports [Go fuzzing](https://go.dev/doc/fuzz/)) in the repository.
    
   Does not support Javascript
* > if it contains a [OneFuzz](https://github.com/microsoft/onefuzz) integration [detection file](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#detecting-the-use-of-onefuzz);
  
    Does not support Javascript

There are a couple JS fuzzing tools out there, but since OSS-Fuzz has settled on Jazzer.js as their supported JS fuzzing tool, perhaps it'd be a good first step if the scorecard checked for the existence of `@jazzer.js/core` in the node config as an alternative way to pass this check?

**Comment by spencerschrock** [comment]
Hmm, I could see about adding logic here:
https://github.com/ossf/scorecard/blob/ef16fd8ae05f4b93b3ef13893d116ef2595967bb/checks/raw/fuzzing.go#L50-L63

I'm not that knowledgable about JS, but would it just be looking for "@jazzer.js/core" in the `package.json` file? That could have some false positives as opposed to parsing the dev dependencies to look for it

**Comment by djahandarie** [comment]
> I'm not that knowledgable about JS, but would it just be looking for "@jazzer.js/core" in the package.json file? 

Yeah.

> That could have some false positives as opposed to parsing the dev dependencies to look for it

In the end it isn't a perfect check as anyone can easily include the dependency and then not actually implementing any fuzzing, so I don't think a false positive due it being in the wrong part of the file is a huge deal.

But I think this is a fine initial level of support, it could be refined to be more accurate if someone comes up with an idea for a more precise check.

**Comment by spencerschrock** [comment]
If someone would like to send a PR they can use #2843 as a template more or less.

**Comment by dubzzz** [comment]
Same as:

> I'd like to propose considering jsfuzz (jsfuzz repository) in addition to @jazzer.js/core.

I think adding "the project is relying on fast-check" should also be considered as a fuzzed project.

**Comment by laurentsimon** [comment]
If you know how how to check support for fas-check, feel free to send a PR

**Comment by spencerschrock** [comment]
Completed initially via #3073, with other issues tracking alternatives (e.g. #3491 for jazzer.js)
