### ISSUE TITLE
Feature: Improve Branch-Protection score calculation

### ISSUE THREAD

**Issue by gabibguti** [ossf/scorecard#2796]
**Is your feature request related to a problem? Please describe.**
Following this discussion https://github.com/ossf/scorecard/pull/2772#discussion_r1146569992

As I understand the Branch-Protection score is divided by tier and each tier has a group of settings. Over time, the settings moved from one tier to another, moved from non-admin to admin classification and new settings were added. That's why enabling some settings do not have the intended effect on the score.

**Describe the solution you'd like**
For me, the score should be count 1 point for each setting but when using non-admin token if you reached all the tier settings you could do you get the max points for that tier.

E.g. Using non-admin token, to reach tier 3 you need to enable 7 settings. Currently, tier 3 counts as 8/10, but by this proposal should be 7/10.

**Describe alternatives you've considered**
As an alternative, the tier scores could be maintained but make sure all settings count.

E.g. Using non-admin token, when you reach tier 3 you have 8/10. To reach tier 4 (9/10) you need to enable 2 settings, but only one of them makes you get 9/10, the other does not count. To make it proportional, you should enable both settings to reach 9/10.

**Additional context**
None.

**Comment by spencerschrock** [comment]
Going to close in favor of discussion in #3123
