### ISSUE TITLE
Feature: Add PR information in the details of CI-Tests, Code-Review and SAST checks

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#2798]
**Is your feature request related to a problem? Please describe.**
It isn't possible to determine which PRs passed or failed according to CI-Tests, Code-Review or SAST checks. This is unfortunate because projects with "unusual" setups frequently get less than a 10/10 for reasons that aren't entirely clear. For example, [google/guava](https://github.com/google/guava) ([API results](https://api.securityscorecards.dev/projects/github.com/google/guava)) gets a 9/10 because only 28/30 PRs counted as reviewed. Given the project's unusual setup (using a bot to force-push commits to main instead of merging PRs), it's hard to diagnose what happened to the 2 missing PRs.

**Describe the solution you'd like**
Information on passing and failing PRs should be displayed whenever these checks are run with `--show-details`. It is my understanding that none of these checks currently use the `details` field, so there should be minimal risk of disrupting dependencies.

**Comment by boahc077** [comment]
I am interested in implementing this feature.
@ossf/scorecard-maintainers:  Could you please assign this issue to me If no one else has volunteered? I would love the opportunity to take on this task and work towards its successful implementation.

**Comment by laurentsimon** [comment]
Done! Thanks for helping out!
