### ISSUE TITLE
BUG: exception when processing gitlab commits with an unmerged pull request

### ISSUE THREAD

**Issue by kgangerlm** [ossf/scorecard#2820]
**Describe the bug**
The new gitlab functionality throws an exception from `commits.go` when there is a merge request associated to the commit, but that merge request is unmerged.    

**Reproduction steps**
1.  Open an MR in a gitlab project
2.  Make at least one commit against the mr
3. Run the scorecard cli against the repository

**Expected behavior**
Looking at the github implementation I believe the expected behavior would be to ignore the associated merge request, and just treat this as a raw commit.  Still assessing the impact of this approach on `Code-Review` score.

**Comment by kgangerlm** [comment]
I am planning on working a PR for this issue.

**Comment by azeemshaikh38** [comment]
Thanks @kgangerlm. @raghavkaul fyi who is working on some changes to GitLab Code-Review check - https://github.com/ossf/scorecard/pull/2764. If you do send a PR, @raghavkaul can help with reviewing it.

**Comment by spencerschrock** [comment]
@kgangerlm or @jimrobison can you confirm if this bug was fixed by #3026
