### ISSUE TITLE
Feature - Implement Ratelimit check for GitHub GraphQL

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#283]
**Is your feature request related to a problem? Please describe.**
The present  rate limit check does not check for GraphQL API Limits

**Describe the solution you'd like**
Implement a Ratelimit check for GraphQL API https://docs.github.com/en/rest/reference/rate-limit

**Comment by afmarcum** [comment]
Does this bug still need to be addressed?
If there is no feedback in the next 7 days on whether this remains important for the project, then this issue will be closed.

**Comment by spencerschrock** [comment]
As far as I know, this was always true, even when the graphQL client was added: https://github.com/ossf/scorecard/pull/45

https://github.com/ossf/scorecard/blob/fd188f526362cc5a7eb994a5b6ca7ea00fcf20be/pkg/scorecard.go#L68-L75
