### ISSUE TITLE
Use the presence of property-based testing in Haskell to detect fuzzing

### ISSUE THREAD

**Issue by chungyc** [ossf/scorecard#2830]
**Is your feature request related to a problem? Please describe.**

Property-based testing is widespread with Haskell projects.  They either generate test instances randomly or exhaustively and test that specific properties are satisfied.  This is pretty much fuzzing and should be treated as such.

**Describe the solution you'd like**

[QuickCheck](https://hackage.haskell.org/package/QuickCheck), [SmallCheck](https://hackage.haskell.org/package/smallcheck), [Hedgehog](https://hedgehog.qa/), and [validity](https://github.com/NorfairKing/validity) are property-based testing frameworks for Haskell that I know of (likely not an exhaustive list).

Detecting their use could be done by scanning for imports of Haskell modules from these Haskell packages in test code, which would be roughly on par with what [fuzzing detection for Go](https://github.com/ossf/scorecard/blob/038c7028b3b7305499e28db8f0955b7c5ce382af/checks/raw/fuzzing.go#L54) does.  This can be an entry in `languageFuzzSpecs` as with Go.

**Describe alternatives you've considered**

An alternative would be to detect the use of property-based testing Haskell packages in [Cabal](https://www.haskell.org/cabal/) or [hpack](https://hackage.haskell.org/package/hpack) files.  However, this may have a much higher false positive or false negative rate given the limited matching based on regular expressions that is available.  Import statements in Haskell have a much more regular form that would be more easily accommodated with regular expressions.

Pattern matching on specific function declarations will not work because there is no standardized function declaration convention for property-based tests; individual tests may not even be in their own named function.

**Additional context**

This is basically declaring my intention and willingness to add this detection to [`fuzzing.go`](https://github.com/ossf/scorecard/blob/main/checks/fuzzing.go) unless the owners think otherwise.

**Comment by naveensrinivasan** [comment]
@chungyc Thanks! Would you like to open a PR to address this?

**Comment by chungyc** [comment]
I have opened https://github.com/ossf/scorecard/pull/2843 as a draft.  It is not ready for review or merging yet, but it is enough to show the direction I am pursuing.

**Comment by chungyc** [comment]
https://github.com/ossf/scorecard/pull/2843 is ready for review.
