### ISSUE TITLE
BUG: docker-compose file with YAML directive breaking

### ISSUE THREAD

**Issue by gabibguti** [ossf/scorecard#2853]
**Describe the bug**
A docker-compose file with YAML directive seems to break the Pinned-Dependencies check.

**Reproduction steps**
1. Run Scorecard @4.10.2 for github.com/grpc/grpc: `scorecard --repo=github.com/grpc/grpc`
2. View that Pinned-Dependencies check ends in:
  ```
  internal error: error parsing shell code: https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
  templates/examples/php/echo/base.Dockerfile.template:1:48
  parameter expansion requires a literal
   ```
    
3. The problematic file/line is https://github.com/grpc/grpc/blob/master/templates/examples/php/echo/base.Dockerfile.template#L1

**Expected behavior**
I expected Scorecard to be able to parse docker-compose files with YAML directive.

**Additional context**
None.

**Comment by spencerschrock** [comment]
I'm guessing it's coming from here:
https://github.com/ossf/scorecard/blob/1fb59608bd73a5bfc0c1821bb1b36c7a4afcad29/checks/raw/shell_download_validate.go#L957-L962

Based on the comment, I'm guessing we aren't ignoring the error everywhere we call it. But I haven't tracked it down.

**Comment by spencerschrock** [comment]
So we used to catch it here:
https://github.com/ossf/scorecard/blob/a004ffb107c5774bf9b170bc84031173d20b933f/checks/shell_download_validate.go#L810-L822

Until it was removed by this large PR #1932

@laurentsimon any idea if this was an intentional removal?

**Comment by spencerschrock** [comment]
Crashing the whole `Pinned-Dependencies` check shouldn't be an issue anymore after #3515. 
There's still a processing error, which gets logged, but this doesn't seem like a normal dockerfile so happy to close this one out.
