### ISSUE TITLE
Feature - Add metadata for Envoy dependencies to scorecard

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#287]
**Is your feature request related to a problem? Please describe.**
Now that scorecard is able to scan 2000+ repositories https://storage.googleapis.com/ossf-scorecards/latest.json it would help to add metadata to these scans easily identify the envoy's dependencies using the `--metadata` feature in the scorecard command line. 

**Describe the solution you'd like**
- Identify the dependencies for the envoy.
-  Probably write a tool to update the `./cron/projects.txt` with some like `project=envoy,dependency=true` to the envoy's dependencies
- The `latest.json` will contain this additional metadata which can help identify scorecard for all of `envoy` dependencies.

**Comment by naveensrinivasan** [comment]
@htuch We are trying to scan all of Envoy's dependencies and add metadata to the results using the `metadata` which can be passed in the command line.

`./scorecard  --repo=https://github.com/ossf/scorecard --metadata=project=openssf,critical=true --format json`

``` json
{
  "Repo": "github.com/ossf/scorecard",
  "Date": "2021-03-18",
  "Checks": [
    {
      "CheckName": "Active",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Branch-Protection",
      "Pass": false,
      "Confidence": 0,
      "Details": null
    },
    {
      "CheckName": "CI-Tests",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "CII-Best-Practices",
      "Pass": false,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Code-Review",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Contributors",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Frozen-Deps",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Fuzzing",
      "Pass": false,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Packaging",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Pull-Requests",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "SAST",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Security-Policy",
      "Pass": true,
      "Confidence": 10,
      "Details": null
    },
    {
      "CheckName": "Signed-Releases",
      "Pass": false,
      "Confidence": 4,
      "Details": null
    },
    {
      "CheckName": "Signed-Tags",
      "Pass": false,
      "Confidence": 5,
      "Details": null
    }
  ],
  "MetaData": [
    "project=openssf",
    "critical=true"
  ]
}
```

Where can we look for `envoy` dependencies? 

cc @inferno-chromium @dlorenc

**Comment by inferno-chromium** [comment]
@asraa - can you help adding those in https://github.com/ossf/scorecard/blob/main/cron/projects.txt

**Comment by asraa** [comment]
> Where can we look for envoy dependencies?

Envoy's deps are specified in the maps in https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl (and it's API deps in https://github.com/envoyproxy/envoy/blob/main/api/bazel/repository_locations.bzl).

What happened to this PR btw? https://github.com/ossf/scorecard/commit/338f9a0874a80a3ae7ca8751bf7350cb6935fee9#diff-6060899d2f700782c4e9cb8d515f0ba2a310ebcbfa14f41ed9471f98d1e27a4f I don't see it reflected in main.

Sure, should I manually add them the projects.txt, or are you looking for a script to automatically get them?

**Comment by naveensrinivasan** [comment]
> > Where can we look for envoy dependencies?
> 
> Envoy's deps are specified in the maps in https://github.com/envoyproxy/envoy/blob/main/bazel/repository_locations.bzl (and it's API deps in https://github.com/envoyproxy/envoy/blob/main/api/bazel/repository_locations.bzl).
> 
> What happened to this PR btw? [338f9a0#diff-6060899d2f700782c4e9cb8d515f0ba2a310ebcbfa14f41ed9471f98d1e27a4f](https://github.com/ossf/scorecard/commit/338f9a0874a80a3ae7ca8751bf7350cb6935fee9#diff-6060899d2f700782c4e9cb8d515f0ba2a310ebcbfa14f41ed9471f98d1e27a4f) I don't see it reflected in main.
> 
Sorry, they got blown off by the other commit. 

> Sure, should I manually add them the projects.txt, or are you looking for a script to automatically get them?

Would appreciate a script, so that we can run them on schedule.

**Comment by asraa** [comment]
Sorry, last follow-up question. Would a python script be OK? I can hack one together fairly easily, we already have the tools to do so when we manually get scorecards for each of our deps
https://github.com/envoyproxy/envoy/blob/2c8f6639ba2fc1b83af5c95115045fb8b1b9fc88/tools/dependency/ossf_scorecard.py#L65

**Comment by naveensrinivasan** [comment]
Python should be good. I would prefer go , the rest of the code base in go.

**Comment by naveensrinivasan** [comment]
I am so sorry, is it possible to do it go? I can help if you need some.

**Comment by asraa** [comment]
I'll give it a first stab and put out a PR, would appreciate review help!
I think the earliest I can get it out will be Monday if that's OK

**Comment by naveensrinivasan** [comment]
> I'll give it a first stab and put out a PR, would appreciate review help!
> I think the earliest I can get it out will be Monday if that's OK

Thank you! That works.

**Comment by htuch** [comment]
I think if the script is living in OSSF tooling it makes sense for it to be Go, if it lives in Envoy repo, best that it be Python, since most of our other dep tooling is Python based and the dependency shepherds are working with that.

**Comment by inferno-chromium** [comment]
Static list is fine for now, since later we will have some dependency calculation logic project in near future.

**Comment by asraa** [comment]
Added a static list for now! Will work on automating soon.

**Comment by naveensrinivasan** [comment]
Thanks

**Comment by afmarcum** [comment]
Is there still work to be done for this issue?
If there is no feedback in the next 7 days on whether this remains important for the project, then this issue will be closed.
