### ISSUE TITLE
Feature - Implement metric based Algorithm for choosing the GitHub Token

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#288]
**Is your feature request related to a problem? Please describe.**
Right now when there are multiple tokens available for scorecard. It uses the RoundRobin approach in choosing the GitHub token.

**Describe the solution you'd like**
Build a Producer/Consumer approach where the token provider uses the GitHub API to determine the token that could be used by using `X-RateLimit-Remaining`and `X-RateLimit-Reset` https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by naveensrinivasan** [comment]
This is a priority for scaling the repository that has to be scanned. The default round-robin might be good enough.

**Comment by inferno-chromium** [comment]
I dont think this is needed with new architecture, working well even for 50k repos, please reopen if needed.
