### ISSUE TITLE
Feature - provide a way for other OSS projects to include their dependencies to be tracked in scorecard

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#289]
**Is your feature request related to a problem? Please describe.**
Similar to #287, there should a standard way to parse the dependencies for critical projects add them to `dailyscore` cron job along with metadata.

For example - scorecard cronjob should help track dependencies for critical projects like kubernetes https://twitter.com/spiffxp/status/1371240897531236354

Instead of scorecard doing the work of parsing each repo and adding it to cronjob, the project should provide an option for other automation that other OSS teams can utilize.

**Describe the solution you'd like**
For example -

1. Parse the `go.mod` file for k8s
2. Find the dependencies 
3. Check if the dependencies are in the scorecard cronjob list `projects.txt`. If not add those
4. If there are already there and include additional metadata

**Comment by naveensrinivasan** [comment]
@inferno-chromium Thoughts?

**Comment by inferno-chromium** [comment]
@naveensrinivasan - this is very go centric, what about other languages like python, etc

There is some work at Google to better evaluate dependency tree structure (@robpike). I recommend waiting on that instead of this.

**Comment by naveensrinivasan** [comment]
@inferno-chromium the initial was only for go. But later expand it to other languages

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan - this is very go centric, what about other languages like python, etc
> 
> There is some work at Google to better evaluate dependency tree structure (@robpike). I recommend waiting on that instead of this.

When does Google likely to have the solution for dependency tree structure?  Based on the timeline we could decide to go one way or the other?

**Comment by inferno-chromium** [comment]
No clue, but i think we have lot of other important things to work on (e.g. scaling, more checks, etc).

**Comment by naveensrinivasan** [comment]
Ok. Let’s keep in the backlog.

**Comment by azeemshaikh38** [comment]
IMO, the focus of Scorecards should be repo-specific automated analysis. Tracking dependencies of a repo is a whole different problem/project of its own. If we plan to tackle it, we should do it orthogonal to Scorecards (maybe in a new repo).

I propose closing this issue in lieu of reducing number of open issues we currently have. If we plan to track dependencies in Scorecard at a future date, we can revisit this.
