### ISSUE TITLE
BUG:Error: check runtime error: CII-Best-Practices: internal error: error during json parsing: error during json.Unmarshal: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by LikeFirstMeet** [ossf/scorecard#2902]
**Describe the bug**

**Reproduction steps**
1. install cli 
2. score  some repos(20~140)
3. it give internal error: error during json.Unmarshal: invalid character '<' looking for beginning of value
4. the concret error url:https://github.com/LikeFirstMeet/ScoreCardActionForOpenHarmony/actions/runs/4794794621/jobs/8528570612

**Expected behavior**
I have scored some repositories before i meet the error!

**Additional context**
score for many repositories.

**Comment by naveensrinivasan** [comment]
This is the error in the logs `Error: check runtime error: CII-Best-Practices: internal error: error during json parsing: error during json.Unmarshal: invalid character '<' looking for beginning of value`

**Comment by spencerschrock** [comment]
The Scorecard binary returns a non-zero (1) exit code when there's a runtime error.

You could add a `|| true` to the end of the command to ignore the exit code.

```
./scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json || true
```

And if you want to hide all error messages you could redirect `stderr`
```
scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json 2>/dev/null
```

Or combine them:
```
scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json 2>/dev/null || true
```

**Comment by LikeFirstMeet** [comment]
> 出现运行时错误时，记分卡二进制文件返回非零 (1) 退出代码。
> 
> `|| true`您可以在命令末尾添加一个以忽略退出代码。
> 
> ```
> ./scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json || true
> ```
> 
> 如果您想隐藏所有错误消息，您可以重定向`stderr`
> 
> ```
> scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json 2>/dev/null
> ```
> 
> 或者将它们结合起来：
> 
> ```
> scorecard --repo https://github.com/laiyoufafa/third_party_grpc --format json 2>/dev/null || true
> ```

Thank you very much. I have solved the error by "|| true".
