### ISSUE TITLE
BUG: internal error parsing Dockerfile

### ISSUE THREAD

**Issue by lucasgonze** [ossf/scorecard#2932]
**Describe the bug**

"internal error: error parsing shell code" from Dockerfile

**Reproduction steps**
1. Open attached file
2. `scorecard --repo=github.com/lucasgonze/magma/ --show-details --format=json | jq` 
3. Pinned-Dependencies code throws this error:

```
    {
      "details": null,
      "score": -1,
      "reason": "internal error: error parsing shell code: lte/gateway/docker/mme/Dockerfile.ubuntu18.04:1:37: \"then\" can only be used in an if",
      "name": "Pinned-Dependencies",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/27cfe92ed356fdb5a398c919ad480817ea907808/docs/checks.md#pinned-dependencies",
        "short": "Determines if the project has declared and pinned the dependencies of its build process."
      }
    },

```

**Expected behavior**
N/A

**Additional context**

The state of the branch at the time of this running was:
https://github.com/lucasgonze/magma/commit/42b8626e9428c6c0255ad3f861b5f9b3bcf6a201

The file is:
https://github.com/lucasgonze/magma/blob/master/lte/gateway/docker/mme/Dockerfile.ubuntu18.04

There is no "then" in that file at the referenced location. The extra "then" is probably in the source code of scorecard.

**Comment by naveensrinivasan** [comment]
Closing this as we have it in here https://github.com/ossf/scorecard/issues/2911
