### ISSUE TITLE
Feature - Extract the Roundtripper into a separate repository

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#294]
**Is your feature request related to a problem? Please describe.**
Extract Roundtripper into a separate Git  repository 
https://github.com/ossf/scorecard/blob/ba42e1ab7bd2850d01a2f17b53fc44f420103f41/roundtripper/roundtripper.go#L15

The roundtripper provides 
- Use of Multiple GitHub token using RoundRobin, the next better approach is to use metrics based #288 
-  HTTP Caching 

These features aren't specific to scorecard. These are common features that can be utilized by other projects that would like to consume GitHub API in a scalable way.

**Comment by naveensrinivasan** [comment]
@inferno-chromium  Thoughts?

**Comment by inferno-chromium** [comment]
Sure, that is fine, but where can we host this?

**Comment by inferno-chromium** [comment]
If we add gitlab and other source code systems, then definitely a very nice thing to have in its own repo.

**Comment by naveensrinivasan** [comment]
> Sure, that is fine, but where can we host this?

With OSSF or another org.

**Comment by dlorenc** [comment]
I can make a repo in ossf if you want. Could you get it staged somewhere else first though - then we can copy it over here, rather than starting with an empty repo here?

**Comment by naveensrinivasan** [comment]
> I can make a repo in ossf if you want. Could you get it staged somewhere else first though - then we can copy it over here, rather than starting with an empty repo here?

Why not clone this to a new repo like we did for feeds and analysis ?

**Comment by azeemshaikh38** [comment]
There are enough changes in roundtripper code now that it seems tailored for Scorecard usage and not generic enough to be a separate repo.

Closing this for now, feel free to re-open if folks think otherwise.
