### ISSUE TITLE
Introducing Scorecard result viewer

### ISSUE THREAD

**Issue by tegioz** [ossf/scorecard#2979]
Hi! 👋 

This is Sergio from [CLOMonitor](https://clomonitor.io/) 🙂

Last week, when we were adding a new check to CLOMonitor for the presence of the OpenSSF Scorecard badge in the repositories' README files, we realized that the badge link points to the Scorecard API result endpoint. We wanted to display that information nicely in CLOMonitor, so we've built a small viewer for the report's json data.

We thought this could be useful outside of CLOMonitor, so instead of adding it as part of the CLOMonitor's UI, we've built it as an independent page that we could donate to you if you'd like. It's just a single [self-contained HTML document](https://github.com/cncf/clomonitor/blob/main/web/public/scorecard.html) that can be controlled via [some query string parameters](https://github.com/cncf/clomonitor/blob/b9ded47677deca9e602b43e40769e6ec0324496e/web/public/scorecard.html#L1-L15). It could serve as a nice badge link destination, for example 😇

You can see it live [here](https://clomonitor.io/scorecard?platform=github.com&org=pixie-io&repo=pixie&theme=light). We'll probably tweak a few details over the next couple of days (i.e. some improvements for mobile devices), but it's mostly looking good.

If you'd rather it to continue living only in CLOMonitor for now, please feel free to use the instance we are serving if you'd like, even for the badges 😉 And of course any feedback to improve it is welcomed!

BTW thank you all for the great work done here! Most of CLOMonitor's security checks rely on Scorecard and it has worked great for us ❤️

<img width="955" alt="scorecard-report-viewer" src="https://github.com/ossf/scorecard/assets/1213902/f1dd28f5-5c0c-4307-810b-b746f0f80f4c">

**Comment by naveensrinivasan** [comment]
@tegioz This is AMAZING!!! Thank you!!

@ossf/scorecard-maintainers  👀

**Comment by evverx** [comment]
Thanks! Those dashboards look great on all sorts of devices (including watches).

I wonder if it would be possible to sort the checks by "severity"? I think the "vulnerabilities" check (which is currently at the bottom) should be higher than "CII-Best-Practices-Badge". An additional option would be to sort by "scores" and within those groups by "severity" (if the use case is to make it easier to figure out what needs addressing).

**Comment by spencerschrock** [comment]
I think the page looks great!

 If it's a static page, it could certainly be hosted on the Netlify portion of Scorecard's website.
I'd have to think about whether or not this is better than keeping it with clomonitor.

**Comment by tegioz** [comment]
Thanks! And thank you for the feedback @evverx!

We've just deployed some additional changes:

- Ability to sort checks by multiple criteria
    - Controlled by the new `sort_by` and `sort_direction` [params](https://github.com/cncf/clomonitor/blob/0a6a6c394474b6e55379c9319d01d7b276bd4f2f/web/public/scorecard.html#L14-L15)
- Added extra symbol to the check score to make its meaning clearer
- Added tooltips to check score and risk level
- Fixed issue selecting text

**Comment by evverx** [comment]
Now that I can sort the checks I think `-1` is tricky in terms of visualization. They are kind of neutral but some of them (like "packaging") are more neutral than "branch-protection" (and I think "branch-protection" is almost always `-1` because adding a PAT isn't worth it). I have to admit I don't know how to convey it. Maybe those nuances would be better conveyed by the scorecard output somehow.

Anyway all I can say is that those dashboards are great. Thank you! I think badges should certainly point to them (once it's decided where they should officially live).

**Comment by spencerschrock** [comment]
In the scorecard default output we replace `-1` with a `?`, which is one possibility.

**Comment by evverx** [comment]
I think something like "? Packaging" indicates that it's unknown whether a project publish packages on GitHub while in reality it usually means that packages aren't published and this check isn't applicable to that particular project at all (i.e. I think "n/a Packaging" makes more sense). "Branch-Protection" is different (though there "n/a" could mean "not available" instead of "not applicable" but if it's almost always "n/a" it isn't clear why it should be shown at all).

**Comment by tegioz** [comment]
We've replaced `-1` with `?` for now, to match scorecard's output. But we'd be happy to switch to something else if needed. Entries with `?` have been pushed to the bottom of the list as well.

<img width="886" alt="Screenshot 2023-05-15 at 13 00 18" src="https://github.com/ossf/scorecard/assets/1213902/9d501f2c-74b9-4356-9654-c85eec137e7a">

**Comment by evverx** [comment]
> Entries with ? have been pushed to the bottom of the list as well

I think as long as they are grouped at the bottom "?" should do. It's certainly better than "n/a"'s scattered all over the place I was proposing here :-)

It seems in dark mode selected areas aren't highlighted:

https://github.com/ossf/scorecard/assets/10195800/5c7a46a8-dc98-46f1-9ea5-f80abaea4377

(on an absolutely unrelated note, I wonder what "CLO" stands for? My guess was that it's some level objectives but I can't seem to figure out what "C" is. Sorry for the off-topic. I'm just curious).

**Comment by tegioz** [comment]
> It seems in dark mode selected areas aren't highlighted:

Thanks, we'll take care of it soon 👍

> (on an absolutely unrelated note, I wonder what "CLO" stands for? My guess was that it's some level objectives but I can't seem to figure out what "C" is. Sorry for the off-topic. I'm just curious).

It comes up every now and then, please see cncf/clomonitor#746 🙂 [CLOTributor](https://clotributor.dev) is another member of the CLO family 😉

**Comment by tegioz** [comment]
Hi @evverx

> It seems in dark mode selected areas aren't highlighted

In what OS are you experiencing this issue? We can't reproduce it in any browser in MacOS. We've also observed an alignment issue in the risk level badge in your video, so we'd like to take a look at that as well.

**Comment by evverx** [comment]
I've just checked and as far as I can tell that laptop comes with macOS Big Sur 11.7.7. Newer laptops seem to be fine (or maybe the brightness settings aren't tweaked there :-)). Looks like it's some weird macOS-specific corner case affecting the dashboard dark mode with the default system dark mode.

**Comment by evverx** [comment]
It's really weird. On YouTube it's dark:

https://github.com/ossf/scorecard/assets/10195800/753f7ebe-608b-4e3b-9f3c-fb0d62d1da12

GitHub seems to get it around though:

https://github.com/ossf/scorecard/assets/10195800/0bd6ada1-2a02-4de8-a31d-98b7fdea7b54

Anyway I'm not sure it needs fixing. I assume YouTube probably did their research and concluded that this case isn't common (and I'd agree with that conclusion :-))

**Comment by tegioz** [comment]
Thanks for looking into it @evverx 🙂

**Comment by evverx** [comment]
This issue has been open for 2 weeks so I'm wondering what is holding this back? Due to https://github.com/ossf/scorecard/issues/1972 I don't have access to the meeting notes (where I assume dashboards would have been mentioned) so I'm kind of in the dark here. As I mentioned elsewhere since the dashboards are great and can be used to view/sort the scorecard output they should also make it possible to cut off the SARIF part of the scorecard action and prevent scorecard alerts from popping up over and over again in the security tab.

**Comment by spencerschrock** [comment]
Super happy to see the feedback + iterations here.

> This issue has been open for 2 weeks so I'm wondering what is holding this back?

I think some of it had to do with the OSS NA conference which multiple maintainers went to. Now that I'm back (and from a personal vacation) I'm ready to see this resolved as well.

In terms of adoption, the underlying API the badges currently link to wont be changing, so it's really just a matter of:

1. deciding where this is hosted
2. updating the scorecard action README to include instructions for linking to the new page, and making a release note for others to do the same. And of course there's nothing stopping individuals from doing this now for repos they care about.

For the other @ossf/scorecard-maintainers, the only decision is hosting on the netlify portion of https://securityscorecards.dev/, or keeping it on  clomonitor.io?

**Comment by naveensrinivasan** [comment]
+1

I recommend using https://securityscorecards.dev/. It enables larger enterprises to whitelist a single DNS entry, which is a great advantage.

**Comment by evverx** [comment]
@spencerschrock got it. Thanks!

One last thing. Looking at https://github.com/ossf/scorecard/milestone/5 it seems something called "Structured results" is on its way. As far as I understand the idea is to dump even more json stuff in the foreseeable future. I wonder if it's going to be used by the scorecard action by default? If so it seems it can break the dashboards (because as far as I understand that format isn't expected) and all that json is going to end up in every check and that would bring the UI back to that human-unfriendly format again (unless it's parsed somehow and formatted somehow).

**Comment by spencerschrock** [comment]
Without going too much off-topic, I don't see that being an immediate problem.

> As far as I understand the idea is to dump even more json stuff in the foreseeable future. I wonder if it's going to be used by the scorecard action by default?

Changing the JSON output structure is something we're very conservative with, so it will be its own output format (currently gated behind an experimental env flag). If any change to the default scorecard action format were to occur, I would expect a major version change to accompany it.

> would bring the UI back to that human-unfriendly format again

Our goal is the opposite, to split up the various checks into sub-components so consumers can look at the bits they care about and tune out the noise. But yes it would require a change to dashboards/visualizations at some point in the future.

**Comment by evverx** [comment]
> Without going too much off-topic. I don't see that being an immediate problem

I'm not sure why it would be offtopic in an issue where the scorecard UI is discussed. I agree it's not exactly an immediate problem.

> split up the various checks into sub-components so consumers can look at the bits they care about and tune out the noise

I went through those issues and I think the idea is to make it easier for machines (not people) to consume that. The UI that actual maintainers can use has never been discussed there.

> it would require a change to dashboards/visualizations at some point in the future

It would but it isn't even included in that milestone (or any other milestone for that matter) as far as I can see.

**Comment by spencerschrock** [comment]
> I went through those issues and I think the idea is to make it easier for machines (not people) to consume that. The UI that actual maintainers can use has never been discussed there.
> It would but it isn't even included in that milestone (or any other milestone for that matter) as far as I can see.

I'd say both it helps with both, but you're right there was no tracker. #3078

> +1
> I recommend using https://securityscorecards.dev/. It enables larger enterprises to whitelist a single DNS entry, which is a great advantage.

Without any further objections, I think the decision is to donate the static page to https://github.com/ossf/scorecard-webapp. I know we have a directory for static files [(link)](https://github.com/ossf/scorecard-webapp/tree/main/scorecards-site/static), but I'm not personally familiar with the router/mux we have setup. At the very least it would be accessible at `https://securityscorecards.dev/scorecard.html` if simply dropped in.


> It's just a single self-contained HTML document

Are changes made directly to the file, or are there source files which get built into the page?

**Comment by evverx** [comment]
> I'd say both it helps with both

I agree and I suspect there're consumers who are probably planning to build some stuff (including all sort of UIs with queries and all kinds of bells and whistles) but my concern was that the UI that maintainers can use wouldn't be a priority. At least until the CLOMonitor folks built those amazing dashboards it was somehow totally acceptable to dump json and call it a day. Time will tell I guess.

Anyway I'm not sure what else I can say here so I'd like to thank the CLOMonitor folks once again!

**Comment by tegioz** [comment]
> Without any further objections, I think the decision is to donate the static page to https://github.com/ossf/scorecard-webapp. I know we have a directory for static files [(link)](https://github.com/ossf/scorecard-webapp/tree/main/scorecards-site/static), but I'm not personally familiar with the router/mux we have setup. At the very least it would be accessible at `https://securityscorecards.dev/scorecard.html` if simply dropped in.

That sounds great to us! @cynthia-sg and I would be happy to help if there is something to fix on it. And eventually when the JSON output changes we could work with you to support the new format.
 
> Are changes made directly to the file, or are there source files which get built into the page?

Yes, changes are made directly to the file, there is no build process. We've a small fix pending that we'll push on Monday.

**Comment by spencerschrock** [comment]
> That sounds great to us! @cynthia-sg and I would be happy to help if there is something to fix on it. And eventually when the JSON output changes we could work with you to support the new format.

Fantastic. Thanks for the viewer and support!

> Yes, changes are made directly to the file, there is no build process. We've a small fix pending that we'll push on Monday.

Sounds good! Do you mind sending the PR to https://github.com/ossf/scorecard-webapp? Dropping it in as `scorecards-site/static/viewer/index.html` should make it accessible at: 
`https://securityscorecards.dev/viewer/?platform=github.com&org=ossf&repo=scorecard&theme=light`

**Comment by tegioz** [comment]
No worries! PR is ready: [ossf/scorecard-webapp/pull/406](https://github.com/ossf/scorecard-webapp/pull/406) 🙂

**Comment by spencerschrock** [comment]
This has been merged into the site. There may be one or two small tweaks around other supported paths (#https://github.com/ossf/scorecard-webapp/issues/415) before announcing this with the next `scorecard-action` release.

**Comment by evverx** [comment]
Nice! Thanks!

I wonder if it's too late for feature requests? Would it be possible to make links to OSV issues like https://github.com/google/oss-fuzz-vulns/pull/35#issuecomment-1586018930 clickable?

**Comment by evverx** [comment]
Just to expand on that. Currently the vulnerabilities check looks like
![OSV](https://github.com/ossf/scorecard/assets/10195800/f9cbd428-b0bd-4652-a576-288c9f73549e)

I think it would be nice if it was possible to click on OSV-2023-119 and ended up at https://osv.dev/vulnerability/OSV-2023-119. Links to GHAdvisories could probably be clickable too.

**Comment by evverx** [comment]
On second thought it probably has nothing to do with dashboards. Probably scorecard itself should produce links so that they could flow to its consumers like dashboards, SARIF stuff and so on.
