### ISSUE TITLE
Any plan for supporting other platform?

### ISSUE THREAD

**Issue by fredgan** [ossf/scorecard#2982]
As far as I know, now scorecard only support GITHUB.

Do we have any plan for supporting other platforms, such as GITLAB, [GITEE](https://gitee.com/)

**Comment by spencerschrock** [comment]
Gitlab support is tracked in #2266 and is working at an experimental stage.

I'd say support for other platforms would depend on usage, available API, etc.

**Comment by gabibguti** [comment]
Hey! Providing an update here, the latest version of Scorecard [v4.12.0](https://github.com/ossf/scorecard/releases/tag/v4.12.0) now supports GitLab repos by default.
