### ISSUE TITLE
Search: unsupported feature

### ISSUE THREAD

**Issue by darker008** [ossf/scorecard#2985]
**Describe the bug**

**Reproduction steps**
1. install scorecard a standalone
2. run scorecard with --local parameter

**Expected behavior**
get score of all checks

however got '?' of dependency-update-tool and vulnerabilities.
it prompts Error: check runtime error: internal error: search: unsupported feature, 

anyone can give suggestion?
thank you in advance

**Additional context**

**Comment by genos1998** [comment]
Is there a update on this one?
I too am facing the same issue

**Comment by spencerschrock** [comment]
> Is there a update on this one? I too am facing the same issue

Is this specifically for the Dependency-Update-Tool? This is partially expected, but could be improved.

I believe `Vulnerabilities` check should be working now locally.

**Comment by pnacht** [comment]
This could be "fixed" by improving the error message to clarify that Dependency-Update-Tool doesn't work with `--local` (and why).

**Comment by spencerschrock** [comment]
> This could be "fixed" by improving the error message to clarify that Dependency-Update-Tool doesn't work with `--local` (and why).

In this particular case, I think the answer is "don't worry about searching for commits" if the repo client doesn't have them.
