### ISSUE TITLE
make public data set available outside GCP

### ISSUE THREAD

**Issue by ctr49** [ossf/scorecard#2986]
**Is your feature request related to a problem? Please describe.**
I cannot access the public data because I do not have a Google account with GCP enabled. Having to create a (personal) Google Account, enabling GCP (which may result in fees) just to access public data is a bit odd. It also looks like accessing the free tier would give you 2-3 queries (per month?) only, which makes it unusable.

**Describe the solution you'd like**
The data set could also be published in GitHub as Git LFS object, workflow artifact, release item (depending on the size) or an S3-like object storage that gives raw access to the data or - ideally - made accessible through a web interface that allows queries.

**Comment by laurentsimon** [comment]
There is a REST API you can use https://github.com/ossf/scorecard#scorecard-rest-api. Would this work for your use case?
