### ISSUE TITLE
Integrate GitHub Actions Results into BigQuery Dataset

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#3041]
**Is your feature request related to a problem? Please describe.**
As part of our ongoing efforts to enhance the Scorecard project, we plan to integrate the results from GitHub Actions into our existing BigQuery (BQ) dataset. This integration will allow us to unify our datasets, providing a more comprehensive view of a project's security posture.

**Comment by spencerschrock** [comment]
Duplicate of #2558
