### ISSUE TITLE
Feature: re-visit the need for multiple RunScorecard function

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#3068]
See https://github.com/ossf/scorecard/pull/3048/files#r1202713060

**Comment by spencerschrock** [comment]
The function which inspired this issue, although [part of discussion](https://github.com/ossf/scorecard/pull/3048#discussion_r1202713060), wasn't part of the PR.

Closing as it's not directly needed anymore, although this may be related to #3717
