### ISSUE TITLE
Feature - Bi-Weekly call 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#307]
**Is your feature request related to a problem?

With lots of upcoming features have a bi-weekly call will help define drive the project to success.

**Comment by naveensrinivasan** [comment]
@inferno-chromium Thougths

**Comment by inferno-chromium** [comment]
SGTM, @azeemshaikh38 was already thinking to set up a call.

**Comment by naveensrinivasan** [comment]
Sounds good. Let’s keep this open till we have calendar set up.

**Comment by azeemshaikh38** [comment]
Assigning to myself for now. Will try and setup a call.

**Comment by azeemshaikh38** [comment]
This is now done. Closing.
