### ISSUE TITLE
Feature - Define Governance 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#308]
**Is your feature request related to a problem? 

We need to define governance. 

- How does one become a commiter?

- How does one become a owner?
- How does one become an approver ?

This will help new contributors understand the policies 

ref: https://github.com/ossf/scorecard/issues/1553

**Comment by justaugustus** [comment]
Closing in favor of https://github.com/ossf/scorecard/issues/1529, which has more activity.
