### ISSUE TITLE
BUG - dailyscore cronjob is down

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#310]
**Describe the bug**
The dailyscore cronjob is down.

![image](https://user-images.githubusercontent.com/172697/112781964-e1189980-9019-11eb-8388-9fa858a9de66.png)

**Additional context**
Part of the fix should include an integration test for cronjob to avoid this in the future PR's.

**Comment by oliverchang** [comment]
I just did a `kubectl apply -f cron.yaml` and it looks like this is running again.

**Comment by naveensrinivasan** [comment]
> I just did a `kubectl apply -f cron.yaml` and it looks like this is running again.

Ok. We still need to investigate as to why it was failing. 

Thanks for checking!

**Comment by oliverchang** [comment]
I think we just needed this step because we removed the command in https://github.com/ossf/scorecard/commit/688dc5e6c7076ece6cb297d560fa374522c289ee#diff-1d2cb5f4057a83f313e447611b0fd3c766fbb86d9946f0bfc2e003dc7250688e

The Kubernetes config was stale and still had the cron.sh reference prior to the `kubectl apply`.

**Comment by oliverchang** [comment]
(For the future, maybe we need to figure out some kind of email notification for these failures).

**Comment by naveensrinivasan** [comment]
> I think we just needed this step because we removed the command in [688dc5e#diff-1d2cb5f4057a83f313e447611b0fd3c766fbb86d9946f0bfc2e003dc7250688e](https://github.com/ossf/scorecard/commit/688dc5e6c7076ece6cb297d560fa374522c289ee#diff-1d2cb5f4057a83f313e447611b0fd3c766fbb86d9946f0bfc2e003dc7250688e)
> 
> The Kubernetes config was stale and still had the cron.sh reference prior to the `kubectl apply`.


 Cool!

**Comment by naveensrinivasan** [comment]
> (For the future, maybe we need to figure out some kind of email notification for these failures).

100% agree on that.

**Comment by naveensrinivasan** [comment]
Closing the issue as it is taken care of.
