### ISSUE TITLE
Evaluate applicability of Fuzzing check on GitLab repos

### ISSUE THREAD

**Issue by raghavkaul** [ossf/scorecard#3100]
This is a tracking issue to ensure this check works on GitLab repos.

To validate, the following must be complete:

- [x]  Check must run successfully (without errors) in nightly cron
- [ ]  Scores should be validated to make sure they generally align with the security practices of the repo (i.e. , should not be 0 when practices are clearly followed, or 10 if practices are clearly not).
- [x]  Major bugs/scoring issues should be fixed
- [x]  Minor parity differences between GitHub and GitLab clients should be documented in checks.yaml and tracked as separate issues

**Comment by raghavkaul** [comment]
In cron results, we haven't found really any GitLab repos that get a high score the Fuzzing check. It's unclear whether there are good Fuzzing options for GitLab repos.

**Comment by spencerschrock** [comment]
> In cron results, we haven't found really any GitLab repos that get a high score the Fuzzing check. It's unclear whether there are good Fuzzing options for GitLab repos.

There are GitLab repos as part of OSS-Fuzz, and the fuzzing checks (e.g. native or some property based library) that are language specific should work just fine regardless of where it's hosted. What requires a GitLab specific option?
