### ISSUE TITLE
Feature: Consider go vet a SAST tool

### ISSUE THREAD

**Issue by joycebrum** [ossf/scorecard#3128]
**Is your feature request related to a problem? Please describe.**
It seems that [go vet](https://pkg.go.dev/cmd/vet) is commonly used by go projects and it claims to statically analysis the code. I'd like to know if it could be considered a SAST tool and perhaps its use be identified by Scorecard tool.

**Describe the solution you'd like**
Understand whether go vet is indeed a SAST tool and if it can be identified by the Scorecard tool. To run, it seems they just use the `go vet` command or by running `go test` with go version >= 1.10.0.

Example: 

**Describe alternatives you've considered**
None.

**Additional context**
Codeql also covers Go projects, so this go vet would be another option for the maintainers to choose.

**Comment by laurentsimon** [comment]
Can you add this to a comment to https://github.com/ossf/scorecard/issues/2318? I think you can close the issue afterwards, since the other issue consolidates all the SAST tool for every language. Thanks!
