### ISSUE TITLE
Bug : ok-to-test action isn't working

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#316]
/ok-to-test sha=c3b949a

_Originally posted by @inferno-chromium in https://github.com/ossf/scorecard/issues/312#issuecomment-810441268_

**Comment by naveensrinivasan** [comment]
Without this, the confidence to merge any dependabot fixes/ PR's from external contributors becomes an issue. We would need to address this ASAP IMO. I am proposing this be included in our next Milestone.

@azeemshaikh38 @inferno-chromium

**Comment by azeemshaikh38** [comment]
I'm not sure I understand this bug fully. Maybe we can discuss this during our meet today?

**Comment by naveensrinivasan** [comment]
Some context 
https://github.com/imjohnbo/ok-to-test 
https://github.com/ossf/scorecard/blob/main/.github/workflows/ok-to-test.yml

**Comment by naveensrinivasan** [comment]
> I'm not sure I understand this bug fully. Maybe we can discuss this during our meet today?

Yes, let's discuss this.

**Comment by inferno-chromium** [comment]
this seems to work now, if yes close ?

**Comment by naveensrinivasan** [comment]
It is working. We can open it reoccurs.
