### ISSUE TITLE
Scorecard json filename is not zero padded anymore

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#323]
**Describe the bug**
gs://ossf-scorecards/4-1-2021.json instead of gs://ossf-scorecards/04-01-2021.json

**Reproduction steps**
this broke after move to go code for cron, need to sprintf with zero padding.

**Expected behavior**
gs://ossf-scorecards/04-01-2021.json

**Comment by naveensrinivasan** [comment]
Ok. Why is this an issue?

**Comment by inferno-chromium** [comment]
> Ok. Why is this an issue?

good to follow iso format like MM-DD-YYYY.json, right now it can be M or MM, D or DD
