### ISSUE TITLE
Discussion: Can probes exist without belonging to a check

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#3235]
The probes (experimental) currently need to belong to a check to be run. What is users need probes that don't fit into a check? Do we create a new check? Do we put all new probes into their own check? In this case, shall we "hide" these checks from the `--checks` option?

I think this will eventually be a case-by-case discussion. But it would be good to have a story. 

I'm currently thinking that if there's not obvious check for a new probe, we could have a fallback "special" check that contains all the probes and not exposed the check within the `--checks` option. This would also allow us to migrate probes to part of a public check once we think that probe(s) should be "promoted" to a public check (based on probe popularity, etc).

**Comment by Luckymhe** [comment]
Action importer.

**Comment by Luckymhe** [comment]
D

**Comment by spencerschrock** [comment]
This exists to some extent already. For the `Binary-Artifact` conversion (#3508), we ended up making two probes:
* `freeOfAnyBinaryArtifacts`
* `freeOfUnverifiedBinaryArtifacts`

Only `freeOfUnverifiedBinaryArtifacts` is hooked up, the other is disconnected from the `Binary-Artifact` check.

A similar situation will happen with some of the optional `Pinned-Dependencies` enhanced probes:
* https://github.com/ossf/scorecard/issues/2132#issuecomment-1871598574
* #2733 (this one may fit under `Dangerous-Workflows` too?)

I think the bigger question will be how raw data collection will work in these cases, as sometimes they use the same data (like `freeOfAnyBinaryArtifacts` above), but the two `Pinned-Dependencies` will need to fetch more data.

**Comment by spencerschrock** [comment]
Also linking #3840, which has me thinking about this again.

There is a CLI argument, `--probes`, which will run some probes. This would work for people that just want the data, but wouldn't handle arbitrary scoring decisions. Something like blank-imports/custom checks may be better suited for that (#3095)

## How to make it work
The initial implementation of `--probes` required setting up extra maps, and has fallen out of date. Ideally, this is setup in a way that keeps itself updated.

There's at least two piece of info we need:
* which raw data fields the probes need (right now, assumes 1:1 mapping)
https://github.com/ossf/scorecard/blob/fb3edd9d63f0c84858d88a65c47205676e330489/probes/entries.go#L195-L200
* which runner func the probe uses
https://github.com/ossf/scorecard/blob/fb3edd9d63f0c84858d88a65c47205676e330489/probes/entries.go#L158-L164

We can always use the same strategy from checks, which is an `init()` block which calls `registerCheck`:
https://github.com/ossf/scorecard/blob/fb3edd9d63f0c84858d88a65c47205676e330489/checks/all_checks.go#L57-L58

If we had a `registerProbe` func, we could presumably have all this data registration taken care of by the probes in the various `impl.go` files:
```go
func init() {
	// may not be able to use constants from checks package due to circular imports
	requiredRawData := []string{
		"Maintained", 
		"SAST",
	}
	supportedRequestTypes := []probes.RequestType{
		probes.CommitBased,
	}
	if err := registerProbe(Probe /* name */ , Run /* func */ , requiredRawData, supportedRequestTypes); err != nil {
		// this should never happen
		panic(err)
	}
}
```

This would also let us register supported request types (which relates to #3718).

**Comment by spencerschrock** [comment]
So I played around with this a little bit in a branch: https://github.com/spencerschrock/scorecard/tree/register-probes

the `init` approach would still require blank imports somewhere, as the probe packages which aren't hooked up to the evaluation code aren't loaded.
https://github.com/ossf/scorecard/blob/c940d9bcf025a2de1b73fd0e058b0a823881a3d9/probes/entries.go#L24-L25

**Comment by spencerschrock** [comment]
Partially completed via #3876, but #3718 may prevent this one from being closed.
