### ISSUE TITLE
Feature - Manage secrets for the cronjob

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#327]
**Is your feature request related to a problem? Please describe.**
Right now the secrets that are used for CronJob (GitHub Tokens) aren't managed within Git. It is Adhoc and manipulated directly. 

**Describe the solution you'd like**
One possible solution
1. Encrypt the  GitHub tokens with KMS keys using https://github.com/mozilla/sops
2. Store the tokens in GitHub
3. Decrypt it before deploying

**Comment by afmarcum** [comment]
This feature does not align with the short term project focus and has not had movement in some time.
If there is no feedback in the next 7 days to the contrary, then this issue will be closed.
