### ISSUE TITLE
Feature: Better logic to determine vulnerabilities

### ISSUE THREAD

**Issue by ajmalab** [ossf/scorecard#3334]
**Is your feature request related to a problem? Please describe.**
Scorecard returns a list of vulnerabilities that have been patched for a repository. This can be good or bad depending on the use-case. But since the scorecard API currently doesn't accept a particular version of a repository, it does not make sense to return vulnerabilities that may have existed on that repository at some point in time. 

A good example is the [postcss-modules-scope repo](https://github.com/css-modules/postcss-modules-scope). It gets a 0 for the Vulnerability check because of the ansi-regex vulnerability, which you can see has been patched. You will also see that the latest commit hash when queried via the osv API returns no vulnerabilities. However, passing the commit SHA to the ossf API still returns the same vulnerabilities. 

Without version granularity, the check is simply adding noise. 

**Describe the solution you'd like**
I don't know yet. Perhaps returning the version tags with the corresponding vulnerabilities? 

**Additional context**
[OSSF scorecard for the repo](https://api.securityscorecards.dev/projects/github.com/css-modules/postcss-modules-scope)
[Scorecard with the latest commit sha](https://api.securityscorecards.dev/projects/github.com/css-modules/postcss-modules-scope?commit=483e084cbd5e1991adef976f82ba559b0348ec0e)
Same package in Snyk that shows no vulnerabilities: https://snyk.io/advisor/npm-package/postcss-modules-scope

**Comment by spencerschrock** [comment]
> It gets a 0 for the Vulnerability check because of the ansi-regex vulnerability, which you can see has been patched

Can you clarify how/where it's patched? Scorecard uses https://github.com/google/osv-scanner for detection, which is parsing the `yarn.lock` file here:
https://github.com/css-modules/postcss-modules-scope/blob/master/yarn.lock#L650

```
ansi-regex@^5.0.0:
  version "5.0.0"
  resolved "https://registry.yarnpkg.com/ansi-regex/-/ansi-regex-5.0.0.tgz#388539f55179bf39339c81af30a654d69f87cb75"
  integrity sha512-bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==
```

Where https://github.com/advisories/GHSA-93q8-gq69-wqmw lists `5.0.0` as an affected version.

**Comment by ajmalab** [comment]
@spencerschrock Apologies, seems I misunderstood that point of this check. I was conflating repository vulnerabilities with published artifact vulnerabilities which don't always overlap. Closing this issue.
