### ISSUE TITLE
BUG - Add a check for GitHub tokens

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#334]
**Describe the bug**
If GitHub tokens are not set, the command gets stuck. Before calling the APIs, check if appropriate tokens are set. 

**Reproduction steps**
1. unset any GITHUB_AUTH_* flag in environment.
2. Run ./scorecard --repo=* command.

**Expected behavior**
If these tokens are not set, exit immediately and print message to inform user about how to remediate it.

**Comment by naveensrinivasan** [comment]
@laurentsimon This will be a good first issue. If you aren't working on it, can you remove the assignment?

**Comment by laurentsimon** [comment]
done.

**Comment by naveensrinivasan** [comment]
> done.

Thanks

**Comment by nanikjava** [comment]
@laurentsimon @naveensrinivasan Can you please assign this ticket to me ? interested to work on this. Thanks.

**Comment by naveensrinivasan** [comment]
> @laurentsimon @naveensrinivasan Can you please assign this ticket to me ? interested to work on this. Thanks.

I have assigned it.

**Comment by laurentsimon** [comment]
I actually think this is fixed and I forgot to close the issue:
```
2021/08/20 16:53:55 GitHub token env var is not set. Please read https://github.com/ossf/scorecard#authentication
exit status 1
```

**Comment by nanikjava** [comment]
@laurentsimon you are correct, tested out `main` branch and indeed it print out that message when `GITHUB_AUTH_TOKEN` is not specified. This ticket need to be closed.
