### ISSUE TITLE
Release: Scorecard 4.12

### ISSUE THREAD

**Issue by raghavkaul** [ossf/scorecard#3353]
**Is your feature request related to a problem? Please describe.**
Release Scorecard v4.12. This version of Scorecard supports GitLab repos by default. 

This release also adds preliminary support for the `scdiff` command which can be used to compare changes in Scorecard scores for a repository between versions of Scorecard, as well as probe support for the `Security-Policy` check. 

Finally, this release fixes scoring issues in the `Branch-Protection` and `Pinned-Dependencies` checks.

**Release Notes**
```
## New
* ✨ scdiff: normalize scorecard results by @spencerschrock in #3294 
* ✨ scdiff: generate cmd skeleton by @spencerschrock in #3275 
## Experimental
* ✨ [experimental] Probe support for security policy check by @laurentsimon in #3241 
## Bug Fixes
* 🐛 Fix Branch-Protection scoring by @gabibguti in #3251
* 🐛 Forgive job-level permissions by @pnacht in #3162 
* 🐛 Add npm installs to Pinned-Dependencies score by @gabibguti in #2960 
## Docs
* 📖 Add release process by @spencerschrock in #3322 
* 📖 Update GitHub documentation links by @martincostello in #3318
* 📖 Fixed slack badge on README by @eddie-knight in #3311
* 📖 update docs for webhooks documentation by @leec94 in #3299
* 📖 Add contributor ladder by @pnacht in #3246 
* 📖 Suggest new score viewer on badge documentation by @diogoteles08 in #3268 
* 📖 Update Branch-Protection admin and non-admin requirements by @gabibguti, @pnacht in #2772 
## New Contributors
* @aaguiarz made their first contribution in #3337
* @thepwagner made their first contribution in #3327
* @martincostello made their first contribution in #3318
* @eustas made their first contribution in #3267 
* @ajmalab made their first contribution in #3248 
```

**Comment by raghavkaul** [comment]
@naveensrinivasan @spencerschrock @laurentsimon Let me know if there are any release blockers here, or +1 if we are good to go. I'd like to get feedback by Monday if possible. Thanks!

**Comment by spencerschrock** [comment]
`scdiff` doesn't do any diffing currently, I wouldn't advertise it as preliminary support yet. Still very much WIP.

**Comment by spencerschrock** [comment]
Note: the goreleaser run failed. https://github.com/ossf/scorecard/actions/runs/5789763554

There are no release artifacts or provenance.

**Comment by raghavkaul** [comment]
The release assets were missing due to an error with signing the provenance ([job](https://github.com/ossf/scorecard/actions/runs/5789763554/job/15718314428)):

First error:
```
creating verifier: Get "https://token.actions.githubusercontent.com/.well-known/openid-configuration": dial tcp 13.107.42.16:443: i/o timeout
```

Followed by:
```
Run actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
Error: Input required and not supplied: path
```

I re-ran the job and it seemed to succeed ([job](https://github.com/ossf/scorecard/actions/runs/5789763554/job/15718446198)). Maybe a transient GitHub timeout?

Release assets should now be available: https://github.com/ossf/scorecard/releases/tag/v4.12.0
