### ISSUE TITLE
Add @gabibguti as triager

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3375]
I'm nominating @gabibguti for the triager role. Gabriela has been participating and contributing over the past year:
- [issues](https://github.com/ossf/scorecard/issues?q=is%3Aissue+author%3Agabibguti)
- [PRs](https://github.com/ossf/scorecard/pulls?q=is%3Apr+author%3Agabibguti+)

Following our [contributor ladder](https://github.com/ossf/scorecard/blob/9033d5149647fc72ae91429ac95df29ea9dd74ce/CONTRIBUTOR_LADDER.md):
- She has been active in the community for more than 3 months
- Is knowledgeable about the codebase, given her bug fixes and issues
- Has helped triaging previous issues. E.g.:
  - https://www.github.com/ossf/scorecard/issues/2838#issuecomment-1632673528
  - https://www.github.com/ossf/scorecard/issues/2639#issuecomment-1468307720
  - https://www.github.com/ossf/scorecard/issues/3220#issuecomment-1633092240
  
As mentioned in the contributor ladder, other @ossf/scorecard-maintainers may object, so I'll leave this issue open to allow time for comments.

**Comment by laurentsimon** [comment]
I'm supportive of welcoming @gabibguti to the team as triager

**Comment by raghavkaul** [comment]
Thanks @gabibguti for the contributions, I support this as well

**Comment by naveensrinivasan** [comment]
👍

**Comment by justaugustus** [comment]
+1 for me!!

**Comment by azeemshaikh38** [comment]
+1

**Comment by hythloda** [comment]
An excellent way to promote! They have been added.
