### ISSUE TITLE
Code coverage hit after updating to go1.21

### ISSUE THREAD

**Issue by justaugustus** [ossf/scorecard#3388]
We took a code coverage hit after updating to go1.21 in https://github.com/ossf/scorecard/pull/3387.
Not sure if this is a blip, but worth investigating.

## [Codecov](https://app.codecov.io/gh/ossf/scorecard/pull/3387?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ossf) Report
> Merging [#3387](https://app.codecov.io/gh/ossf/scorecard/pull/3387?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ossf) (9b7c9ae) into [main](https://app.codecov.io/gh/ossf/scorecard/commit/198aa963ebf52922dcd8ed9096e43b0b0ee6d3ab?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ossf) (198aa96) will **decrease** coverage by `6.22%`.
> The diff coverage is `n/a`.

<details><summary>Additional details and impacted files</summary>

```diff
@@            Coverage Diff             @@
##             main    #3387      +/-   ##
==========================================
- Coverage   74.30%   68.08%   -6.22%     
==========================================
  Files         178      175       -3     
  Lines       12876    12856      -20     
==========================================
- Hits         9567     8753     -814     
- Misses       2766     3593     +827     
+ Partials      543      510      -33     
```

</details>

_Originally posted by @codecov[bot] in https://github.com/ossf/scorecard/issues/3387#issuecomment-1677822921_

**Comment by spencerschrock** [comment]
This is due to e2e tests which run only on push to main, due to their use of a PAT. So all PRs currently show this 6% decrease, but have the higher coverage when merged.
cc @naveensrinivasan

**Comment by naveensrinivasan** [comment]
> This is due to e2e tests which run only on push to main, due to their use of a PAT. So all PRs currently show this 6% decrease, but have the higher coverage when merged. cc @naveensrinivasan

Yes, It is the case. I am closing it. Please reopen if you have concerns.
