### ISSUE TITLE
BUG - Project updates binary does not use GitHub Authentication

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#341]
**Describe the bug**
The https://github.com/ossf/scorecard/tree/main/scripts/update package does not use GitHub Authentication. This would slow down the updates.

**Expected behavior**
Change the implementation to include the GitHub Authentication when pulling source code from GitHub.

**Comment by afmarcum** [comment]
Does this bug still need to be addressed?
If there is no feedback in the next 7 days on whether this remains important for the project, then this issue will be closed.

**Comment by spencerschrock** [comment]
Closing as this functionality was removed in #3269.
