### ISSUE TITLE
Feature: Scorecard output should be human readable HTML

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#342]
**Is your feature request related to a problem? Please describe.**
This is after discussions with the Envoy team. Today, output of Scorecard command says Pass/Fail with confidence numbers. For someone new to Scorecard, this in itself wouldn't relay anything meaningful.  

**Describe the solution you'd like**
Instead, the output should be a detailed report mentioning what the tool tried to do and why the particular check failed. Providing clear reasons about failures and confidence values will let users decide if they care about fixing the failure and how they should go about fixing it.

**Comment by azeemshaikh38** [comment]
@inferno-chromium @asraa

**Comment by laurentsimon** [comment]
We can do this using the following:

1.  Update the checks.yaml to provide more information w.r.t the reasoning for having the check and details about how the check is made.
2.  Update the runtime information given by`--show-details`. Currently this command contains debug info. We can cleanup what we display to make it more user-readable and we can use the debug level to filter information (default would only contain information needed by a typical user; whereas debug could have everything)

Wdut?

**Comment by inferno-chromium** [comment]
> We can do this using the following:
> 
> 1. Update the checks.yaml to provide more information w.r.t the reasoning for having the check and details about how the check is made.
> 2. Update the runtime information given by`--show-details`. Currently this command contains debug info. We can cleanup what we display to make it more user-readable and we can use the debug level to filter information (default would only contain information needed by a typical user; whereas debug could have everything)
> 
> Wdut?

Azeem added some thoughts in another PR - https://github.com/ossf/scorecard/pull/347#discussion_r616364482

**Comment by azeemshaikh38** [comment]
I think the solution in https://github.com/ossf/scorecard/pull/347#discussion_r616364482 should cover this too. If you have thoughts/feedback about that approach, we can discuss more on the other thread.

Once we have a consensus on the solution, I'm happy if someone can take up the implementation of it. Since @naveensrinivasan already had a PR for this - I'll leave it upto @naveensrinivasan and @laurentsimon to decide how to proceed with the implementation.

**Comment by joycebrum** [comment]
How is it going the implementation of this issue? I've got another example of a maintainer requesting this feature https://github.com/systemd/systemd/issues/25042#issuecomment-1534899228

**Comment by laurentsimon** [comment]
nobody is working on it. Who is the consumer of the html result? deps.dev are working on better visualization, would it be enough?

**Comment by evverx** [comment]
That issue seems to have been abandoned in favor of deps.dev

**Comment by spencerschrock** [comment]
Just doing some issue cleanup.
Should have been resolved through https://github.com/ossf/scorecard-webapp/pull/406
