### ISSUE TITLE
The 'allowsDeletions' field requires one of the following scopes: ['public_repo']

### ISSUE THREAD

**Issue by fredgan** [ossf/scorecard#3427]
I build scorecard with the latest commit: b0a96fe9e3b42dffefcdf5d7959329d8de08a9fa

I run the command with `./scorecard --checks CII-Best-Practices,Branch-Protection,License,Vulnerabilities,Dangerous-Workflow,Token-Permissions,Code-Review,Packaging,Security-Policy,Signed-Releases,Dependency-Update-Tool,Pinned-Dependencies,Fuzzing,Binary-Artifacts,SAST,Maintained,CI-Tests,Contributors --format json --repo https://github.com/open-telemetry/opentelemetry-cpp`

The result is given normally except the following error:

> Error: check runtime error: Branch-Protection: internal error: error during branchesHandler.setup: internal error: githubv4.Query: Your token has not been granted the required scopes to execute this query. The 'allowsDeletions' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
> 2023/08/26 15:51:04 error during command execution: check runtime error: Branch-Protection: internal error: error during branchesHandler.setup: internal error: githubv4.Query: Your token has not been granted the required scopes to execute this query. The 'allowsDeletions' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

Why the `allowsDeletions` permission is needed to check the ProtectedBranches in the GithubToken?

**Comment by raghavkaul** [comment]
`allowDeletion` looks like the GitHub GraphQL field for checking whether a repository allows branches to be deleted - to get this from GraphQL, your GitHub PAT needs the `public_repo` scope ([readme](https://github.com/ossf/scorecard/#authentication)).

**Comment by spencerschrock** [comment]
> `allowDeletion` looks like the GitHub GraphQL field for checking whether a repository allows branches to be deleted - to get this from GraphQL, your GitHub PAT needs the `public_repo` scope ([readme](https://github.com/ossf/scorecard/#authentication)).

We should get a consistent recommendation across our repos.

For other alternatives, you can read about:
* [Fine-grained PATs](https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional)
* [The risk with `public_repo` scope](https://github.com/ossf/scorecard-action#classic-personal-access-token-pat-requirements-and-risks)
* Or just remove `Branch-Protection` from your list of `--checks`.

Note: We're hoping to get rid of the need for all this by supporting repository rules: (#3326 which is being implemented in #3354)

**Comment by fredgan** [comment]
I tried many composions of permissions. I found that the `repo` and `delete:packages` should be checked.

<img width="813" alt="image" src="https://github.com/ossf/scorecard/assets/3415532/6de2ba5b-a8ed-47e6-882e-8f91f7b67ac0">

**Comment by raghavkaul** [comment]
What error do you get when  the `delete:packages` permission is unchecked? Scorecard should never attempt to delete packages from GitHub Package Registry.

**Comment by fredgan** [comment]
@raghavkaul I know Scorecard won't delete packages. I think it should be the issue of Github PAT.

Now I try to reproduce this problem, it seems not as same as what occured at that time. Maybe it has been fixed by Github.

Now, just check `repo`-`public_repo` will be OK.
