### ISSUE TITLE
BUG: Didn't recognize BSD 3-Clause license as an FSF or OSI recognized license

### ISSUE THREAD

**Issue by diogoteles08** [ossf/scorecard#3441]
**Describe the bug**
At the License check, Scorecard is supposed to give a 9/10 to repositories that have a license file but have an license not recognized by FSF or OSI. Scorecard is giving a 9/10 to the project github.com/AcademySoftwareFoundation/openexr, but this project has a BSD 3-Clause license, which is listed on the [SPDX licenses list](https://spdx.org/licenses/)

**Reproduction steps**
1. Run the following command to run Scorecard on project github.com/AcademySoftwareFoundation/openexr
```
scorecard --repo=http://github.com/AcademySoftwareFoundation/openexr --checks=License --show-details --format=json | jq .
```
2. Note that the project scores 9/10, even though the project has a BSD 3-Clause license, as can be verified on [their readme](https://github.com/AcademySoftwareFoundation/openexr#license) and on their [license file](https://github.com/AcademySoftwareFoundation/openexr/blob/main/LICENSE.md).

**Expected behavior**
The project should receive a 10/10 on the License check

**Comment by diogoteles08** [comment]
cc @cary-ilm

**Comment by spencerschrock** [comment]
I believe this is a GitHub issue, they don't know what license it is:
```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/AcademySoftwareFoundation/openexr/license
```  



```
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  }
```

**Comment by spencerschrock** [comment]
It seems GitHub is pretty strict in their detection from the templates:

This diff seems to make things work, but no idea if this breaks anything on the repo's end:
```diff
@@ -1,5 +1,4 @@
-<!-- SPDX-License-Identifier: BSD-3-Clause -->
-<!-- Copyright (c) Contributors to the OpenEXR Project -->
+BSD 3-Clause License
 
 Copyright (c) Contributors to the OpenEXR Project. All rights reserved.
 ```

**Comment by gabibguti** [comment]
Scorecard is correctly detecting it was 10/10 for License now. As Spencer said, the SPDX license identifier lines were making GitHub not able to identify the license as BSD 3-Clause. Since they removed the SPDX license identifier lines, everything is working properly now.

https://securityscorecards.dev/viewer/?uri=github.com/AcademySoftwareFoundation/openexr

<img width="445" alt="image" src="https://github.com/ossf/scorecard/assets/27388955/5a7a2de3-3b94-4ce9-b5a0-5222b74f908e">
