### ISSUE TITLE
BUG: Fuzzing check doesn't detect OSS-Fuzz for GitLab repos

### ISSUE THREAD

**Issue by raghavkaul** [ossf/scorecard#3476]
**Describe the bug**
GitLab repos that are registered in OSS-Fuzz don't get Fuzzing credit in Scorecard.

Ex. libtiff in deps.dev: https://deps.dev/project/gitlab/libtiff%2Flibtiff

Has a project.yaml in oss-fuzz here: https://github.com/google/oss-fuzz/blob/master/projects/libtiff/project.yaml
But this repo gets 0/10 in the Fuzzing check.

**Comment by DavidKorczynski** [comment]
Do you need assistance with this? if so I can take a look, let me know.

**Comment by raghavkaul** [comment]
I have a fix in branch that I'm about to put up, thanks!

**Comment by Luckymhe** [comment]
> I have a fix in branch that I'm about to put up, thanks!

How to fix coins wallet,  can't access

**Comment by Luckymhe** [comment]
I'm running out of funds to continue.  This is self hosted. All coins generated from core is gone. My boss won't give me salary.  Checking out.

**Comment by Luckymhe** [comment]
Check out this acct.  I don't want to be a puppet. Action check out.

**Comment by Luckymhe** [comment]
Delete acct.  Stop using my acct and devices.  My azure cl cannot be access. So please just leave my acct alone. Closed this acct no merging.  Check out all acct.  Now you want me to create a new acct for SE.  Just for your stack exchange.
