### ISSUE TITLE
branch protection enhacement

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#349]
**Possible Improvements**
1. Increase the number of reviews needed to 2 (it's currently set to [1)](https://github.com/ossf/scorecard/blob/main/checks/branch_protected.go#L101). The code is duplicated in [code_review.go](https://github.com/ossf/scorecard/blob/main/checks/code_review.go#L110) and [branch_protected.go]: try to see if this is redundant or one of the checks should be removed.(https://github.com/ossf/scorecard/blob/main/checks/branch_protected.go#L101)
2. Require the main branch and the release branches to be protected (currently we only check the [default branch](https://github.com/ossf/scorecard/blob/main/checks/branch_protected.go#L35)). I don't think there is a standard way to detect release branches. We may use a simple regex to start with. We may also propose a standard (if it does not exist) and print it if `--who-details` is passed as arg.
3. Ensure the default branch is called `main` (it used to be `master`)
4. Think about what [contexts](https://docs.github.com/en/rest/reference/repos#statuses) we should look for in the [RequiredStatus check](https://github.com/ossf/scorecard/blob/main/checks/branch_protected.go#L93). Is there anything basic we can check (CI, travis, CircleCI, etc)?
5.  Auto dismissal of stale reviews (accepted but then changed) is [false by default](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection). True would be better. We currently don't check for it.

**Comment by inferno-chromium** [comment]
So, 2 reviews will be nice if the contributor is outside of organization where repo belongs to. [protects unilateral attacks]. when contributor is an in-org contributor, 1 seems fine from another in-org reviewer ?

agree on release branches.

@laurentsimon - try making these improvements or adding to your queue as you see fit.

**Comment by laurentsimon** [comment]
re: 2 reviews.for in-org contributor, 2 reviews may further reduce insider attacks, but agreed 1 review may be enough. To keep the code simple, we can start by having 2 reviews regardless of where contributors are?

**Comment by inferno-chromium** [comment]
> re: 2 reviews.for in-org contributor, 2 reviews may further reduce insider attacks, but agreed 1 review may be enough. To keep the code simple, we can start by having 2 reviews regardless of where contributors are?

if you put 2 reviews everywhere, that would fail on most repos, is that realistic expectation in most cases? basically we try to keep results realistic, otherwise scorecard will feel like enforcing strong policies people can agree upon. should get others thoughts too.

**Comment by laurentsimon** [comment]
sg. Let's keep it to 1 for cross-org then.

**Comment by laurentsimon** [comment]
Added point 4. Please comment if you have ideas.
Edited Point 1 about duplicated check. Please comment.

**Comment by naveensrinivasan** [comment]
>Ensure the default branch is called main (it used to be master)

This will be an issue, there are repositories where `development` is where the `PR` are targeted and the release branch is `master` or main. Deciding on the branch name for the `default` branch is hard and will give false results.

**Comment by naveensrinivasan** [comment]
> RequiredStatus check. Is there anything basic we can enforce?

These are subjective for each project and it is hard to check in a generic manner as it is `text` based.

**Comment by laurentsimon** [comment]
> > Ensure the default branch is called main (it used to be master)
> 
> This will be an issue, there are repositories where `development` is where the `PR` are targeted and the release branch is `master` or main. Deciding on the branch name for the `default` branch is hard and will give false results.

Please tell us if you already have numbers about false positives. This is a chance to enforce

**Comment by naveensrinivasan** [comment]
> > Ensure the default branch is called main (it used to be master)
> 
> This will be an issue, there are repositories where `development` is where the `PR` are targeted and the release branch is `master` or main. Deciding on the branch name for the `default` branch is hard and will give false results.

Here are some examples
https://github.com/smartcontractkit/chainlink
https://github.com/0xProject/0x-mesh/blob/master/CONTRIBUTING.md

**Comment by laurentsimon** [comment]
> > > Ensure the default branch is called main (it used to be master)
> > 
> > 
> > This will be an issue, there are repositories where `development` is where the `PR` are targeted and the release branch is `master` or main. Deciding on the branch name for the `default` branch is hard and will give false results.
> 
> Here are some examples
> https://github.com/smartcontractkit/chainlink
> https://github.com/0xProject/0x-mesh/blob/master/CONTRIBUTING.md

What's the common practice? Outliers are not necessarily a problem if the check is valid for the common cases of repos (`main` and `master` being default branch; with preference for `main`). We should be careful **not** to drop a check in favor of outliers if it can benefit the common case. That said, I have no idea about the distribution is ... :-)

I'm in favor of pulling some numbers and then decide if the gain is worth the loss. wdut?

Thanks for pointing this the potential problem, it's super useful!
