### ISSUE TITLE
BUG: Update branch protection documentation

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#350]
Branch protection result seems to always fail, even on a repo where some sort of branch protection is enabled. Maybe be due to the package we use that is out-of-sync with github APIs, though

**Reproduction steps**
Run `./scorecard --repo=github.com/laurentsimon/branch-protection-test --checks=Branch-Protection --show-details`
`error, retrying: GET https://api.github.com/repos/laurentsimon/branch-protection-test/branches/main/protection: 404 Not Found []`

even though the `Linear History` branch protection is enabled.

**Comment by naveensrinivasan** [comment]
The branch protection docs need to be updated. The branch protection checks would work only when you have admin access to the repository. That is the reason it is not used in the daily cron.

**Comment by naveensrinivasan** [comment]
related issue https://github.com/ossf/scorecard/issues/138
