### ISSUE TITLE
Confidence vs degree of protection

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#352]
We conflate `confidence` and `degree of protection`. Example:
- if we find a commit with no PR we have high confidence it's not branch-protected
- when we calculate confidence , e.g. for branch protection, we +1 for each sub test success. This seems to mean 'degree of protection' 

We should disambiguate the two.

**Comment by laurentsimon** [comment]
several teams are looking at using the results of scorecard, so let's make our results more consistent. Making this a q2 milestone.

**Comment by naveensrinivasan** [comment]
> several teams are looking at using the results of scorecard, so let's make our results more consistent. Making this a q2 milestone.

Who are the several teams? Could you please name some of them?

**Comment by laurentsimon** [comment]
Closing as we fixed this as part of using score-based results.
