### ISSUE TITLE
If I run scorecard on a private GitLab repo on a private GitLab server, does it send any information about my project elsewhere or will it just evaluate the project locally and share the results?

### ISSUE THREAD

**Issue by Jaycon80** [ossf/scorecard#3526]
If I run scorecard on a private GitLab repo on a private GitLab server, does it send any information about my project elsewhere or will it just evaluate the project locally and share the results?

_Originally posted by @flickerfly in https://github.com/ossf/scorecard/discussions/3428_

**Comment by Jaycon80** [comment]
https://github.com/ossf/scorecard/discussions/3428?sort=top#discussion-5564431

**Comment by raghavkaul** [comment]
Closing as duplicate/spam.
