### ISSUE TITLE
Security polices set at the organizational level in GitHub are not detected

### ISSUE THREAD

**Issue by cachedout** [ossf/scorecard#3579]
**Describe the bug**
Scorecard has a check to determine [whether or not a security policy has been defined for a repository](https://github.com/ossf/scorecard/blob/main/docs/checks.md#security-policy). 

While this works correctly if a repository contains a `SECURITY.md` file in its root, this is not the only sanctioned way to set a security policy on GitHub. Per [GitHub's documentation](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository#about-security-policies), it is also possible to add a `SECURITY.md` file to the `.github/` directory of an organization.

Take for example, [this repository](https://github.com/elastic/apm-server) which has a security policy [defined via the organization](https://github.com/elastic/.github) and is [displayed on the repository page](https://github.com/elastic/apm-server/security/policy).

**Reproduction steps**
1. Create a repo in a GitHub organization
2. Create a security policy in `.github/SECURITY.md` for the GitHub organization
3. Verify that the policy is displays on the repo page from step [1]
4. Run Scorecard against the repo and observe that it does not believe that a security policy is defined.

**Expected behavior**
See `Reproduction Steps`. Scorecard should detect cases where a repo has a security policy set at the organizational level in GitHub.

**Additional context**
None.

**Comment by spencerschrock** [comment]
Which version of Scorecard are you using? this works at the latest (v4.13.0) release:

```console
scorecard --repo elastic/apm-server --checks Security-Policy --show-details --format json | jq
{
  "date": "2023-10-17T13:26:12-07:00",
  "repo": {
    "name": "github.com/elastic/apm-server",
    "commit": "d145505fff81530e5467a3cbe1114722e8038faa"
  },
  "scorecard": {
    "version": "v4.13.0",
    "commit": "e1d3abc7fd2bdfe8819ac19b5c82815ea20890e6"
  },
  "score": 10,
  "checks": [
    {
      "details": [
        "Info: security policy file detected: github.com/elastic/.github/SECURITY.md:1",
        "Info: Found linked content: github.com/elastic/.github/SECURITY.md:1",
        "Info: Found disclosure, vulnerability, and/or timelines in security policy: github.com/elastic/.github/SECURITY.md:1",
        "Info: Found text in security policy: github.com/elastic/.github/SECURITY.md:1"
      ],
      "score": 10,
      "reason": "security policy file detected",
      "name": "Security-Policy",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/e1d3abc7fd2bdfe8819ac19b5c82815ea20890e6/docs/checks.md#security-policy",
        "short": "Determines if the project has published a security policy."
      }
    }
  ],
  "metadata": null
}
```

**Comment by cachedout** [comment]
You're absolutely right. This seems to be a bug in the way we're processing scorecard output and not the output itself. Apologies for the noise and thank you for the quick response!
