### ISSUE TITLE
investigate linter issues

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3602]
Some of these linter warnings aren't firing until after they're merged in. This probably has something to do with the only-new-issue aspect of the linter. Either in our settings or in the config file.

This happened more recently with https://github.com/ossf/scorecard/pull/3592 and 
https://github.com/ossf/scorecard/actions/runs/6620661284/job/17983463822

In the past, this PR (https://github.com/ossf/scorecard/pull/3558) introduced a linter issue that went unnoticed until it merged to main.

**Comment by spencerschrock** [comment]
It may have to do with the `only-new-issues` flag, which doesn't work with `push` events. I'm curious if it's necessary since our config has:

```
  new-from-rev: ""
```

**Comment by naveensrinivasan** [comment]
@spencerschrock Can this be closed?

**Comment by spencerschrock** [comment]
I think it's fine either way, but may as well keep it `only-new-issues`

if we keep it:
we still aren't blocking any PRs, it's just a matter of the linter failing after push to main, then it can be fixed whenever

if we remove it:
as long as it never breaks, we wont penalize anyone. but if it does, a PR author will need to fix the linter issues before their PR can be merged
