### ISSUE TITLE
Is there a way to influence a score by providing a proof of what's claimed as absent on a scorecard?

### ISSUE THREAD

**Issue by yrusskih** [ossf/scorecard#3626]
**Describe the bug**
A scorecard says that a project is missing certain security checks. While this is true in the context of GitHub, these checks exist outside of GitHub and we could provide you with a proof that they are there. Is there a way to influence a score if we provide you with a confirmation?

**Comment by spencerschrock** [comment]
Take a look at #1907, which is currently being designed and is on our roadmap.

Going to close this issue to favor discussion there.

**Comment by spencerschrock** [comment]
Of course, another alternative is to open a feature request if its something scorecard could possibly be expanded to detect. But we may advocate waiting for the maintainer annotation feature
