### ISSUE TITLE
findings: values should be exported consts owned by the probe

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3641]
All the places in our code that read values in a finding shouldn't need to redefine what the key is.

**Comment by AdamKorcz** [comment]
Could you write a short example for this?

**Comment by spencerschrock** [comment]
> Could you write a short example for this?

This came up in the SAST/Maintained checks:
Both the probe
https://github.com/ossf/scorecard/blob/6dd91c09975acc57cbac5d3640c7c7794a34dd8c/probes/commitsInLast90Days/impl.go#L62-L64
And then consumer (evaluation code) need to remember `"commitsWithinThreshold"`
https://github.com/ossf/scorecard/blob/6dd91c09975acc57cbac5d3640c7c7794a34dd8c/checks/evaluation/maintained.go#L65-L75

Not to mention all the tests:
https://github.com/ossf/scorecard/blob/6dd91c09975acc57cbac5d3640c7c7794a34dd8c/checks/evaluation/maintained_test.go#L37-L39


So if the probe defined the values it can produce (if known) as a const, then it creates a single source of truth for the key value. 

```go
const (
    Probe = "commitsInLast90Days"
    // I'm not set on the name
    CommitsValue = "commitsWithinThreshold" 
)
```
