### ISSUE TITLE
New check: Check to make sure build/artifact generation and signing is isolated from untrusted tools like coverage, testing

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#367]
E.g. detect things like https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512

**Comment by afmarcum** [comment]
This feature does not align with the short term project focus and has not had movement in some time.
If there is no feedback in the next 7 days to the contrary, then this issue will be closed.
