### ISSUE TITLE
Packages created from a monorepo are not properly analyzed

### ISSUE THREAD

**Issue by fhoeborn** [ossf/scorecard#3687]
**Describe the bug**
I wanted to analyze https://pypi.org/project/rouge-score/ with OSSF Scorecard, which fails apparently with a Timeout, as the linked repo is a folder inside a monorepo. Trying to analyze the referenced GitHub URL fails.

**Reproduction steps**
1. Run `scorecard --pypi rouge-score --show-details --checks Vulnerabilities`
2.  Scorecard tries to analyze the package, but never seems to return
3. Run `scorecard --repo https://github.com/google-research/google-research/tree/master/rouge --show-details --checks Vulnerabilities`
4. Scorecard fails with `error during command execution: RunScorecard: repo unreachable: GET https://api.github.com/repos/google-research/google-research/tree/master/rouge: 404 Not Found []`

**Expected behavior**
I would expect the analysis to analyze the provided path in the linked repo

**Comment by raghavkaul** [comment]
Possibly related to #3464

**Comment by spencerschrock** [comment]
Scorecard is intended to be run at the top level of the repository: e.g. 
```
scorecard --repo https://github.com/google-research/google-research --show-details --checks Vulnerabilities
```

So monorepos have always been problematic for us as some of our checks must be at the repo level, while some can be handled at the subfolder level. For a huge repo like `google-research/google-research`, Scorecard will scan all of the dependencies, and it's either found an infinite loop in our vuln scanning library (google/osv-scanner), or there's just a lot of them to process.

If you're just wondering about vulns in rouge, it's one of the checks that can be done locally:
```console
/tmp/google-research$ scorecard --local=rouge --checks Vulnerabilities --format json | jq
{
  "date": "2023-11-20T10:28:08-08:00",
  "repo": {
    "name": "file://rouge",
    "commit": "unknown"
  },
  "scorecard": {
    "version": "v4.13.0",
    "commit": "e1d3abc7fd2bdfe8819ac19b5c82815ea20890e6"
  },
  "score": 10,
  "checks": [
    {
      "details": null,
      "score": 10,
      "reason": "no vulnerabilities detected",
      "name": "Vulnerabilities",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/e1d3abc7fd2bdfe8819ac19b5c82815ea20890e6/docs/checks.md#vulnerabilities",
        "short": "Determines if the project has open, known unfixed vulnerabilities."
      }
    }
  ],
  "metadata": null
}
```

**Comment by arturfalcao** [comment]
Hey, is  there any update regarding this bug ?

**Comment by spencerschrock** [comment]
> Hey, is there any update regarding this bug ?

I've tried the repo again, and it does finish (although it takes almost 7 minutes). I would say Scorecard is working as intended, it's just that the repo being analyzed is large.

If the desire is to support analyzing a subset of the project, I'd recommend the `--local` approach.

**Comment by fhoeborn** [comment]
Yeah, can confirm this, needs some time, but comes up with results

**Comment by LappleApple** [comment]
Will open a new issue to clarify `--repo` flag and usage
