### ISSUE TITLE
BUG: Internal error when parsing Dockerfile on Pinned-Dependencies check

### ISSUE THREAD

**Issue by joycebrum** [ossf/scorecard#3692]
**Describe the bug**
When running the pinned dependencies check, a parsing error is occurring and no score is calculated. The error is because of this line [Dockerfile:1:184](https://github.com/joycebrum/tensorflow/blob/1c4a834715c5159771a8ad844dd23b096570da7b/ci/devinfra/docker_windows/Dockerfile#L184)

**Reproduction steps**
Versions: 4.10.2, 4.10.5 and 4.13.1
Last tensorflow commit that was running without error: `2bc270a640c17fffb865b225c9fc5d69e80c1dc9`
1. run `scorecard --repo=tensorflow/tensorflow --checks=Pinned-Dependencies`
2. output 
```
Starting [Pinned-Dependencies]
Finished [Pinned-Dependencies]

RESULTS
-------
Aggregate score: ?

Check scores:
|-------|---------------------|----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
| SCORE |        NAME         |                    REASON                    |                                             DOCUMENTATION/REMEDIATION                                              |
|-------|---------------------|----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
| ?     | Pinned-Dependencies | internal error: error parsing shell code:    | https://github.com/ossf/scorecard/blob/49c0eed3a423f00c872b5c3c9f1bbca9e8aae799/docs/checks.md#pinned-dependencies |
|       |                     | ci/devinfra/docker_windows/Dockerfile:1:184: |                                                                                                                    |
|       |                     | a command can only contain words and         |                                                                                                                    |
|       |                     | redirects; encountered (                     |                                                                                                                    |
|-------|---------------------|----------------------------------------------|--------------------------------------------------------------------------------------------------------------------|
Error: check runtime error: Pinned-Dependencies: internal error: error parsing shell code: ci/devinfra/docker_windows/Dockerfile:1:184: a command can only contain words and redirects; encountered (
2023/11/23 19:41:36 error during command execution: check runtime error: Pinned-Dependencies: internal error: error parsing shell code: ci/devinfra/docker_windows/Dockerfile:1:184: a command can only contain words and redirects; encountered (
```

**Expected behavior**
It was expected that the score could be calculated. The Dockerfile seems to be working well on tensorflow

**Comment by balteravishay** [comment]
This issue seems indeed related to supporting powershell in windows containers dockerfiles.
We see the same here: https://github.com/dotnet/runtime/blob/main/eng/docker/libraries-sdk.windows.Dockerfile

Info: Possibly incomplete results: error parsing shell code: & can only immediately follow a statement: eng/docker/libraries-sdk.windows.Dockerfile:17
Info: Possibly incomplete results: error parsing shell code: & can only immediately follow a statement: eng/docker/libraries-sdk.windows.Dockerfile:26

cc. @JonDouglas

@spencerschrock  should this be converted to a feature request?

**Comment by spencerschrock** [comment]
> @spencerschrock should this be converted to a feature request?

Would that just be #4253?

**Comment by balteravishay** [comment]
> > @spencerschrock should this be converted to a feature request?
> 
> Would that just be #4253?

right, I added to the feature description that it should also be supported in windows containers.

**Comment by spencerschrock** [comment]
I'll close this one in favor of #4253 which is already a feature request.
