### ISSUE TITLE
Enhance PullRequest feature

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#370]
1.  Code-Review discards commits made by bots with names `bot`  and `gardener` but only checks for their presence as substrings in the committer name. This is brittle, e.g.commits by user [abotas](https://github.com/abotas) would not be detected by the checks. I think we should use `==` instead.
2. Similarly, we check for reviews via gerrit by checking the presence of string `Reviewed-on:` in the commit message. Is there a better way? Is gerrit always used in combination with PRs?

**Comment by laurentsimon** [comment]
Update: I think gerrit uses status check APIs, and these are independent of the review messages. So this may be a signal we can rely upon work for non-malicious repos with malicious contributors.
If the repo is considered potentially malicious, that won't work unless we can uniquely identify gerrit (and its proper configuration). This seems to suggest the gerrit app would have to be run by github itself and github should attest that it's being run and enforced. I don't know if such a thing exist.

**Comment by afmarcum** [comment]
Does this bug still need to be addressed?
If there is no feedback in the next 7 days on whether this remains important for the project, then this issue will be closed.

**Comment by cpanato** [comment]
is this still relevant?

**Comment by afmarcum** [comment]
Reviewed during refinement and no longer relevant.

**Comment by LappleApple** [comment]
Reviewed during community backlog refinement and determined this is no longer relevant.
