### ISSUE TITLE
Add @diogoteles08 as triager

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3744]
I'm nominating @diogoteles08 for the triager role. Diogo has been participating and contributing over the past year:
- [issues](https://github.com/ossf/scorecard/issues?q=is%3Aissue+author%3Adiogoteles08)
- [PRs](https://github.com/ossf/scorecard/pulls?q=is%3Apr+author%3Adiogoteles08+)

Following our [contributor ladder](https://github.com/ossf/scorecard/blob/2ef20f17fb2e64147c83440cd2c769653454015a/CONTRIBUTOR_LADDER.md):
- He has been active in the community for more than 3 months
- Has knowledge about the codebase, given his bug reporting + contribution
- Has helped triaging previous issues. E.g.:
  - https://www.github.com/ossf/scorecard/issues/2444#issuecomment-1523890517
  - https://www.github.com/ossf/scorecard/issues/3075#issuecomment-1703152792
  - https://www.github.com/ossf/scorecard/issues/2850#issuecomment-1632950612
  
As mentioned in the contributor ladder, other @ossf/scorecard-maintainers may object, so I'll leave this issue open to allow time for comments. **Due to the holidays, this will remain open at least through the new year.**

**Comment by laurentsimon** [comment]
+1. Thanks for your contributions so far @diogoteles08 !

**Comment by raghavkaul** [comment]
Thanks for the contributions @diogoteles08!

**Comment by afmarcum** [comment]
Added @diogoteles08 as triager (invite sent).

**Comment by spencerschrock** [comment]
If you don't see the invite (others haven't been notified in the past), you can find it at https://github.com/orgs/ossf/invitation
