### ISSUE TITLE
de-duplicate SAST workflow scanning

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3745]
Between the 3 existing detected SAST tools, there's a lot of duplication:
https://github.com/ossf/scorecard/blob/2ef20f17fb2e64147c83440cd2c769653454015a/checks/raw/sast.go#L57-L75

(although `getSonarWorkflows` might be a special case?)

Especially as more tools are added (#3743 ), we shouldn't have the same code copy/pasted for each workflow detection. 

It seems like there's a common state for these github action detections:
mapping some SASTWorkflowType value (Snyk, ~~Sonar~~, CodeQL, etc) to some action regex: 

Snyk: strings.HasPrefix(action, "snyk/actions/")
CodeQL: `action == "github/codeql-action/analyze"`

so as regex maybe?
Snyk: "^snyk/actions/.*" (prefix)
CodeQL: "^github/codeql-action/analyze$" full match
qodona: "^JetBrains/qodana-action$" full match
pysa: "^facebook/pysa-action$" full match

**Comment by DavidKorczynski** [comment]
Added fix in https://github.com/ossf/scorecard/pull/3743
