### ISSUE TITLE
Add @leec94 as triager

### ISSUE THREAD

**Issue by leec94** [ossf/scorecard#3765]
I'm proposing to add myself @leec94 to the triager role. Caroline has been participating and contributing over the past year:

- [issues](https://github.com/ossf/scorecard/issues?q=is%3Aissue+author%3Aleec94)
- [PRs](https://github.com/ossf/scorecard/pulls?q=is%3Apr+author%3Aleec94)

Following our [contributor ladder](https://github.com/ossf/scorecard/blob/9033d5149647fc72ae91429ac95df29ea9dd74ce/CONTRIBUTOR_LADDER.md):

 - She has been active in the community for more than 3 months
 - Is knowledgeable about the codebase, given her bug fixes and issues
 - Has helped triaging previous issues. E.g.:
       - https://github.com/ossf/scorecard/issues/2157#issuecomment-1690704577
       - https://github.com/ossf/scorecard/issues/2158#issuecomment-1660942821
       - https://github.com/ossf/scorecard/issues/1024#issuecomment-1277722943

As mentioned in the contributor ladder, @ossf/scorecard-maintainers may object, so I'll leave this issue open to allow time for comments.

**Comment by spencerschrock** [comment]
Since the contributor ladder mentions a maintainer "sponsor", I'll volunteer for that role here. I was going to talk with @leec94 about this anyway, but she asked about it before I had a chance :)

**Comment by leec94** [comment]
Thank you @spencerschrock ! 😄

**Comment by laurentsimon** [comment]
+ from me. Thanks for your contributions @leec94!

**Comment by raghavkaul** [comment]
+1, thanks @leec94!

**Comment by afmarcum** [comment]
Added @leec94 as triager

**Comment by spencerschrock** [comment]
If you don't see the invite (others haven't been notified in the past), you can find it at https://github.com/orgs/ossf/invitation

**Comment by leec94** [comment]
I got and accepted the invite, should be all good now
