### ISSUE TITLE
Support the `.sigstore` bundle extension

### ISSUE THREAD

**Issue by edgarrmondragon** [ossf/scorecard#3771]
**Is your feature request related to a problem? Please describe.**

The [scorecard GH action](https://github.com/ossf/scorecard-action) is detecting that my last 5 releases don't have signed artifacts, though they do have `.sigstore` bundles.

**Describe the solution you'd like**

The `.sigstore` extension should flag a signed artifact.

**Describe alternatives you've considered**

Can't think of any 😅

**Additional context**

* https://github.com/sigstore/sigstore-python/issues/251

**Comment by laurentsimon** [comment]
Good catch. Done in https://github.com/ossf/scorecard/pull/3773/files
