### ISSUE TITLE
Add @ashearin as Triager

### ISSUE THREAD

**Issue by ashearin** [ossf/scorecard#3796]
I'm proposing to add myself @ashearin to the triager role. Allen has been participating and contributing over the past few months.

[issues](https://github.com/ossf/scorecard/issues?q=is%3Aissue+author%3Aashearin)
[PRs](https://github.com/ossf/scorecard/pulls?q=is%3Apr+author%3Aashearin+is%3Amerged)
Following our [contributor ladder](https://github.com/ossf/scorecard/blob/9033d5149647fc72ae91429ac95df29ea9dd74ce/CONTRIBUTOR_LADDER.md):

He has been active in the community for more than 3 months
Is knowledgeable about the codebase, given his bug fixes and issues.
As mentioned in the contributor ladder, @ossf/scorecard-maintainers may object, so I'll leave this issue open to allow time for comments.

**Comment by spencerschrock** [comment]
Happy to be the maintainer sponsor. Thanks for all the GitLab contributions, and attending the community meetings.

**Comment by afmarcum** [comment]
@raghavkaul @laurentsimon @justaugustus @naveensrinivasan Are we good to proceed with adding Allen as a triager?

**Comment by spencerschrock** [comment]
Allen was added to the org yesterday, and to the triage team today.
