### ISSUE TITLE
Feature: Rename OutcomePositive/Negative to something more aligned with the security implication of a probe finding

### ISSUE THREAD

**Issue by pnacht** [ossf/scorecard#3866]
**Is your feature request related to a problem? Please describe.**
`OutcomePositive/Negative` are big words for "yes" and "no". There have been various places/discussions requiring added logic to handle the fact that "yes" for one probe means it is safe, but for another probe it means it's dangerous (most recently, https://github.com/ossf/scorecard/pull/3816#discussion_r1483005286).

**Describe the solution you'd like**
Replace `OutcomePositive/Negative` (i.e. "yes"/"no") with "safe"/"unsafe": `OutcomeSafe/Unsafe`, `OutcomeGood/Bad`, etc.

I believe this will be more immediately legible: "ah, I don't even know what this probe is looking for, but apparently the project is safe from it!"

It may also simplify evaluation logic, since we don't need to special-case probes where `Positive` is a bad thing: `OutcomeGood` will always increase a project's score, `OutcomeBad` will always decrease it.

**Describe alternatives you've considered**
Probes could be renamed so that `OutcomePositive` always means it's safe. But this can lead to "negative" probe names (`doesNotDoX`), which doesn't follow the general coding principle that "variables" should be in the affirmative.

**Comment by spencerschrock** [comment]
See also: #3654
