### ISSUE TITLE
BUG: License LGPL-2.1-only not discovered

### ISSUE THREAD

**Issue by berndgassmann** [ossf/scorecard#3869]
**Describe the bug**
The license of our project LGPL-2.1-only seems not be recognized correctly; neither as FSF nor OSI.

**Reproduction steps**
see:
https://github.com/intel/ad-rss-lib/security/code-scanning/76

also a renaming of LICENSE file into LICENSE-LGPL-2.1-only didn't work
https://github.com/intel/ad-rss-lib/commit/1ffcf5af4dafaf187d10eddc80c6c6a300eb1327

nor adding the SPDX-License-Identifier: LGPL-2.1-only into the file:
https://github.com/intel/ad-rss-lib/commit/7258946e96d97881d6022f9f49009e34ca66ac79

**Expected behavior**
License score of 10 is expected instead of 9.

**Additional context**
Maybe your current setup only recognizes the LGPL-2.1, but LGPL-2.1-only as well as LGPL-2.1-or-later should both be detected as well.

**Comment by spencerschrock** [comment]
We currently rely on GitHub for license detection, and they don't seem to recognize it. 

https://api.github.com/repos/intel/ad-rss-lib
```
  "license": {
    "key": "other",
    "name": "Other",
    "spdx_id": "NOASSERTION",
    "url": null,
    "node_id": "MDc6TGljZW5zZTA="
  },
```

Although it should be within our ability to parse SPDX IDs, if present. Assuming that gets fixed (either on GitHub or our end), we'd need to update our list of FSF or OSI licenses. As `LGPL-2.1-only` should be on the list according to https://spdx.org/licenses
https://github.com/ossf/scorecard/blob/6fc7d4c061d2276fdf2427e40cd736e98598f476/checks/raw/license.go#L418-L419

Or, on the Scorecard Action side, we really shouldn't be complaining about that last 1 point:
https://github.com/ossf/scorecard-action/blob/0ae0fb3a2ca18a43d6dea9c07cfb9bd01d17eae1/policies/template.yml#L29-L31
This value would be better set to 6 or 9, depending on what we want to enforce.

**Comment by berndgassmann** [comment]
Hi,
thanks for the details here. If I understand it correctly, Github uses this one https://github.com/licensee/licensee to detect the license:
https://github.com/licensee/licensee/issues/631

**Comment by mlinksva** [comment]
@berndgassmann unrelated to https://github.com/licensee/licensee/issues/631. The reason https://github.com/intel/ad-rss-lib/blob/98991d6e5e51823c90b3d37a2fbb08cab360b37b/LICENSE can't be identified as LGPL-2.1 is due to differences in the text there (at a glance, prepended text and removal of the preamble) and the expected license text.

**Comment by berndgassmann** [comment]
@mlinksva Thank you very much for the support. The SPDX I had added recently in the hope that this will work out. Now I've copied the license code including preamble and now it's detected as valid license.
 Very much appreciated.

**Comment by pombredanne** [comment]
You should consider using a proper license detection tool, like scancode.
