### ISSUE TITLE
Searching for vuln reporting info outside of GH's security.md

### ISSUE THREAD

**Issue by annabellebertooch** [ossf/scorecard#39]
For the Security Policy field, some projects that use GitHub do have a documented security policy, but are not using the GitHub Security Policy feature, so scraping just for GH's Security Policy via security.md would inaccurately show a false in this field.

I think this is most commonly seen with projects that were established before the Security Policy feature, or for projects mirror to GitHub.

**Comment by inferno-chromium** [comment]
Please provide an example repo (and file path to policy).

**Comment by dlorenc** [comment]
Yeah, if you could point us at a few examples that would help!

**Comment by inferno-chromium** [comment]
We want to make this discoverable by people, so standardizing on github security policy makes sense here. we also support the default community health files as well. So closing, if you have examples, feel free to reopen.
