### ISSUE TITLE
BUG docs haven't been updated to say that Signed-Releases looks for `.sigstore` bundles.

### ISSUE THREAD

**Issue by cpswan** [ossf/scorecard#3914]
**Describe the bug**
#3772 introduced `.sigstore` to the Signed-Releases check but the [documentation](https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases) doesn't mention it.

**Reproduction steps**
1. Take a look at https://github.com/ossf/scorecard/blob/90a3708b19883d176d84dc23e3b399b53f1ee1e9/docs/checks.md?plain=1#L594-L597
2. Then https://github.com/ossf/scorecard/blob/90a3708b19883d176d84dc23e3b399b53f1ee1e9/probes/releasesAreSigned/impl.go#L38

**Expected behavior**
Documentation matches code

**Additional context**
Check doesn't seem to work as expected with `.sigstore` bundles #3913

**Comment by spencerschrock** [comment]
Are you interested in sending a PR? We have instructions for updating documentation:
https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#updating-docs
