### ISSUE TITLE
BUG: `pip install --upgrade pip` in Dockerfile gets flagged

### ISSUE THREAD

**Issue by duggalsu** [ossf/scorecard#3953]
**Describe the bug**
Running `RUN pip install --no-cache-dir --upgrade pip` in a Dockerfile gets flagged with `pipCommand not pinned by hash`. 

**Expected behavior**
The correct approach to doing `pip install` is to upgrade `pip` first, so this should ideally not be flagged.

**Comment by duggalsu** [comment]
Based on the following, it seems to be safe to pin `pip` and `setuptool`. I would suggest a good process would be to first update these as pinned packages from a base `requirements.txt` before doing any further `pip install`.
- https://github.com/jazzband/pip-tools/issues/806
- https://github.com/pypa/pip/issues/6459

**Comment by pdxjohnny** [comment]
It looks like this is because any pip install without a requirement.txt will trigger a pinning finding.
