### ISSUE TITLE
Add @LappleApple as triager

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#3962]
I'm nominating @LappleApple for the triager role. Lauri has been leading our backlog cleanup in our community meetings since December, so giving her the ability to label issues would be nice.
- [meeting notes](https://docs.google.com/document/d/1b6d3CVJLsl7YnTE7ZaZQHdkdYIvuOQ8rzAmvVdypOWM/edit?usp=sharing)

Following our [contributor ladder](https://github.com/ossf/scorecard/blob/b3ad602a5940f097a21601a78dd06a867ddfa46a/CONTRIBUTOR_LADDER.md#triagers):
- Has been active in the community for more than 1 month
- Has knowledge about the codebase (from a project management perspective)
- Has helped triaging previous issues during community meetings since December / January
  
As mentioned in the contributor ladder, other @ossf/scorecard-maintainers may object, so I'll leave this issue open to allow time for comments.

**Comment by laurentsimon** [comment]
+1 from me. Thank @LappleApple for the help!

**Comment by LappleApple** [comment]
Thank you thank you :)

**Comment by justaugustus** [comment]
Huge +1 from me!!

**Comment by raghavkaul** [comment]
+1, thank you for working with us through a challenging backlog @LappleApple !
