### ISSUE TITLE
CI-tests used in Ledmon project was not detected

### ISSUE THREAD

**Issue by ktanska** [ossf/scorecard#3976]
We are using github-actions but system didn't detect that.
Repo: https://github.com/intel/ledmon

**Comment by spencerschrock** [comment]
This doesn't match what I see using v4.13.1

```shell
scorecard --repo intel/ledmon --checks CI-Tests
Starting [CI-Tests]
Finished [CI-Tests]

RESULTS
-------
Aggregate score: 9.0 / 10

Check scores:
|--------|----------|--------------------------------|---------------------------------------------------------------------|
| SCORE  |   NAME   |             REASON             |                      DOCUMENTATION/REMEDIATION                      |
|--------|----------|--------------------------------|---------------------------------------------------------------------|
| 9 / 10 | CI-Tests | 16 out of 17 merged PRs        | https://github.com/ossf/scorecard/blob/main/docs/checks.md#ci-tests |
|        |          | checked by a CI test -- score  |                                                                     |
|        |          | normalized to 9                |                                                                     |
|--------|----------|--------------------------------|---------------------------------------------------------------------|
```

**Comment by ktanska** [comment]
![image](https://github.com/ossf/scorecard/assets/45432608/e36e2c91-d417-4b00-8007-3d14e91f785f)

Repo hasn't been checked from some reason.  If it is not reproducible, I will close it for now and wait for next quarter results.

**Comment by spencerschrock** [comment]
Does that dashboard run scorecard? or use the API?

In our weekly scan of public repos, the check is currently disabled because it's API hungry (with a long standing TODO: #1302). And disabled checks don't show up in the results (#3648)

**Comment by ktanska** [comment]
Looks like it is by scorecard.
![image](https://github.com/ossf/scorecard/assets/45432608/65d62e21-3cd7-44d1-94c3-9c17ce6ed146)
