### ISSUE TITLE
OpenSSF - CII Best Practices badge not detected

### ISSUE THREAD

**Issue by lprimak** [ossf/scorecard#3983]
**Describe the bug**
My project https://github.com/flowlogix/flowlogix has OpenSSF best practices badge: https://www.bestpractices.dev/en/projects/8431
However, it's not being picked up by OpenSSF Scorecard:
https://securityscorecards.dev/viewer/?uri=github.com/flowlogix/flowlogix

**Reproduction steps**
Check the links above

**Expected behavior**
OpenSS Scorecard should pick up Best Practices badge

**Additional context**
[github.com/flowlogix/flowlogix](https://github.com/flowlogix/flowlogix)
API URL: https://api.scorecard.dev/projects/github.com/flowlogix/flowlogix
COMMIT: d9303ad5c3ed034fbe831cf7bb0901bde5a05711
GENERATED AT: 2024-03-25
SCORECARD VERSION: v4.13.1-234-ge780e089

**Comment by spencerschrock** [comment]
The cron can take some time to propagate changes. If you recently got the passing badge, check again next week. 

I see the score using the CLI for example:
```shell
go run main.go --repo github.com/flowlogix/flowlogix --checks CII-Best-Practices
Starting [CII-Best-Practices]
Finished [CII-Best-Practices]

RESULTS
-------
Aggregate score: 5.0 / 10

Check scores:
|--------|--------------------|-------------------------|-------------------------------------------------------------------------------|
| SCORE  |        NAME        |         REASON          |                           DOCUMENTATION/REMEDIATION                           |
|--------|--------------------|-------------------------|-------------------------------------------------------------------------------|
| 5 / 10 | CII-Best-Practices | badge detected: Passing | https://github.com/ossf/scorecard/blob/main/docs/checks.md#cii-best-practices |
|--------|--------------------|-------------------------|-------------------------------------------------------------------------------|
```

**Comment by lprimak** [comment]
@spencerschrock Thanks!
That's just it. I passed the badge over 3 weeks ago and yet it still didn't detect it as o March 25th run.
```
SCORE
7.7/10
Scorecard as of March 25, 2024.
CII-Best-Practices 0/10
Determines if the project has an OpenSSF (formerly CII) Best Practices Badge.
REASONING
no effort to earn an OpenSSF best practices badge detected
```

**Comment by spencerschrock** [comment]
I'm not sure if there's any delay on the OpenSSF Best Practices side of things, but I just checked the `2024-04-01` run (which is still in progress) and I'm seeing a 5/10 score like the CLI says.

You should see it reflected in the Scorecard API in ~5 more days or so.

**Comment by lprimak** [comment]
Thank you, I'll check again.

**Comment by lprimak** [comment]
It was late but it worked. Thanks.
