### ISSUE TITLE
Expand to source repos outside of GitHub

### ISSUE THREAD

**Issue by kimsterv** [ossf/scorecard#40]
I suggest GitLab next.

**Comment by inferno-chromium** [comment]
For Google, a lot of repos live on googlesource.com, e.g. skia.googlesource.com, https://boringssl.googlesource.com/boringssl/ and they clone to github as well. Several results fail for them as they dont follow github processes like codereview, pull requests, etc.

**Comment by afmarcum** [comment]
Proposing this issue be closed and replaced by issues for individual source repos as they arise for specific needs as did with Gitlab. If there is no feedback in the next 7 days to the contrary, then this issue will be closed.
