### ISSUE TITLE
New check: Complain on binary artifacts in source repos, e.g. jars, esp for third_party use

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#400]
**Is your feature request related to a problem? Please describe.**
Third_party libraries might be checked in as binary artifact instead of building from source. These might be compromised artifacts, so discourage this bad security pattern.

**Describe the solution you'd like**
Check fail with details on binary artifacts used.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by laurentsimon** [comment]
Possible ideas:
- OS binaries: .o, .so, .ko, elf (Linux), same for Windows/Macos
- distro packages: .deb, .rpm, etc
- language packages: .whl, etc
- bytecode: .pyc, .jar

**Comment by naveensrinivasan** [comment]
Looking for file types with the extension could be one way. 


The right way to do it is to parse the file header and figure out the type. This is work has been done at https://github.com/h2non/filetype

We could start with this.
1. https://github.com/h2non/filetype#application
2. https://github.com/h2non/filetype#archive

I am not a fan of figuring based on extension alone without checking the contents of the file using the header. The confidence in our results would be higher we actually investigate the header which is done by `filetype`

Thoughts?

**Comment by inferno-chromium** [comment]
> Looking for file types with the extension could be one way.
> 
> The right way to do it is to parse the file header and figure out the type. This is work has been done at https://github.com/h2non/filetype
> 
> We could start with this.
> 
> 1. https://github.com/h2non/filetype#application
> 2. https://github.com/h2non/filetype#archive
> 
> I am not a fan of figuring based on extension alone without checking the contents of the file using the header. The confidence in our results would be higher we actually investigate the header which is done by `filetype`
> 
> Thoughts?

probably both. i think extensions is quick, but we should probably do libmagic based checking as well - https://man7.org/linux/man-pages/man3/libmagic.3.html [https://github.com/h2non/filetype is probably similar idea?]

**Comment by azeemshaikh38** [comment]
Similar idea to `filetype` and `libmagic` is `file -i` command in Unix. 

![image](https://user-images.githubusercontent.com/4825078/118322219-a37dac00-b4b3-11eb-8720-c9d2adb6f83b.png)

**Comment by naveensrinivasan** [comment]
> > Looking for file types with the extension could be one way.
> > The right way to do it is to parse the file header and figure out the type. This is work has been done at https://github.com/h2non/filetype
> > We could start with this.
> > 
> > 1. https://github.com/h2non/filetype#application
> > 2. https://github.com/h2non/filetype#archive
> > 
> > I am not a fan of figuring based on extension alone without checking the contents of the file using the header. The confidence in our results would be higher we actually investigate the header which is done by `filetype`
> > Thoughts?
> 
> probably both. i think extensions is quick (we should definitely start from this), but we should probably do libmagic based checking as well - https://man7.org/linux/man-pages/man3/libmagic.3.html [https://github.com/h2non/filetype is probably similar idea?]

We could do that. Crawl, Walk and Run. 

I am not a fan of libmagic because it brings other external dependencies which becomes an issue for our customers trying to run scorecard from their desktop and that was the reason for looking for something go native https://github.com/h2non/filetype repository.

**Comment by inferno-chromium** [comment]
> > > Looking for file types with the extension could be one way.
> > > The right way to do it is to parse the file header and figure out the type. This is work has been done at https://github.com/h2non/filetype
> > > We could start with this.
> > > 
> > > 1. https://github.com/h2non/filetype#application
> > > 2. https://github.com/h2non/filetype#archive
> > > 
> > > I am not a fan of figuring based on extension alone without checking the contents of the file using the header. The confidence in our results would be higher we actually investigate the header which is done by `filetype`
> > > Thoughts?
> > 
> > 
> > probably both. i think extensions is quick (we should definitely start from this), but we should probably do libmagic based checking as well - https://man7.org/linux/man-pages/man3/libmagic.3.html [https://github.com/h2non/filetype is probably similar idea?]
> 
> We could do that. Crawl, Walk and Run.
> 
> I am not a fan of libmagic because it brings other external dependencies which becomes an issue for our customers trying to run scorecard from their desktop and that was the reason for looking for something go native https://github.com/h2non/filetype repository.

+1, native is better.
https://www.reddit.com/r/golang/comments/amt07f/h2nonfiletype_small_dependencyfree_and_blazing/

> 
> Edit - Any os dependent filetype checks are an issue especially when we are providing a binary for our customers to use,

**Comment by naveensrinivasan** [comment]
I will take on this.

**Comment by naveensrinivasan** [comment]
Going to take the file names with extensions for v1 of this implementation. Let me know if anyone sees that as an issue.

**Comment by inferno-chromium** [comment]
> Going to take the file names with extensions for v1 of this implementation. Let me know if anyone sees that as an issue.

lets discuss this in today's meeting with @azeemshaikh38 @laurentsimon

**Comment by naveensrinivasan** [comment]
> > Going to take the file names with extensions for v1 of this implementation. Let me know if anyone sees that as an issue.
> 
> lets discuss this in today's meeting with @azeemshaikh38 @laurentsimon

Sounds good.

**Comment by inferno-chromium** [comment]
fixed, closing.
