### ISSUE TITLE
Frozen Deps does not check frozen dockerfile image use, CI/CD tools

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#403]
**Is your feature request related to a problem? Please describe.**
1) Check for either hardcoded sha in FROM.*dockerfile use or best to see if signature verification happens (with sigstore)
2) for CI/CD discourage bad patterns, e.g. curl | bash

**Describe the solution you'd like**
Improve frozen deps check to account for these.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by inferno-chromium** [comment]
Needs documentation update as well.

**Comment by dlorenc** [comment]
Here's one tool to help pin Dockerfiles: https://github.com/safe-waters/docker-lock

Another WIP one, designed to help with signatures: https://github.com/sigstore/cosign/pull/189

**Comment by laurentsimon** [comment]
1 is done as #469 
2 `(curl | bash)` is going to take a little bit more work. We'll use [shellcheck](https://www.shellcheck.net/) for shell scripts, I think. We need to check bad patterns not only in shell scripts, but also in makefiles, and even in code `system(...)`, `os.popen()`, so we need some language support for this one.
I'll start with shell script.

**Comment by inferno-chromium** [comment]
> 1 is done as #469
> 2 `(curl | bash)` is going to take a little bit more work. We'll use [shellcheck](https://www.shellcheck.net/) for shell scripts, I think. We need to check bad patterns not only in shell scripts, but also in makefiles, and even in code `system(...)`, `os.popen()`, so we need some language support for this one.
> I'll start with shell script.

+1 shell script is a good start.

**Comment by laurentsimon** [comment]
@inferno-chromium @oliverchang @naveensrinivasan I'm starting to work on `2. repo clones without pinning, e.g. from github.`
I worry this is going to throw false positives whenever CI/CD runs integration tests or releases - scripts will fetch the latest code. So I'm thinking of detecting if the `git clone reponame` is for the same repo scorecard is analyzing or not.
WDUT?

**Comment by inferno-chromium** [comment]
> @inferno-chromium @oliverchang @naveensrinivasan I'm starting to work on `2. repo clones without pinning, e.g. from github.`
> I worry this is going to throw false positives whenever CI/CD runs integration tests or releases - scripts will fetch the latest code. So I'm thinking of detecting if the `git clone reponame` is for the same repo scorecard is analyzing or not.
> WDUT?

you mean catching cases of building from source where people use just trunk and no pinned version/hash. i am expecting this will be crazy ton of false positives? which usecase example where you thinking to solve?

**Comment by laurentsimon** [comment]
correct. I've seen this sort of bugs caught in reviews where the Makefiles would just pull sources from various repos, e.g. `git clone _some_repo_`. I also expect there will be false positives due to genuine cases. Let's shelve this repo chekc for now then?

**Comment by inferno-chromium** [comment]
> correct. I've seen this sort of bugs caught in reviews where the Makefiles would just pull sources from various repos, e.g. `git clone _some_repo_`. I also expect there will be false positives due to genuine cases. Let's shelve this repo check for now then?

yes, but lets file a seperate issue to track this, seems important to think more on this.
