### ISSUE TITLE
update the SPDX license list

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#4031]
As noticed in https://github.com/ossf/scorecard/pull/3838#discussion_r1515142816 (which I'm noticing know is wrong because `Beerware` shouldn't be on out list in the sense of FSF or OSI approved), the SPDX list seems to have fallen out of date and could be refreshed. The list was added ~2 years ago (via #2442) and we're probably missing a few entries.

https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/checks/raw/license.go#L399-L418

**Comment by lelia** [comment]
I can work on this

**Comment by spencerschrock** [comment]
@lelia are you still interested in this?

**Comment by lelia** [comment]
> [@lelia](https://github.com/lelia) are you still interested in this?

Yeah, sorry got sidetracked with some other priorities, but I did generate a new map of updated licenses a while back. I was holding off on making a contribution so we could have a more sustainable solution going forward, but I could always split the contribution into two parts.

**Comment by spencerschrock** [comment]
> I was holding off on making a contribution so we could have a more sustainable solution going forward, but I could always split the contribution into two parts.

At the time, I had thought stale data was part of the cause for #4144, but that wasn't the case. So there isn't a time critical part of this

**Comment by bagder** [comment]
Our project which is 100% REUSE compliant (every single file clearly shows copyright and license) does not score full on **License** by the scorecard because of this problem.

**Comment by spencerschrock** [comment]
> Our project which is 100% REUSE compliant (every single file clearly shows copyright and license) does not score full on **License** by the scorecard because of this problem.

While the issue is closed, it wasn't the root cause for the scoring.

1. We rely on GitHub for license type detection. https://api.github.com/repos/curl/curl/license doesn't identify the `curl` license, but rather `NOASSERTION`
2. The check (as written) awards the last point for "FSF Free/Libre" or "OSI Approved" licenses. An issue or discussion around changing this behavior in favor of REUSE or some other metric (originally just having a LICENSE file was a full score) is a valid discussion, it's just unrelated to this issue.

**Comment by bagder** [comment]
Okay. I'm a little disappointed that the aspirations aren't higher but I'll live.
