### ISSUE TITLE
Cleanup old error names before full v5 release

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard#4033]
We have a few linter exceptions around old errors which don't follow the naming conventions enabled in #3587.

It would be good to take care of the `//nolint:errname` directives while we're doing breaking changes.

https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/errors/public.go#L31-L41

https://github.com/ossf/scorecard/blob/0b9dfb656f1796c7c693ad74f5193657b6a81e0b/cron/config/config.go#L61-L70

**Comment by cmwylie19** [comment]
can you please assign this to me?

**Comment by laurentsimon** [comment]
@cmwylie19  the issue is assigned to you. Welcome!
