### ISSUE TITLE
BUG: Code-Review missing review markers

### ISSUE THREAD

**Issue by emaste** [ossf/scorecard#4038]
**Describe the bug**
Code-Review misses review indicators used by FreeBSD.

**Reproduction steps**
1. Inspect Code-Review for freebsd-src https://securityscorecards.dev/viewer/?uri=github.com/freebsd/freebsd-src
2. Review recent FreeBSD commits https://github.com/freebsd/freebsd-src/commits/main/
3. Observe `Reviewed by:` tags and/or Phabricator URLs indicating review took place, e.g. https://github.com/freebsd/freebsd-src/commit/1b7487592987c91020063a311a14dc15b6e58075

**Expected behavior**
- Match `Reviewed by:` as a synonym for `Reviewed-by:` as evidence of review
- Consider following Phabricator review links and extracting review state

**Additional context**
I suspect FreeBSD may be one of the more significant remaining open source users of Phabricator, and for us review evidence should be included in the commit message directly (via `Reviewed by:`). It may or may not be worth the effort to parse Phabricator state for other projects that use Phabricator and do not indicate the review state in the commit message. LLVM used to be an example of such a project, but they use a completely GitHub-based workflow now.

**Comment by spencerschrock** [comment]
We do try and detect Phabricator review links:
https://github.com/ossf/scorecard/blob/71aed951f99eba4e84737895c1251e295f5b71e5/checks/raw/code_review.go#L95-L105

Where the regex we currently use is:
https://github.com/ossf/scorecard/blob/71aed951f99eba4e84737895c1251e295f5b71e5/checks/raw/code_review.go#L27-L28

I see many commits with content like:
```
Differential Revision: https://reviews.freebsd.org/D44814
Differential Revision: https://reviews.freebsd.org/D44815
```

We do get matches on some of the commits, including https://github.com/freebsd/freebsd-src/commit/1b7487592987c91020063a311a14dc15b6e58075

```
2024/04/30 13:26:54 1b7487592987c91020063a311a14dc15b6e58075 {Phabricator https} Phabricator https
```

But our regex doesn't handle the link, so all of these changes count as 1 revision ("https"). So unrelated commits are getting grouped as one, leading to an under reporting of freebsd's code review practices.

**Comment by emaste** [comment]
Phabricator wants the full URL for auto-closing - see e.g. LLVM's (now obsolete) Phabricator documentation: https://releases.llvm.org/14.0.0/docs/Phabricator.html, so the regex should be changed to match any non-space characters.

**Comment by spencerschrock** [comment]
What do you think about:
```
Differential Revision:[^\r\n]*(D\d+)
```

So it matches the D### on the same line as `Differential Revision`

**Comment by emaste** [comment]
That RE lgtm, and 16/29 seems plausible for the fraction of recent commits with evidence of review based on a quick look in the repo.

**Comment by emaste** [comment]
I'm curious how multiple commits with the same phabricator review link are handled, though -- it's possible that the same code review may be shared by multiple commits (e.g., there may be a bugfix and new functionality that are closely related and make sense to review altogether, but the two parts are committed separately).

**Comment by spencerschrock** [comment]
> I'm curious how multiple commits with the same phabricator review link are handled, though -- it's possible that the same code review may be shared by multiple commits (e.g., there may be a bugfix and new functionality that are closely related and make sense to review altogether, but the two parts are committed separately).

Under the hood they get grouped into the same changeset, in this case by Phabricator revision ID

https://github.com/ossf/scorecard/blob/b9c1f3fc7ac7ce91e582cd5b27537171496ec522/checks/raw/code_review.go#L155-L175


So if you have 4 commits, 2 of which come from the same Phabricator review, and 2 commits which don't have reviews.

this will get grouped into 3 groups, (phabricator revision, unreviewed commit 1, unreviewed commit 2), and be considered 1/3 reviewed.

**Comment by spencerschrock** [comment]
The commit you linked has two linked reviews:
```
Differential Revision: https://reviews.freebsd.org/D44814
Differential Revision: https://reviews.freebsd.org/D44815
```

I think the regex would only associate it with `D44814`, but either way it counts as reviewed
