### ISSUE TITLE
BUG: Patch Maintainers Annotations

### ISSUE THREAD

**Issue by gabibguti** [ossf/scorecard#4048]
**Describe the bug**
Some things still need to be addressed in Maintainers Annotation feature (regarding PR https://github.com/ossf/scorecard/pull/3905):

- [X] In checker/check_result.go, rename IsExempted to Annotations (https://github.com/ossf/scorecard/pull/3905#discussion_r1548354284)
- [X] In config/annotations.go, change IsValidReason to private method as isValidReason (https://github.com/ossf/scorecard/pull/3905#discussion_r1548364147).
- [x] similarly, these errors can probably be private? https://github.com/ossf/scorecard/blob/19f8ae107daead9d25f3f7406f00a206bcd17eef/config/config.go#L28-L31
- [ ] Clarify the desired types for annotations. Define if Paths should be under a Reason or under an Annotation and same thing for Probes. We need to understand the better way for users to fill in the annotations (https://github.com/ossf/scorecard/pull/3905#discussion_r1530869510).
- [x] Define if one invalid check or reason during the config parsing should invalidate the whole config, or if it should be logged and skipped (https://github.com/ossf/scorecard/pull/3905#discussion_r1530857745 and https://github.com/ossf/scorecard/pull/3905#discussion_r1548411138).
- [X] Define if in the case a check is annotated it should not be removed from SARIF result `runs`. Or, if is working as expected and we should not populate `runs` if there are no relevant `results` for that check (https://github.com/ossf/scorecard/pull/3905#issuecomment-2030613931).
- [X] Do we need to pass in checks here? Also this **doesn't work if you only run a subset of checks but there's an annotation for a check which isn't being run**. https://github.com/ossf/scorecard/blob/19f8ae107daead9d25f3f7406f00a206bcd17eef/config/config.go#L73-L74
- [ ] Closing the file with t.Cleanup which is opened here: https://github.com/ossf/scorecard/blob/19f8ae107daead9d25f3f7406f00a206bcd17eef/config/config_test.go#L134-L138
- [X] Make all output format options pointers for consistency?  AsJSON2, AsString, etc: https://github.com/ossf/scorecard/blob/19f8ae107daead9d25f3f7406f00a206bcd17eef/pkg/json.go#L131-L134
- [x] Support more config file locations (e.g. `.scorecard.yml`, `.github/.scorecard.yml`, ...)
- [X] Update the config README, it uses outdated yaml tags / values. 
  - [X] Document config file locations

**Comment by gabibguti** [comment]
Related to: https://github.com/ossf/scorecard/issues/1907

**Comment by raghavkaul** [comment]
>  Do we need to pass in checks here? Also this doesn't work if you only run a subset of checks but there's an annotation for a check which isn't being run.
Yes, but there's an import cycle b/w `checks` and `config` which means we can't use `checks.GetAll` in this file. Looking into this.

> Define if one invalid check or reason during the config parsing should invalidate the whole config, or if it should be logged and skipped.
I think this should be all-or-nothing: maintainers should validate the annotation file by running scorecard on their repo locally before committing it. Closing.

When might a valid annotation file become invalid over time?
* valid reason is removed
* check is removed
Neither of these cases is typical.

**Comment by spencerschrock** [comment]
> * Define if in the case a check is annotated it should not be removed from SARIF result `runs`. Or, if is working as expected and we should not populate `runs` if there are no relevant `results` for that check

Based on this comment, I think the runs field should continue to be populated:
https://github.com/ossf/scorecard/blob/9cd1fb868d5bc2a2f4d16012c692feeadd88b26e/pkg/sarif.go#L644-L649
