### ISSUE TITLE
Unexpected fail of Signed-Tags check

### ISSUE THREAD

**Issue by bkimminich** [ossf/scorecard#41]
The scorecard on `bkimminich/juice-shop` gives this result:

```
RESULTS
-------
Active: Pass 10
CI-Tests: Pass 10
CII-Best-Practices: Pass 10
Code-Review: Fail 10
Contributors: Pass 10
Frozen-Deps: Fail 5
Fuzzing: Fail 3
Pull-Requests: Pass 7
SAST: Pass 8
Security-Policy: Pass 10
Signed-Releases: Fail 10
Signed-Tags: Fail 9
```

I get the `Code-Review` and `Fuzzing` fails, but not the `Signed-Tags` fail:

![image](https://user-images.githubusercontent.com/3531020/98022690-33a4af80-1e06-11eb-807e-91b1c2b82018.png)

All releases (of the last 2+ years at least) are based on signed tags. ~~And since 1 year+ all releases have MD5 signatures of all artifacts as well as artifacts themselves, so the `Signed-Releases` fail seems also unexpected:~~

![image](https://user-images.githubusercontent.com/3531020/98022941-89795780-1e06-11eb-9151-04176031180e.png)

**Comment by inferno-chromium** [comment]
Signed-releases is failing since it is missing signature file - https://github.com/ossf/scorecard/blob/main/checks/signed_releases.go#L49
asc, sig are usual formats for these, see https://wiki.debian.org/Creating%20signed%20GitHub%20releases
md5 is just checksum, not signature file.

Signed-tags is something @dlorenc can look into. when i run with --show-details, only one signed tag is found via api: v11.1.2, commit: dc428cf36d647356de7d44110ddb292250d71704, not the v12 ones.

**Comment by bkimminich** [comment]
Ah, my bad on the tagged releases... one down, one to go. Here at least the GitHub web UI is on my side... 😁

**Comment by dlorenc** [comment]
I reprod this, we must be doing something wrong with the API. I'm seeing this in the results:

- We call ListTags to get all the tags then iterate through them.
- We lookup the commit corresponding to each tag.
- For the first tag here [v12.1.1](https://github.com/bkimminich/juice-shop/releases/tag/v12.1.1), we see commit f43b0444f3d2e49544a1a5084a50ab24e5c41c46
- We then fetch that commit and check the Verification on it. The verification here is 'false' with a reason of 'unsigned'.

**Comment by dlorenc** [comment]
This looks to be the issue here: https://github.community/t/is-there-an-api-to-get-a-single-tag-by-its-tag-name/126107

The "ListTags" API returns a list of tags with names and the commit the tag points at, but does not return the tag sha itself.

The API call to Get a tag requires the tag sha.

**Comment by dlorenc** [comment]
OK, figured this out. Unfortunately the GraphQL API allows you to retrieve the tag_sha, but does not allow you to check the verification status of that tag. So we need to use both APIs here after all.

**Comment by bkimminich** [comment]
`Signed-Tags: Pass 10` looks good now, thanks!
