### ISSUE TITLE
Add @lelia as triager

### ISSUE THREAD

**Issue by lelia** [ossf/scorecard#4136]
I'm nominating myself for the triager role. I have been an active participant in and facilitator of Scorecard community meetings for the past ~6 months, most recently doing work on issue triage, label cleanup, survey feedback and persona development.

* [meeting notes](https://docs.google.com/document/d/1b6d3CVJLsl7YnTE7ZaZQHdkdYIvuOQ8rzAmvVdypOWM/edit?usp=sharing)

Following our [contributor ladder](https://github.com/ossf/scorecard/blob/b3ad602a5940f097a21601a78dd06a867ddfa46a/CONTRIBUTOR_LADDER.md#triagers):

* Have been active in the community for more than 1 month
* Have reported issues / feedback on various Scorecard projects, contributed to Scorecard Monitor
* Have knowledge about the codebase (from a technical and project management perspective)
* Have actively participated in community meetings since January

cc: @spencerschrock @justaugustus

**Comment by justaugustus** [comment]
I am recused from sponsorship, given @lelia is my direct report.

Tagging @ossf/scorecard-maintainers @jeffmendoza for sponsorship!

**Comment by spencerschrock** [comment]
I can be the sponsor. Thanks Lelia for your help managing the issues and survey data

**Comment by justaugustus** [comment]
(Assigned to @spencerschrock and put this on today's agenda for discussion.)

**Comment by raghavkaul** [comment]
+1, thank you Lelia!

**Comment by jeffmendoza** [comment]
+1

**Comment by justaugustus** [comment]
Welcome to @ossf/scorecard-triagers, Lelia!
