### ISSUE TITLE
New check: reduce scope of git token permission

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#414]
Github workflows rely on events (e.g. pull_request, etc). The default permission for the token is read/write. In most cases, read permission should be enough. To reduce the attack surface, we should check for this. We'll need to have a list of actions that we allow to use read permissions.

This is a good candidate for a status check as well.

**Comment by laurentsimon** [comment]
Ideally we'd try to check this [default github token permission setting](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository) and ensures it's set to read only.

Later, we can also verify that repo-specific workflows are not given additional write permission if it's not needed.

**Comment by laurentsimon** [comment]
More information https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ and https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token

**Comment by laurentsimon** [comment]
After a bit of digging/reading, here are some potential options:

1. Check for the settings: I have not found an API to retrieve this. @naveensrinivasan have you seen one?
(In addition, we can parse the workflow config to ensure most workflows don't override it with write permission?)
2. Check if `permission` is declared in workflow yaml files. We could parse it and check that most of them are unset/not declared.
3. Download the workflow [run logs]( https://docs.github.com/en/rest/reference/actions#download-workflow-run-logs) and read the permission the jobs/workflows ran with
4. Look for declaration of `{{ secrets.SECRET_NAME }}` because this is used to declare new permission (Probably noisy and will trigger false positives until we can know when it's acceptable or not). Probably out of scope for this issue.

Comments?

**Comment by laurentsimon** [comment]
I'm going to create this check as a new standalone one. I don't have a good name for it yet. It'd be useful to have a generic name that could encompass other checks like #426 too?

**Comment by laurentsimon** [comment]
Done in [#534](https://github.com/ossf/scorecard/pull/534), except for point 3 and 4.

**Comment by ThisIsMissEm** [comment]
@laurentsimon could this tool actually use the new [Fine Grained Access Tokens](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/)? Or does it need repo admin access or graphql API access to function?

**Comment by spencerschrock** [comment]
As Laurent mentioned, this was implemented in #534, so closing as complete.
