### ISSUE TITLE
Unlicense not accepted as FSF or OSI approved

### ISSUE THREAD

**Issue by egecetin** [ossf/scorecard#4144]
**Describe the bug**
Even if https://spdx.org/licenses/ clearly describes The Unlicense is an approved license, a repository using Unlicense generates 

> Warn: project license file does not contain an FSF or OSI license.

and also removes one point from the score. Check the license score for this [repo](https://scorecard.dev/viewer/?uri=github.com/seladb/PcapPlusPlus)

**Reproduction steps**
N/A

**Expected behavior**
Point should not deducted/scaled since it is an FSF and OSI approved license

**Additional context**
N/A

**Comment by spencerschrock** [comment]
Thanks for the report. This work is already tracked in #4031.

**Comment by spencerschrock** [comment]
Sorry, that wasn't actually the cause. I'm guessing it's related to this block
https://github.com/ossf/scorecard/blob/36d8ad7a6037cdfbd8a42bf0bbca0c4852f7af25/checks/raw/license.go#L230-L241

**Comment by egecetin** [comment]
@spencerschrock Thanks for the quick fix!

**Comment by spencerschrock** [comment]
This wont make it to scorecard action for a bit though, so it may take some time to see it reflected in the API results.
