### ISSUE TITLE
BUG: Scorecards for public repositories without issues sections won't be created

### ISSUE THREAD

**Issue by nwse-che** [ossf/scorecard#4150]
**Describe the bug**
We found out that if a respository has no issues section, then it's not possible to get a scorecard. The output in this case is  empty. An example Respoitory would be: https://github.com/onlyfyio/community.aws

**Reproduction steps**
1. Execute  scorecard --repo=github.com/onlyfyio/community.aws
2. Observe the result

**Expected behavior**
The previous command should display a scorecard as result 

**Additional context**

**Comment by spencerschrock** [comment]
What version of Scorecard are you using? 
`scorecard --repo=github.com/onlyfyio/community.aws` works for me both at `HEAD` and `v4.13.1`.

**Comment by spencerschrock** [comment]
Can't reproduce, but we can always re-open if you provide more info.

**Comment by nwse-che** [comment]
I'm using the newest version which is available in brew

**Comment by spencerschrock** [comment]
I'm still unable to replicate.
```shell
brew install scorecard
scorecard version # returns v4.13.1
scorecard --repo=github.com/onlyfyio/community.aws
```
Works as expected
```
RESULTS
-------
Aggregate score: 4.0 / 10
...
