### ISSUE TITLE
CI-Tests doesn't support Azure Pipelines

### ISSUE THREAD

**Issue by gdong1** [ossf/scorecard#4185]
**Describe the bug**
There is no repo score in CI-Tests even the repo has the CI test enabled with GitHub Azure Pipelines.
It looks the checks don't support Azure Pipelines.

**Reproduction steps**
https://github.com/slimbootloader/slimbootloader enabled Azure Pipelines (refer  https://github.com/slimbootloader/slimbootloader/blob/master/.azurepipelines/azure-pipelines.yml.).
and it will be run on every PR.

**Expected behavior**
It should give a repo score in  CI-Tests.

**Comment by spencerschrock** [comment]
I can't reproduce your report at `HEAD` or our latest release `v4.13.1` or `v5.0.0-rc2`:
```shell
scorecard --repo slimbootloader/slimbootloader --checks CI-Tests --format json --show-details | jq
{
  "date": "2024-06-18T10:55:58-07:00",
  "repo": {
    "name": "github.com/slimbootloader/slimbootloader",
    "commit": "2892960d0655a23272b99e94e833d54508967341"
  },
  "scorecard": {
    "version": "",
    "commit": "unknown"
  },
  "score": 10.0,
  "checks": [
    {
      "details": null,
      "score": 10,
      "reason": "27 out of 27 merged PRs checked by a CI test -- score normalized to 10",
      "name": "CI-Tests",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#ci-tests",
        "short": "Determines if the project runs tests before pull requests are merged."
      }
    }
  ],
  "metadata": null
}
```

Where are you seeing Azure Pipelines not counted?

**Comment by gdong1** [comment]
There is no CI-Tests in the Scorecard Report https://securityscorecards.dev/viewer/?uri=github.com/slimbootloader/slimbootloader.

**Comment by spencerschrock** [comment]
Please see #3648 for a reason, but this is currently working as intended.
