### ISSUE TITLE
Add Adrianne Marcum (@afmarcum) as a triager

### ISSUE THREAD

**Issue by justaugustus** [ossf/scorecard#4205]
@afmarcum has been [instrumental](https://github.com/ossf/scorecard/issues?q=is%3Aissue+is%3Aopen+commenter%3Aafmarcum+) in helping @ossf/scorecard-maintainers and @ossf/allstar-maintainers get organized.

Recent updates to default permissions within the OpenSSF GitHub org have removed her access.
Let's restore that by granting her membership to @ossf/scorecard-triagers.

**Comment by jeffmendoza** [comment]
+1

**Comment by leec94** [comment]
+1

**Comment by justaugustus** [comment]
This is complete.
Welcome to @ossf/scorecard-triagers, Adrianne (and thanks for all of your work)!
