### ISSUE TITLE
BUG - Pinned-Dependencies has false positive on multi-stage Dockerfile

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [ossf/scorecard#4220]
**Describe the bug**
We have a multi-stage Dockerfile with arguments (https://github.com/boostsecurityio/poutine/blob/main/Dockerfile) 

Our scorecard is lower because of this false positive https://securityscorecards.dev/viewer/?uri=github.com/boostsecurityio/poutine 

**Reproduction steps**
1. Create a Dockerfile where the image is specified as an ARG
2. Run scorecard

**Expected behavior**
It should consider it to be pinned

**Comment by spencerschrock** [comment]
Thanks for the report, I'm going to close this as a duplicate of #3684 to track this issue in one place.
