### ISSUE TITLE
Incorrectly formatted example link

### ISSUE THREAD

**Issue by JeremiahAHoward** [ossf/scorecard#4247]
**Describe the bug**
The instructions and link found underneath "[View a Project's Score](https://github.com/JeremiahAHoward/scorecard/blob/main/README.md#view-a-projects-score)" around line 99 in the README.md can be difficult to interpret. This can be difficult to interpret because the link is coming up as half a hyperlink and the other half just text.

**Reproduction steps**
1. Visit this link to view the relevant section of the README.md:
[View a Project's Score](https://github.com/JeremiahAHoward/scorecard/blob/main/README.md#view-a-projects-score)

**Expected behavior**
The instructions should convey:
1. There is a link where you can enter a platform/org/repo to view a scorecard
2. How to manually create a link to view a scorecard

**Additional context**
![image](https://github.com/user-attachments/assets/301ac6ce-5666-48f9-8108-3fa7b3d98ffd)

In collaboration with @silasvm, @klbynum, @wavyeli32, @jordin221, and @emmet0r, we would be happy to submit a pull request.

**Comment by spencerschrock** [comment]
Thanks for the issue and wanting to contribute. 

Do you think it would be more clear if it was in markdown backticks?

`https://scorecard.dev/viewer/?uri=<github_or_gitlab>.com/<user_name_or_org>/<repository_name>`

**Comment by Wavyeli32** [comment]
Thank you @spencerschrock! Yes, that is exactly what we were thinking. We also had a few other ideas on how to clarify this section of the documentation and implemented them in a PR to show you what we had in mind. Please let us know what you think. 😊
