### ISSUE TITLE
BUG githubrepo.Client.GetOrgRepoClient() does not use parent Client transport

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/scorecard#4255]
**Describe the bug**
[githubrepo.Client.GetOrgRepoClient()](https://github.com/ossf/scorecard/blob/57501e5efa5b9312210028d67e48e072081052d7/clients/githubrepo/client.go#L207) simply [calls CreateGithubRepoClient()](https://github.com/ossf/scorecard/blob/57501e5efa5b9312210028d67e48e072081052d7/clients/githubrepo/client.go#L214). Instead it should call `CreateGithubRepoClientWithTransport()` and pass in its own client's transport `client.repoClient.Client().Transport`. 

**Reproduction steps**
Have an authenticated transport, say `it`

```go
rc := githubrepo.CreateGithubRepoClientWithTransport(ctx, it)
res, err := scorecard.Run(ctx, repo,
	scorecard.WithRepoClient(rc),
	scorecard.WithChecks([]string{"Security-Policy"}),
)
```
This should work, but you get:

```
ERRO[0001] GitHub token env var is not set. Please read https://github.com/ossf/scorecard#authentication  error="an error occurred while getting GitHub credentials"
```
due to: https://github.com/ossf/scorecard/blob/main/checks/raw/security_policy.go#L63

**Expected behavior**
Auth works.

**Comment by spencerschrock** [comment]
Thanks for filing the bug. To clarify, this is older behavior right? You should have seen this prior to upgrading to v5?

I had the same thought when providing feedback in #4254, so this seems like a sensible change to make. Do you have time/desire to send a PR?

**Comment by jeffmendoza** [comment]
I am seeing this with v5 and the sample code. I'll send a PR

**Comment by jeffmendoza** [comment]
Oh, Not sure about before v5. I assume so
