### ISSUE TITLE
New check: Check for dangerous code practices in github workflows

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#426]
There are several examples of github token leaks via `pull_request_target` event. It'd be nice to check for it - possibly filtering out known acceptable github actions that use it after we have reviewed their code (and it's pinned by hash). This check goes in the same direction as #414, ie harden github worflows.

**Comment by inferno-chromium** [comment]
Dangerous permissions
or something :)

**Comment by laurentsimon** [comment]
Thinking of broadening this check to "Dangerous workflow coding patterns":
1. dangerous events: `pull_request_target`
2. use of variable in `run` scripts: this lead to injection, see [here](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#understanding-the-risk-of-script-injections). The use is not always vulnerable, e.g. if the value is not attacker's controlled (hash commit) or if there's proper check in the workflow that it's only run on [maintainer's code](https://github.com/ossf/scorecard/blob/main/.github/workflows/integration.yml#L28). We can filter out non-attacker's controlled values to start with.
3.  I'm starting scouring for more :-)

I've left out `curl | bash` because it's part of another check around dependency pinning #403

**Comment by laurentsimon** [comment]
related link https://securitylab.github.com/advisories/GHSL-2020-328-GoogleCloudPlatform-microservices-demo-workflow/

**Comment by JarLob** [comment]
Hi, the important prerequisite for the dangerous pattern of `pull_request_target` is the usage of untrusted data, most commonly an explicit checkout of `github.event.pull_request.head` as in the example above. There are many ways to checkout the pull request code, but I think you can reduce false positives by checking for the most common - checkout action `ref:` parameter. Yet this still doesn't mean it is vulnerable if the code from pull request is treated as data, for example built scripts or tests are not run. But it may be hard to detect it programmatically to completely eliminate FPs. From my experience if `pull_request_target` is used with checkout `ref:` 95% chance the code is vulnerable.

**Comment by laurentsimon** [comment]
Thanks for the information, that's super useful. If someone in your team is interested in taking a stab at this, please let me know.

**Comment by laurentsimon** [comment]
Added a few more bad things to the list after reading https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by laurentsimon** [comment]
part 3 https://securitylab.github.com/research/github-actions-building-blocks/

**Comment by laurentsimon** [comment]
You sure can! I think we can start it as a different check first We can merge them later. I'll assign to you then?
Since it's a pretty comprehensive check, we can start with `pull_request_target` for v4?

**Comment by laurentsimon** [comment]
Let's try to do 5 and 8. They are fairly simple. Adding to v5 milestone. wdut? We can try to share the workload if needed.

**Comment by calebbrown** [comment]
Second order command injection attacks are also possible if attacker controlled input is passed from a workflow to a vulnerable action.

For example:
- this workflow looks safe: [github.com/wayou/wayou.github.io/.github/workflows/main.yml](https://github.com/wayou/wayou.github.io/blob/3484aaa3ae322adbaeff668ec93130a35018e182/.github/workflows/main.yml)
- however, the action it uses is vulnerable to command injection: [github.com/wayou/turn-issues-to-posts-action/action.yml](https://github.com/wayou/turn-issues-to-posts-action/blob/aaa01688298874bed2f5ced14b274d54911e0067/action.yml)
- using the following body in a new issue on the [wayou/wayou.github.io](https://github.com/wayou/wayou.github.io) repo can run arbitrary code:
```
EOF
# The EOF above escapes from the heredoc

# arbitrary commands go here

# make sure the EOF doesn't cause the action to fail
cat <<EOF
```

**Comment by laurentsimon** [comment]
That's an amazing find. Thanks @calebbrown for letting us know!

**Comment by laurentsimon** [comment]
I'll take a stab at 5.

**Comment by spencerschrock** [comment]
Closing as `Dangerous-Workflows` was impelemented. Any remaining enhancements that people care about should be filed as their own issue.

**Comment by laurentsimon** [comment]
Re-opening because there's a list of things we have not implemented. I don't mind closing this issue of we created dedicated issues for the remaining ones

**Comment by laurentsimon** [comment]
Maybe 9 is the only one to create an issue for?

**Comment by spencerschrock** [comment]
#3830
