### ISSUE TITLE
Feature: Support Scorecard as GitHub Action

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#430]
**Is your feature request related to a problem? Please describe.**
Scorecard cannot be run today as part of CI/CD workflows. To enable this, we need to add support for Scorecard to run as GitHub Action.

**Describe the solution you'd like**
N/A

**Comment by naveensrinivasan** [comment]
To run scorecard as a GitHub action and store the results we need SARIF https://github.com/ossf/scorecard/issues/193

**Comment by azeemshaikh38** [comment]
Closing to track as part of #193
