### ISSUE TITLE
BUG: restrict github token for scorecard repo

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#432]
Le's reduce all our tokens' scope to be [read-only by default](https://github.com/ossf/scorecard/settings/actions), unless needed otherwise.

**Comment by azeemshaikh38** [comment]
Adding this our bi-weekly agenda. Let's discuss there.

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  Included a label needs discussion. I have been adding that to the issues that need one.

**Comment by azeemshaikh38** [comment]
Ah I see, nice. I did not notice it. You could also update the agenda doc as and when something comes to your mind. Some topics may not need a GitHub issue.

**Comment by laurentsimon** [comment]
result from scorecard:
```
!! token-permissions/github-token - no permission defined in .github/workflows/codeql-analysis.yml
!! token-permissions/github-token - no permission defined in .github/workflows/gitcache-docker.yaml
!! token-permissions/github-token - no permission defined in .github/workflows/goreleaser.yaml
!! token-permissions/github-token - no permission defined in .github/workflows/integration.yml
!! token-permissions/github-token - no permission defined in .github/workflows/main.yml
!! token-permissions/github-token - no permission defined in .github/workflows/ok-to-test.yml
!! token-permissions/github-token - no permission defined in .github/workflows/stale.yml
!! token-permissions/github-token - no permission defined in .github/workflows/verify.yml

```

**Comment by laurentsimon** [comment]
Once this is fixed, also create an e2e test in scorecard.

**Comment by naveensrinivasan** [comment]
![image](https://user-images.githubusercontent.com/172697/121049960-3396d480-c786-11eb-8f95-373b1c7c122d.png)

FYI. I am changing the permissions to read-only and fixing it while testing the changes.

**Comment by inferno-chromium** [comment]
> ![image](https://user-images.githubusercontent.com/172697/121049960-3396d480-c786-11eb-8f95-373b1c7c122d.png)
> 
> FYI. I am changing the permissions to read-only and fixing it while testing the changes.

Great, i dont know if the check looks for read-only enforcement in settings (it looks on per-file basis), maybe you need to update the check to account for that as well.

**Comment by naveensrinivasan** [comment]
I agree. The code fix does not have that and AFAIK there isn't an API. The existing fixes will provide false positives. Till we have an API to check for these settings we should not run this check to avoid false positives. 

Thoughts?

**Comment by laurentsimon** [comment]
there's no API at the moment, you're right. However, since this is a new github config, virtually nobody is going to have this turned on, so we have a chance to influence how developers turn this feature on with our remediation steps. So I think it's fine  to only look at the file for now and see if people complain - hopefully very few.

**Comment by naveensrinivasan** [comment]
> there's no API at the moment, you're right. However, since this is a new github config, virtually nobody is going to have this turned on, so we have a chance to influence how developers turn this feature on with our remediation steps. So I think it's fine to only look at the file for now and see if people complain - hopefully very few will...
> Note this is no different from the Branch-Protection check: we run it but give it low confidence. I think the token check is in a better shape than branch protection due to what I describe above.

I feel this is a lot of work of teams to manually go and fix each and every workflow file when that setting is available within the UI which is a click away. I feel teams wouldn't want to run these checks.

IMO opinion we would wait for this till the API is available so that we can check if the setting has been turned on and then Fail along with this check. 

Thoughts @inferno-chromium @azeemshaikh38 @oliverchang

**Comment by laurentsimon** [comment]
You make a good point about the UX being easier, I agree.

I think there are 2 scenarios:
1. scorecard cron running on external repos, ie we don't have a token.
Do you think Github will provide an API? Or will they take the view, like for Branch protection, that they don't want to expose it?
In this case we're left trying to infer it via the current code. We could also look up the previous runs and check their permissions to see if most are read-only and provide a confidence based on how many runs have read vs write.

2. case where the maintainers run scorecard with their own token.
@inferno-chromium suggested we could query the UX permission setting via http request ourselves, and switch to using the API later if it's made available.

What if we could create a PR automatically to add the `permission:read-all` to all workflows? Do you think teams would accept the PR, or be reluctant since it will break the few workflows that need write?

**Comment by inferno-chromium** [comment]
> You make a good point about the UX being easier, I agree.
> 
> I think there are 2 scenarios:
> 
> 1. scorecard cron running on external repos, ie we don't have a token.
>    Do you think Github will provide an API? Or will they take the view, like for Branch protection, that they don't want to expose it?
>    In this case we're left trying to infer it via the current code. We could also look up the previous runs and check their permissions to see if most are read-only and provide a confidence based on how many runs have read vs write.
> 2. case where the maintainers run scorecard with their own token.
>    @inferno-chromium suggested we could query the UX permission setting via http request ourselves, and switch to using the API later if it's made available.

Should be a simple lookup on e.g. https://github.com/ossf/scorecard/settings/actions

```
&lt;div class="form-checkbox "&gt;
--
&nbsp; | &lt;label&gt;
&nbsp; | &lt;input
&nbsp; | type="radio"
&nbsp; | name="actions_default_workflow_permissions"
&nbsp; | value="write"
&nbsp; | checked
&nbsp; | &gt;
&nbsp; | Read and write permissions
&nbsp; | &lt;p class="note"&gt;
&nbsp; | Workflows have read and write permissions in the repository for all scopes.
&nbsp; | &lt;/p&gt;
&nbsp; | &lt;/label&gt;
&nbsp; | &lt;/div&gt;
&nbsp; | &nbsp;
&nbsp; | &lt;div class="form-checkbox"&gt;
&nbsp; | &lt;label&gt;
&nbsp; | &lt;input
&nbsp; | type="radio"
&nbsp; | name="actions_default_workflow_permissions"
&nbsp; | value="read"
&nbsp; | &gt;
&nbsp; | Read repository contents permission
&nbsp; | &lt;p class="note"&gt;
&nbsp; | Workflows have read permissions in the repository for the contents scope only.
&nbsp; | &lt;/p&gt;
&nbsp; | &lt;/label&gt;
&nbsp; | &lt;/div&gt;
```

> 
> So we could have:
> 
> 1. Check the UX setting. If this fails
> 2. Look up last X workflow runs' permissions and use some confidence based on #run_with_read/#total_runs. If we cannot conclude, or if it fails,
> 3. Use current code with low confidence
> 
> Somewhat related: What if we could create a PR automatically to add the `permission:read-all` to all workflows? Do you think teams would accept the PR, or be reluctant since it will break the few workflows that need write?

**Comment by inferno-chromium** [comment]
> You make a good point about the UX being easier, I agree.
> 
> I think there are 2 scenarios:
> 
> 1. scorecard cron running on external repos, ie we don't have a token.
>    Do you think Github will provide an API? Or will they take the view, like for Branch protection, that they don't want to expose it?
>    In this case we're left trying to infer it via the current code. We could also look up the previous runs and check their permissions to see if most are read-only and provide a confidence based on how many runs have read vs write.
> 2. case where the maintainers run scorecard with their own token.
>    @inferno-chromium suggested we could query the UX permission setting via http request ourselves, and switch to using the API later if it's made available.
> 
> So we could have:
> 
> 1. Check the UX setting. If this fails

Feels slightly annoying since requires querying security settings on both repo level and org level. org level might not be even accessible to repo devs. such a nightmare (and also burns api quota).

> 2. Look up last X workflow runs' permissions and use some confidence based on #run_with_read/#total_runs. If we cannot conclude, or if it fails,

Is this even doable, like is there a way to distinguish read run?

> 3. Use current code with low confidence
> 
> Somewhat related: What if we could create a PR automatically to add the `permission:read-all` to all workflows? Do you think teams would accept the PR, or be reluctant since it will break the few workflows that need write?

This shouldnt be crazy amount of work for dev and it is best for them to fix those 5-10 avg workflows themselves (rather than doing back and forth with our pr uploads). i actually like configuration in code better. this problem is not unique to this check, we have automated-updates check with dependabot suffer the same fate.

- thoughts @jeffmendoza @laurentsimon @azeemshaikh38 @naveensrinivasan

**Comment by oliverchang** [comment]
> 2. case where the maintainers run scorecard with their own token.
>    @inferno-chromium suggested we could query the UX permission setting via http request ourselves, and switch to using the API later if it's made available.

This doesn't sound too reliable if we're relying on querying something in an unsupported way that could change at any time.. Not sure if we should hold our breath for this to be an exposed API either..

> Look up last X workflow runs' permissions and use some confidence based on #run_with_read/#total_runs. If we cannot conclude, or if it fails,

If this works, it seems like something that would be pretty API-usage heavy? 

Maybe we should just push for people to set this in workflow files as a best practice, even if they might have the UI setting flipped. I agree with @inferno-chromium that configuration in files seems better in general, and has benefits in terms of having an audit log via git.

**Comment by laurentsimon** [comment]
> workflow runs:

it's possible using this [API](https://docs.github.com/en/rest/reference/actions#list-workflow-runs-for-a-repository). It's API intensive: need to 1) list workflow runs, 2) list jobs for each workflow, 3) query job logs, 4) fetch the url given in a header. I just tried 5mn ago, and realized the API is not accessible without a maintainer's PAT. So this is not going to help us.

> push for people to set this in workflow files as a best practice

I also like this approach and thought we could influence users to do this, since very few repos are going to have the setting enabled anyway (the setting was introduced last year). If users start complaining of false negative, we can ask them to use the config file instead of repo setting. I think that's our only chance :/ Worse case scenario is: we kill the check in the future.

**Comment by naveensrinivasan** [comment]
After this I concur it makes sense to go with the approach. Thanks.

**Comment by azeemshaikh38** [comment]
closing this bug. Please re-open if there are more AIs here.
