### ISSUE TITLE
BUG: scorecard does not recognize BSD-2-Clause-Patent license.

### ISSUE THREAD

**Issue by grom72** [ossf/scorecard#4347]
**Describe the bug**
*BSD-2-Clause Plus Patent License* is not detected as an FSF or OSI-recognized license.

See: https://github.com/grom72/SLT/security/code-scanning/12 [https://github.com/grom72/SLT/security/code-scanning/12]([https://github.com/grom72/SLT/security/code-scanning/12])

**Reproduction steps**
1. Create a new Github project with an empty `LICENSE` file
2. Copy contents of the license from https://spdx.org/licenses/BSD-2-Clause-Patent.html 
3. Add the `Scorecard supply-chain security` workflow to the project and run it.
4. Observe `License` issue in ->`Security`-> `Code scanning` page (https://github.com/grom72/SLT/security/code-scanning)
5. Check the comment for `LICENSE` file:
*score is 9: Any licence detected not an FSF or OSI recognized license
Click Remediation section below to solve this issue*

**Expected behavior**
*BSD-2-Clause Plus Patent License* shall be properly detected by scorecard.
The score should be 10.

**Comment by spencerschrock** [comment]
We currently rely on GitHub for license detection, which makes "no assertion" about the license type for your test repo:
https://api.github.com/repos/grom72/SLT/license

It won't help with the scoring, but if you use v2.4.0 instead of v2.3.1 of scorecard action, we don't file a codescanning alert for 9/10 (https://github.com/ossf/scorecard-action/pull/1411).

**Comment by grom72** [comment]
Thank you for your explanation. I will try to ask Github.

**Comment by spencerschrock** [comment]
I had thought GitHub used https://github.com/licensee/licensee [(source)](https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license), which does detect it:
```
docker run licensee detect grom72/SLT --remote
To use multipart middleware with Faraday v2.0+, install `faraday-multipart` gem; note: this is used by the ManageGHES client for uploading licenses
License:        BSD-2-Clause-Patent
Matched files:  LICENSE
LICENSE:
  Content hash:  74f98ac31eae8fba4712be7d721209d8cdb786ff
  Attribution:   Copyright (c) 2024, Tomasz Gromadzki
  Confidence:    99.71%
  Matcher:       Licensee::Matchers::Dice
  License:       BSD-2-Clause-Patent
  Closest non-matching licenses:
    BSD-2-Clause-Patent similarity:  99.71%
    MS-PL similarity:                43.37%
    BSD-3-Clause-Clear similarity:   41.35%
```
