### ISSUE TITLE
Scorecard doesn't detect OpenSSF Best Practices badge

### ISSUE THREAD

**Issue by ivanoblomov** [ossf/scorecard#4413]
**Describe the bug**
Scorecard doesn't detect the OpenSSF Best Practices badge for the project https://github.com/FoveaCentral/hit_counter.

**Reproduction steps**
1. The project [scores 0/10](https://scorecard.dev/viewer/?uri=github.com/FoveaCentral/hit_counter) even though the README has the [badge](https://github.com/FoveaCentral/hit_counter?tab=readme-ov-file#hitcounter) and the Best Practices site has its [report](https://www.bestpractices.dev/en/projects/5375).

**Expected behavior**
The project should get a 5/10 because it has a passing badge.

**Additional context**
I don't think the case-sensitivity issue noted in https://github.com/ossf/scorecard/issues/3466#issuecomment-1756357077 is related since in this case all results are going to the camel-cased https://scorecard.dev/viewer/?uri=github.com/FoveaCentral/hit_counter and nothing ever went to the lowercased https://scorecard.dev/viewer/?uri=github.com/foveacentral/hit_counter.

As another data point, the badge is correctly detected for the sister project https://github.com/FoveaCentral/vaccinesignup since it has the [expected score of 5](https://scorecard.dev/viewer/?uri=github.com/FoveaCentral/vaccinesignup).

The most obvious delta between the two projects is that the working one's default branch is `main` while the other is `master`. I had similar results with another project with a `master` branch.

**Comment by spencerschrock** [comment]
> 1. The project [scores 0/10](https://scorecard.dev/viewer/?uri=github.com/FoveaCentral/hit_counter) even though the README has the [badge](https://github.com/FoveaCentral/hit_counter?tab=readme-ov-file#hitcounter) and the Best Practices site has its [report](https://www.bestpractices.dev/en/projects/5375).

Did you rename your repo? The bestpractice metadata has this for the project URL (which is different from github.com/FoveaCentral/hit_counter):

https://github.com/ivanoblomov/hit_counter

**Comment by ivanoblomov** [comment]
@spencerschrock that's right. To enable 2FA, GitHub required us to move the repo to an organization.

**Comment by spencerschrock** [comment]
Once you update the metadata in Best Practices, it should be detected.

**Comment by ivanoblomov** [comment]
Doh, completely forgot that was user editable. That worked, cheers @spencerschrock!
