### ISSUE TITLE
BigQuery scorecard-v2 table doesn't have new partitions

### ISSUE THREAD

**Issue by mpace965** [ossf/scorecard#4443]
**Describe the bug**
BigQuery scorecard-v2 dataset doesn't have new partitions. The last available partition is `20241125`.

**Reproduction steps**
Use the following query to check for new partitions

```sql
SELECT partition_id
FROM openssf.scorecardcron.INFORMATION_SCHEMA.PARTITIONS
WHERE table_name="scorecard-v2"
AND partition_id!="__NULL__" ORDER BY partition_id DESC
LIMIT 1;
```

The result is `20241125` instead of something more recent like `20241202` or `20241209`.

**Expected behavior**
These partitions exist and have scorecard data.

**Additional context**
I did not see any issues or discussion about this - apologies if this has already been reported. Is this still the right place to check for scorecard data? Or maybe there is an ongoing issue and new partitions are not being generated at the moment.

**Comment by spencerschrock** [comment]
The cron also failed the upload process this past week, with many unprocessed repos. Using this as the tracking issue for the slowdown investigation.

**Comment by spencerschrock** [comment]
Profiling shows 35% of the time is spent in [one hotspot](https://github.com/google/deps.dev/blob/9aabb913fd07d1d752cc98b5d3b033458ad6a439/util/semver/maven.go#L162-L163), which is referenced indirectly via osv-scanner.

Will need to investigate further to understand cause

**Comment by spencerschrock** [comment]
Reverting to osv-scanner v1.9.0 has fixed our throughput, and I'm working with them upstream to fix the issue. I'm not sure if this week's run will finish in time, but it will hopefully be fixed going forward.

**Comment by spencerschrock** [comment]
`2024.12.16` was uploaded successfully after the downgrade.
