### ISSUE TITLE
BUG: CODEOWNERS file not located

### ISSUE THREAD

**Issue by sgammon** [ossf/scorecard#4462]
**Describe the bug**
We have a [`CODEOWNERS` file](https://github.com/sgammon/rules_graalvm/blob/main/.github/CODEOWNERS) and enforce reviews based on that file in [this repo](https://github.com/sgammon/rules_graalvm). GitHub's UI reports that the CODEOWNERS file is valid. However, when the Scorecard action runs, [results show it cannot find the file](https://securityscorecards.dev/viewer/?uri=github.com/sgammon/rules_graalvm):

```
...
Warn: codeowners review is required - but no codeowners file found in repo
...
```
> Part of the Branch-Protection check

**Reproduction steps**
I am not sure.

**Expected behavior**
I expected the Scorecard action to find the file, as far as I can tell it is valid.

**Additional context**
N/A

**Comment by spencerschrock** [comment]
(copying from other issue)

This is unfortunately a known and tricky edge case with how Scorecard looks at files in a repository using the archive tarball.

I'm going to close this in favor of the existing issue, but this is the second or third time to come up this week: 
https://github.com/ossf/scorecard/issues/2489#issuecomment-1331377334

The short term "fix" from the [other issue](https://github.com/ossf/scorecard/issues/4463#issuecomment-2552340436) won't really work the for Branch Protection check, but the long term solution of a git compatibility mode might.
