### ISSUE TITLE
Feature - manage tool dependencies  via go.mod

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#459]
**Is your feature request related to a problem? Please describe.**
Manage tool dependencies via go.mod

**Describe the solution you'd like**
Manage tool dependencies like golint , protoc-gen-go using go.mod https://marcofranssen.nl/manage-go-tools-via-go-modules

**Comment by azeemshaikh38** [comment]
Is this issue same as (or can be merged with): https://github.com/ossf/scorecard/issues/429?

**Comment by naveensrinivasan** [comment]
> Is this issue same as (or can be merged with): #429?

Yes! Closing this in favor of #429
