### ISSUE TITLE
Signed Tags Check: Github "Verified" is a poor metric for source authenticity

### ISSUE THREAD

**Issue by Foxboron** [ossf/scorecard#46]
Github blanket signs releases with their own internal key. There are listed as "Verified" in the UI, and I suspect the library in use does the same. However this is poor UX and should not be relied upon to provide any form of "Signed-Tags" or "Signed-Releases".

An attacker can get access to some account that doesn't have 2FA enabled and have Github generate a "Verified" tag to satisfy the requirement.

There should be a mechanism to ensure the key is only a valid key from the given user, and not the Github signing key.

**Comment by Foxboron** [comment]
And just to point it illustrate with the first repository I found.

https://github.com/containers/python-podman/releases

```
λ scorecard main» ./scorecard --verbosity info --repo=github.com/containers/python-podman --checks=Signed-Releases,Signed-Tags
Starting [Signed-Releases]
Starting [Signed-Tags]
signed tag found: v0.0.2, commit: 55ff382773eec6eac2baf27cd8136cc388a23da9
signed tag found: v0.0.1, commit: 46c74643d20f76baee8ae49472db4e6b1741244a
Finished [Signed-Releases]
signed tag found: 1.6.0, commit: 629316a31f5f9c2e6dd06113de7648082a131cf1
signed tag found: 0.0.3, commit: 1d6120e3253fb01c2df62e487b40164dbcddac30
Finished [Signed-Tags]

RESULTS
-------
Signed-Releases: Fail 0
Signed-Tags: Pass 8
```

But the repository has no actual valid signatures. They are just auto-generated by Github UI merges and release. They provide no source authentication.

**Comment by inferno-chromium** [comment]
@Foxboron - do you have any thoughts on a fix or can contribute a PR here, code is here - https://github.com/ossf/scorecard/blob/main/checks/signed_releases.go and https://github.com/ossf/scorecard/blob/main/checks/signed_tags.go

**Comment by Foxboron** [comment]
It depends what the intention is. Signature verification isn't super trivial so unsure how it would be implemented across different forges, but blacklisting the keyid of the github key is enough in this case.

**Comment by dlorenc** [comment]
Wow, I never noticed the GitHub key. Is that on for every repo or is it some kind of setting? Deny-listing that key or looking for the name (I'll have to check what's in the API response) is probably a good approach.

**Comment by inferno-chromium** [comment]
Signed releases check is not impacted as it is dependent on a signature file existing in assets - https://github.com/ossf/scorecard/blob/main/checks/signed_releases.go#L49

Signed tags is the only affected one here.

**Comment by Foxboron** [comment]
@dlorenc It's on for all repositories and used whenever you do a commit through github. I think it makes sense in some way by proving github was the one that made the commit. But having it indistinguishable from a "proper" signature is a bit bad. Github could probably improve on this one way or another.

@inferno-chromium Yes, I was under the impression releases might be looking at the tag signature. I should have done the checked before submitting the report, but I had already been throttled by the API :)

**Comment by dlorenc** [comment]
Ah, I think I fixed this by accident as part of #41. Previously we were looking at signatures for the **commit** a tag points to, when we were really intending to look at signatures on the tag itself.

Now this correctly fails on the repo you pointed us at. Github doesn't appear to sign tags that are created.

**Comment by Foxboron** [comment]
I still think there are cases where the tag can be signed by github. So denying any form of valid signatures with that keyid should be done I think.

**Comment by dlorenc** [comment]
Ah thanks for checking - do you happen to have any examples I can look at to make sure I get the right key/API responses?

**Comment by Foxboron** [comment]
I need to try recall where I have seen them before and I can try provide a set of test repositories we can use.

**Comment by dlorenc** [comment]
Any luck tracking an example down here? I took a look at a few projects and still haven't found any where GitHub signed the tags.

**Comment by Foxboron** [comment]
I haven't been able to sit down with this :) I can try have a look during the weekend with the rest of my FOSS backlog.

**Comment by dlorenc** [comment]
cool, no worries!

**Comment by Foxboron** [comment]
I found the example I had in my head but it turns out it's just the git signatures which makes it looks like the tag itself is valid, but it's the underlying commit object being signed by Github key.

Building from head the repository is correctly marked as failing the signature checks, but admittedly it's still bad that github makes it look like it's properly signed.

https://github.com/naggie/dsnet/releases

```
λ scorecard main» ./scorecard --verbosity info --repo=github.com/naggie/dsnet --checks=Signed-Releases,Signed-Tags
Starting [Signed-Releases]
Starting [Signed-Tags]
Finished [Signed-Releases]
Finished [Signed-Tags]

RESULTS
-------
Signed-Releases: Fail 10
Signed-Tags: Fail 0
```

I think this closes the issue as the mentioned fix is adequate.

**Comment by dlorenc** [comment]
Thanks! I also found this behavior surprising, and hard to distinguish in both the UI and API.
