### ISSUE TITLE
Feature: repo/file interface for Scorecard library

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#462]
**Is your feature request related to a problem? Please describe.**
Scorecard today is limited to run on GitHub repositories only. We should expand this support to handle local files and other VCS like GitLab, BitBucket etc.

**Describe the solution you'd like**
Create an interface `RepoClient`:

```
type RepoClient interface {
  Commits()
  File()
  ...
}
```

We need to look into our current code and sketch out all the required methods needed in this interface. Update our code bit-by-bit to use this interface instead of directly relying on GitHub API. 

Under the hood use GitHubClient/LocalClient/GitLabClient which implements this interface and can fit clients needs.

**Comment by azeemshaikh38** [comment]
@inferno-chromium @oliverchang @laurentsimon @naveensrinivasan thoughts?

**Comment by oliverchang** [comment]
+1. Sounds great!

**Comment by inferno-chromium** [comment]
+1, this would be awesome, and we definitely need localclient support. some checks might not be applicable when provided a local repo, but we need to add some skip state for those (instead of fail).

**Comment by naveensrinivasan** [comment]
> +1, this would be awesome, and we definitely need localclient support. some checks might not be applicable when provided a local repo, but we need to add some skip state for those (instead of fail).

+1. Great!!

**Comment by laurentsimon** [comment]
+1
