### ISSUE TITLE
BUG: Cron job taking forever

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#495]
This past week the cron job seems to be running excessively slow and hasn't finished a successful run since ~May 16th. The issue seems to be GitHub tokens since the logs are consistently spewing out ratelimit errors after running checks on just 1-2 repos - 

![image](https://user-images.githubusercontent.com/4825078/119246437-6742ef00-bb36-11eb-880b-d8a3c0d29f42.png)

I have been trying to debug this but unable to root cause it so far. @inferno-chromium @oliverchang @naveensrinivasan @laurentsimon FYI.

**Comment by naveensrinivasan** [comment]
I will take a look tomorrow.

**Comment by azeemshaikh38** [comment]
Ok I think I got a clue. I pushed a locally built binary (apologies, I was desperate) and here are the logs:

![image](https://user-images.githubusercontent.com/4825078/119251709-c74c8c00-bb5c-11eb-90dc-2ae5fd4e36df.png)

Looks like there is one token among the 6, at index 1, that has the rate limit of an anonymous token (60/hour instead of 5000/hour). So possibly, some thread gets blocked on that token and we end up waiting for that thread to finish.

**Comment by inferno-chromium** [comment]
> Ok I think I got a clue. I pushed a locally built binary (apologies, I was desperate) and here are the logs:
> 
> ![image](https://user-images.githubusercontent.com/4825078/119251709-c74c8c00-bb5c-11eb-90dc-2ae5fd4e36df.png)
> 
> Looks like there is one token among the 6, at index 1, that has the rate limit of an anonymous token (60/hour instead of 5000/hour). So possibly, some thread gets blocked on that token and we end up waiting for that thread to finish.

ok regenerated config to remove 2nd token in list
```
gcloud init (set project and zone when asked)
echo -n "<list of secrets seperated by commas>" | base64 -w0
kubectl edit secret github
update token with this echo value
```

**Comment by naveensrinivasan** [comment]
1. We need a way to maintain who's token each of these belongs to. 

2. Also, we need to fail fast when the token limit is less than 5000.

**Comment by azeemshaikh38** [comment]
@inferno-chromium thanks!

@naveensrinivasan I think we should update the way we access tokens today in [roundRobinAccessor](https://github.com/ossf/scorecard/blob/main/roundtripper/github.go#L62). This way of accessing tokens means we always block on the weakest (least rate-limited) token. This should instead be a rate-limit aware tokenAccessor, such that as long as there is a token which has sufficient rate-limit, we return that token and only return (and block) an exhausted token when absolutely necessary.  

If folks agree with this idea, I can start a PR for this.

**Comment by inferno-chromium** [comment]
> @inferno-chromium thanks!
> 
> @naveensrinivasan I think we should update the way we access tokens today in [roundRobinAccessor](https://github.com/ossf/scorecard/blob/main/roundtripper/github.go#L62). This way of accessing tokens means we always block on the weakest (least rate-limited) token. This should instead be a rate-limit aware tokenAccessor, such that as long as there is a token which has sufficient rate-limit, we return that token and only return (and block) an exhausted token when absolutely necessary.
> 
> If folks agree with this idea, I can start a PR for this.

How much often do we hit this, probably a one-time mistake, how much work is this, your call!

**Comment by naveensrinivasan** [comment]
I started working on it a while back and ran into issues. 

https://github.com/ossf/scorecard/blob/feat/new-roundtripper/roundtripper/roundtripper.go

**Comment by naveensrinivasan** [comment]
> I started working on it a while back and ran into issues.
> 
> https://github.com/ossf/scorecard/blob/feat/new-roundtripper/roundtripper/roundtripper.go

Sorry wrong branch.

**Comment by azeemshaikh38** [comment]
Actually, I take back what I said. I initially thought updating roundRobinAccessor will allow us to process more repos before blocking. I was wrong, it'll barely make a dent. Don't think its worth pursuing. 

Closing this issue since cron job is now proceeding at its regular rate.
