### ISSUE TITLE
Bug - Random test failures

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#510]
2021/05/26 19:17:22 Failed to export to Stackdriver: [rpc error: code = PermissionDenied desc = Permission monitoring.metricDescriptors.create denied (or the resource may not exist).; rpc error: code = PermissionDenied desc = Permission monitoring.metricDescriptors.create denied (or the resource may not exist).; rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist).; rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist).; rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist).; rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist).]

_Originally posted by @naveensrinivasan in https://github.com/ossf/scorecard/issues/483#issuecomment-849071837_

**Comment by azeemshaikh38** [comment]
IIUC, these failures are because the `gcloud` credentials lack the right permissions. I'd prefer to ignore these failures for now since we will very soon move to the PubSub framework and will be re-writing the `e2e` tests anyways. 

However, this might be a good chance to consider how we will run our future integration tests for the PubSub cron job. Does it make sense to setup our integration tests such that:

i) when its `/ok-to-test`, build and push image to GCP. Tag image with the `PR` id
ii) in a `test` environment in GCP, bring up instances of PubSub `controller` and `worker` jobs which use this tagged image
iii) output results will be under `PR/` dir 
ii) validate test run/output

@inferno-chromium @oliverchang @naveensrinivasan - does it make sense to attempt something like this?

**Comment by oliverchang** [comment]
That sounds great, but I worry that it may slow down PR development if this integration test is very slow. 

Perhaps instead we should do this on pushes to "main" only, and only build/push production images if they pass these tests.

**Comment by azeemshaikh38** [comment]
If its not too much effort to build such a "canary" system, then I vote for the same.

I have added this on the Scorecard bi-weekly agenda to discuss in more detail. Closing the issue for now.

**Comment by naveensrinivasan** [comment]
Opening this issue as it is blocking running e2e for PR merges.https://github.com/ossf/scorecard/actions/runs/885890806

**Comment by naveensrinivasan** [comment]
> IIUC, these failures are because the `gcloud` credentials lack the right permissions. I'd prefer to ignore these failures for now since we will very soon move to the PubSub framework and will be re-writing the `e2e` tests anyways.

Can you specifics as to why would want to rewrite the `e2e`? 

> 
> However, this might be a good chance to consider how we will run our future integration tests for the PubSub cron job. Does it make sense to setup our integration tests such that:
> 
> i) when its `/ok-to-test`, build and push image to GCP. Tag image with the `PR` id
> ii) in a `test` environment in GCP, bring up instances of PubSub `controller` and `worker` jobs which use this tagged image
> iii) output results will be under `PR/` dir
> ii) validate test run/output
> 
> @inferno-chromium @oliverchang @naveensrinivasan - does it make sense to attempt something like this?

**Comment by azeemshaikh38** [comment]
> We need to do some kind of short-term fix like giving that bot account permission to stackdriver.

Sure, if its easy, then lets do that. We can also consider writing a custom `PrintExporter` which implements the same interface as `StackdriverExporter` but simply prints these metrics instead. 

> Can you specifics as to why would want to rewrite the e2e?

Not all `e2e`, just the ones specific to `cron/main.go`. I'm assuming here that we'll be removing this from our codebase soon after the PubSub cron is in place.
