### ISSUE TITLE
Project: Scorecard UX

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#511]
This is an umbrella bug for tracking features/implementation work on improving `how users interact with Scorecard`. So far, we have:

1. Improved remediation: https://github.com/ossf/scorecard/pull/347#discussion_r616364482
2. Human readable HTML output: #342 
3. Scorecard as a GitHub workflow: #193  
4. Scorecard badge: #271 
5. Tracking Scorecard data over time: #12 

Let's use this space to discuss any new UX related ideas and we can spawn off new issues if needed.

**Comment by azeemshaikh38** [comment]
One more: #58

**Comment by azeemshaikh38** [comment]
#304

**Comment by chrismcgehee** [comment]
Azeem suggested I work on adding remediation results to scorecard (#304), so I'll be doing that next. I'll be following what he laid out in his comment https://github.com/ossf/scorecard/pull/347#discussion_r616364482.

**Comment by azeemshaikh38** [comment]
Thanks for taking this up Chris, this'll be a great help!

**Comment by laurentsimon** [comment]
> Azeem suggested I work on adding remediation results to scorecard (#304), so I'll be doing that next. I'll be following what he laid out in his comment [#347 (comment)](https://github.com/ossf/scorecard/pull/347#discussion_r616364482).

any update on this effort?

**Comment by laurentsimon** [comment]
Assigning to myself. In addition to the above, some requisites also include cleaning up how we manage:

1. [score vs confidence](https://github.com/ossf/scorecard/issues/352)
2. error handling (wrapped error, something else). @naveensrinivasan can you send the link about the various options for doing this in golang?
3. error detail reporting

**Comment by chrismcgehee** [comment]
@laurentsimon Sorry I didn't get back to you sooner, been crazy busy getting ready to move and working on selling my house.

I've made some progress on showing remediation suggestions in the results. I'll slack you and give you more details.

**Comment by azeemshaikh38** [comment]
Once we have #193 and #271, worth considering making Scorecard available on Github Marketplace - https://github.com/ossf/scorecard/issues/653
