### ISSUE TITLE
New check: ADD OSV: Show current state w.r.t open security vulnerabilities (e.g. CVEs, OSS-Fuzz, etc)

### ISSUE THREAD

**Issue by inferno-chromium** [ossf/scorecard#52]

**Comment by inferno-chromium** [comment]
api key requirement gone, thanks to @oliverchang. 

curl -X POST -d '{"version": "0.17.0", "package": {"name": "arrow"}}' "https://api.osv.dev/v1/query" | jq

Oliver, what was the way to get latest version ?

**Comment by oliverchang** [comment]
I think we need to look at the upstream repo to get:

- The current HEAD commit sha and use that to commit.
- Or the closest tag name.

**Comment by oliverchang** [comment]
I can try add this.

**Comment by inferno-chromium** [comment]
@oliverchang - we have a launch sometime this week, is this doable in next 2-3 days?

**Comment by oliverchang** [comment]
Will try to tackle this tmrw.
