### ISSUE TITLE
Feature - Include large repository in e2e test

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#521]
**Is your feature request related to a problem? Please describe.**
Include a large repository for the e2e test to validate memory leaks. 

**Describe the solution you'd like**

1. Docker run with constrained memory `--memory=900mb` scorecard
2. Use a large repository like https://github.com/ApolloAuto/apollo
3. If there is a memory leak it is likely to fail.

**Additional context**
https://github.com/ossf/scorecard/issues/512

**Comment by azeemshaikh38** [comment]
With randomized e2e tests, this should be covered.
