### ISSUE TITLE
BUG - PubSub worker filling up logs

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#529]
**Describe the bug**
The pubsub worker is filling up logs with these messages

`timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-199]; rpc error: code = ResourceExhausted desc = One or more TimeSeries could not be written: Monitored resource (scorecard-batch-worker-6d8c74b67d-v2tlf) has too many time series (custom metrics).: timeSeries[0-99]]`

The pubsub worker is filling up with lots of failing error messages for the scorecard cron.

**Comment by azeemshaikh38** [comment]
This might be coming from `number of active time series per metric` limit, which is 30k - 

![image](https://user-images.githubusercontent.com/4825078/121272765-a03fcb00-c87b-11eb-9ffa-6f795a2ae065.png)

I think we easily exceed this limit given that we log at `per repo per check` granularity. So for ~3k repos and 15 checks we have about ~45k unique time series. This is worse for outgoing HTTP requests where it is `per repo per check per http path`. So I'm going to limit the cardinality by only logging at the `per check` granularity. If this also doesn't help, I might consider simply disabling the metric logging.

**Comment by azeemshaikh38** [comment]
https://github.com/ossf/scorecard/pull/556 seems to have fixed the Stackdriver failures. Closing this issue.
