### ISSUE TITLE
Frozen-Deps: Handle npm-shrinkwrap.json like package-lock.json

### ISSUE THREAD

**Issue by RandomByte** [ossf/scorecard#54]
According to npm, both files have the same effect of "freezing" dependencies: https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json

We have a CLI project which uses `npm-shrinkwrap.json` instead of `package-lock.json`: https://github.com/SAP/ui5-cli

I would expect the "Frozen-Deps" check to pass. But it fails since it does not check for `npm-shrinkwrap.json`:

https://github.com/ossf/scorecard/blob/9d18604db8c23aad75672857faaa5d33a56aa563/checks/frozen_deps.go#L80-L82

Is there any reason for that?

By the way, GitHub's handling is very odd in that regard. It seems to detect the content of `npm-shrinkwrap.json` but declares it as `package-lock.json`: https://github.com/SAP/ui5-cli/network/dependencies.  
Also `npm-shrinkwrap.json` seems to be missing in the corresponding [documentation](https://docs.github.com/en/free-pro-team@latest/github/visualizing-repository-data-with-graphs/about-the-dependency-graph#supported-package-ecosystems). I'll try and reach out to GitHub to clarify that 👍

**Comment by dlorenc** [comment]
Thanks for the pointer! This should be straightforward to add, in the location you already found. Any interest in sending the PR? I can take care of it if you don't have the time.

**Comment by RandomByte** [comment]
Sure, thank you! I created a PR: https://github.com/ossf/scorecard/pull/55
