### ISSUE TITLE
Feature - Handle Renovate bot package.json

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#542]
**Is your feature request related to a problem? Please describe.**
https://github.com/ossf/scorecard/pull/322 , does not handle `package.json (within a "renovate" section)` https://docs.renovatebot.com/configuration-options/

**Comment by spencerschrock** [comment]
Closing partially due to age, and Renovate [deprecated this config 2 years ago](https://www.github.com/renovatebot/renovate/pull/13447/files):

> Storing the Renovate configuration in a package.json file is deprecated and support may be removed in the future
