### ISSUE TITLE
Feature - Improve Tarball caching for CheckIfFileExists

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#545]
**Is your feature request related to a problem? Please describe.**
The tarball is downloaded multiple times across scorecard for multiple checks with `CheckIfFileExists`
https://github.com/ossf/scorecard/blob/1ec9ada1376abbd82a19ad97af9e405a51eeafa3/checks/checkforfile.go#L30

This function does not use HTTP caching because the caching initially stores in memory even though disk or blob cache is chosen https://github.com/ossf/scorecard/pull/276

**Describe the solution you'd like**

1. Caching causes OOM because the HTTP caching initially stores it in memory even though disk/blob caching is chosen.
2. Have a larger memory node for CRON jobs.
3. Use HTTP caching, which reduces the roundtrip as well as the API quotas.
4. Have this option as configurable so by default non-cron jobs would not cache it. The client's using scorecard would not run into OOM.

**Describe alternatives you've considered**
The other approach is to rewrite the HTTP caching to stream to the disk instead of storing everything in-memory.

**Comment by naveensrinivasan** [comment]
We could try increasing the node size and changing the max memory for the pods and try out if the solution works. This does not involve much effort.

@azeemshaikh38 @inferno-chromium

**Comment by azeemshaikh38** [comment]
I have already increased the node size and max memory for worker pods using the `worker-node-pool` (I had updated the k8s file locally, will submit the PR later). 

As for the HTTP caching - it won't give us much benefit in terms of API quotas since we only make a handful of repeated calls per repo. The alternative of streaming to disk and reading from there seems good to me, but maybe if we can get away with increased memory limits, we can wait on this. Wdyt?

**Comment by naveensrinivasan** [comment]
> As for the HTTP caching - it won't give us much benefit in terms of API quotas since we only make a handful of repeated calls per repo. The alternative of streaming to disk and reading from there seems good to me, but maybe if we can get away with increased memory limits, we can wait on this. Wdyt?


The caching is using blob store and so in the subsequent runs will use the cache and not use the API quotas if the content hasn’t been updated.

**Comment by azeemshaikh38** [comment]
> The caching is using blob store and so in the subsequent runs will use the cache and not use the API quotas if the content hasn’t been updated.

Do you mean with the help GitHub conditional requests / `Last-Modified` tags? Because it doesn't do that today AFAICT?

**Comment by azeemshaikh38** [comment]
Closing this as we don't have tarball caching issues anymore.
