### ISSUE TITLE
Commit based scorecard

### ISSUE THREAD

**Issue by KPostOffice** [ossf/scorecard#575]
**Is your feature request related to a problem? Please describe.**
I would like to be able to create a score card for either specific releases or commits on GitHub so that I can meaningfully show how a project's health has changed on a release by release basis.

I understand that some scorecard indicators might not work because they interact directly with the GitHub api and are not dependent on the current head commit.  Is there a subset of checks that this could work with though?

**Comment by laurentsimon** [comment]
That's an interesting feature to have, thanks for the suggestion. Any checks that are looking at file content (frozen dependencies, binary artifacts checked-in, etc) would work in this model. In the future, we would like to support other type of code source: not only online repos, but also files/directories on disk, e.g. `scorecard --repo=file://`. This would make commit-based checks feasible.

We are also working on a BigQuery end point to expose the results of our cron run of scorecard. The projects we crawl are in [cron/data/projects.csv](https://github.com/ossf/scorecard/blob/main/cron/data/projects.csv).

@azeemshaikh38 who's leading the above and will have more comments.

**Comment by laurentsimon** [comment]
as part of the work to create a GitHub action that works on pull requests (content-based checks), I'm going to work on this soon. What I plan to do is create a new [repoClient](https://github.com/ossf/scorecard/blob/main/clients/repo_client.go) that takes as input a folder containing code that is already downloaded. The new repo client implementation will only support content-based checks and will use the folder passed as argument by users. Scorecard will then be run as:
```
$git clone some/repo
$scorecard ... --source-code=./repo
```
I will re-use this functionality for the GitHub action on pull request events.

Any further comment?

**Comment by goern** [comment]
I'd love to see a Tekton task for this too ;) Let me know if you need some help with it or if Project Thoth shall go ahead and publish on on the tekton catalog.

**Comment by laurentsimon** [comment]
Hi @goern , thanks for the interest in the project. Having a tekton task sounds like an awesome thing to have!

Would you need all the checks for the task (like we do for our GitHub actions on cron and push triggers https://github.com/ossf/scorecard/issues/1074), or a subset of checks that run on source-code only (basically, this PR)?

What output would you need? (we have JSON and SARIF). SARIF is based on a policy, whereas JSON is the raw output with scores for each check and an aggregate score for the repo.

If you have cycles to build work on it, we'd be more than happy for you to own it.

**Comment by azeemshaikh38** [comment]
Will give this a shot. Might be something worth pursuing for v5.

**Comment by laurentsimon** [comment]
do you know which checks won't be supported? I suppose those using "out-of-band" data not tied to commits, like Fuzzing, branch protection, CI-Badges. Signed Release may be hard too. Just curious.

**Comment by azeemshaikh38** [comment]
Below checks are not commit-dependent. For those, we would just report the current status (same as HEAD). 

Branch-Protection
CII-Best-Practices
Fuzzing
Signed-Releases
Maintained (because we want to see if it is maintained today, not at the commit we are checking for)
Packaging

**Comment by laurentsimon** [comment]
could be confusing to report results for HEAD vs a commit from a user's perspective. Any idea whether we should take a similar approach to `--local`, ie only repo what's supported?

**Comment by azeemshaikh38** [comment]
Well, these checks are not commit-based in the first place. Even today, when we run these checks at HEAD, there is no correlation between the HEAD commit and the results of these checks i.e, the results of these checks can change over time even if HEAD commit hasn't changed. So I think it's ok to keep the behavior same whether user runs at HEAD or at a particular commit.

**Comment by laurentsimon** [comment]
Implicitly, running scorecard at HEAD looks for the most recent signals, whereas commits are in the past. I personally would be confused about what the results mean is it mixed commit and "recent". 

cc @naveensrinivasan @chrismcgehee @justaugustus @olivekl @oliverchang

**Comment by chrismcgehee** [comment]
I think we should use the same approach as with `--local`. When running for a specific commit, we just show the results for what's supported.

**Comment by azeemshaikh38** [comment]
Fair enough. Currently exploring the feasibility of implementing this. If I can do that, will update the CLI to not support non-commit based checks.
