### ISSUE TITLE
Investigate HTTP and Gitcache effeciency

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#580]
Following up on the discussion we had during bi-weekly. Our current monitoring shows that HTTP and Gitcache don't seem to be providing any benefit in terms of how many requests get served out of cache - 

![image](https://user-images.githubusercontent.com/4825078/121994590-64fd3a80-cd5a-11eb-9668-160dc6a1f585.png)

Investigate whether something is off in the way we have setup these caches or in the monitoring itself. And if this is actually not providing any benefit, consider removing this from code.

**Comment by azeemshaikh38** [comment]
Turns out `httpcache` internally already handles `last_modified` GitHub headers - https://github.com/naveensrinivasan/httpcache/blob/master/httpcache.go#L175.

So I'm going to update the way we record these stats to see if the cache is actually working.

**Comment by naveensrinivasan** [comment]
> Turns out `httpcache` internally already handles `last_modified` GitHub headers - https://github.com/naveensrinivasan/httpcache/blob/master/httpcache.go#L175.
> 
> So I'm going to update the way we record these stats to see if the cache is actually working.

Great! Thanks

**Comment by azeemshaikh38** [comment]
Looks like even with the monitoring change, there is no indication that a cache is being used.
