### ISSUE TITLE
latest.json is not in valid json format

### ISSUE THREAD

**Issue by nasifimtiazohi** [ossf/scorecard#607]
**Describe the bug**
https://storage.googleapis.com/ossf-scorecards/latest.json is not valid Json.
For example, opening in Firefox shows `SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data`.
I am also unable to read the `json` response programmatically through `serde_json` package in rust. 

The file currently holds data for each repo in following format: `{} {} {}`

**Expected behavior**
`latest.json` in valid Json format. 
The file should probably be in the format: `[{},{},{}]`

**Comment by naveensrinivasan** [comment]
Scorecard does not publish results to the latest.json. The data is published to BigQuery https://github.com/ossf/scorecard#public-data
