### ISSUE TITLE
FYI: pausing PubSub cron controller

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#615]
Just an FYI that I have temporarily paused the cron controller. I'm debugging/working on some performance improvements in the PubSub worker and don't want to publish to PubSub topic when not needed. Will manually keep running the controller whenever an older run finishes. Will resume the cron job once performance work is completed.

**Comment by naveensrinivasan** [comment]
> Just an FYI that I have temporarily paused the cron controller. I'm debugging/working on some performance improvements in the PubSub worker and don't want to publish to PubSub topic when not needed. Will manually keep running the controller whenever an older run finishes. Will resume the cron job once performance work is completed.

Cool, Thanks. What are the issues/performance improvements?

**Comment by azeemshaikh38** [comment]
Working on improving the tarball decompression issue as of now. Instead of decompressing on every call of `CheckFile*`, we should do it once during `InitRepo` and use the underlying data after.

**Comment by naveensrinivasan** [comment]
> Working on improving the tarball decompression issue as of now. Instead of decompressing on every call of `CheckFile*`, we should do it once during `InitRepo` and use the underlying data after.

Thanks! for the update.

**Comment by azeemshaikh38** [comment]
Unpaused it now. closing this issue.
