### ISSUE TITLE
BUG: `ZeroConfidenceError` and `RetryError` in cron job

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#629]
During the cron job run, checks constantly throw out `ZeroConfidenceError` and `RetryError`. Some checks are doing this more often than the others. This hurts the data quality of the output of our cron job. Filing this bug to track the investigation and understanding the reason behind this.

Some plots that shed light on this:

1. Error count plots available in the GCP monitoring dashboard `ScorecardBatchJob`: 
![image](https://user-images.githubusercontent.com/4825078/123729244-80337400-d849-11eb-9f5e-4e7d03760a23.png)

2. Confidence histogram created using Data Studio: 
![image](https://user-images.githubusercontent.com/4825078/123729426-ce487780-d849-11eb-8c92-ca19f1b8cb68.png)

Plot (2) is especially useful - 

* `Automatic-Dependency-Check` seems to have a high number results with confidence value `3`. This is coming from [here](https://github.com/ossf/scorecard/blob/main/checks/automatic_dependency_update.go#L34). @laurentsimon what's the reason for this to be set to 3? 

* `Signed-Releases` throws out a `ZeroConfidenceError` on ~80% of the repos.
* `Security-Policy` and `Frozen-Deps` show a lot of `5s` on the confidence plot. Although not as bad as a `0`, would be useful to know why we throw out a `5` and how we can reduce this, since a `5` is equivalent to saying `we are as sure about this as we are of a coin toss`.

**Comment by laurentsimon** [comment]
On Mon, Jun 28, 2021 at 8:00 PM Azeem Shaikh ***@***.***>
wrote:

> During the cron job run, checks constantly throw out ZeroConfidenceError
> and RetryError. Some checks are doing this more often than the others.
> This hurts the data quality of the output of our cron job. Filing this bug
> to track the investigation and understanding the reason behind this.
>
> Some plots that shed light on this:
>
>    1.
>
>    Error count plots available in the GCP monitoring dashboard
>    ScorecardBatchJob:
>    [image: image]
>    <https://user-images.githubusercontent.com/4825078/123729244-80337400-d849-11eb-9f5e-4e7d03760a23.png>
>    2.
>
>    Confidence histogram created using Data Studio:
>    [image: image]
>    <https://user-images.githubusercontent.com/4825078/123729426-ce487780-d849-11eb-8c92-ca19f1b8cb68.png>
>
> Plot (2) is especially useful -
>
>    -
>
>    Automatic-Dependency-Check seems to have a high number results with
>    confidence value 3. This is coming from here
>    <https://github.com/ossf/scorecard/blob/main/checks/automatic_dependency_update.go#L34>.
>    @laurentsimon <https://github.com/laurentsimon> what's the reason for
>    this to be set to 3?
>
> this is arbitrary-ish. Naveen set it to 3 because if we don't find a
dependabot file, it may be because users have enabled dependabot in the
github UI.


>
>    -
>    -
>
>    Signed-Releases throws out a ZeroConfidenceError on ~80% of the repos.
>
> https://github.com/ossf/scorecard/blob/main/checks/signed_releases.go#L88
This seems arbitrary. I think it's not set to 1 because there may be other
signature extensions ppl use. We could set it to 1 and wait for people to
complain.


>
>    -
>    -
>
>    Security-Policy and Frozen-Deps show a lot of 5s on the confidence
>    plot. Although not as bad as a 0, would be useful to know why we throw
>    out a 5 and how we can reduce this, since a 5 is equivalent to saying we
>    are as sure about this as we are of a coin toss.
>
>
https://github.com/ossf/scorecard/blob/6a2a1faa6f04cde06b292204293e687ca4d9bfe2/checks/checkforfile.go#L72
This seems arbitrary too. I think we can change to 10.

**Comment by laurentsimon** [comment]
@naveensrinivasan any thoughts on this? I personally don't mind setting all of these to 1 and wait to see if there's push back.

**Comment by azeemshaikh38** [comment]
> set it to 3 because if we don't find a dependabot file, it may be because users have enabled dependabot in the
github UI.

I think 5 is fine here if we can add details why it was rated so. 3 is too arbitrary a number. 

> This seems arbitrary. I think it's not set to 1 because there may be other signature extensions ppl use. We could set it to 1 and wait for people to complain.

+1. I agree that we should rate this at 10 confidence since I don't expect too many types of signature extensions. If they exist and we don't handle it, we should. And if its something that's not very standard, we fail.

> https://github.com/ossf/scorecard/blob/6a2a1faa6f04cde06b292204293e687ca4d9bfe2/checks/checkforfile.go#L72

I think 5 is ok depending on what we are trying to imply here. We can add more info in `CheckResult.Details` about why we are unsure on this result. However, I would say we should change the function signature such that it returns `(bool, error)` instead of a `CheckResult`. It should be upto the check calling `CheckIfFileExists` how to rate the confidence.

**Comment by naveensrinivasan** [comment]
I came up with `3` from this comment https://github.com/ossf/scorecard/pull/322#discussion_r606685146

**Comment by azeemshaikh38** [comment]
> I came up with `3` from this comment [#322 (comment)](https://github.com/ossf/scorecard/pull/322#discussion_r606685146)

In that case, let's add more detail to this failure.

**Comment by azeemshaikh38** [comment]
Actually, I take that back. Let's consider how Scorecard results are applied by teams/users. A `FAIL` Scorecard check result means something is off with the repository and needs to be fixed/looked at more thoroughly. While a `PASS` result simply means - `we didn't find anything obviously wrong here`. 

So IMO, Scorecard checks should only `FAIL` with a high degree of confidence. Our fallback should be a `PASS` result with low confidence. We should update our current checks and README to follow this principle. Wdyt?

@inferno-chromium @oliverchang for feedback/comments.

**Comment by laurentsimon** [comment]
and maybe long-term use a `N/A` when we have low confidence

**Comment by oliverchang** [comment]
+1 to some thing that indicates `N/A`. We need to distinguish between issues with our checks vs a true failure.

**Comment by inferno-chromium** [comment]
yes it would be a nice time to fix these check failure differences (and this confidence inconsistencies), from this point, we would be looking at trendlines on big query datasets (how useful was remediation over time), so lets probably discuss this in next scorecard sync in detail, then we fix this so that data cleans up.

**Comment by laurentsimon** [comment]
> Actually, I take that back. Let's consider how Scorecard results are applied by teams/users. A `FAIL` Scorecard check result means something is off with the repository and needs to be fixed/looked at more thoroughly. While a `PASS` result simply means - `we didn't find anything obviously wrong here`.
> 
> So IMO, Scorecard checks should only `FAIL` with a high degree of confidence. Our fallback should be a `PASS` result with low confidence. We should update our current checks and README to follow this principle. Wdyt?

this sounds like a good idea but does not work for all checks. The one that looks for dependabot config is an example. If we find the config file, we know it's enabled. If we cannot find the file, we don't know if it's enabled in the GH settings. If we were to pass by default, this check would always pass, no matter what. Let's discuss more.


> 
> @inferno-chromium @oliverchang for feedback/comments.

**Comment by azeemshaikh38** [comment]
Closing this since @laurentsimon work on standardizing Scorecard errors addresses this already.
