### ISSUE TITLE
RFE: Tool / Check should provide suggested remediation

### ISSUE THREAD

**Issue by JasonKeirstead** [ossf/scorecard#63]
Currently, a check indicates a simple pass/fail with confidence. For a developer, this does not actually help them know how they should improve the situation. Checks should provide a suggested remediation on how to fix or improve.

**Comment by inferno-chromium** [comment]
You want to propose some recommendation in the doc, maybe https://github.com/ossf/scorecard/blob/main/checks.md ?

**Comment by JasonKeirstead** [comment]
@inferno-chromium I would argue it should output in the tool itself. If there is consensus on that I will try to work on a small PR to get it started.

**Comment by inferno-chromium** [comment]
Yes i meant show the link in tool and improve documentation.

**Comment by dlorenc** [comment]
Yes, makes sense to me. I think having the remediation content itself live on some website with a short summary and links in the tool makes sense.

Some of the guidance could be multiple paragraphs or longer, which could be hard to read in a terminal.

**Comment by naveensrinivasan** [comment]
closing this to track it via #304
