### ISSUE TITLE
Feature: Randomly assign reviewers for dependabot PRs

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#632]
To handle the volume of dependabot PRs, setup a rule/workflow such that incoming dependabot PRs will be randomly assigned a reviewer. It will be the assigned reviewer's responsibility to make sure the PR is safely merged into `main`.

Not sure if this is easy to setup. I found this tool which claims to do the exact thing though - https://mergify.io/.

**Comment by harringj** [comment]
Would a potential solution be to create a team, add that team as a CODEOWNER, and then specify the team name in a "reviewers" section in the dependabot.yml, as described here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers?

**Comment by spencerschrock** [comment]
Closing as we already use a team in our CODEOWNER file and recently turned on the [review auto-assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment) feature.
