### ISSUE TITLE
Feature - Scorecard domain name

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#636]
**Is your feature request related to a problem? Please describe.**
The scorecard needs a web frontend to hold documentation(possibly other things). A vote to choose the scorecard FQDN. 

Here are a couple of choices

1. https://scorecard.dev
2. https://scorecards.dev

**Comment by naveensrinivasan** [comment]
https://scorecard.dev

**Comment by naveensrinivasan** [comment]
https://scorecards.dev

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @laurentsimon @inferno-chromium @chrismcgehee @kimsterv

**Comment by laurentsimon** [comment]
note that the repo name is scorecard, but our upcoming blog post refers to the project as `scorecards` with an `s`.

**Comment by naveensrinivasan** [comment]
> note that the repo name is scorecard, but our upcoming blog post refers to the project as `scorecards` with an `s`.

🤦

**Comment by laurentsimon** [comment]
see the initial announcement last year too https://opensource.googleblog.com/2020/11/security-scorecards-for-open-source.html

**Comment by oliverchang** [comment]
Why not both? :) We can redirect one to the other.

**Comment by inferno-chromium** [comment]
> Why not both? :) We can redirect one to the other.

yes exactly that is already done.

**Comment by naveensrinivasan** [comment]
The domain has been purchased.
