### ISSUE TITLE
How to measure maintaince

### ISSUE THREAD

**Issue by JasonKeirstead** [ossf/scorecard#64]
Current check measures commits and releases.

The question is - does something with a lot of commits imply a secure project? How does commits correlate with security. Mature projects release far less often. 

Less of an issue until this results in some form of automated checks/badging. Some of these checks should be higher weight than others. I would give this a low weight if kept measuring in this fashion....

**Comment by inferno-chromium** [comment]
What are your thoughts here ?

Active check gives some indication - https://github.com/ossf/scorecard/blob/main/checks/active.go

**Comment by JasonKeirstead** [comment]
Sorry not sure how this got submitted without text... edited & fixed.

**Comment by inferno-chromium** [comment]
Right now, we are not putting weights on checks or comparing one check vs other. We are giving the integrator a set of values and then they can make a decision based on that. In future, we will probably be doing scoring based on these values and can account for this aspect as part of that.
