### ISSUE TITLE
Bug - Random test failures

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#646]
```
protoc --go_out=../../../ cron/data/request.proto
/bin/bash: protoc: command not found
make: *** [Makefile:88: cron/data/request.pb.go] Error 127
```

_Originally posted by @laurentsimon in https://github.com/ossf/scorecard/issues/611#issuecomment-872455510_

**Comment by laurentsimon** [comment]
@azeemsgoogle

**Comment by laurentsimon** [comment]
happening on another PR https://github.com/ossf/scorecard/pull/766

**Comment by laurentsimon** [comment]
Copying the link @azeemsgoogle provided in https://github.com/ossf/scorecard/pull/766#issuecomment-887962649: https://lukasjoswiak.com/github-actions-protobuf/
@azeemsgoogle do you have cycles to fix this issue? (It's part of the cron job IIUC)

**Comment by naveensrinivasan** [comment]
I can take this.

**Comment by azeemshaikh38** [comment]
Thanks Naveen!
