### ISSUE TITLE
New check: Detect untracked/unverified installs of `npm` dependencies (`npm (-g) install ${PKG_NAME}`)

### ISSUE THREAD

**Issue by rsprabery** [ossf/scorecard#647]
**Is your feature request related to a problem? Please describe.**

We should track `npm install ${PKG_NAME}` and the global variant (`npm install -g ${PKG_NAME}`) done with out a corresponding `package-lock.json` to encourage verified installs relying on tracking hashes and dependencies.

**Describe the solution you'd like**

We can add a new check and score accordingly. Any time `npm install` is run, there should be a `package-lock.json` present.

**Additional context**

We'll need to provide clear remediation guidelines. Many times, `npm install` is used to install command line tools. Traditionally, the use of `package-lock.json` implies the project will be using the dependency directly in the code, not as a command line utility. 

For command line utilities, we need to provide guidelines on how to update the `${PATH}` as `npm install -g` doesn't support `package.json` afaict.

**Comment by laurentsimon** [comment]
note: `npm i <pkg>` seems to be a shorthand for `npm install`

**Comment by laurentsimon** [comment]
Closing, as the PR got merged. Thanks @rsprabery !
