### ISSUE TITLE
scorecard on github marketplace

### ISSUE THREAD

**Issue by avelino** [ossf/scorecard#653]
**Describe the solution you'd like**
to simplify the adoption of the project it would be important to create a service on the github marketplace and with "one click" it would be possible to add scorecards to the project

**Additional context**
after reading the publication made by google I decided to put scorecard in a project that I am a maintainer ([prest](https://github.com/prest/prest)), after breaking my head with yml I decided to look at the existing actions in scorecard, I made a **"fork"** of the `integration.yml` (https://github.com/prest/prest/pull/566) file
The use of the scorecard can be simplified with action

**Comment by azeemshaikh38** [comment]
Thanks for the feedback :) If I understood https://github.com/prest/prest/pull/566/files correctly, you basically want to enable a workflow such that - on incoming PRs Scorecard gets triggered on your repo. Is that correct?

We have something very similar in our pipeline for current quarter (see https://github.com/ossf/scorecard/issues/193, https://github.com/ossf/scorecard/issues/271). Basically, we want to support a Scorecard action/workflow on Github. Let me know if this would achieve what you are looking for.

**Comment by avelino** [comment]
is related to the issue #193

but this issue would be for scorecard to be available on the [github marketplace](https://github.com/marketplace)

**Comment by azeemshaikh38** [comment]
Interesting, definitely a pretty cool idea. Adding it to #511. Will likely look into this once we have tackled #193.
