### ISSUE TITLE
Feature - accept alternate suffixes for security policy namely `.rst`

### ISSUE THREAD

**Issue by randombit** [ossf/scorecard#655]
**Is your feature request related to a problem? Please describe.**
The script does not detect a security policy named `security.rst`.

**Describe the solution you'd like**
Currently only `security.md` is accepted as a policy. Please consider also detecting at least `security.rst` as RST is a common text format which is directly supported on GH etc.

**Describe alternatives you've considered**
I could rename the policy file to match what the script expects. But as the policy is one of the inputs that are fed into Sphinx to generate the project website and documentation, then the policy would be omitted. Which would not be very helpful.

**Comment by inferno-chromium** [comment]
Sure, feel free to propose PR to add this, it needs to be added here - https://github.com/ossf/scorecard/blob/main/checks/security_policy.go
