### ISSUE TITLE
Bug :- The file glob pattern 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#657]
@azeemshaikh38  The file glob pattern doesn't seem to work with the refactor. `security.rst` could be `docs` or other folders and it is not consistent across repositories.

_Originally posted by @naveensrinivasan in https://github.com/ossf/scorecard/pull/656#discussion_r663547171_

**Comment by azeemshaikh38** [comment]
It does work, we use the glob pattern for matching here: https://github.com/ossf/scorecard/blob/main/checks/checkforcontent.go#L31

You simply need to pass in [`path.Match(globPattern, filename)`](https://golang.org/pkg/path/#Match), as the `predicate` to `ListFiles` API.

**Comment by azeemshaikh38** [comment]
Closing this. Re-open is needed.
