### ISSUE TITLE
Feature: Reorder/sort/color default output format for better legibility

### ISSUE THREAD

**Issue by katrinleinweber** [ossf/scorecard#661]
**Is your feature request related to a problem? Please describe.**

In the `default` output ([examples](https://github.com/ossf/scorecard/blame/v2.0.0/README.md#L107-L120)) it's difficult to visually find the `fail`ing items.

**Describe the solution you'd like**

Swap the column order to for example:

```
Fail  3 Automatic-Dependency-Update
Pass 10 Binary-Artifacts
Fail  0 Branch-Protection
Pass 10 CI-Tests
Pass 10 CII-Best-Practices
Pass 10 Code-Review
Pass 10 Contributors
Fail 10 Frozen-Deps
Pass 10 Fuzzing
Fail  0 Packaging
Pass 10 Pull-Requests
Fail 10 SAST
Fail  5 Security-Policy
Fail 10 Signed-Releases
Fail 10 Signed-Tags
Pass 10 Token-Permissions
```

**Describe alternatives you've considered**

- coloring: red/green or only red for `Fail`
- sorting the `Fail` to either the top of bottom of the list.

Both "alternatives" could be combined with the re-ordering, though.

**Additional context**

CSV & JSON are cool for reporting, but sometimes one just wants to interactively find a problem to work on. An easier-to-read default output would help a lot.

**Comment by naveensrinivasan** [comment]
@katrinleinweber  Thanks for the suggestion! In the initial fix, we aren't including the color.

**Comment by katrinleinweber** [comment]
Wow, that's fast :-) Thank you!
