### ISSUE TITLE
BUG - Frozen Deps handle args

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#710]
**Describe the bug**
The frozen-deps check fails on ARGS being used in the FROM
```
ARG BASEIMAGE
ARG BINARY


FROM "${BASEIMAGE}"
COPY ${BINARY} /usr/local/bin/${BINARY}
```
https://raw.githubusercontent.com/kubernetes/kubernetes/master/build/server-image/Dockerfile

**Comment by naveensrinivasan** [comment]
cc @laurentsimon

**Comment by laurentsimon** [comment]
`ARG` is given via a command line. The `ARG` may be pinned, but dependabot is enable to update a pinned script command.
So it seems like intended result. wdyt?

**Comment by laurentsimon** [comment]
as we roll this check thru allstar, I'll try to see how we can better avoid these (possibly) false positives. May require code annotations for developers to configure some opt-out (scorecard could then have an option to use or ignore the annotations). We could go one step further and require annotations to be LGTM'ed by a security team. Suggestions welcome.

**Comment by naveensrinivasan** [comment]
> as we roll this check thru allstar, I'll try to see how we can better avoid these (possibly) false positives. May require code annotations for developers to configure some opt-out (scorecard could then have an option to use or ignore the annotations). We could go one step further and require annotations to be LGTM'ed by a security team. Suggestions welcome.

I like the idea of added annotations. Let’s discuss this in our next sync up.

**Comment by laurentsimon** [comment]
I think to ensure that that dependency is pinned in `FROM`, the line should look like
```
FROM ${ARG}:@sha256:${HASH}
```

We do this in https://github.com/ossf/scorecard-actions/blob/main/analyze/Dockerfile#L17

wdut?

**Comment by laurentsimon** [comment]
FYI @nanikjava
