### ISSUE TITLE
Cleanup verbosity level

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#717]
We currently use the zap package for logging. We also have a detail level (warn, info, debug) as part of https://github.com/ossf/scorecard/pull/712. Can we simplify the code to only use our own internal detail level as logging level, and get rid of zap dependency?

See https://github.com/ossf/scorecard/pull/712#discussion_r673176415 and https://github.com/ossf/scorecard/pull/712#discussion_r673181170.

@naveensrinivasan @azeemsgoogle

**Comment by spencerschrock** [comment]
Calling this closed with #1502 and #1516
