### ISSUE TITLE
Feature: add line number to Pinned-Dependencies detail reporting

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#725]
add a line number to the `Pinned-Dependencies`, `Token-Permissions` checks. 
Today the details contain the line content only, e.g.:
``Warn: insecure (unpinned) download detected in .github/workflows/pylint-presubmit.yml: 'python -m pip install --upgrade pip'``

We may want to add a line number as well.

**Comment by chrismcgehee** [comment]
I'll take this issue since I have some time now to work on scorecard now that I've settled in from my move. I'd like to have an easier issue to get back into the swing of things.

**Comment by laurentsimon** [comment]
Thank you!

FYI I'm working on adding [SARIF support](https://docs.github.com/en/code-security/secure-coding/integrating-with-code-scanning/sarif-support-for-code-scanning) for scorecard, and for this I need to make some code update to support more structured data in details (line, filename, etc). 
ETA for the required update is ~10 days. You can start working on the PR for sure in the meantime, you'll just need to change the call to `Warn` when I land my update.

**Comment by laurentsimon** [comment]
@chrismcgehee assigned issue to you, thanks again for taking this issue!

**Comment by laurentsimon** [comment]
@chrismcgehee this issue is important for the v4 (~EOY) release. Are you still interested in helping for this issue?
I've finished the SARIF support and you can try it using https://github.com/ossf/scorecard/issues/1074#issuecomment-933653061

**Comment by laurentsimon** [comment]
@chrismcgehee what's left to be done for this? Sorry, I've not kept up with all the commits :-)

**Comment by chrismcgehee** [comment]
> @chrismcgehee what's left to be done for this?

I'm just about ready to submit a PR that will add numbers for more places. The line numbers for anything in shell code is going to be tricky because of the way we pass shell code throughout the program. I'd be open to having help for that part. 

> Do you know if other checks need updates as well?

I believe Pinned Dependencies and Token Permissions are all that need updating. Asra already added proper line numbering for Dangerous Workflow.

**Comment by laurentsimon** [comment]
> > @chrismcgehee what's left to be done for this?
> 
> I'm just about ready to submit a PR that will add numbers for more places. The line numbers for anything in shell code is going to be tricky because of the way we pass shell code throughout the program. I'd be open to having help for that part.

sg. Let us know how we should help. I think you can start by adding the line numbers to entry functions and try to propagate them to callees? Then ask for help when things get tricky? Or would you like to proceed differently?

> > Do you know if other checks need updates as well?
> 
> I believe Pinned Dependencies and Token Permissions are all that need updating. Asra already added proper line numbering for Dangerous Workflow.

cc @asraa

**Comment by chrismcgehee** [comment]
LGTM. Nice work, Laurent!
