### ISSUE TITLE
Merge code-review and pull-request

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#731]
the checks `Code-Review` and `Pull-Request` do more or less the same. Shall we merge them into one?

**Comment by azeemshaikh38** [comment]
SGTM. The concept of PR as given [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) vs. Code-Review as we use it, is same. Although `PullRequest` check has some logic to look for `bot` committers, which might be useful to have in `Code-Review`

FWIW, `Pull-Request` is the 2nd most API consuming check after `Code-Review`, so merging them will also help with performance.

**Comment by inferno-chromium** [comment]
> SGTM. The concept of PR as given [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) vs. Code-Review as we use it, is same. Although `PullRequest` check has some logic to look for `bot` committers, which might be useful to have in `Code-Review`
> 
> FWIW, `Pull-Request` is the 2nd most API consuming check after `Code-Review`, so merging them will also help with performance.

yes makes sense. lgtm. thinking again, it seems weird why we created a seperate check, code-review is the one people care and that one just has some gerrit addition and some bot account exclusion.
