### ISSUE TITLE
BUG: e2e tests always break

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#741]
We have setup our e2e tests such that they query real repositories. If anything changes on their end, our e2e tests break. Thats super flaky and very unproductive since we have to keep fixing them. We need to find a better solution to this. Lets discuss this in the upcoming meet.

**Comment by laurentsimon** [comment]
yep, that's one we need badly. I've left a few comments in the code for that as well.
btw, we already have https://github.com/ossf/scorecard/issues/435

**Comment by naveensrinivasan** [comment]
We add new features which break the existing e2e.  We would have to tend to e2e to keep up with the features that we add.

For example 

This is failing  https://github.com/ossf/scorecard/runs/3156521297?check_suite_focus=true because our expectation of the e2e result changed. 

```
➜  scorecard git:(main) ginkgo --focus="E2E TEST:CITests" ./e2e/...
Running Suite: E2e Suite
========================
Random Seed: 1627250142
Will run 1 of 24 specs

SSSSSSSSSSSSSSSSS
------------------------------
• Failure [8.870 seconds]
E2E TEST:CITests
/home/sammy/go/src/github.com/ossf/scorecard/e2e/ci_tests_test.go:28
  E2E TEST:Validating use of CI tests
  /home/sammy/go/src/github.com/ossf/scorecard/e2e/ci_tests_test.go:29
    Should return use of CI tests [It]
    /home/sammy/go/src/github.com/ossf/scorecard/e2e/ci_tests_test.go:30

    Expected
        <bool>: false
    to be true

    /home/sammy/go/src/github.com/ossf/scorecard/e2e/ci_tests_test.go:55
------------------------------
SSSSSS

Summarizing 1 Failure:

[Fail] E2E TEST:CITests E2E TEST:Validating use of CI tests [It] Should return use of CI tests
/home/sammy/go/src/github.com/ossf/scorecard/e2e/ci_tests_test.go:55

Ran 1 of 24 Specs in 8.872 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 23 Skipped
--- FAIL: TestE2e (8.88s)
```

**Comment by azeemshaikh38** [comment]
But if new features are breaking the e2e, how are we able to submit PRs which cause these breakages?

**Comment by laurentsimon** [comment]
The e2e tests break because the repos we rely on change over time.

For CI-Test, we currently test for [Pass/Fail]( https://github.com/ossf/scorecard/blob/main/e2e/ci_tests_test.go#L52-L53) as before, and we also test for the more granular [score and debug/warn/info messages](https://github.com/ossf/scorecard/blob/main/e2e/ci_tests_test.go#L42-L47).

At the time I migrated CI-Test check to use score instead of Fail/Pass, the # of PRs found by the check was [25](https://github.com/ossf/scorecard/blob/main/e2e/ci_tests_test.go#L47).  At the time of this reply, the number of PRs is only 24:
```SCORECARD_V2=1 go run . --repo=github.com/apache/airflow --show-details --checks CI-Tests
|-------|--------------------------------|----------|---------|---------------------------------------------------------------|
| SCORE |             REASON             |   NAME   | DETAILS |                   DOCUMENTATION/REMEDIATION                   |
|-------|--------------------------------|----------|---------|---------------------------------------------------------------|
| 10    | 24 out of 24 merged PRs        | CI-Tests |         | github.com/ossf/scorecard/blob/main/checks/checks.md#ci-tests |
|       | checked by a CI test -- score  |          |         |                                                               |
|       | normalized to 10               |          |         |                                                               |
|-------|--------------------------------|----------|---------|---------------------------------------------------------------|
```

The new e2e tests are more granular than the previous binary ones, which explains why we're seeing more of them break on a regular basis.
The way to fix the problem is to use repos that don't change over time.

Let's discuss in this afternoon's meeting.

**Comment by azeemshaikh38** [comment]
@laurentsimon one more interesting breakage:

```
SCORECARD_V2=1 go run . --repo=github.com/kubernetes/kubernetes --show-details --checks Frozen-Deps
```

Could you look into this?

**Comment by laurentsimon** [comment]
sure. Are you manually looking at results or you've updated the cron job to keep track of errors/repos already?

**Comment by laurentsimon** [comment]
this file is the culprit https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.Dockerfile.txt
I'll filter out .txt and check if the file has only comments.
Anything else more robust we could do?

**Comment by laurentsimon** [comment]
error is not wrapped in a meaningful way, see https://github.com/moby/buildkit/blob/v0.9.0/frontend/dockerfile/parser/parser.go#L392

**Comment by azeemshaikh38** [comment]
Let's skip analyzing Dockerfiles with only comments. That should be good enough.

**Comment by azeemshaikh38** [comment]
FYI, we now have https://github.com/ossf-tests. @laurentsimon @naveensrinivasan do either of you have the cycles to update our e2e test to use test repos?

**Comment by laurentsimon** [comment]
I'll add a repo `scorecard-frozen-deps` for frozen-deps. All the tests for this checks look at files only, so Ill copy the unit tests files in there. Note that we agreed in the meeting to rename this check `Pinned-Dependencies`, so I'll actually create `scorecard=pinned-dependencies` repo.
