### ISSUE TITLE
Feature: use GitHub security policy URI for `SecurityPolicy` check

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#753]
GitHub graphQL exposes a `securityPolicyURL` field for a repository: 

![image](https://user-images.githubusercontent.com/4825078/127045538-f2f495f4-0151-4f03-826a-fd6db0928538.png)

Wondering if we can simply use this instead of polling through all files in the repo? @inferno-chromium @laurentsimon @naveensrinivasan @oliverchang

**Comment by inferno-chromium** [comment]
going through files helps to work for non-github cases

**Comment by inferno-chromium** [comment]
also, why burn api quota when we can work through files. also, we dont poll all files, we just look in root directory and one another directory.

**Comment by oliverchang** [comment]
+1. doesn't seem necessary to use this API.

**Comment by naveensrinivasan** [comment]
> also, why burn api quota when we can work through files. also, we dont poll all files, we just look in root directory and one another directory.

+1  I concur.

**Comment by azeemshaikh38** [comment]
Sounds good. Closing the issue. Thanks for the responses!
