### ISSUE TITLE
BUG- Addlicense exclude path

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#767]
**Describe the bug**
Scorecard would like to exclude license check https://github.com/ossf/scorecard/pull/766/checks?check_run_id=3176959693 for certain files.

The licensecheck has a PR to address this https://github.com/google/addlicense/pull/70 but does not seem to have any traction on merging the issue

**Comment by naveensrinivasan** [comment]
@inferno-chromium  We have 2 options.

1. Get someone in Google to merge this PR.
2. Fork the repo and fix it by ourselves.

cc @laurentsimon

**Comment by laurentsimon** [comment]
I asked on the PR.

**Comment by mco-gh** [comment]
PR reviewed, left a few comments
