### ISSUE TITLE
New check: signed commits

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#779]
there seems to be a setting under branch protection called `Require signed commits` which may be useful to add.
We could also have this as part of separate check when https://github.com/git/git/pull/1041 is merged and operational.

@FStelzer @djmdjm do you have some rough estimate when ssh signing https://github.com/git/git/pull/1041 will go live and if it will be supported as part of the branch protection setting?

**Comment by laurentsimon** [comment]
some related discussion at https://github.com/ossf/scorecard/issues/223

**Comment by FStelzer** [comment]
I can't really give any indication of when this will be generally available. There is still a bit of review / discussion of specifics going on. And even if it is merged/released soon i have no idea on when github might provide the feature.
I guess when the feature made it into a git release you can open a ticket with github to ask for it. But they'll have to implement some things to manage the allowedSigners as well.

**Comment by laurentsimon** [comment]
> I can't really give any indication of when this will be generally available. There is still a bit of review / discussion of specifics going on. And even if it is merged/released soon i have no idea on when github might provide the feature.
> I guess when the feature made it into a git release you can open a ticket with github to ask for it. But they'll have to implement some things to manage the allowedSigners as well.

Thanks!

**Comment by laurentsimon** [comment]
duplicate https://github.com/ossf/scorecard/issues/379

**Comment by justaugustus** [comment]
(Noting the official thread for SSH signing: https://github.com/github/feedback/discussions/7744)

**Comment by LappleApple** [comment]
@spencerschrock @afmarcum and others: From our Jan 25 meeting, we said we'd close this one as a "won't do."

**Comment by spencerschrock** [comment]
Additionally this one is a duplicate of #379. Any future discussion should take place there.
