### ISSUE TITLE
Accept owner/repo and default to github

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#780]
today users need to pass `--repo=github.com/owner/repo` as argument. Since GitHub is the common case, we may want to make it easier and accept `--repo=owner/repo` and default to GitHub for it.

**Comment by nanikjava** [comment]
@laurentsimon can you assign the ticket to me, I've opened a PR for this. Thanks.

**Comment by azeemshaikh38** [comment]
IMO, we should hold off on this. We plan to expand support to VCS systems other than GitHub.

**Comment by laurentsimon** [comment]
Discussed with @azeemsgoogle offline. GitHub still accounts for the majority of os repos today, so let's move forward with this and merge the PR. Thank you @nanikjava for sending the PR!

**Comment by nanikjava** [comment]
@laurentsimon this ticket can be closed now ?

**Comment by laurentsimon** [comment]
Indeed it can and should. Thanks for the reminder!
