### ISSUE TITLE
Give low importance to github-owned actions

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#802]
in the `Pinned-Dependencies` check, we flag all unpinned actions.
We may give lower risk to github-owned actions. In GH doc and examples, only 3P actions are pinned, e.g., https://docs.github.com/en/actions/guides/publishing-java-packages-with-gradle

We can still give higher score to repos that pin them, of course.

**Comment by nanikjava** [comment]
@laurentsimon Keen to work on this. Few questions:

* Which github repo is suitable for testing to check for both unpinned and pinned action
* In terms of score calculation can you point in the direction on how to calculate this ?

Thanks

**Comment by laurentsimon** [comment]
> @laurentsimon Keen to work on this. 

👍🏾 

Few questions:
> 
> * Which github repo is suitable for testing to check for both unpinned and pinned action

scorecard repo pins all its dependencies.
I can't find a repo that pins all its dependencies except the GitHub-owned ones. 
You're going to have to add unit tests in https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies_test.go, so you can add workflows you need for testing there.

(Note: Familiarize yourself with https://github.com/ossf/scorecard/blob/main/checks/write.md, if you have not done so yet.)

Github-owned actions seem to fall into two categories:
1. those that start with `actions/`, from https://github.com/actions
2. those under `github/`, like semmle/codeql: `github/codeql-action`, from https://github.com/github. 

> * In terms of score calculation can you point in the direction on how to calculate this ?

Let's start with something simple:
- all non-GitHub-owned repos are pinned -> score += 8
- all GitHub-owned repos are pinned -> score += 2

Updating `validateGitHubActionWorkflow()` should be enough.

You can also update the e2e2 tests https://github.com/ossf/scorecard/blob/main/e2e/pinned_dependencies_test.go. Keep in mind that the `Pinned-Dependencies` check currently aggregates many sub-tests, see https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies.go#L105. So the overall result won't change by more than 1 point, I think. We may split this check into independent checks at some point, though...

Let me know if you have question or thoughts.

Thanks!
> 
> Thanks

**Comment by nanikjava** [comment]
Thanks @laurentsimon 

Went through the `pinned_dependencies.go` code and here's my finding, please correct me if I'm wrong:

* The `isGitHubActionsWorkflowPinned` function is filtering files residing inside `.github/workflows` directory and iterating them by converting the file content into `gitHubActionWorkflowConfig` struct

* The `validateGitHubActionWorkflow` iterate the  `gitHubActionWorkflowConfig` and look for job-step that has @ in it



 According to the code comment inside `validateGitHubActionWorkflow` it says

```
// Ensure a hash at least as large as SHA1 is used (40 hex characters).
// Example: action-name@hash
```

so does this mean that the code is actually looking for something like this `actions/checkout@a139292` ? if yes, is this considered as GitHub-owned `pinned dependencies` and should be applied the rule that you mentioned `all GitHub-owned repos are pinned -> score += 2` ?

**Comment by laurentsimon** [comment]
> validateGitHubActionWorkflow



> Thanks @laurentsimon
> 
> Went through the `pinned_dependencies.go` code and here's my finding, please correct me if I'm wrong:
> 
> * The `isGitHubActionsWorkflowPinned` function is filtering files residing inside `.github/workflows` directory and iterating them by converting the file content into `gitHubActionWorkflowConfig` struct

correct. `CheckFilesContent()` calls `validateGitHubActionWorkflow()` as a callback for every file it finds.

> * The `validateGitHubActionWorkflow` iterate the  `gitHubActionWorkflowConfig` and look for job-step that has @ in it

correct.

> According to the code comment inside `validateGitHubActionWorkflow` it says
> 
> ```
> // Ensure a hash at least as large as SHA1 is used (40 hex characters).
> // Example: action-name@hash
> ```
> 
> so does this mean that the code is actually looking for something like this `actions/checkout@a139292` ? if yes, is this considered as GitHub-owned `pinned dependencies` and should be applied the rule that you mentioned `all GitHub-owned repos are pinned -> score += 2` ?

It is looking for anything like `whatever@hash`, but does not differentiate between GitHub-owned and third-party actions yet.
Keep in mind that the function will be called for every file found, so you need to keep a state across calls to `validateGitHubActionWorkflow()`: that's what variable `var r pinnedResult` is for (https://github.com/ossf/scorecard/blob/main/checks/pinned_dependencies.go#L482)

You'll need to update this variable to contain more state (GitHub-owned vs thrird-party). You only need to change the variable type for functions that call `validateGitHubActionWorkflow()`.

Let me know if this clarifies everything.

**Comment by nanikjava** [comment]
@laurentsimon Thanks for the explanation.

Based on explanation I've come up with some code which probably is not correct but thought of showing doing it using code to get a better understanding of the solution.

Please let me know what you think.
