### ISSUE TITLE
Releases do not have version info

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#818]
As a note (you're probably already aware) the `2.1.1` release for linux x86_64 doesnt have version info. I havent checked other architectures or versions :slightly_smiling_face:

_Originally posted by @06kellyjac in https://github.com/ossf/scorecard/issues/651#issuecomment-894288280_

**Comment by azeemshaikh38** [comment]
@loosebazooka FYI, since you implemented the `scorecard version` code. Any ideas what might be off here?

**Comment by loosebazooka** [comment]
interesting, I'll take a look

**Comment by loosebazooka** [comment]
Ah yeah version information is inject at build time from the Makefile. So binaries will have the information, arbitrary runs from go get will not. @dlorenc/@jonjonsonjr is ldflags the standard pattern?

We can probably try to change the code a bit to work better for non-binary installs -- but I don't know how that would look yet.

**Comment by 06kellyjac** [comment]
ldflags is a common pattern for this with golang.

I didn't install it with go get, I extracted it from the release tar

The releases arent built using make, theyre built using goreleaser
You will probably need to change the ldflags config like this https://goreleaser.com/customization/build/

**Comment by loosebazooka** [comment]
@06kellyjac do you recommend re-organizing the code around the defaults? or just writing a custom ldFlags rule?
