### ISSUE TITLE
security policy check

### ISSUE THREAD

**Issue by vosytniazhskyi** [ossf/scorecard#82]
You check only for "security.md" and "SECURITY.md" but Some project has "SECURITY.**MD**".

**Comment by inferno-chromium** [comment]
Can you give some examples ?
Ideally it should be just SECURITY.md as per github docs - https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

**Comment by vosytniazhskyi** [comment]
Hello.
Last project that I've tested:
https://github.com/IdentityServer/IdentityServer4/security.md
https://api.github.com/repos/IdentityServer/IdentityServer4/contents/

 "name": "SECURITY.MD",
    "path": "SECURITY.MD"

If I change the list of strings for securityFile all works as expected.

for _, securityFile := range []string{"SECURITY.md", "security.md",
"SECURITY.MD"}


with best regards

Vasyl
