### ISSUE TITLE
Scorecard fails to run

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#867]
Hello Team,

I am new to scorecard and trying to install and use 

Go installation
using Go installation i tried the below
go get github.com/ossf/scorecard/v2
scorecard --repo
I  get the below error
`2021/08/17 15:41:43 GitHub token env var is not set. Please read https://github.com/ossf/scorecard#authentication`
please help
Thanks in advance

**Comment by inferno-chromium** [comment]
The message says to read https://github.com/ossf/scorecard#authentication . Please read the instructions there to set a github access token before running scorecard.

**Comment by bhuvi11** [comment]
Hello, 
Yeah, I set the Github auth token as part of the environment variable and then ran the scorecard.
It worked :)
