### ISSUE TITLE
Question not a bug

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#868]
Hello Team,
I have successfully installed scorecard in my local and ran it against Github repos.

Is it targeted only for open source projects? can I use it to scan private and commercial projects?
Can i use it for other GIt repositories like (GitLab, Bitbucket)?

Thanks in advance

**Comment by azeemshaikh38** [comment]
Hi @bhuvi11 ,

Thanks for you interest in Scorecard. See answers inline:

> Is it targeted only for open source projects? can I use it to scan private and commercial projects?

It is mainly used for open source projects. But it can be used for private repositories if you have the permissions to access them. See, https://github.com/ossf/scorecard#authentication.
We have an open issue for supporting enterprise projects - https://github.com/ossf/scorecard/issues/660



> Can i use it for other GIt repositories like (GitLab, Bitbucket)?

Currently we only support GitHub repos, but plan on expanding tho other VCS soon.
