### ISSUE TITLE
BUG : is allstar working for all repositories?

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#871]
Hello Team,

I am new to allstar and tried to use it in my GitHub repository. I have few questions

- I have installed the app and given access to all my repositories.
I do have security issues. I am not sure why Allstar is not able to detect and create issues.
Eg, i dont have SECURITY.md file. Allstar should have created an issue similar to :
 
> envoyproxy/java-control-plane#174

Is there something else I need to configure?
This is my public repo for reference :

> 
 https://github.com/bhuvi11/test_allstar
 
- In addition to the above issues, i am trying to do the below operation

 Clone the allstar repo
 Create a new github app
 Fetch the app ID
 Get the .pem file
 go build /cmd/allstar
 I see allstar is built, now how to use it ?
 Can i use it in local desktop?
 
 Note: Using windows
 
- Is it specific only to the GitHub repo? Does it have a docker image or CLI to use it in local/ other git remote repositories
- Does allstar use scorecard internally?

Please help

Thanks in advance

**Comment by naveensrinivasan** [comment]
Please create this issue in Allstar repo. Thanks

**Comment by bhuvi11** [comment]
Hello Team,

I have raised an issue with allstar. I am not getting a response. Is there anyone here who can look into and reply?

> https://github.com/ossf/allstar/issues/33

Thanks in advance
