### ISSUE TITLE
How to use scorecard to scan a specific branch

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#881]
Hello Team,

Is there an option to scan a specific branch using scorecard?

**Comment by laurentsimon** [comment]
duplicate from https://github.com/ossf/scorecard/issues/575.
TL;DR: we're working on as part of our integration as a GitHub action.

**Comment by naveensrinivasan** [comment]
For now, the recommendation is to download the repo and check out the specific branch, and run scorecard on that. 

@azeemshaikh38  Thoughts/recommendations?

**Comment by bhuvi11** [comment]
Hello @naveensrinivasan,

How can i do that? currently i see we can scan only URLs
how can i checkout ? can i scan .git repositories?

**Comment by azeemshaikh38** [comment]
Currently, we don't support running on a specific/local branch. #462 unblocks the implementation of a client which can run on local files. We haven't started the implementation on this yet but might start in a few weeks.

**Comment by laurentsimon** [comment]
We now have support for local repos, but it's limited to a few checks that only use file content and not GitHub APIs.
