### ISSUE TITLE
Official downloadable releases?

### ISSUE THREAD

**Issue by Lawouach** [ossf/scorecard#89]
Hey all,

This projects looks really great. I was naively expecting to download an official release but I see none is being built/proposed. Any reason why? Feels a shame not benefit from on of the great golang asset ;)

**Comment by inferno-chromium** [comment]
Just did https://github.com/ossf/scorecard/releases/tag/v1.0.0, can you try it out.

**Comment by Lawouach** [comment]
Brilliant. Thank you will play with it indeed!
