### ISSUE TITLE
Can severity be integrated with score

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#894]
Hello Team,

Currently we get score for each check.
Is there any plan to add severity as well for the checks?

Similar to,
0-3 : High
4-6 : Medium
6-10 : Low

This will help us to easily categorize the checks and use the severity rather than the score.

Currently can someone explain how score is calculated for each check?

**Comment by azeemshaikh38** [comment]
The idea behind providing scores and not severity is that each users needs are unique. Users may want to configure different Scorecard checks with different severity levels. 

For an explanation of how score is being calculated for each check, use the `--show-details` option. Let me know if that helps.

**Comment by laurentsimon** [comment]
We have some severity in https://github.com/ossf/scorecard/blob/main/docs/checks/checks.yaml which we don't expose in the doc or the result. Can you take a look at them and see if you agree/disagree with what we have?

As @azeemsgoogle

**Comment by bhuvi11** [comment]
Hello @azeemshaikh38 and @laurentsimon,

I totally agree but I am more looking for a degree of severity as the score increase or decreases.
I see that for each check risk is tagged to but for which score range that is risk is applicable is more I am looking for.

For eg, assume for branch protection I get 5 as a score, what risk can I give for that? as per the checks.yaml file the risk mentioned is high for a low score, so where does 5 stand?

**Comment by bhuvi11** [comment]
Hello @laurentsimon,

It would be great if you can define a severity level for the score range like ,
0-3 : Bronze
4-6 : Silver
6-10 : Gold
So that we can use it to provide the severity rather than a score.

**Comment by laurentsimon** [comment]
I see. So you see severity as being the opposite of compliance level. Note that a severity for the same score may vary across different checks. Example: score of 5 for `Pinned-Dependencies` may be lower than score 5 `Vulnerabilities`... and higher than score 5 for `SAST`. This inherently stems from the fact that different checks have different risk levels.

Because of this, I'm not sure we can readily use the severity as you propose. 

But your idea does work if we `weight` the severity/score ranges by check's risk levels.

**Comment by bhuvi11** [comment]
Hello Team,

A small suggestion, 
Can you provide fail/pass for each check

**Comment by laurentsimon** [comment]
We are building policy support (bronze, silver, etc) where a Fail/Pass will be used. Users will be able to decide what policy they want. The core of scorecard will remain a plain score, though.

**Comment by bhuvi11** [comment]
Hello  @laurentsimon,
ok thanks. Any timeline on this enhancement?

**Comment by laurentsimon** [comment]
draft PR https://github.com/ossf/scorecard/pull/1002
We're still discussing it... feel free to comment on the PR nevertheless. Example [policy file ](https://github.com/ossf/scorecard/pull/1002/files#diff-21d5121dc72354c8b6324bfc1d1ab624a23af6d3ff1db63faeda52cbff36027c)
