### ISSUE TITLE
BUG : Token check issue

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#896]
Hello Team,

I dont have any read only tokens in the workflow but i get this as the result

>  {
      "Details": null,
      "Score": 10,
      "Reason": "tokens are read-only in GitHub workflows",
      "Name": "Token-Permissions"
    }

Repository for reference : https://github.com/bhuvi11/ecom-service

Please help

**Comment by azeemshaikh38** [comment]
My guess is that there are no tokens found and hence the score of 10 which is the expected behavior. If you have any tokens with write permissions and the check did not catch it, feel free to re-open this bug.

Closing this for now.

**Comment by bhuvi11** [comment]
Hello @azeemshaikh38,
But shouldnt it tell there is no read token? instead the reason says tokens are read-only in GitHub workflows which means i have tokens that are read only but i dont have any token at all
