### ISSUE TITLE
New check: Does the project use branch protection?

### ISSUE THREAD

**Issue by kimsterv** [ossf/scorecard#9]
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-protected-branches

**Comment by inferno-chromium** [comment]
@naveensrinivasan - is more work pending here, or is this ok to close ?

**Comment by naveensrinivasan** [comment]
There are few things that are still pending.

**Comment by inferno-chromium** [comment]
this is done i think, right @laurentsimon , please close if yes.

**Comment by laurentsimon** [comment]
I still want to add checks for release branches #445 , but I think we can close this one. I'll work on branches in #445.
