### ISSUE TITLE
BUG : How does it identify the vulnerabilities using OSV

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#905]
Hello Team,
I have not registered my project under OSS-fuzz.
How does scorecard identify the vulnerabilities using OSV?

**Comment by bhuvi11** [comment]
Hello @laurentsimon,
Yeah . I see the vulnerability check mentioned as it checks the vulnerabilities from OSV, but how does it checks if this project has this vulnerability? Does it scan the project?

**Comment by oliverchang** [comment]
Today the vulnerabilities check just checks if the repo has any direct vulnerabilities in the OSV database. It does not scan for vulnerabilities in that repo's dependencies (yet).

**Comment by bhuvi11** [comment]
Hello @oliverchang,

Thanks for your quick response.
I see the OSV DB has all the vulnerabilities. Does it store the information of the repository as well?
