### ISSUE TITLE
Scorecard repo fails at `Token-Permissions` with score `0`

### ISSUE THREAD

**Issue by laurentsimon** [ossf/scorecard#942]
We need to fix this. A cursory read of our workflows:

- [x] Codeql -> `contents:read`, `statuses: write`and possibly `security-events: write`
- [ ] Goreleaser -> `contents:read`
- [ ] Integration -> `contents:read`, `pull-requests:write` for this.
- [ ] Main -> `contents:read`, `status:write` for license part.
- [ ] Ok-to-test -> ?
- [ ] Stale -> `contents:read` and `issues:write` and `pull-requests:write`
- [ ] Verify -> `contents:read` and `statuses:write`

We can define `permission:` to set all permissions to `none` at the start of the workflows, and then set what we want in each `runs`. It's fine to set `contents:read` at the start of workflows, if this helps.

See https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/ for more info

**Comment by laurentsimon** [comment]
@naveensrinivasan , can you handle it?

**Comment by laurentsimon** [comment]
As we fix this, let's keep a record to explain the permissions we need. Everyone struggles with GitHub permissions AFAIK

**Comment by naveensrinivasan** [comment]
I will take this.

**Comment by naveensrinivasan** [comment]
> As we fix this, let's keep a record to explain the permissions we need. Everyone struggles with GitHub permissions AFAIK

It would be great to have a tool that will produce the actual permissions needed for these actions.

**Comment by azeemshaikh38** [comment]
Can we close this issue now? @laurentsimon @naveensrinivasan

**Comment by laurentsimon** [comment]
yes. Scorecard still gives a score of 0 but it's a bug. Will create an issue for tracking https://github.com/ossf/scorecard/issues/1400
