### ISSUE TITLE
SBOM generation

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#950]
The proposal is to generate [SBOM](https://www.ntia.gov/SBOM) for `gcr.io/openssf/scorecard` and sign the docker image and the SBOM with [cosign](https://github.com/sigstore/cosign)

## SBOM

A “Software Bill of Materials” (SBOM) is effectively a nested inventory, a list of ingredients that make up software components. The following documents were drafted by stakeholders in an open and transparent process to address transparency around software components and were approved by a consensus of participating stakeholders.

source https://www.ntia.gov/SBOM

### Tool to generate SBOM

Recently the k8s team built a tool for generating SBOM https://github.com/kubernetes/release/blob/master/cmd/bom/README.md which is not specific to k8s. It generates in [SPDX](https://github.com/kubernetes/release/blob/master/docs/bom/create-a-bill-of-materials.md#spdx-software-package-data-exchange) format.

### cosign

cosign will be used to sign the SBOM and the docker container as part of the merge to main. The SBOM and the signature would be store in `gcr.io`

#### Keys
The private keys and public keys for signing the image would be store as plain text in the scorecard repository. The public key can be used to verify the validity of the signature.

**Comment by naveensrinivasan** [comment]
@dlorenc @azeemshaikh38 @inferno-chromium @laurentsimon  Thoughts?

**Comment by azeemshaikh38** [comment]
Updating the scope of this issue as per yesterday's discussion. We already have #309 for the cosign issue. Let's use this issue to instead track the generation of SBOM for Scorecards.
