### ISSUE TITLE
BUG : Pinned dependency issue

### ISSUE THREAD

**Issue by bhuvi11** [ossf/scorecard#957]
Hello Team,

When i run scorecard i recevied the below output for pinned dependencies
 "Warn: no lock files detected for a package manager",
            "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:39",
            "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:43",
            "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:54",
            "Warn: unpinned dependency detected (job 'Analyze'): .github/workflows/codeql-analysis.yml:68",

If you see the github action file has actions with version, not sure why i am receiving it

Repository

> https://github.com/bhuvi11/Macro_automation/blob/master/.github/workflows/codeql-analysis.yml

Please help

**Comment by azeemshaikh38** [comment]
@laurentsimon @naveensrinivasan FYI.

Pinning by version is not considered enough. You need to pin dependencies by hash to improve the checks score. See https://github.com/ossf/scorecard/blob/afe5b40567603d0282f8824edf4c3eeeb8089ece/.github/workflows/main.yml#L23 for an example.

We need to improve our documentation to call this out explicitly and also improve logging to let user know it wasn't pinned by hash.

**Comment by naveensrinivasan** [comment]
The pinned dependencies https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies has the documentation 
>For Dockerfiles and GitHub workflows, pin dependencies by hash. See example gitcache-docker.yaml and Dockerfile examples.

And with this fix, it should take care of the broken link https://github.com/ossf/scorecard/pull/963.

So closing this issue.
