### ISSUE TITLE
Erroneous inconclusive CI-Tests result

### ISSUE THREAD

**Issue by moorereason** [ossf/scorecard#96]
Given:

https://github.com/ossf/scorecard/blob/199161753d0a5c2b2832ea3126165261ca4ac86c/checks/ci_tests.go#L58-L59

Shouldn't that be `if totalMerged == 0`?

If we have 10 merged PRs and zero tests found for those PRs, that should not be an inconclusive result.  It should `Fail 10` not `Fail 0`.  Or am I missing something?

**Comment by moorereason** [comment]
I think I see what's happening here.  `GithubStatuses` returns an inconclusive result if no tests passed because their may be passing results in `GithubCheckRuns`.  Hmm.  The `MultiCheck` makes resolving #95 more complicated.

**Comment by dlorenc** [comment]
Yeah, this is a tough case. It's hard to definitively prove a negative here, so I erred on the side of caution. I don't feel very strongly here either way, if you think something else makes more sense that's fine with me!
