### ISSUE TITLE
Reduce number of `nolint` comments in code 

### ISSUE THREAD

**Issue by azeemshaikh38** [ossf/scorecard#962]
We have way too many `nolint` comments in the code. Tracking issue for improving this technical debt by either:

i) Removing unhelpful linters
ii) Improving coding practices

**Comment by neil465** [comment]
I would like to work on this issue.

**Comment by azeemshaikh38** [comment]
Great, thanks! Assigning this issue to you.

**Comment by naveensrinivasan** [comment]
> We have way too many `nolint` comments in the code. Tracking issue for improving this technical debt by either:
> 
> i) Removing unhelpful linters

Which linters do we want to remove? 

> ii) Improving coding practices

**Comment by azeemshaikh38** [comment]
On the top of my head, the ones I can think of are:

- gomnd (magic number detection. causes lot of false positives)
- prealloc (forces you to pre-allocate slices)
- goerr113 (disallows you from creating errors on the fly)
- dupl (lot of false positives in the `e2e` package)

Also, a lot of times we have `nolint` which disables all linters instead of a specific one. We should fix this too and make it our guideline to only disable specific linters in comment if/when needed.

**Comment by naveensrinivasan** [comment]
> On the top of my head, the ones I can think of are:
> 
> * gomnd (magic number detection. causes lot of false positives)

I agree this can be a pain and wouldn't mind removing this. 

> * prealloc (forces you to pre-allocate slices)

prealloc has performance implications https://github.com/alexkohler/prealloc#purpose , so why do you think this should be removed?

> * goerr113 (disallows you from creating errors on the fly)

The go error in 1.13 https://go.dev/blog/go1.13-errors is the right way to create errors. If we don't handle errors correctly we are likely not nested call-stack of the error. What is your reasoning behind removing this>

> * dupl (lot of false positives in the `e2e` package)

I agree `dupl` is an issue for `e2e` package, but it also helps in avoiding duplicates in the future.  

> 
> Also, a lot of times we have `// nolint` which disables all linters instead of a specific one. We should fix this too and make it our guideline to only disable specific linters in comment if/when needed.

**Comment by azeemshaikh38** [comment]
> prealloc has performance implications https://github.com/alexkohler/prealloc#purpose , so why do you think this should be removed?

Because this link seems to prefer empty slices over pre-allocated one: https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices. I'm ok with either way as long as we agree with one guideline and apply it across the code without the need for `// nolint`. 

> The go error in 1.13 https://go.dev/blog/go1.13-errors is the right way to create errors. If we don't handle errors correctly we are likely not nested call-stack of the error. What is your reasoning behind removing this>

This usually comes up in `main.go` files where there is no error to propagate - https://github.com/ossf/scorecard/blob/276155d1eb82fac2e47c95e1c19f0657f0023d03/docs/checks/validate/main.go#L35. Again, I'm ok keeping it if there is a guideline/best practice on how to handle this. 

> I agree `dupl` is an issue for `e2e` package, but it also helps in avoiding duplicates in the future.

There are too many false positives due to this. I would argue that duplicate code is something that can be easily caught by manual review and the trouble of enabling this linter is not worth the advantages it provides.

**Comment by naveensrinivasan** [comment]
> > prealloc has performance implications https://github.com/alexkohler/prealloc#purpose , so why do you think this should be removed?
> 
> Because this link seems to prefer empty slices over pre-allocated one: https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices. I'm ok with either way as long as we agree with one guideline and apply it across the code without the need for `// nolint`.
> 
OMG!! This is funny. They are contradicting each other. I don't have a dog in the fight on this. Lets remove that linter.
> > The go error in 1.13 https://go.dev/blog/go1.13-errors is the right way to create errors. If we don't handle errors correctly we are likely not nested call-stack of the error. What is your reasoning behind removing this>
> 
> This usually comes up in `main.go` files where there is no error to propagate -
> 
For this one can we just have nolint in the `main.go` this will make it easier to debug?
> https://github.com/ossf/scorecard/blob/276155d1eb82fac2e47c95e1c19f0657f0023d03/docs/checks/validate/main.go#L35
> 
> . Again, I'm ok keeping it if there is a guideline/best practice on how to handle this.
> > I agree `dupl` is an issue for `e2e` package, but it also helps in avoiding duplicates in the future.
> 
> There are too many false positives due to this. I would argue that duplicate code is something that can be easily caught by manual review and the trouble of enabling this linter is not worth the advantages it provides.

Sounds good , lets remove the `dupl`

**Comment by azeemshaikh38** [comment]
Sounds good to me, thanks.

**Comment by naveensrinivasan** [comment]
### Remove these linters
- gomnd (magic number detection. causes lot of false positives) - REMOVE this
- prealloc (forces you to pre-allocate slices) - Remove this
- dupl (lot of false positives in the e2e package)

### Keep this linter and fix the code which has no lint for this
- goerr113 (disallows you from creating errors on the fly)

**Comment by naveensrinivasan** [comment]
> Sounds good to me, thanks.

👍

**Comment by neil465** [comment]
@azeemshaikh38 
I would like to know which error package should I use to replace this one? Can you please provide me an example? Thanks

https://github.com/ossf/scorecard/blob/1c7ba79435007fd5ba04533934dc4d698760e84b/cron/bq/main.go#L97

**Comment by azeemshaikh38** [comment]
The decision was to leave `goerr113` as is, as long as it's in `main.go` or `_test.go` files. I think it conforms to that pretty much everywhere except - https://github.com/ossf/scorecard/blob/d9f52098033b46b48965522a442cf1fc188b25c1/utests/utlib.go#L98

You can create a new error and return that. An example is here: https://github.com/ossf/scorecard/blob/13ef9dd7e006bee29b042343366e308b737e5619/clients/githubrepo/search.go#L28

The other useful change for this issue would be to replace all blanket `// nolint` with specific linters. That will really help narrow down which linters are causing most unhelpful errors.
