### ISSUE TITLE
Eat your own dog food

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#97]
Running the scorecard on the `scorecard repo` should succeed.
<details>
./scorecard --repo=https://github.com/ossf/scorecard
Starting [Active]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Fuzzing]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Signed-Releases]
Starting [Signed-Tags]
Finished [Fuzzing]
Finished [CII-Best-Practices]
Finished [Signed-Releases]
Finished [Frozen-Deps]
Finished [Contributors]
Finished [Signed-Tags]
Finished [Security-Policy]
Finished [SAST]
Finished [Pull-Requests]
Finished [Active]
Finished [Code-Review]
Finished [CI-Tests]

RESULTS
-------
Active: Pass 10
CI-Tests: Fail 0
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Fail 10
Frozen-Deps: Pass 10
Fuzzing: Fail 10
Pull-Requests: Pass 9
SAST: Fail 10
Security-Policy: Fail 10
Signed-Releases: Fail 0
Signed-Tags: Fail 0

</details>

**Comment by naveensrinivasan** [comment]
`codeql` check implemented #101

**Comment by inferno-chromium** [comment]
Thanks to your fixes, new results. Although some of things are not applicable, crucial to this tool itself (e.g. fuzzing, CII best practices). Others like security policy will come in new year. And we will do another release signed with tags.

RESULTS
-------
Active: Pass 10
CI-Tests: Fail 9
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Fail 10
Frozen-Deps: Pass 10
Fuzzing: Fail 10
Pull-Requests: Pass 10
SAST: Pass 10
Security-Policy: Fail 10
Signed-Releases: Fail 0
Signed-Tags: Fail 0

**Comment by naveensrinivasan** [comment]
With the https://github.com/ossf/scorecard/releases/tag/v1.1.1 release expect `CII-Best-Practices` and `Fuzzing` everything else is implemented. So closing this one.
```
./scorecard --repo=https://github.com/ossf/scorecard
Starting [Active]
Starting [Branch-Protection]
Starting [CI-Tests]
Starting [CII-Best-Practices]
Starting [Code-Review]
Starting [Contributors]
Starting [Frozen-Deps]
Starting [Fuzzing]
Starting [Packaging]
Starting [Pull-Requests]
Starting [SAST]
Starting [Security-Policy]
Starting [Signed-Releases]
Starting [Signed-Tags]
Finished [SAST]
Finished [Fuzzing]
Finished [CII-Best-Practices]
Finished [Branch-Protection]
Finished [Security-Policy]
Finished [Frozen-Deps]
Finished [Signed-Releases]
Finished [Signed-Tags]
Finished [Packaging]
Finished [Contributors]
Finished [CI-Tests]
Finished [Code-Review]
Finished [Pull-Requests]
Finished [Active]

RESULTS
-------
Active: Pass 10
Branch-Protection: Pass 10
CI-Tests: Pass 10
CII-Best-Practices: Fail 10
Code-Review: Pass 10
Contributors: Pass 10
Frozen-Deps: Pass 10
Fuzzing: Fail 10
Packaging: Pass 10
Pull-Requests: Pass 10
SAST: Pass 10
Security-Policy: Pass 10
Signed-Releases: Fail 5
Signed-Tags: Fail 7
```
