### ISSUE TITLE
Feature - Scorecard identify Expression injection in Actions

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/scorecard#990]
**Is your feature request related to a problem? Please describe.**
Scorecard should identify `Expression injection in Actions` https://github.com/github/codeql/blob/main/javascript/ql/src/experimental/Security/CWE-094/ExpressionInjection.ql

This is already handled by this `go` library which we could use https://github.com/rhysd/actionlint/blob/f05f9da49f93decc2ac8e61b1f951ed19b7303a7/expr_insecure.go#L96

Related to #989

**Comment by naveensrinivasan** [comment]
@laurentsimon FYI...

**Comment by laurentsimon** [comment]
We have this issue https://github.com/ossf/scorecard/issues/426 that suggest writing a more comprehensive number of checks for GH workflows. Let me close this one and link to it in the other one.

**Comment by azeemshaikh38** [comment]
I think @asraa has implemented this now. Can we close this?

**Comment by asraa** [comment]
Yep, looks like it's covered from untrusted code checkout.
