### ISSUE TITLE
Include URL for more information

### ISSUE THREAD

**Issue by david-a-wheeler** [ossf/scorecard#998]
**Is your feature request related to a problem? Please describe.**

Currently there's a very short description of the issues & what to do, but many users will need more information. e.g., on *why* that's a problem, the impact if not changed, and specifics of how to fix it for various circumstances.

**Describe the solution you'd like**

Please include, for the output of each check, a URL to more detail within ossf/scorecard/docs. You could use a link to https://github.com/ossf/scorecard/blob/main/docs/checks.md#CHECK-NAME , though I think it might be wise for each check to have its own *separate* file inside `docs`. The top-level README.md should also link to this docs/ information for each check. Then you can easily update the documentation, and users can easily see the current documentation (without updating the tool just to see better docs).

**Describe alternatives you've considered**

Links to pages *not* under the scorecard page seem like a terrible idea, because scorecard can't fix them. Link to scorecard, and then scorecard can link to those other pages as appropriate.

Don't include documentation in the tool itself; then people have to update the tool to update the docs.

**Additional context**

This should be relatively easy, you already have at least starting material. It's important to also improve the documentation about the checks, but this feature request would make those docs more widely used.

**Comment by david-a-wheeler** [comment]
@naveensrinivasan - This was inspired by the CII Best Practices badge experience so far.

**Comment by laurentsimon** [comment]
This is now supported:
```
go run . --repo=https://github.com/bhuvi11/ecom-service --checks Code-Review --show-details --format json | jq
{
  "date": "2021-09-10",
  "repo": {
    "name": "github.com/bhuvi11/ecom-service",
    "commit": "bb5488c6b99bcbb0954bf5cb7b569068c1cf89fb"
  },
  "scorecard": {
    "version": "unknown",
    "commit": "unknown"
  },
  "checks": [
    {
      "details": [
        "Info: Gerrit code reviews found for 0 commits out of the last 30",
        "Info: Prow code reviews found for 0 commits out of the last 5"
      ],
      "score": 10,
      "reason": "GitHub code reviews found for 5 commits out of the last 5 -- score normalized to 10",
      "name": "Code-Review",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/main/docs/checks.md#code-review",
        "short": "Determines if the project requires code review before pull requests are merged."
      }
    }
  ],
  "metadata": null
}

```

This does not address the other things like a dedicated doc file for each check, etc. We'll get there was we refine check's documentation and remediation.
@david-a-wheeler please confirm this addresses this issue.

@olivekl FYI

**Comment by laurentsimon** [comment]
Additional note: `Don't include documentation in the tool itself; then people have to update the tool to update the docs.`. The current implementation does link to doc for the scorecard's commit hash that was used. You make a good point about update.As checks evolve, we thought of keeping the doc in sync with the scorecard's version run.
For example, if allstar uses our doc for a check, they need to use the doc for the version of scorecard they use.
The limitation is the one you describe... no automatic doc update... happy to revert if we sync the risk of breaking doc change is marginal vs the gain offered by automatic doc update.

Maybe a good compromise is to link to a scorecard's version (2.max.max if scorecard tool is v2.x.y) and not a specific commit.. if this is feasible.

**Comment by laurentsimon** [comment]
let's close since the URL is not present in the results. @david-a-wheeler also helped with better explaining checks in the checks.yaml.
